/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.ApplicationAssignJournal;
import com.astra.dewa.model.ApplicationAssignJournalModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ApplicationAssignJournal service. Represents a row in the &quot;ApplicationAssignJournal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ApplicationAssignJournalModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApplicationAssignJournalImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApplicationAssignJournalImpl
 * @generated
 */
public class ApplicationAssignJournalModelImpl
	extends BaseModelImpl<ApplicationAssignJournal>
	implements ApplicationAssignJournalModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a application assign journal model instance should use the <code>ApplicationAssignJournal</code> interface instead.
	 */
	public static final String TABLE_NAME = "ApplicationAssignJournal";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"ApplicationAssignId", Types.INTEGER},
		{"ApplicationHeaderId", Types.INTEGER},
		{"ApplicationAssignStatusId", Types.INTEGER},
		{"ProfileId", Types.BIGINT}, {"StartDateOn", Types.TIMESTAMP},
		{"CompletedDateOn", Types.TIMESTAMP}, {"Notes", Types.VARCHAR},
		{"RowStatus", Types.BOOLEAN}, {"CreatedBy", Types.VARCHAR},
		{"CreatedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApplicationAssignId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApplicationHeaderId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApplicationAssignStatusId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ProfileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("StartDateOn", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CompletedDateOn", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("Notes", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ApplicationAssignJournal (Id INTEGER not null primary key IDENTITY,ApplicationAssignId INTEGER,ApplicationHeaderId INTEGER,ApplicationAssignStatusId INTEGER,ProfileId LONG,StartDateOn DATE null,CompletedDateOn DATE null,Notes VARCHAR(75) null,RowStatus BOOLEAN,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table ApplicationAssignJournal";

	public static final String ORDER_BY_JPQL =
		" ORDER BY applicationAssignJournal.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ApplicationAssignJournal.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.ApplicationAssignJournal"));

	public ApplicationAssignJournalModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ApplicationAssignJournal.class;
	}

	@Override
	public String getModelClassName() {
		return ApplicationAssignJournal.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ApplicationAssignJournal, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ApplicationAssignJournal, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApplicationAssignJournal, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ApplicationAssignJournal)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ApplicationAssignJournal, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ApplicationAssignJournal, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ApplicationAssignJournal)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ApplicationAssignJournal, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ApplicationAssignJournal, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ApplicationAssignJournal, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<ApplicationAssignJournal, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<ApplicationAssignJournal, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ApplicationAssignJournal, Object>>();
		Map<String, BiConsumer<ApplicationAssignJournal, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ApplicationAssignJournal, ?>>();

		attributeGetterFunctions.put("Id", ApplicationAssignJournal::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<ApplicationAssignJournal, Integer>)
				ApplicationAssignJournal::setId);
		attributeGetterFunctions.put(
			"ApplicationAssignId",
			ApplicationAssignJournal::getApplicationAssignId);
		attributeSetterBiConsumers.put(
			"ApplicationAssignId",
			(BiConsumer<ApplicationAssignJournal, Integer>)
				ApplicationAssignJournal::setApplicationAssignId);
		attributeGetterFunctions.put(
			"ApplicationHeaderId",
			ApplicationAssignJournal::getApplicationHeaderId);
		attributeSetterBiConsumers.put(
			"ApplicationHeaderId",
			(BiConsumer<ApplicationAssignJournal, Integer>)
				ApplicationAssignJournal::setApplicationHeaderId);
		attributeGetterFunctions.put(
			"ApplicationAssignStatusId",
			ApplicationAssignJournal::getApplicationAssignStatusId);
		attributeSetterBiConsumers.put(
			"ApplicationAssignStatusId",
			(BiConsumer<ApplicationAssignJournal, Integer>)
				ApplicationAssignJournal::setApplicationAssignStatusId);
		attributeGetterFunctions.put(
			"ProfileId", ApplicationAssignJournal::getProfileId);
		attributeSetterBiConsumers.put(
			"ProfileId",
			(BiConsumer<ApplicationAssignJournal, Long>)
				ApplicationAssignJournal::setProfileId);
		attributeGetterFunctions.put(
			"StartDateOn", ApplicationAssignJournal::getStartDateOn);
		attributeSetterBiConsumers.put(
			"StartDateOn",
			(BiConsumer<ApplicationAssignJournal, Date>)
				ApplicationAssignJournal::setStartDateOn);
		attributeGetterFunctions.put(
			"CompletedDateOn", ApplicationAssignJournal::getCompletedDateOn);
		attributeSetterBiConsumers.put(
			"CompletedDateOn",
			(BiConsumer<ApplicationAssignJournal, Date>)
				ApplicationAssignJournal::setCompletedDateOn);
		attributeGetterFunctions.put(
			"Notes", ApplicationAssignJournal::getNotes);
		attributeSetterBiConsumers.put(
			"Notes",
			(BiConsumer<ApplicationAssignJournal, String>)
				ApplicationAssignJournal::setNotes);
		attributeGetterFunctions.put(
			"RowStatus", ApplicationAssignJournal::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<ApplicationAssignJournal, Boolean>)
				ApplicationAssignJournal::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedBy", ApplicationAssignJournal::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<ApplicationAssignJournal, String>)
				ApplicationAssignJournal::setCreatedBy);
		attributeGetterFunctions.put(
			"CreatedDate", ApplicationAssignJournal::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<ApplicationAssignJournal, Date>)
				ApplicationAssignJournal::setCreatedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", ApplicationAssignJournal::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<ApplicationAssignJournal, String>)
				ApplicationAssignJournal::setModifiedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", ApplicationAssignJournal::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<ApplicationAssignJournal, Date>)
				ApplicationAssignJournal::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getApplicationAssignId() {
		return _ApplicationAssignId;
	}

	@Override
	public void setApplicationAssignId(int ApplicationAssignId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApplicationAssignId = ApplicationAssignId;
	}

	@Override
	public int getApplicationHeaderId() {
		return _ApplicationHeaderId;
	}

	@Override
	public void setApplicationHeaderId(int ApplicationHeaderId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApplicationHeaderId = ApplicationHeaderId;
	}

	@Override
	public int getApplicationAssignStatusId() {
		return _ApplicationAssignStatusId;
	}

	@Override
	public void setApplicationAssignStatusId(int ApplicationAssignStatusId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApplicationAssignStatusId = ApplicationAssignStatusId;
	}

	@Override
	public long getProfileId() {
		return _ProfileId;
	}

	@Override
	public void setProfileId(long ProfileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ProfileId = ProfileId;
	}

	@Override
	public Date getStartDateOn() {
		return _StartDateOn;
	}

	@Override
	public void setStartDateOn(Date StartDateOn) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_StartDateOn = StartDateOn;
	}

	@Override
	public Date getCompletedDateOn() {
		return _CompletedDateOn;
	}

	@Override
	public void setCompletedDateOn(Date CompletedDateOn) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CompletedDateOn = CompletedDateOn;
	}

	@Override
	public String getNotes() {
		if (_Notes == null) {
			return "";
		}
		else {
			return _Notes;
		}
	}

	@Override
	public void setNotes(String Notes) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Notes = Notes;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ApplicationAssignJournal toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ApplicationAssignJournal>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ApplicationAssignJournalImpl applicationAssignJournalImpl =
			new ApplicationAssignJournalImpl();

		applicationAssignJournalImpl.setId(getId());
		applicationAssignJournalImpl.setApplicationAssignId(
			getApplicationAssignId());
		applicationAssignJournalImpl.setApplicationHeaderId(
			getApplicationHeaderId());
		applicationAssignJournalImpl.setApplicationAssignStatusId(
			getApplicationAssignStatusId());
		applicationAssignJournalImpl.setProfileId(getProfileId());
		applicationAssignJournalImpl.setStartDateOn(getStartDateOn());
		applicationAssignJournalImpl.setCompletedDateOn(getCompletedDateOn());
		applicationAssignJournalImpl.setNotes(getNotes());
		applicationAssignJournalImpl.setRowStatus(getRowStatus());
		applicationAssignJournalImpl.setCreatedBy(getCreatedBy());
		applicationAssignJournalImpl.setCreatedDate(getCreatedDate());
		applicationAssignJournalImpl.setModifiedBy(getModifiedBy());
		applicationAssignJournalImpl.setModifiedDate(getModifiedDate());

		applicationAssignJournalImpl.resetOriginalValues();

		return applicationAssignJournalImpl;
	}

	@Override
	public ApplicationAssignJournal cloneWithOriginalValues() {
		ApplicationAssignJournalImpl applicationAssignJournalImpl =
			new ApplicationAssignJournalImpl();

		applicationAssignJournalImpl.setId(
			this.<Integer>getColumnOriginalValue("Id"));
		applicationAssignJournalImpl.setApplicationAssignId(
			this.<Integer>getColumnOriginalValue("ApplicationAssignId"));
		applicationAssignJournalImpl.setApplicationHeaderId(
			this.<Integer>getColumnOriginalValue("ApplicationHeaderId"));
		applicationAssignJournalImpl.setApplicationAssignStatusId(
			this.<Integer>getColumnOriginalValue("ApplicationAssignStatusId"));
		applicationAssignJournalImpl.setProfileId(
			this.<Long>getColumnOriginalValue("ProfileId"));
		applicationAssignJournalImpl.setStartDateOn(
			this.<Date>getColumnOriginalValue("StartDateOn"));
		applicationAssignJournalImpl.setCompletedDateOn(
			this.<Date>getColumnOriginalValue("CompletedDateOn"));
		applicationAssignJournalImpl.setNotes(
			this.<String>getColumnOriginalValue("Notes"));
		applicationAssignJournalImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		applicationAssignJournalImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		applicationAssignJournalImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		applicationAssignJournalImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));
		applicationAssignJournalImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));

		return applicationAssignJournalImpl;
	}

	@Override
	public int compareTo(ApplicationAssignJournal applicationAssignJournal) {
		int primaryKey = applicationAssignJournal.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ApplicationAssignJournal)) {
			return false;
		}

		ApplicationAssignJournal applicationAssignJournal =
			(ApplicationAssignJournal)object;

		int primaryKey = applicationAssignJournal.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ApplicationAssignJournal> toCacheModel() {
		ApplicationAssignJournalCacheModel applicationAssignJournalCacheModel =
			new ApplicationAssignJournalCacheModel();

		applicationAssignJournalCacheModel.Id = getId();

		applicationAssignJournalCacheModel.ApplicationAssignId =
			getApplicationAssignId();

		applicationAssignJournalCacheModel.ApplicationHeaderId =
			getApplicationHeaderId();

		applicationAssignJournalCacheModel.ApplicationAssignStatusId =
			getApplicationAssignStatusId();

		applicationAssignJournalCacheModel.ProfileId = getProfileId();

		Date StartDateOn = getStartDateOn();

		if (StartDateOn != null) {
			applicationAssignJournalCacheModel.StartDateOn =
				StartDateOn.getTime();
		}
		else {
			applicationAssignJournalCacheModel.StartDateOn = Long.MIN_VALUE;
		}

		Date CompletedDateOn = getCompletedDateOn();

		if (CompletedDateOn != null) {
			applicationAssignJournalCacheModel.CompletedDateOn =
				CompletedDateOn.getTime();
		}
		else {
			applicationAssignJournalCacheModel.CompletedDateOn = Long.MIN_VALUE;
		}

		applicationAssignJournalCacheModel.Notes = getNotes();

		String Notes = applicationAssignJournalCacheModel.Notes;

		if ((Notes != null) && (Notes.length() == 0)) {
			applicationAssignJournalCacheModel.Notes = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			applicationAssignJournalCacheModel.RowStatus = RowStatus;
		}

		applicationAssignJournalCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = applicationAssignJournalCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			applicationAssignJournalCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			applicationAssignJournalCacheModel.CreatedDate =
				CreatedDate.getTime();
		}
		else {
			applicationAssignJournalCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		applicationAssignJournalCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = applicationAssignJournalCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			applicationAssignJournalCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			applicationAssignJournalCacheModel.ModifiedDate =
				ModifiedDate.getTime();
		}
		else {
			applicationAssignJournalCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		return applicationAssignJournalCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ApplicationAssignJournal, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ApplicationAssignJournal, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApplicationAssignJournal, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ApplicationAssignJournal)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, ApplicationAssignJournal>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						ApplicationAssignJournal.class, ModelWrapper.class);

	}

	private int _Id;
	private int _ApplicationAssignId;
	private int _ApplicationHeaderId;
	private int _ApplicationAssignStatusId;
	private long _ProfileId;
	private Date _StartDateOn;
	private Date _CompletedDateOn;
	private String _Notes;
	private Boolean _RowStatus;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<ApplicationAssignJournal, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ApplicationAssignJournal)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("ApplicationAssignId", _ApplicationAssignId);
		_columnOriginalValues.put("ApplicationHeaderId", _ApplicationHeaderId);
		_columnOriginalValues.put(
			"ApplicationAssignStatusId", _ApplicationAssignStatusId);
		_columnOriginalValues.put("ProfileId", _ProfileId);
		_columnOriginalValues.put("StartDateOn", _StartDateOn);
		_columnOriginalValues.put("CompletedDateOn", _CompletedDateOn);
		_columnOriginalValues.put("Notes", _Notes);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("ApplicationAssignId", 2L);

		columnBitmasks.put("ApplicationHeaderId", 4L);

		columnBitmasks.put("ApplicationAssignStatusId", 8L);

		columnBitmasks.put("ProfileId", 16L);

		columnBitmasks.put("StartDateOn", 32L);

		columnBitmasks.put("CompletedDateOn", 64L);

		columnBitmasks.put("Notes", 128L);

		columnBitmasks.put("RowStatus", 256L);

		columnBitmasks.put("CreatedBy", 512L);

		columnBitmasks.put("CreatedDate", 1024L);

		columnBitmasks.put("ModifiedBy", 2048L);

		columnBitmasks.put("ModifiedDate", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ApplicationAssignJournal _escapedModel;

}