/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.ApplicationAssignStatus;
import com.astra.dewa.model.ApplicationAssignStatusModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ApplicationAssignStatus service. Represents a row in the &quot;ApplicationAssignStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ApplicationAssignStatusModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApplicationAssignStatusImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApplicationAssignStatusImpl
 * @generated
 */
public class ApplicationAssignStatusModelImpl
	extends BaseModelImpl<ApplicationAssignStatus>
	implements ApplicationAssignStatusModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a application assign status model instance should use the <code>ApplicationAssignStatus</code> interface instead.
	 */
	public static final String TABLE_NAME = "ApplicationAssignStatus";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"Name", Types.VARCHAR},
		{"Description", Types.VARCHAR}, {"RowStatus", Types.BOOLEAN},
		{"CreatedBy", Types.VARCHAR}, {"CreatedDate", Types.TIMESTAMP},
		{"ModifiedBy", Types.VARCHAR}, {"ModifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ApplicationAssignStatus (Id INTEGER not null primary key IDENTITY,Name VARCHAR(75) null,Description VARCHAR(75) null,RowStatus BOOLEAN,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table ApplicationAssignStatus";

	public static final String ORDER_BY_JPQL =
		" ORDER BY applicationAssignStatus.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ApplicationAssignStatus.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.ApplicationAssignStatus"));

	public ApplicationAssignStatusModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ApplicationAssignStatus.class;
	}

	@Override
	public String getModelClassName() {
		return ApplicationAssignStatus.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ApplicationAssignStatus, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ApplicationAssignStatus, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApplicationAssignStatus, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ApplicationAssignStatus)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ApplicationAssignStatus, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ApplicationAssignStatus, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ApplicationAssignStatus)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ApplicationAssignStatus, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ApplicationAssignStatus, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ApplicationAssignStatus, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<ApplicationAssignStatus, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<ApplicationAssignStatus, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ApplicationAssignStatus, Object>>();
		Map<String, BiConsumer<ApplicationAssignStatus, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ApplicationAssignStatus, ?>>();

		attributeGetterFunctions.put("Id", ApplicationAssignStatus::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<ApplicationAssignStatus, Integer>)
				ApplicationAssignStatus::setId);
		attributeGetterFunctions.put("Name", ApplicationAssignStatus::getName);
		attributeSetterBiConsumers.put(
			"Name",
			(BiConsumer<ApplicationAssignStatus, String>)
				ApplicationAssignStatus::setName);
		attributeGetterFunctions.put(
			"Description", ApplicationAssignStatus::getDescription);
		attributeSetterBiConsumers.put(
			"Description",
			(BiConsumer<ApplicationAssignStatus, String>)
				ApplicationAssignStatus::setDescription);
		attributeGetterFunctions.put(
			"RowStatus", ApplicationAssignStatus::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<ApplicationAssignStatus, Boolean>)
				ApplicationAssignStatus::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedBy", ApplicationAssignStatus::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<ApplicationAssignStatus, String>)
				ApplicationAssignStatus::setCreatedBy);
		attributeGetterFunctions.put(
			"CreatedDate", ApplicationAssignStatus::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<ApplicationAssignStatus, Date>)
				ApplicationAssignStatus::setCreatedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", ApplicationAssignStatus::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<ApplicationAssignStatus, String>)
				ApplicationAssignStatus::setModifiedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", ApplicationAssignStatus::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<ApplicationAssignStatus, Date>)
				ApplicationAssignStatus::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public String getName() {
		if (_Name == null) {
			return "";
		}
		else {
			return _Name;
		}
	}

	@Override
	public void setName(String Name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Name = Name;
	}

	@Override
	public String getDescription() {
		if (_Description == null) {
			return "";
		}
		else {
			return _Description;
		}
	}

	@Override
	public void setDescription(String Description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Description = Description;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ApplicationAssignStatus toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ApplicationAssignStatus>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ApplicationAssignStatusImpl applicationAssignStatusImpl =
			new ApplicationAssignStatusImpl();

		applicationAssignStatusImpl.setId(getId());
		applicationAssignStatusImpl.setName(getName());
		applicationAssignStatusImpl.setDescription(getDescription());
		applicationAssignStatusImpl.setRowStatus(getRowStatus());
		applicationAssignStatusImpl.setCreatedBy(getCreatedBy());
		applicationAssignStatusImpl.setCreatedDate(getCreatedDate());
		applicationAssignStatusImpl.setModifiedBy(getModifiedBy());
		applicationAssignStatusImpl.setModifiedDate(getModifiedDate());

		applicationAssignStatusImpl.resetOriginalValues();

		return applicationAssignStatusImpl;
	}

	@Override
	public ApplicationAssignStatus cloneWithOriginalValues() {
		ApplicationAssignStatusImpl applicationAssignStatusImpl =
			new ApplicationAssignStatusImpl();

		applicationAssignStatusImpl.setId(
			this.<Integer>getColumnOriginalValue("Id"));
		applicationAssignStatusImpl.setName(
			this.<String>getColumnOriginalValue("Name"));
		applicationAssignStatusImpl.setDescription(
			this.<String>getColumnOriginalValue("Description"));
		applicationAssignStatusImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		applicationAssignStatusImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		applicationAssignStatusImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		applicationAssignStatusImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));
		applicationAssignStatusImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));

		return applicationAssignStatusImpl;
	}

	@Override
	public int compareTo(ApplicationAssignStatus applicationAssignStatus) {
		int primaryKey = applicationAssignStatus.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ApplicationAssignStatus)) {
			return false;
		}

		ApplicationAssignStatus applicationAssignStatus =
			(ApplicationAssignStatus)object;

		int primaryKey = applicationAssignStatus.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ApplicationAssignStatus> toCacheModel() {
		ApplicationAssignStatusCacheModel applicationAssignStatusCacheModel =
			new ApplicationAssignStatusCacheModel();

		applicationAssignStatusCacheModel.Id = getId();

		applicationAssignStatusCacheModel.Name = getName();

		String Name = applicationAssignStatusCacheModel.Name;

		if ((Name != null) && (Name.length() == 0)) {
			applicationAssignStatusCacheModel.Name = null;
		}

		applicationAssignStatusCacheModel.Description = getDescription();

		String Description = applicationAssignStatusCacheModel.Description;

		if ((Description != null) && (Description.length() == 0)) {
			applicationAssignStatusCacheModel.Description = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			applicationAssignStatusCacheModel.RowStatus = RowStatus;
		}

		applicationAssignStatusCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = applicationAssignStatusCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			applicationAssignStatusCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			applicationAssignStatusCacheModel.CreatedDate =
				CreatedDate.getTime();
		}
		else {
			applicationAssignStatusCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		applicationAssignStatusCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = applicationAssignStatusCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			applicationAssignStatusCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			applicationAssignStatusCacheModel.ModifiedDate =
				ModifiedDate.getTime();
		}
		else {
			applicationAssignStatusCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		return applicationAssignStatusCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ApplicationAssignStatus, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ApplicationAssignStatus, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApplicationAssignStatus, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ApplicationAssignStatus)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, ApplicationAssignStatus>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						ApplicationAssignStatus.class, ModelWrapper.class);

	}

	private int _Id;
	private String _Name;
	private String _Description;
	private Boolean _RowStatus;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<ApplicationAssignStatus, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ApplicationAssignStatus)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("Name", _Name);
		_columnOriginalValues.put("Description", _Description);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("Name", 2L);

		columnBitmasks.put("Description", 4L);

		columnBitmasks.put("RowStatus", 8L);

		columnBitmasks.put("CreatedBy", 16L);

		columnBitmasks.put("CreatedDate", 32L);

		columnBitmasks.put("ModifiedBy", 64L);

		columnBitmasks.put("ModifiedDate", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ApplicationAssignStatus _escapedModel;

}