/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.ApplicationAssign;
import com.astra.dewa.model.ApplicationAssignModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ApplicationAssign service. Represents a row in the &quot;ApplicationAssign&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ApplicationAssignModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApplicationAssignImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApplicationAssignImpl
 * @generated
 */
public class ApplicationAssignModelImpl
	extends BaseModelImpl<ApplicationAssign> implements ApplicationAssignModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a application assign model instance should use the <code>ApplicationAssign</code> interface instead.
	 */
	public static final String TABLE_NAME = "ApplicationAssign";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"ApplicationHeaderId", Types.INTEGER},
		{"ApplicationAssignStatusId", Types.INTEGER},
		{"ProfileId", Types.BIGINT}, {"StartDateOn", Types.TIMESTAMP},
		{"CompletedDateOn", Types.TIMESTAMP}, {"Notes", Types.VARCHAR},
		{"RowStatus", Types.BOOLEAN}, {"CreatedBy", Types.VARCHAR},
		{"CreatedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApplicationHeaderId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApplicationAssignStatusId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ProfileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("StartDateOn", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CompletedDateOn", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("Notes", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ApplicationAssign (Id INTEGER not null primary key IDENTITY,ApplicationHeaderId INTEGER,ApplicationAssignStatusId INTEGER,ProfileId LONG,StartDateOn DATE null,CompletedDateOn DATE null,Notes VARCHAR(75) null,RowStatus BOOLEAN,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table ApplicationAssign";

	public static final String ORDER_BY_JPQL =
		" ORDER BY applicationAssign.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ApplicationAssign.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.ApplicationAssign"));

	public ApplicationAssignModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ApplicationAssign.class;
	}

	@Override
	public String getModelClassName() {
		return ApplicationAssign.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ApplicationAssign, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ApplicationAssign, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApplicationAssign, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ApplicationAssign)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ApplicationAssign, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ApplicationAssign, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ApplicationAssign)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ApplicationAssign, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ApplicationAssign, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ApplicationAssign, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ApplicationAssign, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ApplicationAssign, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ApplicationAssign, Object>>();
		Map<String, BiConsumer<ApplicationAssign, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ApplicationAssign, ?>>();

		attributeGetterFunctions.put("Id", ApplicationAssign::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<ApplicationAssign, Integer>)ApplicationAssign::setId);
		attributeGetterFunctions.put(
			"ApplicationHeaderId", ApplicationAssign::getApplicationHeaderId);
		attributeSetterBiConsumers.put(
			"ApplicationHeaderId",
			(BiConsumer<ApplicationAssign, Integer>)
				ApplicationAssign::setApplicationHeaderId);
		attributeGetterFunctions.put(
			"ApplicationAssignStatusId",
			ApplicationAssign::getApplicationAssignStatusId);
		attributeSetterBiConsumers.put(
			"ApplicationAssignStatusId",
			(BiConsumer<ApplicationAssign, Integer>)
				ApplicationAssign::setApplicationAssignStatusId);
		attributeGetterFunctions.put(
			"ProfileId", ApplicationAssign::getProfileId);
		attributeSetterBiConsumers.put(
			"ProfileId",
			(BiConsumer<ApplicationAssign, Long>)
				ApplicationAssign::setProfileId);
		attributeGetterFunctions.put(
			"StartDateOn", ApplicationAssign::getStartDateOn);
		attributeSetterBiConsumers.put(
			"StartDateOn",
			(BiConsumer<ApplicationAssign, Date>)
				ApplicationAssign::setStartDateOn);
		attributeGetterFunctions.put(
			"CompletedDateOn", ApplicationAssign::getCompletedDateOn);
		attributeSetterBiConsumers.put(
			"CompletedDateOn",
			(BiConsumer<ApplicationAssign, Date>)
				ApplicationAssign::setCompletedDateOn);
		attributeGetterFunctions.put("Notes", ApplicationAssign::getNotes);
		attributeSetterBiConsumers.put(
			"Notes",
			(BiConsumer<ApplicationAssign, String>)ApplicationAssign::setNotes);
		attributeGetterFunctions.put(
			"RowStatus", ApplicationAssign::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<ApplicationAssign, Boolean>)
				ApplicationAssign::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedBy", ApplicationAssign::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<ApplicationAssign, String>)
				ApplicationAssign::setCreatedBy);
		attributeGetterFunctions.put(
			"CreatedDate", ApplicationAssign::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<ApplicationAssign, Date>)
				ApplicationAssign::setCreatedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", ApplicationAssign::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<ApplicationAssign, String>)
				ApplicationAssign::setModifiedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", ApplicationAssign::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<ApplicationAssign, Date>)
				ApplicationAssign::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getApplicationHeaderId() {
		return _ApplicationHeaderId;
	}

	@Override
	public void setApplicationHeaderId(int ApplicationHeaderId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApplicationHeaderId = ApplicationHeaderId;
	}

	@Override
	public int getApplicationAssignStatusId() {
		return _ApplicationAssignStatusId;
	}

	@Override
	public void setApplicationAssignStatusId(int ApplicationAssignStatusId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApplicationAssignStatusId = ApplicationAssignStatusId;
	}

	@Override
	public long getProfileId() {
		return _ProfileId;
	}

	@Override
	public void setProfileId(long ProfileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ProfileId = ProfileId;
	}

	@Override
	public Date getStartDateOn() {
		return _StartDateOn;
	}

	@Override
	public void setStartDateOn(Date StartDateOn) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_StartDateOn = StartDateOn;
	}

	@Override
	public Date getCompletedDateOn() {
		return _CompletedDateOn;
	}

	@Override
	public void setCompletedDateOn(Date CompletedDateOn) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CompletedDateOn = CompletedDateOn;
	}

	@Override
	public String getNotes() {
		if (_Notes == null) {
			return "";
		}
		else {
			return _Notes;
		}
	}

	@Override
	public void setNotes(String Notes) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Notes = Notes;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ApplicationAssign toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ApplicationAssign>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ApplicationAssignImpl applicationAssignImpl =
			new ApplicationAssignImpl();

		applicationAssignImpl.setId(getId());
		applicationAssignImpl.setApplicationHeaderId(getApplicationHeaderId());
		applicationAssignImpl.setApplicationAssignStatusId(
			getApplicationAssignStatusId());
		applicationAssignImpl.setProfileId(getProfileId());
		applicationAssignImpl.setStartDateOn(getStartDateOn());
		applicationAssignImpl.setCompletedDateOn(getCompletedDateOn());
		applicationAssignImpl.setNotes(getNotes());
		applicationAssignImpl.setRowStatus(getRowStatus());
		applicationAssignImpl.setCreatedBy(getCreatedBy());
		applicationAssignImpl.setCreatedDate(getCreatedDate());
		applicationAssignImpl.setModifiedBy(getModifiedBy());
		applicationAssignImpl.setModifiedDate(getModifiedDate());

		applicationAssignImpl.resetOriginalValues();

		return applicationAssignImpl;
	}

	@Override
	public ApplicationAssign cloneWithOriginalValues() {
		ApplicationAssignImpl applicationAssignImpl =
			new ApplicationAssignImpl();

		applicationAssignImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		applicationAssignImpl.setApplicationHeaderId(
			this.<Integer>getColumnOriginalValue("ApplicationHeaderId"));
		applicationAssignImpl.setApplicationAssignStatusId(
			this.<Integer>getColumnOriginalValue("ApplicationAssignStatusId"));
		applicationAssignImpl.setProfileId(
			this.<Long>getColumnOriginalValue("ProfileId"));
		applicationAssignImpl.setStartDateOn(
			this.<Date>getColumnOriginalValue("StartDateOn"));
		applicationAssignImpl.setCompletedDateOn(
			this.<Date>getColumnOriginalValue("CompletedDateOn"));
		applicationAssignImpl.setNotes(
			this.<String>getColumnOriginalValue("Notes"));
		applicationAssignImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		applicationAssignImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		applicationAssignImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		applicationAssignImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));
		applicationAssignImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));

		return applicationAssignImpl;
	}

	@Override
	public int compareTo(ApplicationAssign applicationAssign) {
		int primaryKey = applicationAssign.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ApplicationAssign)) {
			return false;
		}

		ApplicationAssign applicationAssign = (ApplicationAssign)object;

		int primaryKey = applicationAssign.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ApplicationAssign> toCacheModel() {
		ApplicationAssignCacheModel applicationAssignCacheModel =
			new ApplicationAssignCacheModel();

		applicationAssignCacheModel.Id = getId();

		applicationAssignCacheModel.ApplicationHeaderId =
			getApplicationHeaderId();

		applicationAssignCacheModel.ApplicationAssignStatusId =
			getApplicationAssignStatusId();

		applicationAssignCacheModel.ProfileId = getProfileId();

		Date StartDateOn = getStartDateOn();

		if (StartDateOn != null) {
			applicationAssignCacheModel.StartDateOn = StartDateOn.getTime();
		}
		else {
			applicationAssignCacheModel.StartDateOn = Long.MIN_VALUE;
		}

		Date CompletedDateOn = getCompletedDateOn();

		if (CompletedDateOn != null) {
			applicationAssignCacheModel.CompletedDateOn =
				CompletedDateOn.getTime();
		}
		else {
			applicationAssignCacheModel.CompletedDateOn = Long.MIN_VALUE;
		}

		applicationAssignCacheModel.Notes = getNotes();

		String Notes = applicationAssignCacheModel.Notes;

		if ((Notes != null) && (Notes.length() == 0)) {
			applicationAssignCacheModel.Notes = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			applicationAssignCacheModel.RowStatus = RowStatus;
		}

		applicationAssignCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = applicationAssignCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			applicationAssignCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			applicationAssignCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			applicationAssignCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		applicationAssignCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = applicationAssignCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			applicationAssignCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			applicationAssignCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			applicationAssignCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		return applicationAssignCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ApplicationAssign, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ApplicationAssign, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApplicationAssign, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ApplicationAssign)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ApplicationAssign>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ApplicationAssign.class, ModelWrapper.class);

	}

	private int _Id;
	private int _ApplicationHeaderId;
	private int _ApplicationAssignStatusId;
	private long _ProfileId;
	private Date _StartDateOn;
	private Date _CompletedDateOn;
	private String _Notes;
	private Boolean _RowStatus;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<ApplicationAssign, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ApplicationAssign)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("ApplicationHeaderId", _ApplicationHeaderId);
		_columnOriginalValues.put(
			"ApplicationAssignStatusId", _ApplicationAssignStatusId);
		_columnOriginalValues.put("ProfileId", _ProfileId);
		_columnOriginalValues.put("StartDateOn", _StartDateOn);
		_columnOriginalValues.put("CompletedDateOn", _CompletedDateOn);
		_columnOriginalValues.put("Notes", _Notes);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("ApplicationHeaderId", 2L);

		columnBitmasks.put("ApplicationAssignStatusId", 4L);

		columnBitmasks.put("ProfileId", 8L);

		columnBitmasks.put("StartDateOn", 16L);

		columnBitmasks.put("CompletedDateOn", 32L);

		columnBitmasks.put("Notes", 64L);

		columnBitmasks.put("RowStatus", 128L);

		columnBitmasks.put("CreatedBy", 256L);

		columnBitmasks.put("CreatedDate", 512L);

		columnBitmasks.put("ModifiedBy", 1024L);

		columnBitmasks.put("ModifiedDate", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ApplicationAssign _escapedModel;

}