/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.ApprovalHeaderUser;
import com.astra.dewa.model.ApprovalHeaderUserModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ApprovalHeaderUser service. Represents a row in the &quot;ApprovalHeaderUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ApprovalHeaderUserModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApprovalHeaderUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApprovalHeaderUserImpl
 * @generated
 */
public class ApprovalHeaderUserModelImpl
	extends BaseModelImpl<ApprovalHeaderUser>
	implements ApprovalHeaderUserModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a approval header user model instance should use the <code>ApprovalHeaderUser</code> interface instead.
	 */
	public static final String TABLE_NAME = "ApprovalHeaderUser";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"ApplicationAssignStatusId", Types.INTEGER},
		{"ApproverUserId", Types.BIGINT}, {"DealerId", Types.INTEGER},
		{"CabangId", Types.INTEGER}, {"RequesterName", Types.VARCHAR},
		{"RequesterEmail", Types.VARCHAR}, {"RejectReason", Types.VARCHAR},
		{"RowStatus", Types.BOOLEAN}, {"CreatedBy", Types.VARCHAR},
		{"CreatedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApplicationAssignStatusId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApproverUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("CabangId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("RequesterName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RequesterEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RejectReason", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ApprovalHeaderUser (Id INTEGER not null primary key IDENTITY,ApplicationAssignStatusId INTEGER,ApproverUserId LONG,DealerId INTEGER,CabangId INTEGER,RequesterName VARCHAR(75) null,RequesterEmail VARCHAR(75) null,RejectReason VARCHAR(75) null,RowStatus BOOLEAN,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table ApprovalHeaderUser";

	public static final String ORDER_BY_JPQL =
		" ORDER BY approvalHeaderUser.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ApprovalHeaderUser.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.ApprovalHeaderUser"));

	public ApprovalHeaderUserModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ApprovalHeaderUser.class;
	}

	@Override
	public String getModelClassName() {
		return ApprovalHeaderUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ApprovalHeaderUser, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ApprovalHeaderUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApprovalHeaderUser, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ApprovalHeaderUser)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ApprovalHeaderUser, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ApprovalHeaderUser, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ApprovalHeaderUser)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ApprovalHeaderUser, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ApprovalHeaderUser, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ApprovalHeaderUser, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ApprovalHeaderUser, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ApprovalHeaderUser, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ApprovalHeaderUser, Object>>();
		Map<String, BiConsumer<ApprovalHeaderUser, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ApprovalHeaderUser, ?>>();

		attributeGetterFunctions.put("Id", ApprovalHeaderUser::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<ApprovalHeaderUser, Integer>)ApprovalHeaderUser::setId);
		attributeGetterFunctions.put(
			"ApplicationAssignStatusId",
			ApprovalHeaderUser::getApplicationAssignStatusId);
		attributeSetterBiConsumers.put(
			"ApplicationAssignStatusId",
			(BiConsumer<ApprovalHeaderUser, Integer>)
				ApprovalHeaderUser::setApplicationAssignStatusId);
		attributeGetterFunctions.put(
			"ApproverUserId", ApprovalHeaderUser::getApproverUserId);
		attributeSetterBiConsumers.put(
			"ApproverUserId",
			(BiConsumer<ApprovalHeaderUser, Long>)
				ApprovalHeaderUser::setApproverUserId);
		attributeGetterFunctions.put(
			"DealerId", ApprovalHeaderUser::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId",
			(BiConsumer<ApprovalHeaderUser, Integer>)
				ApprovalHeaderUser::setDealerId);
		attributeGetterFunctions.put(
			"CabangId", ApprovalHeaderUser::getCabangId);
		attributeSetterBiConsumers.put(
			"CabangId",
			(BiConsumer<ApprovalHeaderUser, Integer>)
				ApprovalHeaderUser::setCabangId);
		attributeGetterFunctions.put(
			"RequesterName", ApprovalHeaderUser::getRequesterName);
		attributeSetterBiConsumers.put(
			"RequesterName",
			(BiConsumer<ApprovalHeaderUser, String>)
				ApprovalHeaderUser::setRequesterName);
		attributeGetterFunctions.put(
			"RequesterEmail", ApprovalHeaderUser::getRequesterEmail);
		attributeSetterBiConsumers.put(
			"RequesterEmail",
			(BiConsumer<ApprovalHeaderUser, String>)
				ApprovalHeaderUser::setRequesterEmail);
		attributeGetterFunctions.put(
			"RejectReason", ApprovalHeaderUser::getRejectReason);
		attributeSetterBiConsumers.put(
			"RejectReason",
			(BiConsumer<ApprovalHeaderUser, String>)
				ApprovalHeaderUser::setRejectReason);
		attributeGetterFunctions.put(
			"RowStatus", ApprovalHeaderUser::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<ApprovalHeaderUser, Boolean>)
				ApprovalHeaderUser::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedBy", ApprovalHeaderUser::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<ApprovalHeaderUser, String>)
				ApprovalHeaderUser::setCreatedBy);
		attributeGetterFunctions.put(
			"CreatedDate", ApprovalHeaderUser::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<ApprovalHeaderUser, Date>)
				ApprovalHeaderUser::setCreatedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", ApprovalHeaderUser::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<ApprovalHeaderUser, String>)
				ApprovalHeaderUser::setModifiedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", ApprovalHeaderUser::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<ApprovalHeaderUser, Date>)
				ApprovalHeaderUser::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getApplicationAssignStatusId() {
		return _ApplicationAssignStatusId;
	}

	@Override
	public void setApplicationAssignStatusId(int ApplicationAssignStatusId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApplicationAssignStatusId = ApplicationAssignStatusId;
	}

	@Override
	public long getApproverUserId() {
		return _ApproverUserId;
	}

	@Override
	public void setApproverUserId(long ApproverUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApproverUserId = ApproverUserId;
	}

	@Override
	public String getApproverUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getApproverUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setApproverUserUuid(String ApproverUserUuid) {
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public int getCabangId() {
		return _CabangId;
	}

	@Override
	public void setCabangId(int CabangId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CabangId = CabangId;
	}

	@Override
	public String getRequesterName() {
		if (_RequesterName == null) {
			return "";
		}
		else {
			return _RequesterName;
		}
	}

	@Override
	public void setRequesterName(String RequesterName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RequesterName = RequesterName;
	}

	@Override
	public String getRequesterEmail() {
		if (_RequesterEmail == null) {
			return "";
		}
		else {
			return _RequesterEmail;
		}
	}

	@Override
	public void setRequesterEmail(String RequesterEmail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RequesterEmail = RequesterEmail;
	}

	@Override
	public String getRejectReason() {
		if (_RejectReason == null) {
			return "";
		}
		else {
			return _RejectReason;
		}
	}

	@Override
	public void setRejectReason(String RejectReason) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RejectReason = RejectReason;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ApprovalHeaderUser toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ApprovalHeaderUser>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ApprovalHeaderUserImpl approvalHeaderUserImpl =
			new ApprovalHeaderUserImpl();

		approvalHeaderUserImpl.setId(getId());
		approvalHeaderUserImpl.setApplicationAssignStatusId(
			getApplicationAssignStatusId());
		approvalHeaderUserImpl.setApproverUserId(getApproverUserId());
		approvalHeaderUserImpl.setDealerId(getDealerId());
		approvalHeaderUserImpl.setCabangId(getCabangId());
		approvalHeaderUserImpl.setRequesterName(getRequesterName());
		approvalHeaderUserImpl.setRequesterEmail(getRequesterEmail());
		approvalHeaderUserImpl.setRejectReason(getRejectReason());
		approvalHeaderUserImpl.setRowStatus(getRowStatus());
		approvalHeaderUserImpl.setCreatedBy(getCreatedBy());
		approvalHeaderUserImpl.setCreatedDate(getCreatedDate());
		approvalHeaderUserImpl.setModifiedBy(getModifiedBy());
		approvalHeaderUserImpl.setModifiedDate(getModifiedDate());

		approvalHeaderUserImpl.resetOriginalValues();

		return approvalHeaderUserImpl;
	}

	@Override
	public ApprovalHeaderUser cloneWithOriginalValues() {
		ApprovalHeaderUserImpl approvalHeaderUserImpl =
			new ApprovalHeaderUserImpl();

		approvalHeaderUserImpl.setId(
			this.<Integer>getColumnOriginalValue("Id"));
		approvalHeaderUserImpl.setApplicationAssignStatusId(
			this.<Integer>getColumnOriginalValue("ApplicationAssignStatusId"));
		approvalHeaderUserImpl.setApproverUserId(
			this.<Long>getColumnOriginalValue("ApproverUserId"));
		approvalHeaderUserImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("DealerId"));
		approvalHeaderUserImpl.setCabangId(
			this.<Integer>getColumnOriginalValue("CabangId"));
		approvalHeaderUserImpl.setRequesterName(
			this.<String>getColumnOriginalValue("RequesterName"));
		approvalHeaderUserImpl.setRequesterEmail(
			this.<String>getColumnOriginalValue("RequesterEmail"));
		approvalHeaderUserImpl.setRejectReason(
			this.<String>getColumnOriginalValue("RejectReason"));
		approvalHeaderUserImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		approvalHeaderUserImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		approvalHeaderUserImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		approvalHeaderUserImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));
		approvalHeaderUserImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));

		return approvalHeaderUserImpl;
	}

	@Override
	public int compareTo(ApprovalHeaderUser approvalHeaderUser) {
		int primaryKey = approvalHeaderUser.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ApprovalHeaderUser)) {
			return false;
		}

		ApprovalHeaderUser approvalHeaderUser = (ApprovalHeaderUser)object;

		int primaryKey = approvalHeaderUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ApprovalHeaderUser> toCacheModel() {
		ApprovalHeaderUserCacheModel approvalHeaderUserCacheModel =
			new ApprovalHeaderUserCacheModel();

		approvalHeaderUserCacheModel.Id = getId();

		approvalHeaderUserCacheModel.ApplicationAssignStatusId =
			getApplicationAssignStatusId();

		approvalHeaderUserCacheModel.ApproverUserId = getApproverUserId();

		approvalHeaderUserCacheModel.DealerId = getDealerId();

		approvalHeaderUserCacheModel.CabangId = getCabangId();

		approvalHeaderUserCacheModel.RequesterName = getRequesterName();

		String RequesterName = approvalHeaderUserCacheModel.RequesterName;

		if ((RequesterName != null) && (RequesterName.length() == 0)) {
			approvalHeaderUserCacheModel.RequesterName = null;
		}

		approvalHeaderUserCacheModel.RequesterEmail = getRequesterEmail();

		String RequesterEmail = approvalHeaderUserCacheModel.RequesterEmail;

		if ((RequesterEmail != null) && (RequesterEmail.length() == 0)) {
			approvalHeaderUserCacheModel.RequesterEmail = null;
		}

		approvalHeaderUserCacheModel.RejectReason = getRejectReason();

		String RejectReason = approvalHeaderUserCacheModel.RejectReason;

		if ((RejectReason != null) && (RejectReason.length() == 0)) {
			approvalHeaderUserCacheModel.RejectReason = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			approvalHeaderUserCacheModel.RowStatus = RowStatus;
		}

		approvalHeaderUserCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = approvalHeaderUserCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			approvalHeaderUserCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			approvalHeaderUserCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			approvalHeaderUserCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		approvalHeaderUserCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = approvalHeaderUserCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			approvalHeaderUserCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			approvalHeaderUserCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			approvalHeaderUserCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		return approvalHeaderUserCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ApprovalHeaderUser, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ApprovalHeaderUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApprovalHeaderUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ApprovalHeaderUser)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ApprovalHeaderUser>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ApprovalHeaderUser.class, ModelWrapper.class);

	}

	private int _Id;
	private int _ApplicationAssignStatusId;
	private long _ApproverUserId;
	private int _DealerId;
	private int _CabangId;
	private String _RequesterName;
	private String _RequesterEmail;
	private String _RejectReason;
	private Boolean _RowStatus;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<ApprovalHeaderUser, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ApprovalHeaderUser)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put(
			"ApplicationAssignStatusId", _ApplicationAssignStatusId);
		_columnOriginalValues.put("ApproverUserId", _ApproverUserId);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("CabangId", _CabangId);
		_columnOriginalValues.put("RequesterName", _RequesterName);
		_columnOriginalValues.put("RequesterEmail", _RequesterEmail);
		_columnOriginalValues.put("RejectReason", _RejectReason);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("ApplicationAssignStatusId", 2L);

		columnBitmasks.put("ApproverUserId", 4L);

		columnBitmasks.put("DealerId", 8L);

		columnBitmasks.put("CabangId", 16L);

		columnBitmasks.put("RequesterName", 32L);

		columnBitmasks.put("RequesterEmail", 64L);

		columnBitmasks.put("RejectReason", 128L);

		columnBitmasks.put("RowStatus", 256L);

		columnBitmasks.put("CreatedBy", 512L);

		columnBitmasks.put("CreatedDate", 1024L);

		columnBitmasks.put("ModifiedBy", 2048L);

		columnBitmasks.put("ModifiedDate", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ApprovalHeaderUser _escapedModel;

}