/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.Banner;
import com.astra.dewa.model.BannerModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Banner service. Represents a row in the &quot;Banner&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BannerModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BannerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BannerImpl
 * @generated
 */
public class BannerModelImpl
	extends BaseModelImpl<Banner> implements BannerModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a banner model instance should use the <code>Banner</code> interface instead.
	 */
	public static final String TABLE_NAME = "Banner";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"IsShow", Types.BOOLEAN},
		{"FileId", Types.BIGINT}, {"FileName", Types.VARCHAR},
		{"FilePath", Types.VARCHAR}, {"RowStatus", Types.BOOLEAN},
		{"CreatedBy", Types.VARCHAR}, {"CreatedDate", Types.TIMESTAMP},
		{"ModifiedBy", Types.VARCHAR}, {"ModifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("IsShow", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("FileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FilePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Banner (Id INTEGER not null primary key IDENTITY,IsShow BOOLEAN,FileId LONG,FileName VARCHAR(75) null,FilePath VARCHAR(75) null,RowStatus BOOLEAN,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table Banner";

	public static final String ORDER_BY_JPQL = " ORDER BY banner.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY Banner.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.Banner"));

	public BannerModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Banner.class;
	}

	@Override
	public String getModelClassName() {
		return Banner.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Banner, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Banner, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Banner, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Banner)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Banner, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Banner, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Banner)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Banner, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Banner, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Banner, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Banner, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Banner, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Banner, Object>>();
		Map<String, BiConsumer<Banner, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Banner, ?>>();

		attributeGetterFunctions.put("Id", Banner::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<Banner, Integer>)Banner::setId);
		attributeGetterFunctions.put("IsShow", Banner::getIsShow);
		attributeSetterBiConsumers.put(
			"IsShow", (BiConsumer<Banner, Boolean>)Banner::setIsShow);
		attributeGetterFunctions.put("FileId", Banner::getFileId);
		attributeSetterBiConsumers.put(
			"FileId", (BiConsumer<Banner, Long>)Banner::setFileId);
		attributeGetterFunctions.put("FileName", Banner::getFileName);
		attributeSetterBiConsumers.put(
			"FileName", (BiConsumer<Banner, String>)Banner::setFileName);
		attributeGetterFunctions.put("FilePath", Banner::getFilePath);
		attributeSetterBiConsumers.put(
			"FilePath", (BiConsumer<Banner, String>)Banner::setFilePath);
		attributeGetterFunctions.put("RowStatus", Banner::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus", (BiConsumer<Banner, Boolean>)Banner::setRowStatus);
		attributeGetterFunctions.put("CreatedBy", Banner::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy", (BiConsumer<Banner, String>)Banner::setCreatedBy);
		attributeGetterFunctions.put("CreatedDate", Banner::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate", (BiConsumer<Banner, Date>)Banner::setCreatedDate);
		attributeGetterFunctions.put("ModifiedBy", Banner::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy", (BiConsumer<Banner, String>)Banner::setModifiedBy);
		attributeGetterFunctions.put("ModifiedDate", Banner::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate", (BiConsumer<Banner, Date>)Banner::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public Boolean getIsShow() {
		return _IsShow;
	}

	@Override
	public void setIsShow(Boolean IsShow) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_IsShow = IsShow;
	}

	@Override
	public Long getFileId() {
		return _FileId;
	}

	@Override
	public void setFileId(Long FileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileId = FileId;
	}

	@Override
	public String getFileName() {
		if (_FileName == null) {
			return "";
		}
		else {
			return _FileName;
		}
	}

	@Override
	public void setFileName(String FileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileName = FileName;
	}

	@Override
	public String getFilePath() {
		if (_FilePath == null) {
			return "";
		}
		else {
			return _FilePath;
		}
	}

	@Override
	public void setFilePath(String FilePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FilePath = FilePath;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Banner toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Banner>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BannerImpl bannerImpl = new BannerImpl();

		bannerImpl.setId(getId());
		bannerImpl.setIsShow(getIsShow());
		bannerImpl.setFileId(getFileId());
		bannerImpl.setFileName(getFileName());
		bannerImpl.setFilePath(getFilePath());
		bannerImpl.setRowStatus(getRowStatus());
		bannerImpl.setCreatedBy(getCreatedBy());
		bannerImpl.setCreatedDate(getCreatedDate());
		bannerImpl.setModifiedBy(getModifiedBy());
		bannerImpl.setModifiedDate(getModifiedDate());

		bannerImpl.resetOriginalValues();

		return bannerImpl;
	}

	@Override
	public Banner cloneWithOriginalValues() {
		BannerImpl bannerImpl = new BannerImpl();

		bannerImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		bannerImpl.setIsShow(this.<Boolean>getColumnOriginalValue("IsShow"));
		bannerImpl.setFileId(this.<Long>getColumnOriginalValue("FileId"));
		bannerImpl.setFileName(this.<String>getColumnOriginalValue("FileName"));
		bannerImpl.setFilePath(this.<String>getColumnOriginalValue("FilePath"));
		bannerImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		bannerImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		bannerImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		bannerImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));
		bannerImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));

		return bannerImpl;
	}

	@Override
	public int compareTo(Banner banner) {
		int primaryKey = banner.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Banner)) {
			return false;
		}

		Banner banner = (Banner)object;

		int primaryKey = banner.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Banner> toCacheModel() {
		BannerCacheModel bannerCacheModel = new BannerCacheModel();

		bannerCacheModel.Id = getId();

		Boolean IsShow = getIsShow();

		if (IsShow != null) {
			bannerCacheModel.IsShow = IsShow;
		}

		Long FileId = getFileId();

		if (FileId != null) {
			bannerCacheModel.FileId = FileId;
		}

		bannerCacheModel.FileName = getFileName();

		String FileName = bannerCacheModel.FileName;

		if ((FileName != null) && (FileName.length() == 0)) {
			bannerCacheModel.FileName = null;
		}

		bannerCacheModel.FilePath = getFilePath();

		String FilePath = bannerCacheModel.FilePath;

		if ((FilePath != null) && (FilePath.length() == 0)) {
			bannerCacheModel.FilePath = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			bannerCacheModel.RowStatus = RowStatus;
		}

		bannerCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = bannerCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			bannerCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			bannerCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			bannerCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		bannerCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = bannerCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			bannerCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			bannerCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			bannerCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		return bannerCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Banner, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Banner, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Banner, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Banner)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Banner>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Banner.class, ModelWrapper.class);

	}

	private int _Id;
	private Boolean _IsShow;
	private Long _FileId;
	private String _FileName;
	private String _FilePath;
	private Boolean _RowStatus;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<Banner, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Banner)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("IsShow", _IsShow);
		_columnOriginalValues.put("FileId", _FileId);
		_columnOriginalValues.put("FileName", _FileName);
		_columnOriginalValues.put("FilePath", _FilePath);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("IsShow", 2L);

		columnBitmasks.put("FileId", 4L);

		columnBitmasks.put("FileName", 8L);

		columnBitmasks.put("FilePath", 16L);

		columnBitmasks.put("RowStatus", 32L);

		columnBitmasks.put("CreatedBy", 64L);

		columnBitmasks.put("CreatedDate", 128L);

		columnBitmasks.put("ModifiedBy", 256L);

		columnBitmasks.put("ModifiedDate", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Banner _escapedModel;

}