/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.CalenderEventParticipant;
import com.astra.dewa.model.CalenderEventParticipantModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CalenderEventParticipant service. Represents a row in the &quot;calender_event_participant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CalenderEventParticipantModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CalenderEventParticipantImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CalenderEventParticipantImpl
 * @generated
 */
public class CalenderEventParticipantModelImpl
	extends BaseModelImpl<CalenderEventParticipant>
	implements CalenderEventParticipantModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a calender event participant model instance should use the <code>CalenderEventParticipant</code> interface instead.
	 */
	public static final String TABLE_NAME = "calender_event_participant";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"CalenderEventId", Types.INTEGER},
		{"DealerId", Types.INTEGER}, {"FullName", Types.VARCHAR},
		{"Email", Types.VARCHAR}, {"Phone", Types.VARCHAR},
		{"RowStatus", Types.BOOLEAN}, {"CreatedDate", Types.TIMESTAMP},
		{"CreatedBy", Types.VARCHAR}, {"ModifiedDate", Types.TIMESTAMP},
		{"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("CalenderEventId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("FullName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Phone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table calender_event_participant (Id INTEGER not null primary key IDENTITY,CalenderEventId INTEGER,DealerId INTEGER,FullName VARCHAR(75) null,Email VARCHAR(75) null,Phone VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table calender_event_participant";

	public static final String ORDER_BY_JPQL =
		" ORDER BY calenderEventParticipant.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY calender_event_participant.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.CalenderEventParticipant"));

	public CalenderEventParticipantModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CalenderEventParticipant.class;
	}

	@Override
	public String getModelClassName() {
		return CalenderEventParticipant.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CalenderEventParticipant, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CalenderEventParticipant, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CalenderEventParticipant, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CalenderEventParticipant)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CalenderEventParticipant, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CalenderEventParticipant, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CalenderEventParticipant)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CalenderEventParticipant, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CalenderEventParticipant, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<CalenderEventParticipant, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<CalenderEventParticipant, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<CalenderEventParticipant, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<CalenderEventParticipant, Object>>();
		Map<String, BiConsumer<CalenderEventParticipant, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<CalenderEventParticipant, ?>>();

		attributeGetterFunctions.put("Id", CalenderEventParticipant::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<CalenderEventParticipant, Integer>)
				CalenderEventParticipant::setId);
		attributeGetterFunctions.put(
			"CalenderEventId", CalenderEventParticipant::getCalenderEventId);
		attributeSetterBiConsumers.put(
			"CalenderEventId",
			(BiConsumer<CalenderEventParticipant, Integer>)
				CalenderEventParticipant::setCalenderEventId);
		attributeGetterFunctions.put(
			"DealerId", CalenderEventParticipant::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId",
			(BiConsumer<CalenderEventParticipant, Integer>)
				CalenderEventParticipant::setDealerId);
		attributeGetterFunctions.put(
			"FullName", CalenderEventParticipant::getFullName);
		attributeSetterBiConsumers.put(
			"FullName",
			(BiConsumer<CalenderEventParticipant, String>)
				CalenderEventParticipant::setFullName);
		attributeGetterFunctions.put(
			"Email", CalenderEventParticipant::getEmail);
		attributeSetterBiConsumers.put(
			"Email",
			(BiConsumer<CalenderEventParticipant, String>)
				CalenderEventParticipant::setEmail);
		attributeGetterFunctions.put(
			"Phone", CalenderEventParticipant::getPhone);
		attributeSetterBiConsumers.put(
			"Phone",
			(BiConsumer<CalenderEventParticipant, String>)
				CalenderEventParticipant::setPhone);
		attributeGetterFunctions.put(
			"RowStatus", CalenderEventParticipant::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<CalenderEventParticipant, Boolean>)
				CalenderEventParticipant::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", CalenderEventParticipant::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<CalenderEventParticipant, Date>)
				CalenderEventParticipant::setCreatedDate);
		attributeGetterFunctions.put(
			"CreatedBy", CalenderEventParticipant::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<CalenderEventParticipant, String>)
				CalenderEventParticipant::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", CalenderEventParticipant::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<CalenderEventParticipant, Date>)
				CalenderEventParticipant::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", CalenderEventParticipant::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<CalenderEventParticipant, String>)
				CalenderEventParticipant::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getCalenderEventId() {
		return _CalenderEventId;
	}

	@Override
	public void setCalenderEventId(int CalenderEventId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CalenderEventId = CalenderEventId;
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public String getFullName() {
		if (_FullName == null) {
			return "";
		}
		else {
			return _FullName;
		}
	}

	@Override
	public void setFullName(String FullName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FullName = FullName;
	}

	@Override
	public String getEmail() {
		if (_Email == null) {
			return "";
		}
		else {
			return _Email;
		}
	}

	@Override
	public void setEmail(String Email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Email = Email;
	}

	@Override
	public String getPhone() {
		if (_Phone == null) {
			return "";
		}
		else {
			return _Phone;
		}
	}

	@Override
	public void setPhone(String Phone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Phone = Phone;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public CalenderEventParticipant toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CalenderEventParticipant>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CalenderEventParticipantImpl calenderEventParticipantImpl =
			new CalenderEventParticipantImpl();

		calenderEventParticipantImpl.setId(getId());
		calenderEventParticipantImpl.setCalenderEventId(getCalenderEventId());
		calenderEventParticipantImpl.setDealerId(getDealerId());
		calenderEventParticipantImpl.setFullName(getFullName());
		calenderEventParticipantImpl.setEmail(getEmail());
		calenderEventParticipantImpl.setPhone(getPhone());
		calenderEventParticipantImpl.setRowStatus(getRowStatus());
		calenderEventParticipantImpl.setCreatedDate(getCreatedDate());
		calenderEventParticipantImpl.setCreatedBy(getCreatedBy());
		calenderEventParticipantImpl.setModifiedDate(getModifiedDate());
		calenderEventParticipantImpl.setModifiedBy(getModifiedBy());

		calenderEventParticipantImpl.resetOriginalValues();

		return calenderEventParticipantImpl;
	}

	@Override
	public CalenderEventParticipant cloneWithOriginalValues() {
		CalenderEventParticipantImpl calenderEventParticipantImpl =
			new CalenderEventParticipantImpl();

		calenderEventParticipantImpl.setId(
			this.<Integer>getColumnOriginalValue("Id"));
		calenderEventParticipantImpl.setCalenderEventId(
			this.<Integer>getColumnOriginalValue("CalenderEventId"));
		calenderEventParticipantImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("DealerId"));
		calenderEventParticipantImpl.setFullName(
			this.<String>getColumnOriginalValue("FullName"));
		calenderEventParticipantImpl.setEmail(
			this.<String>getColumnOriginalValue("Email"));
		calenderEventParticipantImpl.setPhone(
			this.<String>getColumnOriginalValue("Phone"));
		calenderEventParticipantImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		calenderEventParticipantImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		calenderEventParticipantImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		calenderEventParticipantImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		calenderEventParticipantImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return calenderEventParticipantImpl;
	}

	@Override
	public int compareTo(CalenderEventParticipant calenderEventParticipant) {
		int primaryKey = calenderEventParticipant.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CalenderEventParticipant)) {
			return false;
		}

		CalenderEventParticipant calenderEventParticipant =
			(CalenderEventParticipant)object;

		int primaryKey = calenderEventParticipant.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CalenderEventParticipant> toCacheModel() {
		CalenderEventParticipantCacheModel calenderEventParticipantCacheModel =
			new CalenderEventParticipantCacheModel();

		calenderEventParticipantCacheModel.Id = getId();

		calenderEventParticipantCacheModel.CalenderEventId =
			getCalenderEventId();

		calenderEventParticipantCacheModel.DealerId = getDealerId();

		calenderEventParticipantCacheModel.FullName = getFullName();

		String FullName = calenderEventParticipantCacheModel.FullName;

		if ((FullName != null) && (FullName.length() == 0)) {
			calenderEventParticipantCacheModel.FullName = null;
		}

		calenderEventParticipantCacheModel.Email = getEmail();

		String Email = calenderEventParticipantCacheModel.Email;

		if ((Email != null) && (Email.length() == 0)) {
			calenderEventParticipantCacheModel.Email = null;
		}

		calenderEventParticipantCacheModel.Phone = getPhone();

		String Phone = calenderEventParticipantCacheModel.Phone;

		if ((Phone != null) && (Phone.length() == 0)) {
			calenderEventParticipantCacheModel.Phone = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			calenderEventParticipantCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			calenderEventParticipantCacheModel.CreatedDate =
				CreatedDate.getTime();
		}
		else {
			calenderEventParticipantCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		calenderEventParticipantCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = calenderEventParticipantCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			calenderEventParticipantCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			calenderEventParticipantCacheModel.ModifiedDate =
				ModifiedDate.getTime();
		}
		else {
			calenderEventParticipantCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		calenderEventParticipantCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = calenderEventParticipantCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			calenderEventParticipantCacheModel.ModifiedBy = null;
		}

		return calenderEventParticipantCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CalenderEventParticipant, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CalenderEventParticipant, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CalenderEventParticipant, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CalenderEventParticipant)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CalenderEventParticipant>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						CalenderEventParticipant.class, ModelWrapper.class);

	}

	private int _Id;
	private int _CalenderEventId;
	private int _DealerId;
	private String _FullName;
	private String _Email;
	private String _Phone;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<CalenderEventParticipant, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CalenderEventParticipant)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("CalenderEventId", _CalenderEventId);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("FullName", _FullName);
		_columnOriginalValues.put("Email", _Email);
		_columnOriginalValues.put("Phone", _Phone);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("CalenderEventId", 2L);

		columnBitmasks.put("DealerId", 4L);

		columnBitmasks.put("FullName", 8L);

		columnBitmasks.put("Email", 16L);

		columnBitmasks.put("Phone", 32L);

		columnBitmasks.put("RowStatus", 64L);

		columnBitmasks.put("CreatedDate", 128L);

		columnBitmasks.put("CreatedBy", 256L);

		columnBitmasks.put("ModifiedDate", 512L);

		columnBitmasks.put("ModifiedBy", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CalenderEventParticipant _escapedModel;

}