/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.Common;
import com.astra.dewa.model.CommonModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Common service. Represents a row in the &quot;common&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CommonModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommonImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CommonImpl
 * @generated
 */
public class CommonModelImpl
	extends BaseModelImpl<Common> implements CommonModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a common model instance should use the <code>Common</code> interface instead.
	 */
	public static final String TABLE_NAME = "common";

	public static final Object[][] TABLE_COLUMNS = {
		{"CommonKey", Types.VARCHAR}, {"CommonCode", Types.VARCHAR},
		{"CommonDesc1", Types.VARCHAR}, {"CommonDesc2", Types.VARCHAR},
		{"CommonDesc3", Types.VARCHAR}, {"CommonDesc4", Types.VARCHAR},
		{"CommonDesc5", Types.VARCHAR}, {"Sequence", Types.INTEGER},
		{"IsActive", Types.BOOLEAN}, {"CreatedBy", Types.VARCHAR},
		{"CreatedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("CommonKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CommonCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CommonDesc1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CommonDesc2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CommonDesc3", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CommonDesc4", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CommonDesc5", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Sequence", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("IsActive", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table common (CommonKey VARCHAR(75) not null primary key,CommonCode VARCHAR(75) null,CommonDesc1 VARCHAR(75) null,CommonDesc2 VARCHAR(75) null,CommonDesc3 VARCHAR(75) null,CommonDesc4 VARCHAR(75) null,CommonDesc5 VARCHAR(75) null,Sequence INTEGER,IsActive BOOLEAN,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table common";

	public static final String ORDER_BY_JPQL = " ORDER BY common.CommonKey ASC";

	public static final String ORDER_BY_SQL = " ORDER BY common.CommonKey ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMMONKEY_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.Common"));

	public CommonModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _CommonKey;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setCommonKey(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _CommonKey;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Common.class;
	}

	@Override
	public String getModelClassName() {
		return Common.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Common, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Common, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Common, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Common)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Common, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Common, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Common)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Common, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Common, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Common, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Common, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Common, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Common, Object>>();
		Map<String, BiConsumer<Common, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Common, ?>>();

		attributeGetterFunctions.put("CommonKey", Common::getCommonKey);
		attributeSetterBiConsumers.put(
			"CommonKey", (BiConsumer<Common, String>)Common::setCommonKey);
		attributeGetterFunctions.put("CommonCode", Common::getCommonCode);
		attributeSetterBiConsumers.put(
			"CommonCode", (BiConsumer<Common, String>)Common::setCommonCode);
		attributeGetterFunctions.put("CommonDesc1", Common::getCommonDesc1);
		attributeSetterBiConsumers.put(
			"CommonDesc1", (BiConsumer<Common, String>)Common::setCommonDesc1);
		attributeGetterFunctions.put("CommonDesc2", Common::getCommonDesc2);
		attributeSetterBiConsumers.put(
			"CommonDesc2", (BiConsumer<Common, String>)Common::setCommonDesc2);
		attributeGetterFunctions.put("CommonDesc3", Common::getCommonDesc3);
		attributeSetterBiConsumers.put(
			"CommonDesc3", (BiConsumer<Common, String>)Common::setCommonDesc3);
		attributeGetterFunctions.put("CommonDesc4", Common::getCommonDesc4);
		attributeSetterBiConsumers.put(
			"CommonDesc4", (BiConsumer<Common, String>)Common::setCommonDesc4);
		attributeGetterFunctions.put("CommonDesc5", Common::getCommonDesc5);
		attributeSetterBiConsumers.put(
			"CommonDesc5", (BiConsumer<Common, String>)Common::setCommonDesc5);
		attributeGetterFunctions.put("Sequence", Common::getSequence);
		attributeSetterBiConsumers.put(
			"Sequence", (BiConsumer<Common, Integer>)Common::setSequence);
		attributeGetterFunctions.put("IsActive", Common::getIsActive);
		attributeSetterBiConsumers.put(
			"IsActive", (BiConsumer<Common, Boolean>)Common::setIsActive);
		attributeGetterFunctions.put("CreatedBy", Common::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy", (BiConsumer<Common, String>)Common::setCreatedBy);
		attributeGetterFunctions.put("CreatedDate", Common::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate", (BiConsumer<Common, Date>)Common::setCreatedDate);
		attributeGetterFunctions.put("ModifiedBy", Common::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy", (BiConsumer<Common, String>)Common::setModifiedBy);
		attributeGetterFunctions.put("ModifiedDate", Common::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate", (BiConsumer<Common, Date>)Common::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getCommonKey() {
		if (_CommonKey == null) {
			return "";
		}
		else {
			return _CommonKey;
		}
	}

	@Override
	public void setCommonKey(String CommonKey) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CommonKey = CommonKey;
	}

	@Override
	public String getCommonCode() {
		if (_CommonCode == null) {
			return "";
		}
		else {
			return _CommonCode;
		}
	}

	@Override
	public void setCommonCode(String CommonCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CommonCode = CommonCode;
	}

	@Override
	public String getCommonDesc1() {
		if (_CommonDesc1 == null) {
			return "";
		}
		else {
			return _CommonDesc1;
		}
	}

	@Override
	public void setCommonDesc1(String CommonDesc1) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CommonDesc1 = CommonDesc1;
	}

	@Override
	public String getCommonDesc2() {
		if (_CommonDesc2 == null) {
			return "";
		}
		else {
			return _CommonDesc2;
		}
	}

	@Override
	public void setCommonDesc2(String CommonDesc2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CommonDesc2 = CommonDesc2;
	}

	@Override
	public String getCommonDesc3() {
		if (_CommonDesc3 == null) {
			return "";
		}
		else {
			return _CommonDesc3;
		}
	}

	@Override
	public void setCommonDesc3(String CommonDesc3) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CommonDesc3 = CommonDesc3;
	}

	@Override
	public String getCommonDesc4() {
		if (_CommonDesc4 == null) {
			return "";
		}
		else {
			return _CommonDesc4;
		}
	}

	@Override
	public void setCommonDesc4(String CommonDesc4) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CommonDesc4 = CommonDesc4;
	}

	@Override
	public String getCommonDesc5() {
		if (_CommonDesc5 == null) {
			return "";
		}
		else {
			return _CommonDesc5;
		}
	}

	@Override
	public void setCommonDesc5(String CommonDesc5) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CommonDesc5 = CommonDesc5;
	}

	@Override
	public int getSequence() {
		return _Sequence;
	}

	@Override
	public void setSequence(int Sequence) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Sequence = Sequence;
	}

	@Override
	public boolean getIsActive() {
		return _IsActive;
	}

	@Override
	public boolean isIsActive() {
		return _IsActive;
	}

	@Override
	public void setIsActive(boolean IsActive) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_IsActive = IsActive;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Common toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Common>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommonImpl commonImpl = new CommonImpl();

		commonImpl.setCommonKey(getCommonKey());
		commonImpl.setCommonCode(getCommonCode());
		commonImpl.setCommonDesc1(getCommonDesc1());
		commonImpl.setCommonDesc2(getCommonDesc2());
		commonImpl.setCommonDesc3(getCommonDesc3());
		commonImpl.setCommonDesc4(getCommonDesc4());
		commonImpl.setCommonDesc5(getCommonDesc5());
		commonImpl.setSequence(getSequence());
		commonImpl.setIsActive(isIsActive());
		commonImpl.setCreatedBy(getCreatedBy());
		commonImpl.setCreatedDate(getCreatedDate());
		commonImpl.setModifiedBy(getModifiedBy());
		commonImpl.setModifiedDate(getModifiedDate());

		commonImpl.resetOriginalValues();

		return commonImpl;
	}

	@Override
	public Common cloneWithOriginalValues() {
		CommonImpl commonImpl = new CommonImpl();

		commonImpl.setCommonKey(
			this.<String>getColumnOriginalValue("CommonKey"));
		commonImpl.setCommonCode(
			this.<String>getColumnOriginalValue("CommonCode"));
		commonImpl.setCommonDesc1(
			this.<String>getColumnOriginalValue("CommonDesc1"));
		commonImpl.setCommonDesc2(
			this.<String>getColumnOriginalValue("CommonDesc2"));
		commonImpl.setCommonDesc3(
			this.<String>getColumnOriginalValue("CommonDesc3"));
		commonImpl.setCommonDesc4(
			this.<String>getColumnOriginalValue("CommonDesc4"));
		commonImpl.setCommonDesc5(
			this.<String>getColumnOriginalValue("CommonDesc5"));
		commonImpl.setSequence(
			this.<Integer>getColumnOriginalValue("Sequence"));
		commonImpl.setIsActive(
			this.<Boolean>getColumnOriginalValue("IsActive"));
		commonImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		commonImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		commonImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));
		commonImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));

		return commonImpl;
	}

	@Override
	public int compareTo(Common common) {
		String primaryKey = common.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Common)) {
			return false;
		}

		Common common = (Common)object;

		String primaryKey = common.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Common> toCacheModel() {
		CommonCacheModel commonCacheModel = new CommonCacheModel();

		commonCacheModel.CommonKey = getCommonKey();

		String CommonKey = commonCacheModel.CommonKey;

		if ((CommonKey != null) && (CommonKey.length() == 0)) {
			commonCacheModel.CommonKey = null;
		}

		commonCacheModel.CommonCode = getCommonCode();

		String CommonCode = commonCacheModel.CommonCode;

		if ((CommonCode != null) && (CommonCode.length() == 0)) {
			commonCacheModel.CommonCode = null;
		}

		commonCacheModel.CommonDesc1 = getCommonDesc1();

		String CommonDesc1 = commonCacheModel.CommonDesc1;

		if ((CommonDesc1 != null) && (CommonDesc1.length() == 0)) {
			commonCacheModel.CommonDesc1 = null;
		}

		commonCacheModel.CommonDesc2 = getCommonDesc2();

		String CommonDesc2 = commonCacheModel.CommonDesc2;

		if ((CommonDesc2 != null) && (CommonDesc2.length() == 0)) {
			commonCacheModel.CommonDesc2 = null;
		}

		commonCacheModel.CommonDesc3 = getCommonDesc3();

		String CommonDesc3 = commonCacheModel.CommonDesc3;

		if ((CommonDesc3 != null) && (CommonDesc3.length() == 0)) {
			commonCacheModel.CommonDesc3 = null;
		}

		commonCacheModel.CommonDesc4 = getCommonDesc4();

		String CommonDesc4 = commonCacheModel.CommonDesc4;

		if ((CommonDesc4 != null) && (CommonDesc4.length() == 0)) {
			commonCacheModel.CommonDesc4 = null;
		}

		commonCacheModel.CommonDesc5 = getCommonDesc5();

		String CommonDesc5 = commonCacheModel.CommonDesc5;

		if ((CommonDesc5 != null) && (CommonDesc5.length() == 0)) {
			commonCacheModel.CommonDesc5 = null;
		}

		commonCacheModel.Sequence = getSequence();

		commonCacheModel.IsActive = isIsActive();

		commonCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = commonCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			commonCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			commonCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			commonCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		commonCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = commonCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			commonCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			commonCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			commonCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		return commonCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Common, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Common, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Common, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Common)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Common>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Common.class, ModelWrapper.class);

	}

	private String _CommonKey;
	private String _CommonCode;
	private String _CommonDesc1;
	private String _CommonDesc2;
	private String _CommonDesc3;
	private String _CommonDesc4;
	private String _CommonDesc5;
	private int _Sequence;
	private boolean _IsActive;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<Common, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Common)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("CommonKey", _CommonKey);
		_columnOriginalValues.put("CommonCode", _CommonCode);
		_columnOriginalValues.put("CommonDesc1", _CommonDesc1);
		_columnOriginalValues.put("CommonDesc2", _CommonDesc2);
		_columnOriginalValues.put("CommonDesc3", _CommonDesc3);
		_columnOriginalValues.put("CommonDesc4", _CommonDesc4);
		_columnOriginalValues.put("CommonDesc5", _CommonDesc5);
		_columnOriginalValues.put("Sequence", _Sequence);
		_columnOriginalValues.put("IsActive", _IsActive);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("CommonKey", 1L);

		columnBitmasks.put("CommonCode", 2L);

		columnBitmasks.put("CommonDesc1", 4L);

		columnBitmasks.put("CommonDesc2", 8L);

		columnBitmasks.put("CommonDesc3", 16L);

		columnBitmasks.put("CommonDesc4", 32L);

		columnBitmasks.put("CommonDesc5", 64L);

		columnBitmasks.put("Sequence", 128L);

		columnBitmasks.put("IsActive", 256L);

		columnBitmasks.put("CreatedBy", 512L);

		columnBitmasks.put("CreatedDate", 1024L);

		columnBitmasks.put("ModifiedBy", 2048L);

		columnBitmasks.put("ModifiedDate", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Common _escapedModel;

}