/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.EmailDomain;
import com.astra.dewa.model.EmailDomainModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmailDomain service. Represents a row in the &quot;email_domain&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmailDomainModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmailDomainImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmailDomainImpl
 * @generated
 */
public class EmailDomainModelImpl
	extends BaseModelImpl<EmailDomain> implements EmailDomainModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a email domain model instance should use the <code>EmailDomain</code> interface instead.
	 */
	public static final String TABLE_NAME = "email_domain";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"DomainName", Types.VARCHAR},
		{"Category", Types.VARCHAR}, {"RowStatus", Types.BOOLEAN},
		{"CreatedBy", Types.VARCHAR}, {"CreatedDate", Types.TIMESTAMP},
		{"ModifiedBy", Types.VARCHAR}, {"ModifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("DomainName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Category", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table email_domain (Id INTEGER not null primary key IDENTITY,DomainName VARCHAR(75) null,Category VARCHAR(75) null,RowStatus BOOLEAN,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table email_domain";

	public static final String ORDER_BY_JPQL = " ORDER BY emailDomain.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY email_domain.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.EmailDomain"));

	public EmailDomainModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmailDomain.class;
	}

	@Override
	public String getModelClassName() {
		return EmailDomain.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmailDomain, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmailDomain, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmailDomain, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmailDomain)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmailDomain, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmailDomain, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmailDomain)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmailDomain, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmailDomain, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<EmailDomain, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EmailDomain, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EmailDomain, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<EmailDomain, Object>>();
		Map<String, BiConsumer<EmailDomain, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<EmailDomain, ?>>();

		attributeGetterFunctions.put("Id", EmailDomain::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<EmailDomain, Integer>)EmailDomain::setId);
		attributeGetterFunctions.put("DomainName", EmailDomain::getDomainName);
		attributeSetterBiConsumers.put(
			"DomainName",
			(BiConsumer<EmailDomain, String>)EmailDomain::setDomainName);
		attributeGetterFunctions.put("Category", EmailDomain::getCategory);
		attributeSetterBiConsumers.put(
			"Category",
			(BiConsumer<EmailDomain, String>)EmailDomain::setCategory);
		attributeGetterFunctions.put("RowStatus", EmailDomain::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<EmailDomain, Boolean>)EmailDomain::setRowStatus);
		attributeGetterFunctions.put("CreatedBy", EmailDomain::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<EmailDomain, String>)EmailDomain::setCreatedBy);
		attributeGetterFunctions.put(
			"CreatedDate", EmailDomain::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<EmailDomain, Date>)EmailDomain::setCreatedDate);
		attributeGetterFunctions.put("ModifiedBy", EmailDomain::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<EmailDomain, String>)EmailDomain::setModifiedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", EmailDomain::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<EmailDomain, Date>)EmailDomain::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public String getDomainName() {
		if (_DomainName == null) {
			return "";
		}
		else {
			return _DomainName;
		}
	}

	@Override
	public void setDomainName(String DomainName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DomainName = DomainName;
	}

	@Override
	public String getCategory() {
		if (_Category == null) {
			return "";
		}
		else {
			return _Category;
		}
	}

	@Override
	public void setCategory(String Category) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Category = Category;
	}

	@Override
	public boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public boolean isRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public EmailDomain toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmailDomain>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmailDomainImpl emailDomainImpl = new EmailDomainImpl();

		emailDomainImpl.setId(getId());
		emailDomainImpl.setDomainName(getDomainName());
		emailDomainImpl.setCategory(getCategory());
		emailDomainImpl.setRowStatus(isRowStatus());
		emailDomainImpl.setCreatedBy(getCreatedBy());
		emailDomainImpl.setCreatedDate(getCreatedDate());
		emailDomainImpl.setModifiedBy(getModifiedBy());
		emailDomainImpl.setModifiedDate(getModifiedDate());

		emailDomainImpl.resetOriginalValues();

		return emailDomainImpl;
	}

	@Override
	public EmailDomain cloneWithOriginalValues() {
		EmailDomainImpl emailDomainImpl = new EmailDomainImpl();

		emailDomainImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		emailDomainImpl.setDomainName(
			this.<String>getColumnOriginalValue("DomainName"));
		emailDomainImpl.setCategory(
			this.<String>getColumnOriginalValue("Category"));
		emailDomainImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		emailDomainImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		emailDomainImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		emailDomainImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));
		emailDomainImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));

		return emailDomainImpl;
	}

	@Override
	public int compareTo(EmailDomain emailDomain) {
		int primaryKey = emailDomain.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmailDomain)) {
			return false;
		}

		EmailDomain emailDomain = (EmailDomain)object;

		int primaryKey = emailDomain.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmailDomain> toCacheModel() {
		EmailDomainCacheModel emailDomainCacheModel =
			new EmailDomainCacheModel();

		emailDomainCacheModel.Id = getId();

		emailDomainCacheModel.DomainName = getDomainName();

		String DomainName = emailDomainCacheModel.DomainName;

		if ((DomainName != null) && (DomainName.length() == 0)) {
			emailDomainCacheModel.DomainName = null;
		}

		emailDomainCacheModel.Category = getCategory();

		String Category = emailDomainCacheModel.Category;

		if ((Category != null) && (Category.length() == 0)) {
			emailDomainCacheModel.Category = null;
		}

		emailDomainCacheModel.RowStatus = isRowStatus();

		emailDomainCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = emailDomainCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			emailDomainCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			emailDomainCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			emailDomainCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		emailDomainCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = emailDomainCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			emailDomainCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			emailDomainCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			emailDomainCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		return emailDomainCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmailDomain, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmailDomain, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmailDomain, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((EmailDomain)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmailDomain>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EmailDomain.class, ModelWrapper.class);

	}

	private int _Id;
	private String _DomainName;
	private String _Category;
	private boolean _RowStatus;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<EmailDomain, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmailDomain)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("DomainName", _DomainName);
		_columnOriginalValues.put("Category", _Category);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("DomainName", 2L);

		columnBitmasks.put("Category", 4L);

		columnBitmasks.put("RowStatus", 8L);

		columnBitmasks.put("CreatedBy", 16L);

		columnBitmasks.put("CreatedDate", 32L);

		columnBitmasks.put("ModifiedBy", 64L);

		columnBitmasks.put("ModifiedDate", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmailDomain _escapedModel;

}