/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.FakturIndirect;
import com.astra.dewa.model.FakturIndirectModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FakturIndirect service. Represents a row in the &quot;faktur_indirect&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FakturIndirectModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FakturIndirectImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FakturIndirectImpl
 * @generated
 */
public class FakturIndirectModelImpl
	extends BaseModelImpl<FakturIndirect> implements FakturIndirectModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a faktur indirect model instance should use the <code>FakturIndirect</code> interface instead.
	 */
	public static final String TABLE_NAME = "faktur_indirect";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"DealerId", Types.INTEGER},
		{"Keterangan", Types.VARCHAR}, {"InvoiceDate", Types.TIMESTAMP},
		{"UploadDate", Types.TIMESTAMP}, {"FileId", Types.BIGINT},
		{"FileName", Types.VARCHAR}, {"FilePath", Types.VARCHAR},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR},
		{"RowStatus", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Keterangan", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("InvoiceDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("UploadDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("FileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FilePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table faktur_indirect (Id INTEGER not null primary key IDENTITY,DealerId INTEGER,Keterangan VARCHAR(75) null,InvoiceDate DATE null,UploadDate DATE null,FileId LONG,FileName VARCHAR(75) null,FilePath VARCHAR(75) null,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null,RowStatus BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table faktur_indirect";

	public static final String ORDER_BY_JPQL =
		" ORDER BY fakturIndirect.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY faktur_indirect.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.FakturIndirect"));

	public FakturIndirectModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FakturIndirect.class;
	}

	@Override
	public String getModelClassName() {
		return FakturIndirect.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FakturIndirect, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FakturIndirect, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FakturIndirect, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((FakturIndirect)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FakturIndirect, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FakturIndirect, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FakturIndirect)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FakturIndirect, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FakturIndirect, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<FakturIndirect, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<FakturIndirect, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<FakturIndirect, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<FakturIndirect, Object>>();
		Map<String, BiConsumer<FakturIndirect, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<FakturIndirect, ?>>();

		attributeGetterFunctions.put("Id", FakturIndirect::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<FakturIndirect, Integer>)FakturIndirect::setId);
		attributeGetterFunctions.put("DealerId", FakturIndirect::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId",
			(BiConsumer<FakturIndirect, Integer>)FakturIndirect::setDealerId);
		attributeGetterFunctions.put(
			"Keterangan", FakturIndirect::getKeterangan);
		attributeSetterBiConsumers.put(
			"Keterangan",
			(BiConsumer<FakturIndirect, String>)FakturIndirect::setKeterangan);
		attributeGetterFunctions.put(
			"InvoiceDate", FakturIndirect::getInvoiceDate);
		attributeSetterBiConsumers.put(
			"InvoiceDate",
			(BiConsumer<FakturIndirect, Date>)FakturIndirect::setInvoiceDate);
		attributeGetterFunctions.put(
			"UploadDate", FakturIndirect::getUploadDate);
		attributeSetterBiConsumers.put(
			"UploadDate",
			(BiConsumer<FakturIndirect, Date>)FakturIndirect::setUploadDate);
		attributeGetterFunctions.put("FileId", FakturIndirect::getFileId);
		attributeSetterBiConsumers.put(
			"FileId",
			(BiConsumer<FakturIndirect, Long>)FakturIndirect::setFileId);
		attributeGetterFunctions.put("FileName", FakturIndirect::getFileName);
		attributeSetterBiConsumers.put(
			"FileName",
			(BiConsumer<FakturIndirect, String>)FakturIndirect::setFileName);
		attributeGetterFunctions.put("FilePath", FakturIndirect::getFilePath);
		attributeSetterBiConsumers.put(
			"FilePath",
			(BiConsumer<FakturIndirect, String>)FakturIndirect::setFilePath);
		attributeGetterFunctions.put(
			"CreatedDate", FakturIndirect::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<FakturIndirect, Date>)FakturIndirect::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", FakturIndirect::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<FakturIndirect, String>)FakturIndirect::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", FakturIndirect::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<FakturIndirect, Date>)FakturIndirect::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", FakturIndirect::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<FakturIndirect, String>)FakturIndirect::setModifiedBy);
		attributeGetterFunctions.put("RowStatus", FakturIndirect::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<FakturIndirect, Boolean>)FakturIndirect::setRowStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public String getKeterangan() {
		if (_Keterangan == null) {
			return "";
		}
		else {
			return _Keterangan;
		}
	}

	@Override
	public void setKeterangan(String Keterangan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Keterangan = Keterangan;
	}

	@Override
	public Date getInvoiceDate() {
		return _InvoiceDate;
	}

	@Override
	public void setInvoiceDate(Date InvoiceDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_InvoiceDate = InvoiceDate;
	}

	@Override
	public Date getUploadDate() {
		return _UploadDate;
	}

	@Override
	public void setUploadDate(Date UploadDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_UploadDate = UploadDate;
	}

	@Override
	public Long getFileId() {
		return _FileId;
	}

	@Override
	public void setFileId(Long FileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileId = FileId;
	}

	@Override
	public String getFileName() {
		if (_FileName == null) {
			return "";
		}
		else {
			return _FileName;
		}
	}

	@Override
	public void setFileName(String FileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileName = FileName;
	}

	@Override
	public String getFilePath() {
		if (_FilePath == null) {
			return "";
		}
		else {
			return _FilePath;
		}
	}

	@Override
	public void setFilePath(String FilePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FilePath = FilePath;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	@Override
	public boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public boolean isRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public FakturIndirect toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FakturIndirect>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FakturIndirectImpl fakturIndirectImpl = new FakturIndirectImpl();

		fakturIndirectImpl.setId(getId());
		fakturIndirectImpl.setDealerId(getDealerId());
		fakturIndirectImpl.setKeterangan(getKeterangan());
		fakturIndirectImpl.setInvoiceDate(getInvoiceDate());
		fakturIndirectImpl.setUploadDate(getUploadDate());
		fakturIndirectImpl.setFileId(getFileId());
		fakturIndirectImpl.setFileName(getFileName());
		fakturIndirectImpl.setFilePath(getFilePath());
		fakturIndirectImpl.setCreatedDate(getCreatedDate());
		fakturIndirectImpl.setCreatedBy(getCreatedBy());
		fakturIndirectImpl.setModifiedDate(getModifiedDate());
		fakturIndirectImpl.setModifiedBy(getModifiedBy());
		fakturIndirectImpl.setRowStatus(isRowStatus());

		fakturIndirectImpl.resetOriginalValues();

		return fakturIndirectImpl;
	}

	@Override
	public FakturIndirect cloneWithOriginalValues() {
		FakturIndirectImpl fakturIndirectImpl = new FakturIndirectImpl();

		fakturIndirectImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		fakturIndirectImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("DealerId"));
		fakturIndirectImpl.setKeterangan(
			this.<String>getColumnOriginalValue("Keterangan"));
		fakturIndirectImpl.setInvoiceDate(
			this.<Date>getColumnOriginalValue("InvoiceDate"));
		fakturIndirectImpl.setUploadDate(
			this.<Date>getColumnOriginalValue("UploadDate"));
		fakturIndirectImpl.setFileId(
			this.<Long>getColumnOriginalValue("FileId"));
		fakturIndirectImpl.setFileName(
			this.<String>getColumnOriginalValue("FileName"));
		fakturIndirectImpl.setFilePath(
			this.<String>getColumnOriginalValue("FilePath"));
		fakturIndirectImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		fakturIndirectImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		fakturIndirectImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		fakturIndirectImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));
		fakturIndirectImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));

		return fakturIndirectImpl;
	}

	@Override
	public int compareTo(FakturIndirect fakturIndirect) {
		int primaryKey = fakturIndirect.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FakturIndirect)) {
			return false;
		}

		FakturIndirect fakturIndirect = (FakturIndirect)object;

		int primaryKey = fakturIndirect.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FakturIndirect> toCacheModel() {
		FakturIndirectCacheModel fakturIndirectCacheModel =
			new FakturIndirectCacheModel();

		fakturIndirectCacheModel.Id = getId();

		fakturIndirectCacheModel.DealerId = getDealerId();

		fakturIndirectCacheModel.Keterangan = getKeterangan();

		String Keterangan = fakturIndirectCacheModel.Keterangan;

		if ((Keterangan != null) && (Keterangan.length() == 0)) {
			fakturIndirectCacheModel.Keterangan = null;
		}

		Date InvoiceDate = getInvoiceDate();

		if (InvoiceDate != null) {
			fakturIndirectCacheModel.InvoiceDate = InvoiceDate.getTime();
		}
		else {
			fakturIndirectCacheModel.InvoiceDate = Long.MIN_VALUE;
		}

		Date UploadDate = getUploadDate();

		if (UploadDate != null) {
			fakturIndirectCacheModel.UploadDate = UploadDate.getTime();
		}
		else {
			fakturIndirectCacheModel.UploadDate = Long.MIN_VALUE;
		}

		Long FileId = getFileId();

		if (FileId != null) {
			fakturIndirectCacheModel.FileId = FileId;
		}

		fakturIndirectCacheModel.FileName = getFileName();

		String FileName = fakturIndirectCacheModel.FileName;

		if ((FileName != null) && (FileName.length() == 0)) {
			fakturIndirectCacheModel.FileName = null;
		}

		fakturIndirectCacheModel.FilePath = getFilePath();

		String FilePath = fakturIndirectCacheModel.FilePath;

		if ((FilePath != null) && (FilePath.length() == 0)) {
			fakturIndirectCacheModel.FilePath = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			fakturIndirectCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			fakturIndirectCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		fakturIndirectCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = fakturIndirectCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			fakturIndirectCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			fakturIndirectCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			fakturIndirectCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		fakturIndirectCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = fakturIndirectCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			fakturIndirectCacheModel.ModifiedBy = null;
		}

		fakturIndirectCacheModel.RowStatus = isRowStatus();

		return fakturIndirectCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FakturIndirect, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FakturIndirect, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FakturIndirect, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((FakturIndirect)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FakturIndirect>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FakturIndirect.class, ModelWrapper.class);

	}

	private int _Id;
	private int _DealerId;
	private String _Keterangan;
	private Date _InvoiceDate;
	private Date _UploadDate;
	private Long _FileId;
	private String _FileName;
	private String _FilePath;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;
	private boolean _RowStatus;

	public <T> T getColumnValue(String columnName) {
		Function<FakturIndirect, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FakturIndirect)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("Keterangan", _Keterangan);
		_columnOriginalValues.put("InvoiceDate", _InvoiceDate);
		_columnOriginalValues.put("UploadDate", _UploadDate);
		_columnOriginalValues.put("FileId", _FileId);
		_columnOriginalValues.put("FileName", _FileName);
		_columnOriginalValues.put("FilePath", _FilePath);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
		_columnOriginalValues.put("RowStatus", _RowStatus);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("DealerId", 2L);

		columnBitmasks.put("Keterangan", 4L);

		columnBitmasks.put("InvoiceDate", 8L);

		columnBitmasks.put("UploadDate", 16L);

		columnBitmasks.put("FileId", 32L);

		columnBitmasks.put("FileName", 64L);

		columnBitmasks.put("FilePath", 128L);

		columnBitmasks.put("CreatedDate", 256L);

		columnBitmasks.put("CreatedBy", 512L);

		columnBitmasks.put("ModifiedDate", 1024L);

		columnBitmasks.put("ModifiedBy", 2048L);

		columnBitmasks.put("RowStatus", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FakturIndirect _escapedModel;

}