/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.JenisMateri;
import com.astra.dewa.model.JenisMateriModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the JenisMateri service. Represents a row in the &quot;jenis_materi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>JenisMateriModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JenisMateriImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JenisMateriImpl
 * @generated
 */
public class JenisMateriModelImpl
	extends BaseModelImpl<JenisMateri> implements JenisMateriModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a jenis materi model instance should use the <code>JenisMateri</code> interface instead.
	 */
	public static final String TABLE_NAME = "jenis_materi";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"Name", Types.VARCHAR},
		{"ImageId", Types.BIGINT}, {"ImageName", Types.VARCHAR},
		{"ImagePath", Types.VARCHAR}, {"RowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ImageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ImageName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ImagePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table jenis_materi (Id INTEGER not null primary key IDENTITY,Name VARCHAR(75) null,ImageId LONG,ImageName VARCHAR(75) null,ImagePath VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table jenis_materi";

	public static final String ORDER_BY_JPQL = " ORDER BY jenisMateri.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY jenis_materi.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.JenisMateri"));

	public JenisMateriModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return JenisMateri.class;
	}

	@Override
	public String getModelClassName() {
		return JenisMateri.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<JenisMateri, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<JenisMateri, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<JenisMateri, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((JenisMateri)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<JenisMateri, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<JenisMateri, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(JenisMateri)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<JenisMateri, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<JenisMateri, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<JenisMateri, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<JenisMateri, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<JenisMateri, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<JenisMateri, Object>>();
		Map<String, BiConsumer<JenisMateri, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<JenisMateri, ?>>();

		attributeGetterFunctions.put("Id", JenisMateri::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<JenisMateri, Integer>)JenisMateri::setId);
		attributeGetterFunctions.put("Name", JenisMateri::getName);
		attributeSetterBiConsumers.put(
			"Name", (BiConsumer<JenisMateri, String>)JenisMateri::setName);
		attributeGetterFunctions.put("ImageId", JenisMateri::getImageId);
		attributeSetterBiConsumers.put(
			"ImageId", (BiConsumer<JenisMateri, Long>)JenisMateri::setImageId);
		attributeGetterFunctions.put("ImageName", JenisMateri::getImageName);
		attributeSetterBiConsumers.put(
			"ImageName",
			(BiConsumer<JenisMateri, String>)JenisMateri::setImageName);
		attributeGetterFunctions.put("ImagePath", JenisMateri::getImagePath);
		attributeSetterBiConsumers.put(
			"ImagePath",
			(BiConsumer<JenisMateri, String>)JenisMateri::setImagePath);
		attributeGetterFunctions.put("RowStatus", JenisMateri::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<JenisMateri, Boolean>)JenisMateri::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", JenisMateri::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<JenisMateri, Date>)JenisMateri::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", JenisMateri::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<JenisMateri, String>)JenisMateri::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", JenisMateri::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<JenisMateri, Date>)JenisMateri::setModifiedDate);
		attributeGetterFunctions.put("ModifiedBy", JenisMateri::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<JenisMateri, String>)JenisMateri::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public String getName() {
		if (_Name == null) {
			return "";
		}
		else {
			return _Name;
		}
	}

	@Override
	public void setName(String Name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Name = Name;
	}

	@Override
	public Long getImageId() {
		return _ImageId;
	}

	@Override
	public void setImageId(Long ImageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ImageId = ImageId;
	}

	@Override
	public String getImageName() {
		if (_ImageName == null) {
			return "";
		}
		else {
			return _ImageName;
		}
	}

	@Override
	public void setImageName(String ImageName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ImageName = ImageName;
	}

	@Override
	public String getImagePath() {
		if (_ImagePath == null) {
			return "";
		}
		else {
			return _ImagePath;
		}
	}

	@Override
	public void setImagePath(String ImagePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ImagePath = ImagePath;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public JenisMateri toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, JenisMateri>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		JenisMateriImpl jenisMateriImpl = new JenisMateriImpl();

		jenisMateriImpl.setId(getId());
		jenisMateriImpl.setName(getName());
		jenisMateriImpl.setImageId(getImageId());
		jenisMateriImpl.setImageName(getImageName());
		jenisMateriImpl.setImagePath(getImagePath());
		jenisMateriImpl.setRowStatus(getRowStatus());
		jenisMateriImpl.setCreatedDate(getCreatedDate());
		jenisMateriImpl.setCreatedBy(getCreatedBy());
		jenisMateriImpl.setModifiedDate(getModifiedDate());
		jenisMateriImpl.setModifiedBy(getModifiedBy());

		jenisMateriImpl.resetOriginalValues();

		return jenisMateriImpl;
	}

	@Override
	public JenisMateri cloneWithOriginalValues() {
		JenisMateriImpl jenisMateriImpl = new JenisMateriImpl();

		jenisMateriImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		jenisMateriImpl.setName(this.<String>getColumnOriginalValue("Name"));
		jenisMateriImpl.setImageId(
			this.<Long>getColumnOriginalValue("ImageId"));
		jenisMateriImpl.setImageName(
			this.<String>getColumnOriginalValue("ImageName"));
		jenisMateriImpl.setImagePath(
			this.<String>getColumnOriginalValue("ImagePath"));
		jenisMateriImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		jenisMateriImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		jenisMateriImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		jenisMateriImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		jenisMateriImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return jenisMateriImpl;
	}

	@Override
	public int compareTo(JenisMateri jenisMateri) {
		int primaryKey = jenisMateri.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof JenisMateri)) {
			return false;
		}

		JenisMateri jenisMateri = (JenisMateri)object;

		int primaryKey = jenisMateri.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<JenisMateri> toCacheModel() {
		JenisMateriCacheModel jenisMateriCacheModel =
			new JenisMateriCacheModel();

		jenisMateriCacheModel.Id = getId();

		jenisMateriCacheModel.Name = getName();

		String Name = jenisMateriCacheModel.Name;

		if ((Name != null) && (Name.length() == 0)) {
			jenisMateriCacheModel.Name = null;
		}

		Long ImageId = getImageId();

		if (ImageId != null) {
			jenisMateriCacheModel.ImageId = ImageId;
		}

		jenisMateriCacheModel.ImageName = getImageName();

		String ImageName = jenisMateriCacheModel.ImageName;

		if ((ImageName != null) && (ImageName.length() == 0)) {
			jenisMateriCacheModel.ImageName = null;
		}

		jenisMateriCacheModel.ImagePath = getImagePath();

		String ImagePath = jenisMateriCacheModel.ImagePath;

		if ((ImagePath != null) && (ImagePath.length() == 0)) {
			jenisMateriCacheModel.ImagePath = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			jenisMateriCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			jenisMateriCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			jenisMateriCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		jenisMateriCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = jenisMateriCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			jenisMateriCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			jenisMateriCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			jenisMateriCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		jenisMateriCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = jenisMateriCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			jenisMateriCacheModel.ModifiedBy = null;
		}

		return jenisMateriCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<JenisMateri, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<JenisMateri, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<JenisMateri, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((JenisMateri)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, JenisMateri>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					JenisMateri.class, ModelWrapper.class);

	}

	private int _Id;
	private String _Name;
	private Long _ImageId;
	private String _ImageName;
	private String _ImagePath;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<JenisMateri, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((JenisMateri)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("Name", _Name);
		_columnOriginalValues.put("ImageId", _ImageId);
		_columnOriginalValues.put("ImageName", _ImageName);
		_columnOriginalValues.put("ImagePath", _ImagePath);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("Name", 2L);

		columnBitmasks.put("ImageId", 4L);

		columnBitmasks.put("ImageName", 8L);

		columnBitmasks.put("ImagePath", 16L);

		columnBitmasks.put("RowStatus", 32L);

		columnBitmasks.put("CreatedDate", 64L);

		columnBitmasks.put("CreatedBy", 128L);

		columnBitmasks.put("ModifiedDate", 256L);

		columnBitmasks.put("ModifiedBy", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private JenisMateri _escapedModel;

}