/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.KategoriDealer;
import com.astra.dewa.model.KategoriDealerModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the KategoriDealer service. Represents a row in the &quot;kategori_dealer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>KategoriDealerModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KategoriDealerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KategoriDealerImpl
 * @generated
 */
public class KategoriDealerModelImpl
	extends BaseModelImpl<KategoriDealer> implements KategoriDealerModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a kategori dealer model instance should use the <code>KategoriDealer</code> interface instead.
	 */
	public static final String TABLE_NAME = "kategori_dealer";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.BIGINT}, {"DealerId", Types.INTEGER},
		{"Judul", Types.VARCHAR}, {"PeriodeReview", Types.VARCHAR},
		{"Tahun", Types.INTEGER}, {"FileId", Types.BIGINT},
		{"FileName", Types.VARCHAR}, {"rowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Judul", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PeriodeReview", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Tahun", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("FileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("rowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table kategori_dealer (Id LONG not null primary key,DealerId INTEGER,Judul VARCHAR(75) null,PeriodeReview VARCHAR(75) null,Tahun INTEGER,FileId LONG,FileName VARCHAR(75) null,rowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table kategori_dealer";

	public static final String ORDER_BY_JPQL =
		" ORDER BY kategoriDealer.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY kategori_dealer.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.KategoriDealer"));

	public KategoriDealerModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return KategoriDealer.class;
	}

	@Override
	public String getModelClassName() {
		return KategoriDealer.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<KategoriDealer, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<KategoriDealer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<KategoriDealer, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((KategoriDealer)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<KategoriDealer, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<KategoriDealer, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(KategoriDealer)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<KategoriDealer, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<KategoriDealer, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<KategoriDealer, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<KategoriDealer, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<KategoriDealer, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<KategoriDealer, Object>>();
		Map<String, BiConsumer<KategoriDealer, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<KategoriDealer, ?>>();

		attributeGetterFunctions.put("Id", KategoriDealer::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<KategoriDealer, Long>)KategoriDealer::setId);
		attributeGetterFunctions.put("DealerId", KategoriDealer::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId",
			(BiConsumer<KategoriDealer, Integer>)KategoriDealer::setDealerId);
		attributeGetterFunctions.put("Judul", KategoriDealer::getJudul);
		attributeSetterBiConsumers.put(
			"Judul",
			(BiConsumer<KategoriDealer, String>)KategoriDealer::setJudul);
		attributeGetterFunctions.put(
			"PeriodeReview", KategoriDealer::getPeriodeReview);
		attributeSetterBiConsumers.put(
			"PeriodeReview",
			(BiConsumer<KategoriDealer, String>)
				KategoriDealer::setPeriodeReview);
		attributeGetterFunctions.put("Tahun", KategoriDealer::getTahun);
		attributeSetterBiConsumers.put(
			"Tahun",
			(BiConsumer<KategoriDealer, Integer>)KategoriDealer::setTahun);
		attributeGetterFunctions.put("FileId", KategoriDealer::getFileId);
		attributeSetterBiConsumers.put(
			"FileId",
			(BiConsumer<KategoriDealer, Long>)KategoriDealer::setFileId);
		attributeGetterFunctions.put("FileName", KategoriDealer::getFileName);
		attributeSetterBiConsumers.put(
			"FileName",
			(BiConsumer<KategoriDealer, String>)KategoriDealer::setFileName);
		attributeGetterFunctions.put("rowStatus", KategoriDealer::getRowStatus);
		attributeSetterBiConsumers.put(
			"rowStatus",
			(BiConsumer<KategoriDealer, Boolean>)KategoriDealer::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", KategoriDealer::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<KategoriDealer, Date>)KategoriDealer::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", KategoriDealer::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<KategoriDealer, String>)KategoriDealer::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", KategoriDealer::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<KategoriDealer, Date>)KategoriDealer::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", KategoriDealer::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<KategoriDealer, String>)KategoriDealer::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _Id;
	}

	@Override
	public void setId(long Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public String getJudul() {
		if (_Judul == null) {
			return "";
		}
		else {
			return _Judul;
		}
	}

	@Override
	public void setJudul(String Judul) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Judul = Judul;
	}

	@Override
	public String getPeriodeReview() {
		if (_PeriodeReview == null) {
			return "";
		}
		else {
			return _PeriodeReview;
		}
	}

	@Override
	public void setPeriodeReview(String PeriodeReview) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_PeriodeReview = PeriodeReview;
	}

	@Override
	public int getTahun() {
		return _Tahun;
	}

	@Override
	public void setTahun(int Tahun) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Tahun = Tahun;
	}

	@Override
	public Long getFileId() {
		return _FileId;
	}

	@Override
	public void setFileId(Long FileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileId = FileId;
	}

	@Override
	public String getFileName() {
		if (_FileName == null) {
			return "";
		}
		else {
			return _FileName;
		}
	}

	@Override
	public void setFileName(String FileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileName = FileName;
	}

	@Override
	public boolean getRowStatus() {
		return _rowStatus;
	}

	@Override
	public boolean isRowStatus() {
		return _rowStatus;
	}

	@Override
	public void setRowStatus(boolean rowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_rowStatus = rowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, KategoriDealer.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public KategoriDealer toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, KategoriDealer>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		KategoriDealerImpl kategoriDealerImpl = new KategoriDealerImpl();

		kategoriDealerImpl.setId(getId());
		kategoriDealerImpl.setDealerId(getDealerId());
		kategoriDealerImpl.setJudul(getJudul());
		kategoriDealerImpl.setPeriodeReview(getPeriodeReview());
		kategoriDealerImpl.setTahun(getTahun());
		kategoriDealerImpl.setFileId(getFileId());
		kategoriDealerImpl.setFileName(getFileName());
		kategoriDealerImpl.setRowStatus(isRowStatus());
		kategoriDealerImpl.setCreatedDate(getCreatedDate());
		kategoriDealerImpl.setCreatedBy(getCreatedBy());
		kategoriDealerImpl.setModifiedDate(getModifiedDate());
		kategoriDealerImpl.setModifiedBy(getModifiedBy());

		kategoriDealerImpl.resetOriginalValues();

		return kategoriDealerImpl;
	}

	@Override
	public KategoriDealer cloneWithOriginalValues() {
		KategoriDealerImpl kategoriDealerImpl = new KategoriDealerImpl();

		kategoriDealerImpl.setId(this.<Long>getColumnOriginalValue("Id"));
		kategoriDealerImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("DealerId"));
		kategoriDealerImpl.setJudul(
			this.<String>getColumnOriginalValue("Judul"));
		kategoriDealerImpl.setPeriodeReview(
			this.<String>getColumnOriginalValue("PeriodeReview"));
		kategoriDealerImpl.setTahun(
			this.<Integer>getColumnOriginalValue("Tahun"));
		kategoriDealerImpl.setFileId(
			this.<Long>getColumnOriginalValue("FileId"));
		kategoriDealerImpl.setFileName(
			this.<String>getColumnOriginalValue("FileName"));
		kategoriDealerImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("rowStatus"));
		kategoriDealerImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		kategoriDealerImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		kategoriDealerImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		kategoriDealerImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return kategoriDealerImpl;
	}

	@Override
	public int compareTo(KategoriDealer kategoriDealer) {
		long primaryKey = kategoriDealer.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof KategoriDealer)) {
			return false;
		}

		KategoriDealer kategoriDealer = (KategoriDealer)object;

		long primaryKey = kategoriDealer.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<KategoriDealer> toCacheModel() {
		KategoriDealerCacheModel kategoriDealerCacheModel =
			new KategoriDealerCacheModel();

		kategoriDealerCacheModel.Id = getId();

		kategoriDealerCacheModel.DealerId = getDealerId();

		kategoriDealerCacheModel.Judul = getJudul();

		String Judul = kategoriDealerCacheModel.Judul;

		if ((Judul != null) && (Judul.length() == 0)) {
			kategoriDealerCacheModel.Judul = null;
		}

		kategoriDealerCacheModel.PeriodeReview = getPeriodeReview();

		String PeriodeReview = kategoriDealerCacheModel.PeriodeReview;

		if ((PeriodeReview != null) && (PeriodeReview.length() == 0)) {
			kategoriDealerCacheModel.PeriodeReview = null;
		}

		kategoriDealerCacheModel.Tahun = getTahun();

		Long FileId = getFileId();

		if (FileId != null) {
			kategoriDealerCacheModel.FileId = FileId;
		}

		kategoriDealerCacheModel.FileName = getFileName();

		String FileName = kategoriDealerCacheModel.FileName;

		if ((FileName != null) && (FileName.length() == 0)) {
			kategoriDealerCacheModel.FileName = null;
		}

		kategoriDealerCacheModel.rowStatus = isRowStatus();

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			kategoriDealerCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			kategoriDealerCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		kategoriDealerCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = kategoriDealerCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			kategoriDealerCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			kategoriDealerCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			kategoriDealerCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		kategoriDealerCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = kategoriDealerCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			kategoriDealerCacheModel.ModifiedBy = null;
		}

		return kategoriDealerCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<KategoriDealer, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<KategoriDealer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<KategoriDealer, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((KategoriDealer)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, KategoriDealer>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					KategoriDealer.class, ModelWrapper.class);

	}

	private long _Id;
	private int _DealerId;
	private String _Judul;
	private String _PeriodeReview;
	private int _Tahun;
	private Long _FileId;
	private String _FileName;
	private boolean _rowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<KategoriDealer, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((KategoriDealer)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("Judul", _Judul);
		_columnOriginalValues.put("PeriodeReview", _PeriodeReview);
		_columnOriginalValues.put("Tahun", _Tahun);
		_columnOriginalValues.put("FileId", _FileId);
		_columnOriginalValues.put("FileName", _FileName);
		_columnOriginalValues.put("rowStatus", _rowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("DealerId", 2L);

		columnBitmasks.put("Judul", 4L);

		columnBitmasks.put("PeriodeReview", 8L);

		columnBitmasks.put("Tahun", 16L);

		columnBitmasks.put("FileId", 32L);

		columnBitmasks.put("FileName", 64L);

		columnBitmasks.put("rowStatus", 128L);

		columnBitmasks.put("CreatedDate", 256L);

		columnBitmasks.put("CreatedBy", 512L);

		columnBitmasks.put("ModifiedDate", 1024L);

		columnBitmasks.put("ModifiedBy", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private KategoriDealer _escapedModel;

}