/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.MasterApprovalDetail;
import com.astra.dewa.model.MasterApprovalDetailModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MasterApprovalDetail service. Represents a row in the &quot;master_approval_detail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MasterApprovalDetailModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MasterApprovalDetailImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MasterApprovalDetailImpl
 * @generated
 */
public class MasterApprovalDetailModelImpl
	extends BaseModelImpl<MasterApprovalDetail>
	implements MasterApprovalDetailModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a master approval detail model instance should use the <code>MasterApprovalDetail</code> interface instead.
	 */
	public static final String TABLE_NAME = "master_approval_detail";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"MasterApprovalId", Types.INTEGER},
		{"UserId", Types.BIGINT}, {"ApprovalLevel", Types.INTEGER},
		{"IsDefault", Types.BOOLEAN}, {"RowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("MasterApprovalId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("UserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ApprovalLevel", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("IsDefault", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table master_approval_detail (Id INTEGER not null primary key IDENTITY,MasterApprovalId INTEGER,UserId LONG,ApprovalLevel INTEGER,IsDefault BOOLEAN,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table master_approval_detail";

	public static final String ORDER_BY_JPQL =
		" ORDER BY masterApprovalDetail.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY master_approval_detail.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.MasterApprovalDetail"));

	public MasterApprovalDetailModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MasterApprovalDetail.class;
	}

	@Override
	public String getModelClassName() {
		return MasterApprovalDetail.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MasterApprovalDetail, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MasterApprovalDetail, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterApprovalDetail, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MasterApprovalDetail)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MasterApprovalDetail, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MasterApprovalDetail, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MasterApprovalDetail)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MasterApprovalDetail, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MasterApprovalDetail, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MasterApprovalDetail, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MasterApprovalDetail, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MasterApprovalDetail, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<MasterApprovalDetail, Object>>();
		Map<String, BiConsumer<MasterApprovalDetail, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<MasterApprovalDetail, ?>>();

		attributeGetterFunctions.put("Id", MasterApprovalDetail::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<MasterApprovalDetail, Integer>)
				MasterApprovalDetail::setId);
		attributeGetterFunctions.put(
			"MasterApprovalId", MasterApprovalDetail::getMasterApprovalId);
		attributeSetterBiConsumers.put(
			"MasterApprovalId",
			(BiConsumer<MasterApprovalDetail, Integer>)
				MasterApprovalDetail::setMasterApprovalId);
		attributeGetterFunctions.put("UserId", MasterApprovalDetail::getUserId);
		attributeSetterBiConsumers.put(
			"UserId",
			(BiConsumer<MasterApprovalDetail, Long>)
				MasterApprovalDetail::setUserId);
		attributeGetterFunctions.put(
			"ApprovalLevel", MasterApprovalDetail::getApprovalLevel);
		attributeSetterBiConsumers.put(
			"ApprovalLevel",
			(BiConsumer<MasterApprovalDetail, Integer>)
				MasterApprovalDetail::setApprovalLevel);
		attributeGetterFunctions.put(
			"IsDefault", MasterApprovalDetail::getIsDefault);
		attributeSetterBiConsumers.put(
			"IsDefault",
			(BiConsumer<MasterApprovalDetail, Boolean>)
				MasterApprovalDetail::setIsDefault);
		attributeGetterFunctions.put(
			"RowStatus", MasterApprovalDetail::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<MasterApprovalDetail, Boolean>)
				MasterApprovalDetail::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", MasterApprovalDetail::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<MasterApprovalDetail, Date>)
				MasterApprovalDetail::setCreatedDate);
		attributeGetterFunctions.put(
			"CreatedBy", MasterApprovalDetail::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<MasterApprovalDetail, String>)
				MasterApprovalDetail::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", MasterApprovalDetail::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<MasterApprovalDetail, Date>)
				MasterApprovalDetail::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", MasterApprovalDetail::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<MasterApprovalDetail, String>)
				MasterApprovalDetail::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getMasterApprovalId() {
		return _MasterApprovalId;
	}

	@Override
	public void setMasterApprovalId(int MasterApprovalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_MasterApprovalId = MasterApprovalId;
	}

	@Override
	public long getUserId() {
		return _UserId;
	}

	@Override
	public void setUserId(long UserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_UserId = UserId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String UserUuid) {
	}

	@Override
	public int getApprovalLevel() {
		return _ApprovalLevel;
	}

	@Override
	public void setApprovalLevel(int ApprovalLevel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApprovalLevel = ApprovalLevel;
	}

	@Override
	public boolean getIsDefault() {
		return _IsDefault;
	}

	@Override
	public boolean isIsDefault() {
		return _IsDefault;
	}

	@Override
	public void setIsDefault(boolean IsDefault) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_IsDefault = IsDefault;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public MasterApprovalDetail toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MasterApprovalDetail>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MasterApprovalDetailImpl masterApprovalDetailImpl =
			new MasterApprovalDetailImpl();

		masterApprovalDetailImpl.setId(getId());
		masterApprovalDetailImpl.setMasterApprovalId(getMasterApprovalId());
		masterApprovalDetailImpl.setUserId(getUserId());
		masterApprovalDetailImpl.setApprovalLevel(getApprovalLevel());
		masterApprovalDetailImpl.setIsDefault(isIsDefault());
		masterApprovalDetailImpl.setRowStatus(getRowStatus());
		masterApprovalDetailImpl.setCreatedDate(getCreatedDate());
		masterApprovalDetailImpl.setCreatedBy(getCreatedBy());
		masterApprovalDetailImpl.setModifiedDate(getModifiedDate());
		masterApprovalDetailImpl.setModifiedBy(getModifiedBy());

		masterApprovalDetailImpl.resetOriginalValues();

		return masterApprovalDetailImpl;
	}

	@Override
	public MasterApprovalDetail cloneWithOriginalValues() {
		MasterApprovalDetailImpl masterApprovalDetailImpl =
			new MasterApprovalDetailImpl();

		masterApprovalDetailImpl.setId(
			this.<Integer>getColumnOriginalValue("Id"));
		masterApprovalDetailImpl.setMasterApprovalId(
			this.<Integer>getColumnOriginalValue("MasterApprovalId"));
		masterApprovalDetailImpl.setUserId(
			this.<Long>getColumnOriginalValue("UserId"));
		masterApprovalDetailImpl.setApprovalLevel(
			this.<Integer>getColumnOriginalValue("ApprovalLevel"));
		masterApprovalDetailImpl.setIsDefault(
			this.<Boolean>getColumnOriginalValue("IsDefault"));
		masterApprovalDetailImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		masterApprovalDetailImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		masterApprovalDetailImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		masterApprovalDetailImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		masterApprovalDetailImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return masterApprovalDetailImpl;
	}

	@Override
	public int compareTo(MasterApprovalDetail masterApprovalDetail) {
		int primaryKey = masterApprovalDetail.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MasterApprovalDetail)) {
			return false;
		}

		MasterApprovalDetail masterApprovalDetail =
			(MasterApprovalDetail)object;

		int primaryKey = masterApprovalDetail.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MasterApprovalDetail> toCacheModel() {
		MasterApprovalDetailCacheModel masterApprovalDetailCacheModel =
			new MasterApprovalDetailCacheModel();

		masterApprovalDetailCacheModel.Id = getId();

		masterApprovalDetailCacheModel.MasterApprovalId = getMasterApprovalId();

		masterApprovalDetailCacheModel.UserId = getUserId();

		masterApprovalDetailCacheModel.ApprovalLevel = getApprovalLevel();

		masterApprovalDetailCacheModel.IsDefault = isIsDefault();

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			masterApprovalDetailCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			masterApprovalDetailCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			masterApprovalDetailCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		masterApprovalDetailCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = masterApprovalDetailCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			masterApprovalDetailCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			masterApprovalDetailCacheModel.ModifiedDate =
				ModifiedDate.getTime();
		}
		else {
			masterApprovalDetailCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		masterApprovalDetailCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = masterApprovalDetailCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			masterApprovalDetailCacheModel.ModifiedBy = null;
		}

		return masterApprovalDetailCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MasterApprovalDetail, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MasterApprovalDetail, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterApprovalDetail, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(MasterApprovalDetail)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MasterApprovalDetail>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MasterApprovalDetail.class, ModelWrapper.class);

	}

	private int _Id;
	private int _MasterApprovalId;
	private long _UserId;
	private int _ApprovalLevel;
	private boolean _IsDefault;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<MasterApprovalDetail, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MasterApprovalDetail)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("MasterApprovalId", _MasterApprovalId);
		_columnOriginalValues.put("UserId", _UserId);
		_columnOriginalValues.put("ApprovalLevel", _ApprovalLevel);
		_columnOriginalValues.put("IsDefault", _IsDefault);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("MasterApprovalId", 2L);

		columnBitmasks.put("UserId", 4L);

		columnBitmasks.put("ApprovalLevel", 8L);

		columnBitmasks.put("IsDefault", 16L);

		columnBitmasks.put("RowStatus", 32L);

		columnBitmasks.put("CreatedDate", 64L);

		columnBitmasks.put("CreatedBy", 128L);

		columnBitmasks.put("ModifiedDate", 256L);

		columnBitmasks.put("ModifiedBy", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MasterApprovalDetail _escapedModel;

}