/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.ReportPlafond;
import com.astra.dewa.model.ReportPlafondModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ReportPlafond service. Represents a row in the &quot;report_plafond&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ReportPlafondModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReportPlafondImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReportPlafondImpl
 * @generated
 */
public class ReportPlafondModelImpl
	extends BaseModelImpl<ReportPlafond> implements ReportPlafondModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a report plafond model instance should use the <code>ReportPlafond</code> interface instead.
	 */
	public static final String TABLE_NAME = "report_plafond";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"DealerId", Types.INTEGER},
		{"FileId", Types.BIGINT}, {"FileName", Types.VARCHAR},
		{"FilePath", Types.VARCHAR}, {"Periode", Types.TIMESTAMP},
		{"Keterangan", Types.VARCHAR}, {"RowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("FileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FilePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Periode", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("Keterangan", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table report_plafond (Id INTEGER not null primary key IDENTITY,DealerId INTEGER,FileId LONG,FileName VARCHAR(75) null,FilePath VARCHAR(75) null,Periode DATE null,Keterangan VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table report_plafond";

	public static final String ORDER_BY_JPQL = " ORDER BY reportPlafond.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY report_plafond.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.ReportPlafond"));

	public ReportPlafondModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ReportPlafond.class;
	}

	@Override
	public String getModelClassName() {
		return ReportPlafond.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ReportPlafond, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ReportPlafond, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReportPlafond, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ReportPlafond)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ReportPlafond, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ReportPlafond, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ReportPlafond)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ReportPlafond, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ReportPlafond, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ReportPlafond, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ReportPlafond, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ReportPlafond, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ReportPlafond, Object>>();
		Map<String, BiConsumer<ReportPlafond, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ReportPlafond, ?>>();

		attributeGetterFunctions.put("Id", ReportPlafond::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<ReportPlafond, Integer>)ReportPlafond::setId);
		attributeGetterFunctions.put("DealerId", ReportPlafond::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId",
			(BiConsumer<ReportPlafond, Integer>)ReportPlafond::setDealerId);
		attributeGetterFunctions.put("FileId", ReportPlafond::getFileId);
		attributeSetterBiConsumers.put(
			"FileId",
			(BiConsumer<ReportPlafond, Long>)ReportPlafond::setFileId);
		attributeGetterFunctions.put("FileName", ReportPlafond::getFileName);
		attributeSetterBiConsumers.put(
			"FileName",
			(BiConsumer<ReportPlafond, String>)ReportPlafond::setFileName);
		attributeGetterFunctions.put("FilePath", ReportPlafond::getFilePath);
		attributeSetterBiConsumers.put(
			"FilePath",
			(BiConsumer<ReportPlafond, String>)ReportPlafond::setFilePath);
		attributeGetterFunctions.put("Periode", ReportPlafond::getPeriode);
		attributeSetterBiConsumers.put(
			"Periode",
			(BiConsumer<ReportPlafond, Date>)ReportPlafond::setPeriode);
		attributeGetterFunctions.put(
			"Keterangan", ReportPlafond::getKeterangan);
		attributeSetterBiConsumers.put(
			"Keterangan",
			(BiConsumer<ReportPlafond, String>)ReportPlafond::setKeterangan);
		attributeGetterFunctions.put("RowStatus", ReportPlafond::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<ReportPlafond, Boolean>)ReportPlafond::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", ReportPlafond::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<ReportPlafond, Date>)ReportPlafond::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", ReportPlafond::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<ReportPlafond, String>)ReportPlafond::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", ReportPlafond::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<ReportPlafond, Date>)ReportPlafond::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", ReportPlafond::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<ReportPlafond, String>)ReportPlafond::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public Long getFileId() {
		return _FileId;
	}

	@Override
	public void setFileId(Long FileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileId = FileId;
	}

	@Override
	public String getFileName() {
		if (_FileName == null) {
			return "";
		}
		else {
			return _FileName;
		}
	}

	@Override
	public void setFileName(String FileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileName = FileName;
	}

	@Override
	public String getFilePath() {
		if (_FilePath == null) {
			return "";
		}
		else {
			return _FilePath;
		}
	}

	@Override
	public void setFilePath(String FilePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FilePath = FilePath;
	}

	@Override
	public Date getPeriode() {
		return _Periode;
	}

	@Override
	public void setPeriode(Date Periode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Periode = Periode;
	}

	@Override
	public String getKeterangan() {
		if (_Keterangan == null) {
			return "";
		}
		else {
			return _Keterangan;
		}
	}

	@Override
	public void setKeterangan(String Keterangan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Keterangan = Keterangan;
	}

	@Override
	public boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public boolean isRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ReportPlafond toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ReportPlafond>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ReportPlafondImpl reportPlafondImpl = new ReportPlafondImpl();

		reportPlafondImpl.setId(getId());
		reportPlafondImpl.setDealerId(getDealerId());
		reportPlafondImpl.setFileId(getFileId());
		reportPlafondImpl.setFileName(getFileName());
		reportPlafondImpl.setFilePath(getFilePath());
		reportPlafondImpl.setPeriode(getPeriode());
		reportPlafondImpl.setKeterangan(getKeterangan());
		reportPlafondImpl.setRowStatus(isRowStatus());
		reportPlafondImpl.setCreatedDate(getCreatedDate());
		reportPlafondImpl.setCreatedBy(getCreatedBy());
		reportPlafondImpl.setModifiedDate(getModifiedDate());
		reportPlafondImpl.setModifiedBy(getModifiedBy());

		reportPlafondImpl.resetOriginalValues();

		return reportPlafondImpl;
	}

	@Override
	public ReportPlafond cloneWithOriginalValues() {
		ReportPlafondImpl reportPlafondImpl = new ReportPlafondImpl();

		reportPlafondImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		reportPlafondImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("DealerId"));
		reportPlafondImpl.setFileId(
			this.<Long>getColumnOriginalValue("FileId"));
		reportPlafondImpl.setFileName(
			this.<String>getColumnOriginalValue("FileName"));
		reportPlafondImpl.setFilePath(
			this.<String>getColumnOriginalValue("FilePath"));
		reportPlafondImpl.setPeriode(
			this.<Date>getColumnOriginalValue("Periode"));
		reportPlafondImpl.setKeterangan(
			this.<String>getColumnOriginalValue("Keterangan"));
		reportPlafondImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		reportPlafondImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		reportPlafondImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		reportPlafondImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		reportPlafondImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return reportPlafondImpl;
	}

	@Override
	public int compareTo(ReportPlafond reportPlafond) {
		int primaryKey = reportPlafond.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ReportPlafond)) {
			return false;
		}

		ReportPlafond reportPlafond = (ReportPlafond)object;

		int primaryKey = reportPlafond.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ReportPlafond> toCacheModel() {
		ReportPlafondCacheModel reportPlafondCacheModel =
			new ReportPlafondCacheModel();

		reportPlafondCacheModel.Id = getId();

		reportPlafondCacheModel.DealerId = getDealerId();

		Long FileId = getFileId();

		if (FileId != null) {
			reportPlafondCacheModel.FileId = FileId;
		}

		reportPlafondCacheModel.FileName = getFileName();

		String FileName = reportPlafondCacheModel.FileName;

		if ((FileName != null) && (FileName.length() == 0)) {
			reportPlafondCacheModel.FileName = null;
		}

		reportPlafondCacheModel.FilePath = getFilePath();

		String FilePath = reportPlafondCacheModel.FilePath;

		if ((FilePath != null) && (FilePath.length() == 0)) {
			reportPlafondCacheModel.FilePath = null;
		}

		Date Periode = getPeriode();

		if (Periode != null) {
			reportPlafondCacheModel.Periode = Periode.getTime();
		}
		else {
			reportPlafondCacheModel.Periode = Long.MIN_VALUE;
		}

		reportPlafondCacheModel.Keterangan = getKeterangan();

		String Keterangan = reportPlafondCacheModel.Keterangan;

		if ((Keterangan != null) && (Keterangan.length() == 0)) {
			reportPlafondCacheModel.Keterangan = null;
		}

		reportPlafondCacheModel.RowStatus = isRowStatus();

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			reportPlafondCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			reportPlafondCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		reportPlafondCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = reportPlafondCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			reportPlafondCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			reportPlafondCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			reportPlafondCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		reportPlafondCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = reportPlafondCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			reportPlafondCacheModel.ModifiedBy = null;
		}

		return reportPlafondCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ReportPlafond, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ReportPlafond, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReportPlafond, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ReportPlafond)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ReportPlafond>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ReportPlafond.class, ModelWrapper.class);

	}

	private int _Id;
	private int _DealerId;
	private Long _FileId;
	private String _FileName;
	private String _FilePath;
	private Date _Periode;
	private String _Keterangan;
	private boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<ReportPlafond, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ReportPlafond)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("FileId", _FileId);
		_columnOriginalValues.put("FileName", _FileName);
		_columnOriginalValues.put("FilePath", _FilePath);
		_columnOriginalValues.put("Periode", _Periode);
		_columnOriginalValues.put("Keterangan", _Keterangan);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("DealerId", 2L);

		columnBitmasks.put("FileId", 4L);

		columnBitmasks.put("FileName", 8L);

		columnBitmasks.put("FilePath", 16L);

		columnBitmasks.put("Periode", 32L);

		columnBitmasks.put("Keterangan", 64L);

		columnBitmasks.put("RowStatus", 128L);

		columnBitmasks.put("CreatedDate", 256L);

		columnBitmasks.put("CreatedBy", 512L);

		columnBitmasks.put("ModifiedDate", 1024L);

		columnBitmasks.put("ModifiedBy", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ReportPlafond _escapedModel;

}