/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.SalesReport;
import com.astra.dewa.model.SalesReportModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SalesReport service. Represents a row in the &quot;sales_report&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SalesReportModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SalesReportImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SalesReportImpl
 * @generated
 */
public class SalesReportModelImpl
	extends BaseModelImpl<SalesReport> implements SalesReportModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sales report model instance should use the <code>SalesReport</code> interface instead.
	 */
	public static final String TABLE_NAME = "sales_report";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"DealerId", Types.INTEGER},
		{"FileId", Types.BIGINT}, {"FileName", Types.VARCHAR},
		{"FilePath", Types.VARCHAR}, {"Periode", Types.TIMESTAMP},
		{"Keterangan", Types.VARCHAR}, {"RowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("FileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FilePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Periode", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("Keterangan", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table sales_report (Id INTEGER not null primary key IDENTITY,DealerId INTEGER,FileId LONG,FileName VARCHAR(75) null,FilePath VARCHAR(75) null,Periode DATE null,Keterangan VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table sales_report";

	public static final String ORDER_BY_JPQL = " ORDER BY salesReport.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY sales_report.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.SalesReport"));

	public SalesReportModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SalesReport.class;
	}

	@Override
	public String getModelClassName() {
		return SalesReport.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SalesReport, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SalesReport, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SalesReport, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SalesReport)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SalesReport, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SalesReport, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SalesReport)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SalesReport, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SalesReport, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SalesReport, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SalesReport, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SalesReport, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<SalesReport, Object>>();
		Map<String, BiConsumer<SalesReport, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SalesReport, ?>>();

		attributeGetterFunctions.put("Id", SalesReport::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<SalesReport, Integer>)SalesReport::setId);
		attributeGetterFunctions.put("DealerId", SalesReport::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId",
			(BiConsumer<SalesReport, Integer>)SalesReport::setDealerId);
		attributeGetterFunctions.put("FileId", SalesReport::getFileId);
		attributeSetterBiConsumers.put(
			"FileId", (BiConsumer<SalesReport, Long>)SalesReport::setFileId);
		attributeGetterFunctions.put("FileName", SalesReport::getFileName);
		attributeSetterBiConsumers.put(
			"FileName",
			(BiConsumer<SalesReport, String>)SalesReport::setFileName);
		attributeGetterFunctions.put("FilePath", SalesReport::getFilePath);
		attributeSetterBiConsumers.put(
			"FilePath",
			(BiConsumer<SalesReport, String>)SalesReport::setFilePath);
		attributeGetterFunctions.put("Periode", SalesReport::getPeriode);
		attributeSetterBiConsumers.put(
			"Periode", (BiConsumer<SalesReport, Date>)SalesReport::setPeriode);
		attributeGetterFunctions.put("Keterangan", SalesReport::getKeterangan);
		attributeSetterBiConsumers.put(
			"Keterangan",
			(BiConsumer<SalesReport, String>)SalesReport::setKeterangan);
		attributeGetterFunctions.put("RowStatus", SalesReport::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<SalesReport, Boolean>)SalesReport::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", SalesReport::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<SalesReport, Date>)SalesReport::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", SalesReport::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<SalesReport, String>)SalesReport::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", SalesReport::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<SalesReport, Date>)SalesReport::setModifiedDate);
		attributeGetterFunctions.put("ModifiedBy", SalesReport::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<SalesReport, String>)SalesReport::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public Long getFileId() {
		return _FileId;
	}

	@Override
	public void setFileId(Long FileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileId = FileId;
	}

	@Override
	public String getFileName() {
		if (_FileName == null) {
			return "";
		}
		else {
			return _FileName;
		}
	}

	@Override
	public void setFileName(String FileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileName = FileName;
	}

	@Override
	public String getFilePath() {
		if (_FilePath == null) {
			return "";
		}
		else {
			return _FilePath;
		}
	}

	@Override
	public void setFilePath(String FilePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FilePath = FilePath;
	}

	@Override
	public Date getPeriode() {
		return _Periode;
	}

	@Override
	public void setPeriode(Date Periode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Periode = Periode;
	}

	@Override
	public String getKeterangan() {
		if (_Keterangan == null) {
			return "";
		}
		else {
			return _Keterangan;
		}
	}

	@Override
	public void setKeterangan(String Keterangan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Keterangan = Keterangan;
	}

	@Override
	public boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public boolean isRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public SalesReport toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SalesReport>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SalesReportImpl salesReportImpl = new SalesReportImpl();

		salesReportImpl.setId(getId());
		salesReportImpl.setDealerId(getDealerId());
		salesReportImpl.setFileId(getFileId());
		salesReportImpl.setFileName(getFileName());
		salesReportImpl.setFilePath(getFilePath());
		salesReportImpl.setPeriode(getPeriode());
		salesReportImpl.setKeterangan(getKeterangan());
		salesReportImpl.setRowStatus(isRowStatus());
		salesReportImpl.setCreatedDate(getCreatedDate());
		salesReportImpl.setCreatedBy(getCreatedBy());
		salesReportImpl.setModifiedDate(getModifiedDate());
		salesReportImpl.setModifiedBy(getModifiedBy());

		salesReportImpl.resetOriginalValues();

		return salesReportImpl;
	}

	@Override
	public SalesReport cloneWithOriginalValues() {
		SalesReportImpl salesReportImpl = new SalesReportImpl();

		salesReportImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		salesReportImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("DealerId"));
		salesReportImpl.setFileId(this.<Long>getColumnOriginalValue("FileId"));
		salesReportImpl.setFileName(
			this.<String>getColumnOriginalValue("FileName"));
		salesReportImpl.setFilePath(
			this.<String>getColumnOriginalValue("FilePath"));
		salesReportImpl.setPeriode(
			this.<Date>getColumnOriginalValue("Periode"));
		salesReportImpl.setKeterangan(
			this.<String>getColumnOriginalValue("Keterangan"));
		salesReportImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		salesReportImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		salesReportImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		salesReportImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		salesReportImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return salesReportImpl;
	}

	@Override
	public int compareTo(SalesReport salesReport) {
		int primaryKey = salesReport.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SalesReport)) {
			return false;
		}

		SalesReport salesReport = (SalesReport)object;

		int primaryKey = salesReport.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SalesReport> toCacheModel() {
		SalesReportCacheModel salesReportCacheModel =
			new SalesReportCacheModel();

		salesReportCacheModel.Id = getId();

		salesReportCacheModel.DealerId = getDealerId();

		Long FileId = getFileId();

		if (FileId != null) {
			salesReportCacheModel.FileId = FileId;
		}

		salesReportCacheModel.FileName = getFileName();

		String FileName = salesReportCacheModel.FileName;

		if ((FileName != null) && (FileName.length() == 0)) {
			salesReportCacheModel.FileName = null;
		}

		salesReportCacheModel.FilePath = getFilePath();

		String FilePath = salesReportCacheModel.FilePath;

		if ((FilePath != null) && (FilePath.length() == 0)) {
			salesReportCacheModel.FilePath = null;
		}

		Date Periode = getPeriode();

		if (Periode != null) {
			salesReportCacheModel.Periode = Periode.getTime();
		}
		else {
			salesReportCacheModel.Periode = Long.MIN_VALUE;
		}

		salesReportCacheModel.Keterangan = getKeterangan();

		String Keterangan = salesReportCacheModel.Keterangan;

		if ((Keterangan != null) && (Keterangan.length() == 0)) {
			salesReportCacheModel.Keterangan = null;
		}

		salesReportCacheModel.RowStatus = isRowStatus();

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			salesReportCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			salesReportCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		salesReportCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = salesReportCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			salesReportCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			salesReportCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			salesReportCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		salesReportCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = salesReportCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			salesReportCacheModel.ModifiedBy = null;
		}

		return salesReportCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SalesReport, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SalesReport, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SalesReport, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SalesReport)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SalesReport>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SalesReport.class, ModelWrapper.class);

	}

	private int _Id;
	private int _DealerId;
	private Long _FileId;
	private String _FileName;
	private String _FilePath;
	private Date _Periode;
	private String _Keterangan;
	private boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<SalesReport, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SalesReport)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("FileId", _FileId);
		_columnOriginalValues.put("FileName", _FileName);
		_columnOriginalValues.put("FilePath", _FilePath);
		_columnOriginalValues.put("Periode", _Periode);
		_columnOriginalValues.put("Keterangan", _Keterangan);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("DealerId", 2L);

		columnBitmasks.put("FileId", 4L);

		columnBitmasks.put("FileName", 8L);

		columnBitmasks.put("FilePath", 16L);

		columnBitmasks.put("Periode", 32L);

		columnBitmasks.put("Keterangan", 64L);

		columnBitmasks.put("RowStatus", 128L);

		columnBitmasks.put("CreatedDate", 256L);

		columnBitmasks.put("CreatedBy", 512L);

		columnBitmasks.put("ModifiedDate", 1024L);

		columnBitmasks.put("ModifiedBy", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SalesReport _escapedModel;

}