/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.SalesProgram;
import com.astra.dewa.model.SalesProgramModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SalesProgram service. Represents a row in the &quot;sales_program&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SalesProgramModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SalesProgramImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SalesProgramImpl
 * @generated
 */
public class SalesProgramModelImpl
	extends BaseModelImpl<SalesProgram> implements SalesProgramModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sales program model instance should use the <code>SalesProgram</code> interface instead.
	 */
	public static final String TABLE_NAME = "sales_program";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.BIGINT}, {"Tahun", Types.INTEGER},
		{"Periode", Types.VARCHAR}, {"FileId", Types.BIGINT},
		{"FileName", Types.VARCHAR}, {"rowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Tahun", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Periode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("rowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table sales_program (Id LONG not null primary key,Tahun INTEGER,Periode VARCHAR(75) null,FileId LONG,FileName VARCHAR(75) null,rowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table sales_program";

	public static final String ORDER_BY_JPQL = " ORDER BY salesProgram.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY sales_program.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.SalesProgram"));

	public SalesProgramModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SalesProgram.class;
	}

	@Override
	public String getModelClassName() {
		return SalesProgram.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SalesProgram, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SalesProgram, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SalesProgram, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SalesProgram)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SalesProgram, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SalesProgram, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SalesProgram)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SalesProgram, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SalesProgram, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SalesProgram, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SalesProgram, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SalesProgram, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<SalesProgram, Object>>();
		Map<String, BiConsumer<SalesProgram, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SalesProgram, ?>>();

		attributeGetterFunctions.put("Id", SalesProgram::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<SalesProgram, Long>)SalesProgram::setId);
		attributeGetterFunctions.put("Tahun", SalesProgram::getTahun);
		attributeSetterBiConsumers.put(
			"Tahun", (BiConsumer<SalesProgram, Integer>)SalesProgram::setTahun);
		attributeGetterFunctions.put("Periode", SalesProgram::getPeriode);
		attributeSetterBiConsumers.put(
			"Periode",
			(BiConsumer<SalesProgram, String>)SalesProgram::setPeriode);
		attributeGetterFunctions.put("FileId", SalesProgram::getFileId);
		attributeSetterBiConsumers.put(
			"FileId", (BiConsumer<SalesProgram, Long>)SalesProgram::setFileId);
		attributeGetterFunctions.put("FileName", SalesProgram::getFileName);
		attributeSetterBiConsumers.put(
			"FileName",
			(BiConsumer<SalesProgram, String>)SalesProgram::setFileName);
		attributeGetterFunctions.put("rowStatus", SalesProgram::getRowStatus);
		attributeSetterBiConsumers.put(
			"rowStatus",
			(BiConsumer<SalesProgram, Boolean>)SalesProgram::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", SalesProgram::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<SalesProgram, Date>)SalesProgram::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", SalesProgram::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<SalesProgram, String>)SalesProgram::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", SalesProgram::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<SalesProgram, Date>)SalesProgram::setModifiedDate);
		attributeGetterFunctions.put("ModifiedBy", SalesProgram::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<SalesProgram, String>)SalesProgram::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _Id;
	}

	@Override
	public void setId(long Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getTahun() {
		return _Tahun;
	}

	@Override
	public void setTahun(int Tahun) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Tahun = Tahun;
	}

	@Override
	public String getPeriode() {
		if (_Periode == null) {
			return "";
		}
		else {
			return _Periode;
		}
	}

	@Override
	public void setPeriode(String Periode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Periode = Periode;
	}

	@Override
	public Long getFileId() {
		return _FileId;
	}

	@Override
	public void setFileId(Long FileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileId = FileId;
	}

	@Override
	public String getFileName() {
		if (_FileName == null) {
			return "";
		}
		else {
			return _FileName;
		}
	}

	@Override
	public void setFileName(String FileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileName = FileName;
	}

	@Override
	public boolean getRowStatus() {
		return _rowStatus;
	}

	@Override
	public boolean isRowStatus() {
		return _rowStatus;
	}

	@Override
	public void setRowStatus(boolean rowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_rowStatus = rowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, SalesProgram.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SalesProgram toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SalesProgram>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SalesProgramImpl salesProgramImpl = new SalesProgramImpl();

		salesProgramImpl.setId(getId());
		salesProgramImpl.setTahun(getTahun());
		salesProgramImpl.setPeriode(getPeriode());
		salesProgramImpl.setFileId(getFileId());
		salesProgramImpl.setFileName(getFileName());
		salesProgramImpl.setRowStatus(isRowStatus());
		salesProgramImpl.setCreatedDate(getCreatedDate());
		salesProgramImpl.setCreatedBy(getCreatedBy());
		salesProgramImpl.setModifiedDate(getModifiedDate());
		salesProgramImpl.setModifiedBy(getModifiedBy());

		salesProgramImpl.resetOriginalValues();

		return salesProgramImpl;
	}

	@Override
	public SalesProgram cloneWithOriginalValues() {
		SalesProgramImpl salesProgramImpl = new SalesProgramImpl();

		salesProgramImpl.setId(this.<Long>getColumnOriginalValue("Id"));
		salesProgramImpl.setTahun(
			this.<Integer>getColumnOriginalValue("Tahun"));
		salesProgramImpl.setPeriode(
			this.<String>getColumnOriginalValue("Periode"));
		salesProgramImpl.setFileId(this.<Long>getColumnOriginalValue("FileId"));
		salesProgramImpl.setFileName(
			this.<String>getColumnOriginalValue("FileName"));
		salesProgramImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("rowStatus"));
		salesProgramImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		salesProgramImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		salesProgramImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		salesProgramImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return salesProgramImpl;
	}

	@Override
	public int compareTo(SalesProgram salesProgram) {
		long primaryKey = salesProgram.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SalesProgram)) {
			return false;
		}

		SalesProgram salesProgram = (SalesProgram)object;

		long primaryKey = salesProgram.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SalesProgram> toCacheModel() {
		SalesProgramCacheModel salesProgramCacheModel =
			new SalesProgramCacheModel();

		salesProgramCacheModel.Id = getId();

		salesProgramCacheModel.Tahun = getTahun();

		salesProgramCacheModel.Periode = getPeriode();

		String Periode = salesProgramCacheModel.Periode;

		if ((Periode != null) && (Periode.length() == 0)) {
			salesProgramCacheModel.Periode = null;
		}

		Long FileId = getFileId();

		if (FileId != null) {
			salesProgramCacheModel.FileId = FileId;
		}

		salesProgramCacheModel.FileName = getFileName();

		String FileName = salesProgramCacheModel.FileName;

		if ((FileName != null) && (FileName.length() == 0)) {
			salesProgramCacheModel.FileName = null;
		}

		salesProgramCacheModel.rowStatus = isRowStatus();

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			salesProgramCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			salesProgramCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		salesProgramCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = salesProgramCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			salesProgramCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			salesProgramCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			salesProgramCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		salesProgramCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = salesProgramCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			salesProgramCacheModel.ModifiedBy = null;
		}

		return salesProgramCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SalesProgram, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SalesProgram, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SalesProgram, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SalesProgram)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SalesProgram>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SalesProgram.class, ModelWrapper.class);

	}

	private long _Id;
	private int _Tahun;
	private String _Periode;
	private Long _FileId;
	private String _FileName;
	private boolean _rowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<SalesProgram, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SalesProgram)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("Tahun", _Tahun);
		_columnOriginalValues.put("Periode", _Periode);
		_columnOriginalValues.put("FileId", _FileId);
		_columnOriginalValues.put("FileName", _FileName);
		_columnOriginalValues.put("rowStatus", _rowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("Tahun", 2L);

		columnBitmasks.put("Periode", 4L);

		columnBitmasks.put("FileId", 8L);

		columnBitmasks.put("FileName", 16L);

		columnBitmasks.put("rowStatus", 32L);

		columnBitmasks.put("CreatedDate", 64L);

		columnBitmasks.put("CreatedBy", 128L);

		columnBitmasks.put("ModifiedDate", 256L);

		columnBitmasks.put("ModifiedBy", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SalesProgram _escapedModel;

}