/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.Setting;
import com.astra.dewa.model.SettingModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Setting service. Represents a row in the &quot;Setting&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SettingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SettingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SettingImpl
 * @generated
 */
public class SettingModelImpl
	extends BaseModelImpl<Setting> implements SettingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a setting model instance should use the <code>Setting</code> interface instead.
	 */
	public static final String TABLE_NAME = "Setting";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"KeySetting", Types.VARCHAR},
		{"Code", Types.VARCHAR}, {"Value", Types.VARCHAR},
		{"RowStatus", Types.BOOLEAN}, {"CreatedBy", Types.VARCHAR},
		{"CreatedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("KeySetting", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Value", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Setting (Id INTEGER not null primary key IDENTITY,KeySetting VARCHAR(75) null,Code VARCHAR(75) null,Value VARCHAR(75) null,RowStatus BOOLEAN,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table Setting";

	public static final String ORDER_BY_JPQL = " ORDER BY setting.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY Setting.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CODE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long KEYSETTING_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.Setting"));

	public SettingModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Setting.class;
	}

	@Override
	public String getModelClassName() {
		return Setting.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Setting, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Setting, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Setting, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Setting)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Setting, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Setting, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Setting)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Setting, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Setting, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Setting, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Setting, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Setting, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Setting, Object>>();
		Map<String, BiConsumer<Setting, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Setting, ?>>();

		attributeGetterFunctions.put("Id", Setting::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<Setting, Integer>)Setting::setId);
		attributeGetterFunctions.put("KeySetting", Setting::getKeySetting);
		attributeSetterBiConsumers.put(
			"KeySetting", (BiConsumer<Setting, String>)Setting::setKeySetting);
		attributeGetterFunctions.put("Code", Setting::getCode);
		attributeSetterBiConsumers.put(
			"Code", (BiConsumer<Setting, String>)Setting::setCode);
		attributeGetterFunctions.put("Value", Setting::getValue);
		attributeSetterBiConsumers.put(
			"Value", (BiConsumer<Setting, String>)Setting::setValue);
		attributeGetterFunctions.put("RowStatus", Setting::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus", (BiConsumer<Setting, Boolean>)Setting::setRowStatus);
		attributeGetterFunctions.put("CreatedBy", Setting::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy", (BiConsumer<Setting, String>)Setting::setCreatedBy);
		attributeGetterFunctions.put("CreatedDate", Setting::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate", (BiConsumer<Setting, Date>)Setting::setCreatedDate);
		attributeGetterFunctions.put("ModifiedBy", Setting::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy", (BiConsumer<Setting, String>)Setting::setModifiedBy);
		attributeGetterFunctions.put("ModifiedDate", Setting::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<Setting, Date>)Setting::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public String getKeySetting() {
		if (_KeySetting == null) {
			return "";
		}
		else {
			return _KeySetting;
		}
	}

	@Override
	public void setKeySetting(String KeySetting) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_KeySetting = KeySetting;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalKeySetting() {
		return getColumnOriginalValue("KeySetting");
	}

	@Override
	public String getCode() {
		if (_Code == null) {
			return "";
		}
		else {
			return _Code;
		}
	}

	@Override
	public void setCode(String Code) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Code = Code;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCode() {
		return getColumnOriginalValue("Code");
	}

	@Override
	public String getValue() {
		if (_Value == null) {
			return "";
		}
		else {
			return _Value;
		}
	}

	@Override
	public void setValue(String Value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Value = Value;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Setting toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Setting>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SettingImpl settingImpl = new SettingImpl();

		settingImpl.setId(getId());
		settingImpl.setKeySetting(getKeySetting());
		settingImpl.setCode(getCode());
		settingImpl.setValue(getValue());
		settingImpl.setRowStatus(getRowStatus());
		settingImpl.setCreatedBy(getCreatedBy());
		settingImpl.setCreatedDate(getCreatedDate());
		settingImpl.setModifiedBy(getModifiedBy());
		settingImpl.setModifiedDate(getModifiedDate());

		settingImpl.resetOriginalValues();

		return settingImpl;
	}

	@Override
	public Setting cloneWithOriginalValues() {
		SettingImpl settingImpl = new SettingImpl();

		settingImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		settingImpl.setKeySetting(
			this.<String>getColumnOriginalValue("KeySetting"));
		settingImpl.setCode(this.<String>getColumnOriginalValue("Code"));
		settingImpl.setValue(this.<String>getColumnOriginalValue("Value"));
		settingImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		settingImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		settingImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		settingImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));
		settingImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));

		return settingImpl;
	}

	@Override
	public int compareTo(Setting setting) {
		int primaryKey = setting.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Setting)) {
			return false;
		}

		Setting setting = (Setting)object;

		int primaryKey = setting.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Setting> toCacheModel() {
		SettingCacheModel settingCacheModel = new SettingCacheModel();

		settingCacheModel.Id = getId();

		settingCacheModel.KeySetting = getKeySetting();

		String KeySetting = settingCacheModel.KeySetting;

		if ((KeySetting != null) && (KeySetting.length() == 0)) {
			settingCacheModel.KeySetting = null;
		}

		settingCacheModel.Code = getCode();

		String Code = settingCacheModel.Code;

		if ((Code != null) && (Code.length() == 0)) {
			settingCacheModel.Code = null;
		}

		settingCacheModel.Value = getValue();

		String Value = settingCacheModel.Value;

		if ((Value != null) && (Value.length() == 0)) {
			settingCacheModel.Value = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			settingCacheModel.RowStatus = RowStatus;
		}

		settingCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = settingCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			settingCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			settingCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			settingCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		settingCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = settingCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			settingCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			settingCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			settingCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		return settingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Setting, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Setting, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Setting, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Setting)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Setting>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Setting.class, ModelWrapper.class);

	}

	private int _Id;
	private String _KeySetting;
	private String _Code;
	private String _Value;
	private Boolean _RowStatus;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<Setting, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Setting)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("KeySetting", _KeySetting);
		_columnOriginalValues.put("Code", _Code);
		_columnOriginalValues.put("Value", _Value);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("KeySetting", 2L);

		columnBitmasks.put("Code", 4L);

		columnBitmasks.put("Value", 8L);

		columnBitmasks.put("RowStatus", 16L);

		columnBitmasks.put("CreatedBy", 32L);

		columnBitmasks.put("CreatedDate", 64L);

		columnBitmasks.put("ModifiedBy", 128L);

		columnBitmasks.put("ModifiedDate", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Setting _escapedModel;

}