/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.SP3D;
import com.astra.dewa.model.SP3DModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SP3D service. Represents a row in the &quot;sp3d&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SP3DModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SP3DImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SP3DImpl
 * @generated
 */
public class SP3DModelImpl extends BaseModelImpl<SP3D> implements SP3DModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sp3d model instance should use the <code>SP3D</code> interface instead.
	 */
	public static final String TABLE_NAME = "sp3d";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"DealerId", Types.INTEGER},
		{"Tahun", Types.INTEGER}, {"Bulan", Types.VARCHAR},
		{"FileId", Types.BIGINT}, {"FileName", Types.VARCHAR},
		{"FilePath", Types.VARCHAR}, {"RowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Tahun", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Bulan", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FilePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table sp3d (Id INTEGER not null primary key IDENTITY,DealerId INTEGER,Tahun INTEGER,Bulan VARCHAR(75) null,FileId LONG,FileName VARCHAR(75) null,FilePath VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table sp3d";

	public static final String ORDER_BY_JPQL = " ORDER BY sp3d.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY sp3d.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.SP3D"));

	public SP3DModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SP3D.class;
	}

	@Override
	public String getModelClassName() {
		return SP3D.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SP3D, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SP3D, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SP3D, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((SP3D)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SP3D, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SP3D, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((SP3D)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SP3D, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SP3D, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SP3D, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SP3D, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SP3D, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<SP3D, Object>>();
		Map<String, BiConsumer<SP3D, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SP3D, ?>>();

		attributeGetterFunctions.put("Id", SP3D::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<SP3D, Integer>)SP3D::setId);
		attributeGetterFunctions.put("DealerId", SP3D::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId", (BiConsumer<SP3D, Integer>)SP3D::setDealerId);
		attributeGetterFunctions.put("Tahun", SP3D::getTahun);
		attributeSetterBiConsumers.put(
			"Tahun", (BiConsumer<SP3D, Integer>)SP3D::setTahun);
		attributeGetterFunctions.put("Bulan", SP3D::getBulan);
		attributeSetterBiConsumers.put(
			"Bulan", (BiConsumer<SP3D, String>)SP3D::setBulan);
		attributeGetterFunctions.put("FileId", SP3D::getFileId);
		attributeSetterBiConsumers.put(
			"FileId", (BiConsumer<SP3D, Long>)SP3D::setFileId);
		attributeGetterFunctions.put("FileName", SP3D::getFileName);
		attributeSetterBiConsumers.put(
			"FileName", (BiConsumer<SP3D, String>)SP3D::setFileName);
		attributeGetterFunctions.put("FilePath", SP3D::getFilePath);
		attributeSetterBiConsumers.put(
			"FilePath", (BiConsumer<SP3D, String>)SP3D::setFilePath);
		attributeGetterFunctions.put("RowStatus", SP3D::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus", (BiConsumer<SP3D, Boolean>)SP3D::setRowStatus);
		attributeGetterFunctions.put("CreatedDate", SP3D::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate", (BiConsumer<SP3D, Date>)SP3D::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", SP3D::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy", (BiConsumer<SP3D, String>)SP3D::setCreatedBy);
		attributeGetterFunctions.put("ModifiedDate", SP3D::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate", (BiConsumer<SP3D, Date>)SP3D::setModifiedDate);
		attributeGetterFunctions.put("ModifiedBy", SP3D::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy", (BiConsumer<SP3D, String>)SP3D::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public Integer getTahun() {
		return _Tahun;
	}

	@Override
	public void setTahun(Integer Tahun) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Tahun = Tahun;
	}

	@Override
	public String getBulan() {
		if (_Bulan == null) {
			return "";
		}
		else {
			return _Bulan;
		}
	}

	@Override
	public void setBulan(String Bulan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Bulan = Bulan;
	}

	@Override
	public Long getFileId() {
		return _FileId;
	}

	@Override
	public void setFileId(Long FileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileId = FileId;
	}

	@Override
	public String getFileName() {
		if (_FileName == null) {
			return "";
		}
		else {
			return _FileName;
		}
	}

	@Override
	public void setFileName(String FileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileName = FileName;
	}

	@Override
	public String getFilePath() {
		if (_FilePath == null) {
			return "";
		}
		else {
			return _FilePath;
		}
	}

	@Override
	public void setFilePath(String FilePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FilePath = FilePath;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public SP3D toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SP3D>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SP3DImpl sp3dImpl = new SP3DImpl();

		sp3dImpl.setId(getId());
		sp3dImpl.setDealerId(getDealerId());
		sp3dImpl.setTahun(getTahun());
		sp3dImpl.setBulan(getBulan());
		sp3dImpl.setFileId(getFileId());
		sp3dImpl.setFileName(getFileName());
		sp3dImpl.setFilePath(getFilePath());
		sp3dImpl.setRowStatus(getRowStatus());
		sp3dImpl.setCreatedDate(getCreatedDate());
		sp3dImpl.setCreatedBy(getCreatedBy());
		sp3dImpl.setModifiedDate(getModifiedDate());
		sp3dImpl.setModifiedBy(getModifiedBy());

		sp3dImpl.resetOriginalValues();

		return sp3dImpl;
	}

	@Override
	public SP3D cloneWithOriginalValues() {
		SP3DImpl sp3dImpl = new SP3DImpl();

		sp3dImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		sp3dImpl.setDealerId(this.<Integer>getColumnOriginalValue("DealerId"));
		sp3dImpl.setTahun(this.<Integer>getColumnOriginalValue("Tahun"));
		sp3dImpl.setBulan(this.<String>getColumnOriginalValue("Bulan"));
		sp3dImpl.setFileId(this.<Long>getColumnOriginalValue("FileId"));
		sp3dImpl.setFileName(this.<String>getColumnOriginalValue("FileName"));
		sp3dImpl.setFilePath(this.<String>getColumnOriginalValue("FilePath"));
		sp3dImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		sp3dImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		sp3dImpl.setCreatedBy(this.<String>getColumnOriginalValue("CreatedBy"));
		sp3dImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		sp3dImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return sp3dImpl;
	}

	@Override
	public int compareTo(SP3D sp3d) {
		int primaryKey = sp3d.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SP3D)) {
			return false;
		}

		SP3D sp3d = (SP3D)object;

		int primaryKey = sp3d.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SP3D> toCacheModel() {
		SP3DCacheModel sp3dCacheModel = new SP3DCacheModel();

		sp3dCacheModel.Id = getId();

		sp3dCacheModel.DealerId = getDealerId();

		Integer Tahun = getTahun();

		if (Tahun != null) {
			sp3dCacheModel.Tahun = Tahun;
		}

		sp3dCacheModel.Bulan = getBulan();

		String Bulan = sp3dCacheModel.Bulan;

		if ((Bulan != null) && (Bulan.length() == 0)) {
			sp3dCacheModel.Bulan = null;
		}

		Long FileId = getFileId();

		if (FileId != null) {
			sp3dCacheModel.FileId = FileId;
		}

		sp3dCacheModel.FileName = getFileName();

		String FileName = sp3dCacheModel.FileName;

		if ((FileName != null) && (FileName.length() == 0)) {
			sp3dCacheModel.FileName = null;
		}

		sp3dCacheModel.FilePath = getFilePath();

		String FilePath = sp3dCacheModel.FilePath;

		if ((FilePath != null) && (FilePath.length() == 0)) {
			sp3dCacheModel.FilePath = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			sp3dCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			sp3dCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			sp3dCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		sp3dCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = sp3dCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			sp3dCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			sp3dCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			sp3dCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		sp3dCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = sp3dCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			sp3dCacheModel.ModifiedBy = null;
		}

		return sp3dCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SP3D, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SP3D, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SP3D, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SP3D)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SP3D>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SP3D.class, ModelWrapper.class);

	}

	private int _Id;
	private int _DealerId;
	private Integer _Tahun;
	private String _Bulan;
	private Long _FileId;
	private String _FileName;
	private String _FilePath;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<SP3D, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SP3D)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("Tahun", _Tahun);
		_columnOriginalValues.put("Bulan", _Bulan);
		_columnOriginalValues.put("FileId", _FileId);
		_columnOriginalValues.put("FileName", _FileName);
		_columnOriginalValues.put("FilePath", _FilePath);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("DealerId", 2L);

		columnBitmasks.put("Tahun", 4L);

		columnBitmasks.put("Bulan", 8L);

		columnBitmasks.put("FileId", 16L);

		columnBitmasks.put("FileName", 32L);

		columnBitmasks.put("FilePath", 64L);

		columnBitmasks.put("RowStatus", 128L);

		columnBitmasks.put("CreatedDate", 256L);

		columnBitmasks.put("CreatedBy", 512L);

		columnBitmasks.put("ModifiedDate", 1024L);

		columnBitmasks.put("ModifiedBy", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SP3D _escapedModel;

}