/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.Ticket;
import com.astra.dewa.model.TicketModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Ticket service. Represents a row in the &quot;ticket&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TicketModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TicketImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketImpl
 * @generated
 */
public class TicketModelImpl
	extends BaseModelImpl<Ticket> implements TicketModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ticket model instance should use the <code>Ticket</code> interface instead.
	 */
	public static final String TABLE_NAME = "ticket";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.VARCHAR}, {"DealerCode", Types.VARCHAR},
		{"TicketDate", Types.TIMESTAMP}, {"TicketNumber", Types.VARCHAR},
		{"RequestName", Types.VARCHAR}, {"FirstApprover", Types.VARCHAR},
		{"Email", Types.VARCHAR}, {"EmailCc", Types.VARCHAR},
		{"Phone", Types.VARCHAR}, {"RequestCategory", Types.VARCHAR},
		{"RequestDescription", Types.VARCHAR},
		{"BussinesBenefit", Types.VARCHAR}, {"NameFile", Types.VARCHAR},
		{"PathFile", Types.VARCHAR}, {"CreatedDate", Types.TIMESTAMP},
		{"CreatedBy", Types.VARCHAR}, {"ModifiedDate", Types.TIMESTAMP},
		{"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DealerCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("TicketDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("TicketNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RequestName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FirstApprover", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("EmailCc", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Phone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RequestCategory", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RequestDescription", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("BussinesBenefit", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("NameFile", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PathFile", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ticket (Id VARCHAR(75) not null primary key,DealerCode VARCHAR(75) null,TicketDate DATE null,TicketNumber VARCHAR(75) null,RequestName VARCHAR(75) null,FirstApprover VARCHAR(75) null,Email VARCHAR(75) null,EmailCc VARCHAR(75) null,Phone VARCHAR(75) null,RequestCategory VARCHAR(75) null,RequestDescription VARCHAR(75) null,BussinesBenefit VARCHAR(75) null,NameFile VARCHAR(75) null,PathFile VARCHAR(75) null,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table ticket";

	public static final String ORDER_BY_JPQL = " ORDER BY ticket.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY ticket.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.Ticket"));

	public TicketModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Ticket.class;
	}

	@Override
	public String getModelClassName() {
		return Ticket.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Ticket, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Ticket, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Ticket, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Ticket)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Ticket, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Ticket, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Ticket)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Ticket, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Ticket, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Ticket, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Ticket, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Ticket, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Ticket, Object>>();
		Map<String, BiConsumer<Ticket, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Ticket, ?>>();

		attributeGetterFunctions.put("Id", Ticket::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<Ticket, String>)Ticket::setId);
		attributeGetterFunctions.put("DealerCode", Ticket::getDealerCode);
		attributeSetterBiConsumers.put(
			"DealerCode", (BiConsumer<Ticket, String>)Ticket::setDealerCode);
		attributeGetterFunctions.put("TicketDate", Ticket::getTicketDate);
		attributeSetterBiConsumers.put(
			"TicketDate", (BiConsumer<Ticket, Date>)Ticket::setTicketDate);
		attributeGetterFunctions.put("TicketNumber", Ticket::getTicketNumber);
		attributeSetterBiConsumers.put(
			"TicketNumber",
			(BiConsumer<Ticket, String>)Ticket::setTicketNumber);
		attributeGetterFunctions.put("RequestName", Ticket::getRequestName);
		attributeSetterBiConsumers.put(
			"RequestName", (BiConsumer<Ticket, String>)Ticket::setRequestName);
		attributeGetterFunctions.put("FirstApprover", Ticket::getFirstApprover);
		attributeSetterBiConsumers.put(
			"FirstApprover",
			(BiConsumer<Ticket, String>)Ticket::setFirstApprover);
		attributeGetterFunctions.put("Email", Ticket::getEmail);
		attributeSetterBiConsumers.put(
			"Email", (BiConsumer<Ticket, String>)Ticket::setEmail);
		attributeGetterFunctions.put("EmailCc", Ticket::getEmailCc);
		attributeSetterBiConsumers.put(
			"EmailCc", (BiConsumer<Ticket, String>)Ticket::setEmailCc);
		attributeGetterFunctions.put("Phone", Ticket::getPhone);
		attributeSetterBiConsumers.put(
			"Phone", (BiConsumer<Ticket, String>)Ticket::setPhone);
		attributeGetterFunctions.put(
			"RequestCategory", Ticket::getRequestCategory);
		attributeSetterBiConsumers.put(
			"RequestCategory",
			(BiConsumer<Ticket, String>)Ticket::setRequestCategory);
		attributeGetterFunctions.put(
			"RequestDescription", Ticket::getRequestDescription);
		attributeSetterBiConsumers.put(
			"RequestDescription",
			(BiConsumer<Ticket, String>)Ticket::setRequestDescription);
		attributeGetterFunctions.put(
			"BussinesBenefit", Ticket::getBussinesBenefit);
		attributeSetterBiConsumers.put(
			"BussinesBenefit",
			(BiConsumer<Ticket, String>)Ticket::setBussinesBenefit);
		attributeGetterFunctions.put("NameFile", Ticket::getNameFile);
		attributeSetterBiConsumers.put(
			"NameFile", (BiConsumer<Ticket, String>)Ticket::setNameFile);
		attributeGetterFunctions.put("PathFile", Ticket::getPathFile);
		attributeSetterBiConsumers.put(
			"PathFile", (BiConsumer<Ticket, String>)Ticket::setPathFile);
		attributeGetterFunctions.put("CreatedDate", Ticket::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate", (BiConsumer<Ticket, Date>)Ticket::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", Ticket::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy", (BiConsumer<Ticket, String>)Ticket::setCreatedBy);
		attributeGetterFunctions.put("ModifiedDate", Ticket::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate", (BiConsumer<Ticket, Date>)Ticket::setModifiedDate);
		attributeGetterFunctions.put("ModifiedBy", Ticket::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy", (BiConsumer<Ticket, String>)Ticket::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getId() {
		if (_Id == null) {
			return "";
		}
		else {
			return _Id;
		}
	}

	@Override
	public void setId(String Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public String getDealerCode() {
		if (_DealerCode == null) {
			return "";
		}
		else {
			return _DealerCode;
		}
	}

	@Override
	public void setDealerCode(String DealerCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerCode = DealerCode;
	}

	@Override
	public Date getTicketDate() {
		return _TicketDate;
	}

	@Override
	public void setTicketDate(Date TicketDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TicketDate = TicketDate;
	}

	@Override
	public String getTicketNumber() {
		if (_TicketNumber == null) {
			return "";
		}
		else {
			return _TicketNumber;
		}
	}

	@Override
	public void setTicketNumber(String TicketNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TicketNumber = TicketNumber;
	}

	@Override
	public String getRequestName() {
		if (_RequestName == null) {
			return "";
		}
		else {
			return _RequestName;
		}
	}

	@Override
	public void setRequestName(String RequestName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RequestName = RequestName;
	}

	@Override
	public String getFirstApprover() {
		if (_FirstApprover == null) {
			return "";
		}
		else {
			return _FirstApprover;
		}
	}

	@Override
	public void setFirstApprover(String FirstApprover) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FirstApprover = FirstApprover;
	}

	@Override
	public String getEmail() {
		if (_Email == null) {
			return "";
		}
		else {
			return _Email;
		}
	}

	@Override
	public void setEmail(String Email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Email = Email;
	}

	@Override
	public String getEmailCc() {
		if (_EmailCc == null) {
			return "";
		}
		else {
			return _EmailCc;
		}
	}

	@Override
	public void setEmailCc(String EmailCc) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_EmailCc = EmailCc;
	}

	@Override
	public String getPhone() {
		if (_Phone == null) {
			return "";
		}
		else {
			return _Phone;
		}
	}

	@Override
	public void setPhone(String Phone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Phone = Phone;
	}

	@Override
	public String getRequestCategory() {
		if (_RequestCategory == null) {
			return "";
		}
		else {
			return _RequestCategory;
		}
	}

	@Override
	public void setRequestCategory(String RequestCategory) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RequestCategory = RequestCategory;
	}

	@Override
	public String getRequestDescription() {
		if (_RequestDescription == null) {
			return "";
		}
		else {
			return _RequestDescription;
		}
	}

	@Override
	public void setRequestDescription(String RequestDescription) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RequestDescription = RequestDescription;
	}

	@Override
	public String getBussinesBenefit() {
		if (_BussinesBenefit == null) {
			return "";
		}
		else {
			return _BussinesBenefit;
		}
	}

	@Override
	public void setBussinesBenefit(String BussinesBenefit) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_BussinesBenefit = BussinesBenefit;
	}

	@Override
	public String getNameFile() {
		if (_NameFile == null) {
			return "";
		}
		else {
			return _NameFile;
		}
	}

	@Override
	public void setNameFile(String NameFile) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_NameFile = NameFile;
	}

	@Override
	public String getPathFile() {
		if (_PathFile == null) {
			return "";
		}
		else {
			return _PathFile;
		}
	}

	@Override
	public void setPathFile(String PathFile) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_PathFile = PathFile;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Ticket toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Ticket>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TicketImpl ticketImpl = new TicketImpl();

		ticketImpl.setId(getId());
		ticketImpl.setDealerCode(getDealerCode());
		ticketImpl.setTicketDate(getTicketDate());
		ticketImpl.setTicketNumber(getTicketNumber());
		ticketImpl.setRequestName(getRequestName());
		ticketImpl.setFirstApprover(getFirstApprover());
		ticketImpl.setEmail(getEmail());
		ticketImpl.setEmailCc(getEmailCc());
		ticketImpl.setPhone(getPhone());
		ticketImpl.setRequestCategory(getRequestCategory());
		ticketImpl.setRequestDescription(getRequestDescription());
		ticketImpl.setBussinesBenefit(getBussinesBenefit());
		ticketImpl.setNameFile(getNameFile());
		ticketImpl.setPathFile(getPathFile());
		ticketImpl.setCreatedDate(getCreatedDate());
		ticketImpl.setCreatedBy(getCreatedBy());
		ticketImpl.setModifiedDate(getModifiedDate());
		ticketImpl.setModifiedBy(getModifiedBy());

		ticketImpl.resetOriginalValues();

		return ticketImpl;
	}

	@Override
	public Ticket cloneWithOriginalValues() {
		TicketImpl ticketImpl = new TicketImpl();

		ticketImpl.setId(this.<String>getColumnOriginalValue("Id"));
		ticketImpl.setDealerCode(
			this.<String>getColumnOriginalValue("DealerCode"));
		ticketImpl.setTicketDate(
			this.<Date>getColumnOriginalValue("TicketDate"));
		ticketImpl.setTicketNumber(
			this.<String>getColumnOriginalValue("TicketNumber"));
		ticketImpl.setRequestName(
			this.<String>getColumnOriginalValue("RequestName"));
		ticketImpl.setFirstApprover(
			this.<String>getColumnOriginalValue("FirstApprover"));
		ticketImpl.setEmail(this.<String>getColumnOriginalValue("Email"));
		ticketImpl.setEmailCc(this.<String>getColumnOriginalValue("EmailCc"));
		ticketImpl.setPhone(this.<String>getColumnOriginalValue("Phone"));
		ticketImpl.setRequestCategory(
			this.<String>getColumnOriginalValue("RequestCategory"));
		ticketImpl.setRequestDescription(
			this.<String>getColumnOriginalValue("RequestDescription"));
		ticketImpl.setBussinesBenefit(
			this.<String>getColumnOriginalValue("BussinesBenefit"));
		ticketImpl.setNameFile(this.<String>getColumnOriginalValue("NameFile"));
		ticketImpl.setPathFile(this.<String>getColumnOriginalValue("PathFile"));
		ticketImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		ticketImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		ticketImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		ticketImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return ticketImpl;
	}

	@Override
	public int compareTo(Ticket ticket) {
		String primaryKey = ticket.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Ticket)) {
			return false;
		}

		Ticket ticket = (Ticket)object;

		String primaryKey = ticket.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Ticket> toCacheModel() {
		TicketCacheModel ticketCacheModel = new TicketCacheModel();

		ticketCacheModel.Id = getId();

		String Id = ticketCacheModel.Id;

		if ((Id != null) && (Id.length() == 0)) {
			ticketCacheModel.Id = null;
		}

		ticketCacheModel.DealerCode = getDealerCode();

		String DealerCode = ticketCacheModel.DealerCode;

		if ((DealerCode != null) && (DealerCode.length() == 0)) {
			ticketCacheModel.DealerCode = null;
		}

		Date TicketDate = getTicketDate();

		if (TicketDate != null) {
			ticketCacheModel.TicketDate = TicketDate.getTime();
		}
		else {
			ticketCacheModel.TicketDate = Long.MIN_VALUE;
		}

		ticketCacheModel.TicketNumber = getTicketNumber();

		String TicketNumber = ticketCacheModel.TicketNumber;

		if ((TicketNumber != null) && (TicketNumber.length() == 0)) {
			ticketCacheModel.TicketNumber = null;
		}

		ticketCacheModel.RequestName = getRequestName();

		String RequestName = ticketCacheModel.RequestName;

		if ((RequestName != null) && (RequestName.length() == 0)) {
			ticketCacheModel.RequestName = null;
		}

		ticketCacheModel.FirstApprover = getFirstApprover();

		String FirstApprover = ticketCacheModel.FirstApprover;

		if ((FirstApprover != null) && (FirstApprover.length() == 0)) {
			ticketCacheModel.FirstApprover = null;
		}

		ticketCacheModel.Email = getEmail();

		String Email = ticketCacheModel.Email;

		if ((Email != null) && (Email.length() == 0)) {
			ticketCacheModel.Email = null;
		}

		ticketCacheModel.EmailCc = getEmailCc();

		String EmailCc = ticketCacheModel.EmailCc;

		if ((EmailCc != null) && (EmailCc.length() == 0)) {
			ticketCacheModel.EmailCc = null;
		}

		ticketCacheModel.Phone = getPhone();

		String Phone = ticketCacheModel.Phone;

		if ((Phone != null) && (Phone.length() == 0)) {
			ticketCacheModel.Phone = null;
		}

		ticketCacheModel.RequestCategory = getRequestCategory();

		String RequestCategory = ticketCacheModel.RequestCategory;

		if ((RequestCategory != null) && (RequestCategory.length() == 0)) {
			ticketCacheModel.RequestCategory = null;
		}

		ticketCacheModel.RequestDescription = getRequestDescription();

		String RequestDescription = ticketCacheModel.RequestDescription;

		if ((RequestDescription != null) &&
			(RequestDescription.length() == 0)) {

			ticketCacheModel.RequestDescription = null;
		}

		ticketCacheModel.BussinesBenefit = getBussinesBenefit();

		String BussinesBenefit = ticketCacheModel.BussinesBenefit;

		if ((BussinesBenefit != null) && (BussinesBenefit.length() == 0)) {
			ticketCacheModel.BussinesBenefit = null;
		}

		ticketCacheModel.NameFile = getNameFile();

		String NameFile = ticketCacheModel.NameFile;

		if ((NameFile != null) && (NameFile.length() == 0)) {
			ticketCacheModel.NameFile = null;
		}

		ticketCacheModel.PathFile = getPathFile();

		String PathFile = ticketCacheModel.PathFile;

		if ((PathFile != null) && (PathFile.length() == 0)) {
			ticketCacheModel.PathFile = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			ticketCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			ticketCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		ticketCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = ticketCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			ticketCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			ticketCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			ticketCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		ticketCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = ticketCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			ticketCacheModel.ModifiedBy = null;
		}

		return ticketCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Ticket, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Ticket, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Ticket, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Ticket)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Ticket>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Ticket.class, ModelWrapper.class);

	}

	private String _Id;
	private String _DealerCode;
	private Date _TicketDate;
	private String _TicketNumber;
	private String _RequestName;
	private String _FirstApprover;
	private String _Email;
	private String _EmailCc;
	private String _Phone;
	private String _RequestCategory;
	private String _RequestDescription;
	private String _BussinesBenefit;
	private String _NameFile;
	private String _PathFile;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<Ticket, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Ticket)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("DealerCode", _DealerCode);
		_columnOriginalValues.put("TicketDate", _TicketDate);
		_columnOriginalValues.put("TicketNumber", _TicketNumber);
		_columnOriginalValues.put("RequestName", _RequestName);
		_columnOriginalValues.put("FirstApprover", _FirstApprover);
		_columnOriginalValues.put("Email", _Email);
		_columnOriginalValues.put("EmailCc", _EmailCc);
		_columnOriginalValues.put("Phone", _Phone);
		_columnOriginalValues.put("RequestCategory", _RequestCategory);
		_columnOriginalValues.put("RequestDescription", _RequestDescription);
		_columnOriginalValues.put("BussinesBenefit", _BussinesBenefit);
		_columnOriginalValues.put("NameFile", _NameFile);
		_columnOriginalValues.put("PathFile", _PathFile);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("DealerCode", 2L);

		columnBitmasks.put("TicketDate", 4L);

		columnBitmasks.put("TicketNumber", 8L);

		columnBitmasks.put("RequestName", 16L);

		columnBitmasks.put("FirstApprover", 32L);

		columnBitmasks.put("Email", 64L);

		columnBitmasks.put("EmailCc", 128L);

		columnBitmasks.put("Phone", 256L);

		columnBitmasks.put("RequestCategory", 512L);

		columnBitmasks.put("RequestDescription", 1024L);

		columnBitmasks.put("BussinesBenefit", 2048L);

		columnBitmasks.put("NameFile", 4096L);

		columnBitmasks.put("PathFile", 8192L);

		columnBitmasks.put("CreatedDate", 16384L);

		columnBitmasks.put("CreatedBy", 32768L);

		columnBitmasks.put("ModifiedDate", 65536L);

		columnBitmasks.put("ModifiedBy", 131072L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Ticket _escapedModel;

}