/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.Token;
import com.astra.dewa.model.TokenModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Token service. Represents a row in the &quot;Token&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TokenModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TokenImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TokenImpl
 * @generated
 */
public class TokenModelImpl extends BaseModelImpl<Token> implements TokenModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a token model instance should use the <code>Token</code> interface instead.
	 */
	public static final String TABLE_NAME = "Token";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"TokenNumber", Types.VARCHAR},
		{"CreatedDate", Types.TIMESTAMP}, {"ExpiredDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("TokenNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ExpiredDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Token (Id INTEGER not null primary key IDENTITY,TokenNumber VARCHAR(75) null,CreatedDate DATE null,ExpiredDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table Token";

	public static final String ORDER_BY_JPQL = " ORDER BY token.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY Token.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.Token"));

	public TokenModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Token.class;
	}

	@Override
	public String getModelClassName() {
		return Token.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Token, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Token, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Token, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Token)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Token, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Token, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Token)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Token, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Token, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Token, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Token, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Token, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Token, Object>>();
		Map<String, BiConsumer<Token, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Token, ?>>();

		attributeGetterFunctions.put("Id", Token::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<Token, Integer>)Token::setId);
		attributeGetterFunctions.put("TokenNumber", Token::getTokenNumber);
		attributeSetterBiConsumers.put(
			"TokenNumber", (BiConsumer<Token, String>)Token::setTokenNumber);
		attributeGetterFunctions.put("CreatedDate", Token::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate", (BiConsumer<Token, Date>)Token::setCreatedDate);
		attributeGetterFunctions.put("ExpiredDate", Token::getExpiredDate);
		attributeSetterBiConsumers.put(
			"ExpiredDate", (BiConsumer<Token, Date>)Token::setExpiredDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public String getTokenNumber() {
		if (_TokenNumber == null) {
			return "";
		}
		else {
			return _TokenNumber;
		}
	}

	@Override
	public void setTokenNumber(String TokenNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TokenNumber = TokenNumber;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public Date getExpiredDate() {
		return _ExpiredDate;
	}

	@Override
	public void setExpiredDate(Date ExpiredDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ExpiredDate = ExpiredDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Token toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Token>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TokenImpl tokenImpl = new TokenImpl();

		tokenImpl.setId(getId());
		tokenImpl.setTokenNumber(getTokenNumber());
		tokenImpl.setCreatedDate(getCreatedDate());
		tokenImpl.setExpiredDate(getExpiredDate());

		tokenImpl.resetOriginalValues();

		return tokenImpl;
	}

	@Override
	public Token cloneWithOriginalValues() {
		TokenImpl tokenImpl = new TokenImpl();

		tokenImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		tokenImpl.setTokenNumber(
			this.<String>getColumnOriginalValue("TokenNumber"));
		tokenImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		tokenImpl.setExpiredDate(
			this.<Date>getColumnOriginalValue("ExpiredDate"));

		return tokenImpl;
	}

	@Override
	public int compareTo(Token token) {
		int primaryKey = token.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Token)) {
			return false;
		}

		Token token = (Token)object;

		int primaryKey = token.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Token> toCacheModel() {
		TokenCacheModel tokenCacheModel = new TokenCacheModel();

		tokenCacheModel.Id = getId();

		tokenCacheModel.TokenNumber = getTokenNumber();

		String TokenNumber = tokenCacheModel.TokenNumber;

		if ((TokenNumber != null) && (TokenNumber.length() == 0)) {
			tokenCacheModel.TokenNumber = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			tokenCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			tokenCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		Date ExpiredDate = getExpiredDate();

		if (ExpiredDate != null) {
			tokenCacheModel.ExpiredDate = ExpiredDate.getTime();
		}
		else {
			tokenCacheModel.ExpiredDate = Long.MIN_VALUE;
		}

		return tokenCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Token, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Token, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Token, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Token)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Token>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Token.class, ModelWrapper.class);

	}

	private int _Id;
	private String _TokenNumber;
	private Date _CreatedDate;
	private Date _ExpiredDate;

	public <T> T getColumnValue(String columnName) {
		Function<Token, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Token)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("TokenNumber", _TokenNumber);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("ExpiredDate", _ExpiredDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("TokenNumber", 2L);

		columnBitmasks.put("CreatedDate", 4L);

		columnBitmasks.put("ExpiredDate", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Token _escapedModel;

}