/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.TrainingMateri;
import com.astra.dewa.model.TrainingMateriModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TrainingMateri service. Represents a row in the &quot;training_materi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TrainingMateriModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrainingMateriImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TrainingMateriImpl
 * @generated
 */
public class TrainingMateriModelImpl
	extends BaseModelImpl<TrainingMateri> implements TrainingMateriModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a training materi model instance should use the <code>TrainingMateri</code> interface instead.
	 */
	public static final String TABLE_NAME = "training_materi";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"JenisMateriId", Types.INTEGER},
		{"TopikMateriId", Types.INTEGER}, {"JudulMateri", Types.VARCHAR},
		{"ImageId", Types.BIGINT}, {"ImageName", Types.VARCHAR},
		{"ImagePath", Types.VARCHAR}, {"RowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("JenisMateriId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("TopikMateriId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("JudulMateri", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ImageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ImageName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ImagePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table training_materi (Id INTEGER not null primary key IDENTITY,JenisMateriId INTEGER,TopikMateriId INTEGER,JudulMateri VARCHAR(75) null,ImageId LONG,ImageName VARCHAR(75) null,ImagePath VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table training_materi";

	public static final String ORDER_BY_JPQL =
		" ORDER BY trainingMateri.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY training_materi.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.TrainingMateri"));

	public TrainingMateriModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TrainingMateri.class;
	}

	@Override
	public String getModelClassName() {
		return TrainingMateri.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TrainingMateri, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TrainingMateri, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TrainingMateri, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TrainingMateri)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TrainingMateri, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TrainingMateri, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TrainingMateri)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TrainingMateri, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TrainingMateri, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TrainingMateri, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TrainingMateri, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TrainingMateri, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TrainingMateri, Object>>();
		Map<String, BiConsumer<TrainingMateri, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TrainingMateri, ?>>();

		attributeGetterFunctions.put("Id", TrainingMateri::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<TrainingMateri, Integer>)TrainingMateri::setId);
		attributeGetterFunctions.put(
			"JenisMateriId", TrainingMateri::getJenisMateriId);
		attributeSetterBiConsumers.put(
			"JenisMateriId",
			(BiConsumer<TrainingMateri, Integer>)
				TrainingMateri::setJenisMateriId);
		attributeGetterFunctions.put(
			"TopikMateriId", TrainingMateri::getTopikMateriId);
		attributeSetterBiConsumers.put(
			"TopikMateriId",
			(BiConsumer<TrainingMateri, Integer>)
				TrainingMateri::setTopikMateriId);
		attributeGetterFunctions.put(
			"JudulMateri", TrainingMateri::getJudulMateri);
		attributeSetterBiConsumers.put(
			"JudulMateri",
			(BiConsumer<TrainingMateri, String>)TrainingMateri::setJudulMateri);
		attributeGetterFunctions.put("ImageId", TrainingMateri::getImageId);
		attributeSetterBiConsumers.put(
			"ImageId",
			(BiConsumer<TrainingMateri, Long>)TrainingMateri::setImageId);
		attributeGetterFunctions.put("ImageName", TrainingMateri::getImageName);
		attributeSetterBiConsumers.put(
			"ImageName",
			(BiConsumer<TrainingMateri, String>)TrainingMateri::setImageName);
		attributeGetterFunctions.put("ImagePath", TrainingMateri::getImagePath);
		attributeSetterBiConsumers.put(
			"ImagePath",
			(BiConsumer<TrainingMateri, String>)TrainingMateri::setImagePath);
		attributeGetterFunctions.put("RowStatus", TrainingMateri::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<TrainingMateri, Boolean>)TrainingMateri::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", TrainingMateri::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<TrainingMateri, Date>)TrainingMateri::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", TrainingMateri::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<TrainingMateri, String>)TrainingMateri::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", TrainingMateri::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<TrainingMateri, Date>)TrainingMateri::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", TrainingMateri::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<TrainingMateri, String>)TrainingMateri::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getJenisMateriId() {
		return _JenisMateriId;
	}

	@Override
	public void setJenisMateriId(int JenisMateriId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_JenisMateriId = JenisMateriId;
	}

	@Override
	public int getTopikMateriId() {
		return _TopikMateriId;
	}

	@Override
	public void setTopikMateriId(int TopikMateriId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TopikMateriId = TopikMateriId;
	}

	@Override
	public String getJudulMateri() {
		if (_JudulMateri == null) {
			return "";
		}
		else {
			return _JudulMateri;
		}
	}

	@Override
	public void setJudulMateri(String JudulMateri) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_JudulMateri = JudulMateri;
	}

	@Override
	public Long getImageId() {
		return _ImageId;
	}

	@Override
	public void setImageId(Long ImageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ImageId = ImageId;
	}

	@Override
	public String getImageName() {
		if (_ImageName == null) {
			return "";
		}
		else {
			return _ImageName;
		}
	}

	@Override
	public void setImageName(String ImageName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ImageName = ImageName;
	}

	@Override
	public String getImagePath() {
		if (_ImagePath == null) {
			return "";
		}
		else {
			return _ImagePath;
		}
	}

	@Override
	public void setImagePath(String ImagePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ImagePath = ImagePath;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public TrainingMateri toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TrainingMateri>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TrainingMateriImpl trainingMateriImpl = new TrainingMateriImpl();

		trainingMateriImpl.setId(getId());
		trainingMateriImpl.setJenisMateriId(getJenisMateriId());
		trainingMateriImpl.setTopikMateriId(getTopikMateriId());
		trainingMateriImpl.setJudulMateri(getJudulMateri());
		trainingMateriImpl.setImageId(getImageId());
		trainingMateriImpl.setImageName(getImageName());
		trainingMateriImpl.setImagePath(getImagePath());
		trainingMateriImpl.setRowStatus(getRowStatus());
		trainingMateriImpl.setCreatedDate(getCreatedDate());
		trainingMateriImpl.setCreatedBy(getCreatedBy());
		trainingMateriImpl.setModifiedDate(getModifiedDate());
		trainingMateriImpl.setModifiedBy(getModifiedBy());

		trainingMateriImpl.resetOriginalValues();

		return trainingMateriImpl;
	}

	@Override
	public TrainingMateri cloneWithOriginalValues() {
		TrainingMateriImpl trainingMateriImpl = new TrainingMateriImpl();

		trainingMateriImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		trainingMateriImpl.setJenisMateriId(
			this.<Integer>getColumnOriginalValue("JenisMateriId"));
		trainingMateriImpl.setTopikMateriId(
			this.<Integer>getColumnOriginalValue("TopikMateriId"));
		trainingMateriImpl.setJudulMateri(
			this.<String>getColumnOriginalValue("JudulMateri"));
		trainingMateriImpl.setImageId(
			this.<Long>getColumnOriginalValue("ImageId"));
		trainingMateriImpl.setImageName(
			this.<String>getColumnOriginalValue("ImageName"));
		trainingMateriImpl.setImagePath(
			this.<String>getColumnOriginalValue("ImagePath"));
		trainingMateriImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		trainingMateriImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		trainingMateriImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		trainingMateriImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		trainingMateriImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return trainingMateriImpl;
	}

	@Override
	public int compareTo(TrainingMateri trainingMateri) {
		int primaryKey = trainingMateri.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TrainingMateri)) {
			return false;
		}

		TrainingMateri trainingMateri = (TrainingMateri)object;

		int primaryKey = trainingMateri.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TrainingMateri> toCacheModel() {
		TrainingMateriCacheModel trainingMateriCacheModel =
			new TrainingMateriCacheModel();

		trainingMateriCacheModel.Id = getId();

		trainingMateriCacheModel.JenisMateriId = getJenisMateriId();

		trainingMateriCacheModel.TopikMateriId = getTopikMateriId();

		trainingMateriCacheModel.JudulMateri = getJudulMateri();

		String JudulMateri = trainingMateriCacheModel.JudulMateri;

		if ((JudulMateri != null) && (JudulMateri.length() == 0)) {
			trainingMateriCacheModel.JudulMateri = null;
		}

		Long ImageId = getImageId();

		if (ImageId != null) {
			trainingMateriCacheModel.ImageId = ImageId;
		}

		trainingMateriCacheModel.ImageName = getImageName();

		String ImageName = trainingMateriCacheModel.ImageName;

		if ((ImageName != null) && (ImageName.length() == 0)) {
			trainingMateriCacheModel.ImageName = null;
		}

		trainingMateriCacheModel.ImagePath = getImagePath();

		String ImagePath = trainingMateriCacheModel.ImagePath;

		if ((ImagePath != null) && (ImagePath.length() == 0)) {
			trainingMateriCacheModel.ImagePath = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			trainingMateriCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			trainingMateriCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			trainingMateriCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		trainingMateriCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = trainingMateriCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			trainingMateriCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			trainingMateriCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			trainingMateriCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		trainingMateriCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = trainingMateriCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			trainingMateriCacheModel.ModifiedBy = null;
		}

		return trainingMateriCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TrainingMateri, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TrainingMateri, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TrainingMateri, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TrainingMateri)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TrainingMateri>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TrainingMateri.class, ModelWrapper.class);

	}

	private int _Id;
	private int _JenisMateriId;
	private int _TopikMateriId;
	private String _JudulMateri;
	private Long _ImageId;
	private String _ImageName;
	private String _ImagePath;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<TrainingMateri, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TrainingMateri)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("JenisMateriId", _JenisMateriId);
		_columnOriginalValues.put("TopikMateriId", _TopikMateriId);
		_columnOriginalValues.put("JudulMateri", _JudulMateri);
		_columnOriginalValues.put("ImageId", _ImageId);
		_columnOriginalValues.put("ImageName", _ImageName);
		_columnOriginalValues.put("ImagePath", _ImagePath);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("JenisMateriId", 2L);

		columnBitmasks.put("TopikMateriId", 4L);

		columnBitmasks.put("JudulMateri", 8L);

		columnBitmasks.put("ImageId", 16L);

		columnBitmasks.put("ImageName", 32L);

		columnBitmasks.put("ImagePath", 64L);

		columnBitmasks.put("RowStatus", 128L);

		columnBitmasks.put("CreatedDate", 256L);

		columnBitmasks.put("CreatedBy", 512L);

		columnBitmasks.put("ModifiedDate", 1024L);

		columnBitmasks.put("ModifiedBy", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TrainingMateri _escapedModel;

}