/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.TrainingAgendaParticipantUf;
import com.astra.dewa.model.TrainingAgendaParticipantUfModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TrainingAgendaParticipantUf service. Represents a row in the &quot;training_agenda_participant_uf&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TrainingAgendaParticipantUfModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrainingAgendaParticipantUfImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TrainingAgendaParticipantUfImpl
 * @generated
 */
public class TrainingAgendaParticipantUfModelImpl
	extends BaseModelImpl<TrainingAgendaParticipantUf>
	implements TrainingAgendaParticipantUfModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a training agenda participant uf model instance should use the <code>TrainingAgendaParticipantUf</code> interface instead.
	 */
	public static final String TABLE_NAME = "training_agenda_participant_uf";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"TrainingAgendaId", Types.INTEGER},
		{"DealerId", Types.INTEGER}, {"FileId", Types.BIGINT},
		{"FileName", Types.VARCHAR}, {"FilePath", Types.VARCHAR},
		{"RowStatus", Types.BOOLEAN}, {"CreatedDate", Types.TIMESTAMP},
		{"CreatedBy", Types.VARCHAR}, {"ModifiedDate", Types.TIMESTAMP},
		{"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("TrainingAgendaId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("FileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FilePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table training_agenda_participant_uf (Id INTEGER not null primary key IDENTITY,TrainingAgendaId INTEGER,DealerId INTEGER,FileId LONG,FileName VARCHAR(75) null,FilePath VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table training_agenda_participant_uf";

	public static final String ORDER_BY_JPQL =
		" ORDER BY trainingAgendaParticipantUf.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY training_agenda_participant_uf.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.TrainingAgendaParticipantUf"));

	public TrainingAgendaParticipantUfModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TrainingAgendaParticipantUf.class;
	}

	@Override
	public String getModelClassName() {
		return TrainingAgendaParticipantUf.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TrainingAgendaParticipantUf, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TrainingAgendaParticipantUf, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TrainingAgendaParticipantUf, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(TrainingAgendaParticipantUf)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TrainingAgendaParticipantUf, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TrainingAgendaParticipantUf, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TrainingAgendaParticipantUf)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TrainingAgendaParticipantUf, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TrainingAgendaParticipantUf, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<TrainingAgendaParticipantUf, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<TrainingAgendaParticipantUf, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<TrainingAgendaParticipantUf, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<TrainingAgendaParticipantUf, Object>>();
		Map<String, BiConsumer<TrainingAgendaParticipantUf, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<TrainingAgendaParticipantUf, ?>>();

		attributeGetterFunctions.put("Id", TrainingAgendaParticipantUf::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<TrainingAgendaParticipantUf, Integer>)
				TrainingAgendaParticipantUf::setId);
		attributeGetterFunctions.put(
			"TrainingAgendaId",
			TrainingAgendaParticipantUf::getTrainingAgendaId);
		attributeSetterBiConsumers.put(
			"TrainingAgendaId",
			(BiConsumer<TrainingAgendaParticipantUf, Integer>)
				TrainingAgendaParticipantUf::setTrainingAgendaId);
		attributeGetterFunctions.put(
			"DealerId", TrainingAgendaParticipantUf::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId",
			(BiConsumer<TrainingAgendaParticipantUf, Integer>)
				TrainingAgendaParticipantUf::setDealerId);
		attributeGetterFunctions.put(
			"FileId", TrainingAgendaParticipantUf::getFileId);
		attributeSetterBiConsumers.put(
			"FileId",
			(BiConsumer<TrainingAgendaParticipantUf, Long>)
				TrainingAgendaParticipantUf::setFileId);
		attributeGetterFunctions.put(
			"FileName", TrainingAgendaParticipantUf::getFileName);
		attributeSetterBiConsumers.put(
			"FileName",
			(BiConsumer<TrainingAgendaParticipantUf, String>)
				TrainingAgendaParticipantUf::setFileName);
		attributeGetterFunctions.put(
			"FilePath", TrainingAgendaParticipantUf::getFilePath);
		attributeSetterBiConsumers.put(
			"FilePath",
			(BiConsumer<TrainingAgendaParticipantUf, String>)
				TrainingAgendaParticipantUf::setFilePath);
		attributeGetterFunctions.put(
			"RowStatus", TrainingAgendaParticipantUf::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<TrainingAgendaParticipantUf, Boolean>)
				TrainingAgendaParticipantUf::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", TrainingAgendaParticipantUf::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<TrainingAgendaParticipantUf, Date>)
				TrainingAgendaParticipantUf::setCreatedDate);
		attributeGetterFunctions.put(
			"CreatedBy", TrainingAgendaParticipantUf::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<TrainingAgendaParticipantUf, String>)
				TrainingAgendaParticipantUf::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", TrainingAgendaParticipantUf::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<TrainingAgendaParticipantUf, Date>)
				TrainingAgendaParticipantUf::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", TrainingAgendaParticipantUf::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<TrainingAgendaParticipantUf, String>)
				TrainingAgendaParticipantUf::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getTrainingAgendaId() {
		return _TrainingAgendaId;
	}

	@Override
	public void setTrainingAgendaId(int TrainingAgendaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TrainingAgendaId = TrainingAgendaId;
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public Long getFileId() {
		return _FileId;
	}

	@Override
	public void setFileId(Long FileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileId = FileId;
	}

	@Override
	public String getFileName() {
		if (_FileName == null) {
			return "";
		}
		else {
			return _FileName;
		}
	}

	@Override
	public void setFileName(String FileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileName = FileName;
	}

	@Override
	public String getFilePath() {
		if (_FilePath == null) {
			return "";
		}
		else {
			return _FilePath;
		}
	}

	@Override
	public void setFilePath(String FilePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FilePath = FilePath;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public TrainingAgendaParticipantUf toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TrainingAgendaParticipantUf>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TrainingAgendaParticipantUfImpl trainingAgendaParticipantUfImpl =
			new TrainingAgendaParticipantUfImpl();

		trainingAgendaParticipantUfImpl.setId(getId());
		trainingAgendaParticipantUfImpl.setTrainingAgendaId(
			getTrainingAgendaId());
		trainingAgendaParticipantUfImpl.setDealerId(getDealerId());
		trainingAgendaParticipantUfImpl.setFileId(getFileId());
		trainingAgendaParticipantUfImpl.setFileName(getFileName());
		trainingAgendaParticipantUfImpl.setFilePath(getFilePath());
		trainingAgendaParticipantUfImpl.setRowStatus(getRowStatus());
		trainingAgendaParticipantUfImpl.setCreatedDate(getCreatedDate());
		trainingAgendaParticipantUfImpl.setCreatedBy(getCreatedBy());
		trainingAgendaParticipantUfImpl.setModifiedDate(getModifiedDate());
		trainingAgendaParticipantUfImpl.setModifiedBy(getModifiedBy());

		trainingAgendaParticipantUfImpl.resetOriginalValues();

		return trainingAgendaParticipantUfImpl;
	}

	@Override
	public TrainingAgendaParticipantUf cloneWithOriginalValues() {
		TrainingAgendaParticipantUfImpl trainingAgendaParticipantUfImpl =
			new TrainingAgendaParticipantUfImpl();

		trainingAgendaParticipantUfImpl.setId(
			this.<Integer>getColumnOriginalValue("Id"));
		trainingAgendaParticipantUfImpl.setTrainingAgendaId(
			this.<Integer>getColumnOriginalValue("TrainingAgendaId"));
		trainingAgendaParticipantUfImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("DealerId"));
		trainingAgendaParticipantUfImpl.setFileId(
			this.<Long>getColumnOriginalValue("FileId"));
		trainingAgendaParticipantUfImpl.setFileName(
			this.<String>getColumnOriginalValue("FileName"));
		trainingAgendaParticipantUfImpl.setFilePath(
			this.<String>getColumnOriginalValue("FilePath"));
		trainingAgendaParticipantUfImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		trainingAgendaParticipantUfImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		trainingAgendaParticipantUfImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		trainingAgendaParticipantUfImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		trainingAgendaParticipantUfImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return trainingAgendaParticipantUfImpl;
	}

	@Override
	public int compareTo(
		TrainingAgendaParticipantUf trainingAgendaParticipantUf) {

		int primaryKey = trainingAgendaParticipantUf.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TrainingAgendaParticipantUf)) {
			return false;
		}

		TrainingAgendaParticipantUf trainingAgendaParticipantUf =
			(TrainingAgendaParticipantUf)object;

		int primaryKey = trainingAgendaParticipantUf.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TrainingAgendaParticipantUf> toCacheModel() {
		TrainingAgendaParticipantUfCacheModel
			trainingAgendaParticipantUfCacheModel =
				new TrainingAgendaParticipantUfCacheModel();

		trainingAgendaParticipantUfCacheModel.Id = getId();

		trainingAgendaParticipantUfCacheModel.TrainingAgendaId =
			getTrainingAgendaId();

		trainingAgendaParticipantUfCacheModel.DealerId = getDealerId();

		Long FileId = getFileId();

		if (FileId != null) {
			trainingAgendaParticipantUfCacheModel.FileId = FileId;
		}

		trainingAgendaParticipantUfCacheModel.FileName = getFileName();

		String FileName = trainingAgendaParticipantUfCacheModel.FileName;

		if ((FileName != null) && (FileName.length() == 0)) {
			trainingAgendaParticipantUfCacheModel.FileName = null;
		}

		trainingAgendaParticipantUfCacheModel.FilePath = getFilePath();

		String FilePath = trainingAgendaParticipantUfCacheModel.FilePath;

		if ((FilePath != null) && (FilePath.length() == 0)) {
			trainingAgendaParticipantUfCacheModel.FilePath = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			trainingAgendaParticipantUfCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			trainingAgendaParticipantUfCacheModel.CreatedDate =
				CreatedDate.getTime();
		}
		else {
			trainingAgendaParticipantUfCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		trainingAgendaParticipantUfCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = trainingAgendaParticipantUfCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			trainingAgendaParticipantUfCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			trainingAgendaParticipantUfCacheModel.ModifiedDate =
				ModifiedDate.getTime();
		}
		else {
			trainingAgendaParticipantUfCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		trainingAgendaParticipantUfCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = trainingAgendaParticipantUfCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			trainingAgendaParticipantUfCacheModel.ModifiedBy = null;
		}

		return trainingAgendaParticipantUfCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TrainingAgendaParticipantUf, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TrainingAgendaParticipantUf, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TrainingAgendaParticipantUf, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(TrainingAgendaParticipantUf)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, TrainingAgendaParticipantUf>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						TrainingAgendaParticipantUf.class, ModelWrapper.class);

	}

	private int _Id;
	private int _TrainingAgendaId;
	private int _DealerId;
	private Long _FileId;
	private String _FileName;
	private String _FilePath;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<TrainingAgendaParticipantUf, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TrainingAgendaParticipantUf)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("TrainingAgendaId", _TrainingAgendaId);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("FileId", _FileId);
		_columnOriginalValues.put("FileName", _FileName);
		_columnOriginalValues.put("FilePath", _FilePath);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("TrainingAgendaId", 2L);

		columnBitmasks.put("DealerId", 4L);

		columnBitmasks.put("FileId", 8L);

		columnBitmasks.put("FileName", 16L);

		columnBitmasks.put("FilePath", 32L);

		columnBitmasks.put("RowStatus", 64L);

		columnBitmasks.put("CreatedDate", 128L);

		columnBitmasks.put("CreatedBy", 256L);

		columnBitmasks.put("ModifiedDate", 512L);

		columnBitmasks.put("ModifiedBy", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TrainingAgendaParticipantUf _escapedModel;

}