/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.TrainingMateriLampiran;
import com.astra.dewa.model.TrainingMateriLampiranModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TrainingMateriLampiran service. Represents a row in the &quot;training_materi_lampiran&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TrainingMateriLampiranModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrainingMateriLampiranImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TrainingMateriLampiranImpl
 * @generated
 */
public class TrainingMateriLampiranModelImpl
	extends BaseModelImpl<TrainingMateriLampiran>
	implements TrainingMateriLampiranModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a training materi lampiran model instance should use the <code>TrainingMateriLampiran</code> interface instead.
	 */
	public static final String TABLE_NAME = "training_materi_lampiran";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"TrainingMateriId", Types.INTEGER},
		{"FileId", Types.BIGINT}, {"FileName", Types.VARCHAR},
		{"FilePath", Types.VARCHAR}, {"RowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("TrainingMateriId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("FileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FilePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table training_materi_lampiran (Id INTEGER not null primary key IDENTITY,TrainingMateriId INTEGER,FileId LONG,FileName VARCHAR(75) null,FilePath VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table training_materi_lampiran";

	public static final String ORDER_BY_JPQL =
		" ORDER BY trainingMateriLampiran.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY training_materi_lampiran.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.TrainingMateriLampiran"));

	public TrainingMateriLampiranModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TrainingMateriLampiran.class;
	}

	@Override
	public String getModelClassName() {
		return TrainingMateriLampiran.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TrainingMateriLampiran, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TrainingMateriLampiran, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TrainingMateriLampiran, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TrainingMateriLampiran)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TrainingMateriLampiran, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TrainingMateriLampiran, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TrainingMateriLampiran)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TrainingMateriLampiran, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TrainingMateriLampiran, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TrainingMateriLampiran, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TrainingMateriLampiran, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TrainingMateriLampiran, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<TrainingMateriLampiran, Object>>();
		Map<String, BiConsumer<TrainingMateriLampiran, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<TrainingMateriLampiran, ?>>();

		attributeGetterFunctions.put("Id", TrainingMateriLampiran::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<TrainingMateriLampiran, Integer>)
				TrainingMateriLampiran::setId);
		attributeGetterFunctions.put(
			"TrainingMateriId", TrainingMateriLampiran::getTrainingMateriId);
		attributeSetterBiConsumers.put(
			"TrainingMateriId",
			(BiConsumer<TrainingMateriLampiran, Integer>)
				TrainingMateriLampiran::setTrainingMateriId);
		attributeGetterFunctions.put(
			"FileId", TrainingMateriLampiran::getFileId);
		attributeSetterBiConsumers.put(
			"FileId",
			(BiConsumer<TrainingMateriLampiran, Long>)
				TrainingMateriLampiran::setFileId);
		attributeGetterFunctions.put(
			"FileName", TrainingMateriLampiran::getFileName);
		attributeSetterBiConsumers.put(
			"FileName",
			(BiConsumer<TrainingMateriLampiran, String>)
				TrainingMateriLampiran::setFileName);
		attributeGetterFunctions.put(
			"FilePath", TrainingMateriLampiran::getFilePath);
		attributeSetterBiConsumers.put(
			"FilePath",
			(BiConsumer<TrainingMateriLampiran, String>)
				TrainingMateriLampiran::setFilePath);
		attributeGetterFunctions.put(
			"RowStatus", TrainingMateriLampiran::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<TrainingMateriLampiran, Boolean>)
				TrainingMateriLampiran::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", TrainingMateriLampiran::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<TrainingMateriLampiran, Date>)
				TrainingMateriLampiran::setCreatedDate);
		attributeGetterFunctions.put(
			"CreatedBy", TrainingMateriLampiran::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<TrainingMateriLampiran, String>)
				TrainingMateriLampiran::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", TrainingMateriLampiran::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<TrainingMateriLampiran, Date>)
				TrainingMateriLampiran::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", TrainingMateriLampiran::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<TrainingMateriLampiran, String>)
				TrainingMateriLampiran::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getTrainingMateriId() {
		return _TrainingMateriId;
	}

	@Override
	public void setTrainingMateriId(int TrainingMateriId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TrainingMateriId = TrainingMateriId;
	}

	@Override
	public Long getFileId() {
		return _FileId;
	}

	@Override
	public void setFileId(Long FileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileId = FileId;
	}

	@Override
	public String getFileName() {
		if (_FileName == null) {
			return "";
		}
		else {
			return _FileName;
		}
	}

	@Override
	public void setFileName(String FileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileName = FileName;
	}

	@Override
	public String getFilePath() {
		if (_FilePath == null) {
			return "";
		}
		else {
			return _FilePath;
		}
	}

	@Override
	public void setFilePath(String FilePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FilePath = FilePath;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public TrainingMateriLampiran toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TrainingMateriLampiran>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TrainingMateriLampiranImpl trainingMateriLampiranImpl =
			new TrainingMateriLampiranImpl();

		trainingMateriLampiranImpl.setId(getId());
		trainingMateriLampiranImpl.setTrainingMateriId(getTrainingMateriId());
		trainingMateriLampiranImpl.setFileId(getFileId());
		trainingMateriLampiranImpl.setFileName(getFileName());
		trainingMateriLampiranImpl.setFilePath(getFilePath());
		trainingMateriLampiranImpl.setRowStatus(getRowStatus());
		trainingMateriLampiranImpl.setCreatedDate(getCreatedDate());
		trainingMateriLampiranImpl.setCreatedBy(getCreatedBy());
		trainingMateriLampiranImpl.setModifiedDate(getModifiedDate());
		trainingMateriLampiranImpl.setModifiedBy(getModifiedBy());

		trainingMateriLampiranImpl.resetOriginalValues();

		return trainingMateriLampiranImpl;
	}

	@Override
	public TrainingMateriLampiran cloneWithOriginalValues() {
		TrainingMateriLampiranImpl trainingMateriLampiranImpl =
			new TrainingMateriLampiranImpl();

		trainingMateriLampiranImpl.setId(
			this.<Integer>getColumnOriginalValue("Id"));
		trainingMateriLampiranImpl.setTrainingMateriId(
			this.<Integer>getColumnOriginalValue("TrainingMateriId"));
		trainingMateriLampiranImpl.setFileId(
			this.<Long>getColumnOriginalValue("FileId"));
		trainingMateriLampiranImpl.setFileName(
			this.<String>getColumnOriginalValue("FileName"));
		trainingMateriLampiranImpl.setFilePath(
			this.<String>getColumnOriginalValue("FilePath"));
		trainingMateriLampiranImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		trainingMateriLampiranImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		trainingMateriLampiranImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		trainingMateriLampiranImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		trainingMateriLampiranImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return trainingMateriLampiranImpl;
	}

	@Override
	public int compareTo(TrainingMateriLampiran trainingMateriLampiran) {
		int primaryKey = trainingMateriLampiran.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TrainingMateriLampiran)) {
			return false;
		}

		TrainingMateriLampiran trainingMateriLampiran =
			(TrainingMateriLampiran)object;

		int primaryKey = trainingMateriLampiran.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TrainingMateriLampiran> toCacheModel() {
		TrainingMateriLampiranCacheModel trainingMateriLampiranCacheModel =
			new TrainingMateriLampiranCacheModel();

		trainingMateriLampiranCacheModel.Id = getId();

		trainingMateriLampiranCacheModel.TrainingMateriId =
			getTrainingMateriId();

		Long FileId = getFileId();

		if (FileId != null) {
			trainingMateriLampiranCacheModel.FileId = FileId;
		}

		trainingMateriLampiranCacheModel.FileName = getFileName();

		String FileName = trainingMateriLampiranCacheModel.FileName;

		if ((FileName != null) && (FileName.length() == 0)) {
			trainingMateriLampiranCacheModel.FileName = null;
		}

		trainingMateriLampiranCacheModel.FilePath = getFilePath();

		String FilePath = trainingMateriLampiranCacheModel.FilePath;

		if ((FilePath != null) && (FilePath.length() == 0)) {
			trainingMateriLampiranCacheModel.FilePath = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			trainingMateriLampiranCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			trainingMateriLampiranCacheModel.CreatedDate =
				CreatedDate.getTime();
		}
		else {
			trainingMateriLampiranCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		trainingMateriLampiranCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = trainingMateriLampiranCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			trainingMateriLampiranCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			trainingMateriLampiranCacheModel.ModifiedDate =
				ModifiedDate.getTime();
		}
		else {
			trainingMateriLampiranCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		trainingMateriLampiranCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = trainingMateriLampiranCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			trainingMateriLampiranCacheModel.ModifiedBy = null;
		}

		return trainingMateriLampiranCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TrainingMateriLampiran, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TrainingMateriLampiran, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TrainingMateriLampiran, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(TrainingMateriLampiran)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TrainingMateriLampiran>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TrainingMateriLampiran.class, ModelWrapper.class);

	}

	private int _Id;
	private int _TrainingMateriId;
	private Long _FileId;
	private String _FileName;
	private String _FilePath;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<TrainingMateriLampiran, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TrainingMateriLampiran)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("TrainingMateriId", _TrainingMateriId);
		_columnOriginalValues.put("FileId", _FileId);
		_columnOriginalValues.put("FileName", _FileName);
		_columnOriginalValues.put("FilePath", _FilePath);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("TrainingMateriId", 2L);

		columnBitmasks.put("FileId", 4L);

		columnBitmasks.put("FileName", 8L);

		columnBitmasks.put("FilePath", 16L);

		columnBitmasks.put("RowStatus", 32L);

		columnBitmasks.put("CreatedDate", 64L);

		columnBitmasks.put("CreatedBy", 128L);

		columnBitmasks.put("ModifiedDate", 256L);

		columnBitmasks.put("ModifiedBy", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TrainingMateriLampiran _escapedModel;

}