/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.TrainingAgenda;
import com.astra.dewa.model.TrainingAgendaModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TrainingAgenda service. Represents a row in the &quot;training_agenda&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TrainingAgendaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrainingAgendaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TrainingAgendaImpl
 * @generated
 */
public class TrainingAgendaModelImpl
	extends BaseModelImpl<TrainingAgenda> implements TrainingAgendaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a training agenda model instance should use the <code>TrainingAgenda</code> interface instead.
	 */
	public static final String TABLE_NAME = "training_agenda";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"JenisAgenda", Types.INTEGER},
		{"StatusAgenda", Types.INTEGER}, {"Judul", Types.VARCHAR},
		{"Location", Types.VARCHAR}, {"LinkMeeting", Types.VARCHAR},
		{"Deskripsi", Types.VARCHAR}, {"StartDate", Types.TIMESTAMP},
		{"StartDateHours", Types.VARCHAR}, {"EndDate", Types.TIMESTAMP},
		{"EndDateHours", Types.VARCHAR},
		{"RegistrationLimitDate", Types.TIMESTAMP},
		{"RegistrationLimitDateHours", Types.VARCHAR},
		{"ImageId", Types.BIGINT}, {"ImageName", Types.VARCHAR},
		{"ImagePath", Types.VARCHAR}, {"RowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("JenisAgenda", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("StatusAgenda", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Judul", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Location", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("LinkMeeting", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Deskripsi", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("StartDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("StartDateHours", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("EndDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("EndDateHours", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RegistrationLimitDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("RegistrationLimitDateHours", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ImageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ImageName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ImagePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table training_agenda (Id INTEGER not null primary key IDENTITY,JenisAgenda INTEGER,StatusAgenda INTEGER,Judul VARCHAR(75) null,Location VARCHAR(75) null,LinkMeeting VARCHAR(75) null,Deskripsi VARCHAR(75) null,StartDate DATE null,StartDateHours VARCHAR(75) null,EndDate DATE null,EndDateHours VARCHAR(75) null,RegistrationLimitDate DATE null,RegistrationLimitDateHours VARCHAR(75) null,ImageId LONG,ImageName VARCHAR(75) null,ImagePath VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table training_agenda";

	public static final String ORDER_BY_JPQL =
		" ORDER BY trainingAgenda.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY training_agenda.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.TrainingAgenda"));

	public TrainingAgendaModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TrainingAgenda.class;
	}

	@Override
	public String getModelClassName() {
		return TrainingAgenda.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TrainingAgenda, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TrainingAgenda, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TrainingAgenda, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TrainingAgenda)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TrainingAgenda, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TrainingAgenda, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TrainingAgenda)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TrainingAgenda, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TrainingAgenda, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TrainingAgenda, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TrainingAgenda, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TrainingAgenda, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TrainingAgenda, Object>>();
		Map<String, BiConsumer<TrainingAgenda, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TrainingAgenda, ?>>();

		attributeGetterFunctions.put("Id", TrainingAgenda::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<TrainingAgenda, Integer>)TrainingAgenda::setId);
		attributeGetterFunctions.put(
			"JenisAgenda", TrainingAgenda::getJenisAgenda);
		attributeSetterBiConsumers.put(
			"JenisAgenda",
			(BiConsumer<TrainingAgenda, Integer>)
				TrainingAgenda::setJenisAgenda);
		attributeGetterFunctions.put(
			"StatusAgenda", TrainingAgenda::getStatusAgenda);
		attributeSetterBiConsumers.put(
			"StatusAgenda",
			(BiConsumer<TrainingAgenda, Integer>)
				TrainingAgenda::setStatusAgenda);
		attributeGetterFunctions.put("Judul", TrainingAgenda::getJudul);
		attributeSetterBiConsumers.put(
			"Judul",
			(BiConsumer<TrainingAgenda, String>)TrainingAgenda::setJudul);
		attributeGetterFunctions.put("Location", TrainingAgenda::getLocation);
		attributeSetterBiConsumers.put(
			"Location",
			(BiConsumer<TrainingAgenda, String>)TrainingAgenda::setLocation);
		attributeGetterFunctions.put(
			"LinkMeeting", TrainingAgenda::getLinkMeeting);
		attributeSetterBiConsumers.put(
			"LinkMeeting",
			(BiConsumer<TrainingAgenda, String>)TrainingAgenda::setLinkMeeting);
		attributeGetterFunctions.put("Deskripsi", TrainingAgenda::getDeskripsi);
		attributeSetterBiConsumers.put(
			"Deskripsi",
			(BiConsumer<TrainingAgenda, String>)TrainingAgenda::setDeskripsi);
		attributeGetterFunctions.put("StartDate", TrainingAgenda::getStartDate);
		attributeSetterBiConsumers.put(
			"StartDate",
			(BiConsumer<TrainingAgenda, Date>)TrainingAgenda::setStartDate);
		attributeGetterFunctions.put(
			"StartDateHours", TrainingAgenda::getStartDateHours);
		attributeSetterBiConsumers.put(
			"StartDateHours",
			(BiConsumer<TrainingAgenda, String>)
				TrainingAgenda::setStartDateHours);
		attributeGetterFunctions.put("EndDate", TrainingAgenda::getEndDate);
		attributeSetterBiConsumers.put(
			"EndDate",
			(BiConsumer<TrainingAgenda, Date>)TrainingAgenda::setEndDate);
		attributeGetterFunctions.put(
			"EndDateHours", TrainingAgenda::getEndDateHours);
		attributeSetterBiConsumers.put(
			"EndDateHours",
			(BiConsumer<TrainingAgenda, String>)
				TrainingAgenda::setEndDateHours);
		attributeGetterFunctions.put(
			"RegistrationLimitDate", TrainingAgenda::getRegistrationLimitDate);
		attributeSetterBiConsumers.put(
			"RegistrationLimitDate",
			(BiConsumer<TrainingAgenda, Date>)
				TrainingAgenda::setRegistrationLimitDate);
		attributeGetterFunctions.put(
			"RegistrationLimitDateHours",
			TrainingAgenda::getRegistrationLimitDateHours);
		attributeSetterBiConsumers.put(
			"RegistrationLimitDateHours",
			(BiConsumer<TrainingAgenda, String>)
				TrainingAgenda::setRegistrationLimitDateHours);
		attributeGetterFunctions.put("ImageId", TrainingAgenda::getImageId);
		attributeSetterBiConsumers.put(
			"ImageId",
			(BiConsumer<TrainingAgenda, Long>)TrainingAgenda::setImageId);
		attributeGetterFunctions.put("ImageName", TrainingAgenda::getImageName);
		attributeSetterBiConsumers.put(
			"ImageName",
			(BiConsumer<TrainingAgenda, String>)TrainingAgenda::setImageName);
		attributeGetterFunctions.put("ImagePath", TrainingAgenda::getImagePath);
		attributeSetterBiConsumers.put(
			"ImagePath",
			(BiConsumer<TrainingAgenda, String>)TrainingAgenda::setImagePath);
		attributeGetterFunctions.put("RowStatus", TrainingAgenda::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<TrainingAgenda, Boolean>)TrainingAgenda::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", TrainingAgenda::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<TrainingAgenda, Date>)TrainingAgenda::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", TrainingAgenda::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<TrainingAgenda, String>)TrainingAgenda::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", TrainingAgenda::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<TrainingAgenda, Date>)TrainingAgenda::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", TrainingAgenda::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<TrainingAgenda, String>)TrainingAgenda::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getJenisAgenda() {
		return _JenisAgenda;
	}

	@Override
	public void setJenisAgenda(int JenisAgenda) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_JenisAgenda = JenisAgenda;
	}

	@Override
	public int getStatusAgenda() {
		return _StatusAgenda;
	}

	@Override
	public void setStatusAgenda(int StatusAgenda) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_StatusAgenda = StatusAgenda;
	}

	@Override
	public String getJudul() {
		if (_Judul == null) {
			return "";
		}
		else {
			return _Judul;
		}
	}

	@Override
	public void setJudul(String Judul) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Judul = Judul;
	}

	@Override
	public String getLocation() {
		if (_Location == null) {
			return "";
		}
		else {
			return _Location;
		}
	}

	@Override
	public void setLocation(String Location) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Location = Location;
	}

	@Override
	public String getLinkMeeting() {
		if (_LinkMeeting == null) {
			return "";
		}
		else {
			return _LinkMeeting;
		}
	}

	@Override
	public void setLinkMeeting(String LinkMeeting) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_LinkMeeting = LinkMeeting;
	}

	@Override
	public String getDeskripsi() {
		if (_Deskripsi == null) {
			return "";
		}
		else {
			return _Deskripsi;
		}
	}

	@Override
	public void setDeskripsi(String Deskripsi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Deskripsi = Deskripsi;
	}

	@Override
	public Date getStartDate() {
		return _StartDate;
	}

	@Override
	public void setStartDate(Date StartDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_StartDate = StartDate;
	}

	@Override
	public String getStartDateHours() {
		if (_StartDateHours == null) {
			return "";
		}
		else {
			return _StartDateHours;
		}
	}

	@Override
	public void setStartDateHours(String StartDateHours) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_StartDateHours = StartDateHours;
	}

	@Override
	public Date getEndDate() {
		return _EndDate;
	}

	@Override
	public void setEndDate(Date EndDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_EndDate = EndDate;
	}

	@Override
	public String getEndDateHours() {
		if (_EndDateHours == null) {
			return "";
		}
		else {
			return _EndDateHours;
		}
	}

	@Override
	public void setEndDateHours(String EndDateHours) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_EndDateHours = EndDateHours;
	}

	@Override
	public Date getRegistrationLimitDate() {
		return _RegistrationLimitDate;
	}

	@Override
	public void setRegistrationLimitDate(Date RegistrationLimitDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RegistrationLimitDate = RegistrationLimitDate;
	}

	@Override
	public String getRegistrationLimitDateHours() {
		if (_RegistrationLimitDateHours == null) {
			return "";
		}
		else {
			return _RegistrationLimitDateHours;
		}
	}

	@Override
	public void setRegistrationLimitDateHours(
		String RegistrationLimitDateHours) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RegistrationLimitDateHours = RegistrationLimitDateHours;
	}

	@Override
	public Long getImageId() {
		return _ImageId;
	}

	@Override
	public void setImageId(Long ImageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ImageId = ImageId;
	}

	@Override
	public String getImageName() {
		if (_ImageName == null) {
			return "";
		}
		else {
			return _ImageName;
		}
	}

	@Override
	public void setImageName(String ImageName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ImageName = ImageName;
	}

	@Override
	public String getImagePath() {
		if (_ImagePath == null) {
			return "";
		}
		else {
			return _ImagePath;
		}
	}

	@Override
	public void setImagePath(String ImagePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ImagePath = ImagePath;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public TrainingAgenda toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TrainingAgenda>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TrainingAgendaImpl trainingAgendaImpl = new TrainingAgendaImpl();

		trainingAgendaImpl.setId(getId());
		trainingAgendaImpl.setJenisAgenda(getJenisAgenda());
		trainingAgendaImpl.setStatusAgenda(getStatusAgenda());
		trainingAgendaImpl.setJudul(getJudul());
		trainingAgendaImpl.setLocation(getLocation());
		trainingAgendaImpl.setLinkMeeting(getLinkMeeting());
		trainingAgendaImpl.setDeskripsi(getDeskripsi());
		trainingAgendaImpl.setStartDate(getStartDate());
		trainingAgendaImpl.setStartDateHours(getStartDateHours());
		trainingAgendaImpl.setEndDate(getEndDate());
		trainingAgendaImpl.setEndDateHours(getEndDateHours());
		trainingAgendaImpl.setRegistrationLimitDate(getRegistrationLimitDate());
		trainingAgendaImpl.setRegistrationLimitDateHours(
			getRegistrationLimitDateHours());
		trainingAgendaImpl.setImageId(getImageId());
		trainingAgendaImpl.setImageName(getImageName());
		trainingAgendaImpl.setImagePath(getImagePath());
		trainingAgendaImpl.setRowStatus(getRowStatus());
		trainingAgendaImpl.setCreatedDate(getCreatedDate());
		trainingAgendaImpl.setCreatedBy(getCreatedBy());
		trainingAgendaImpl.setModifiedDate(getModifiedDate());
		trainingAgendaImpl.setModifiedBy(getModifiedBy());

		trainingAgendaImpl.resetOriginalValues();

		return trainingAgendaImpl;
	}

	@Override
	public TrainingAgenda cloneWithOriginalValues() {
		TrainingAgendaImpl trainingAgendaImpl = new TrainingAgendaImpl();

		trainingAgendaImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		trainingAgendaImpl.setJenisAgenda(
			this.<Integer>getColumnOriginalValue("JenisAgenda"));
		trainingAgendaImpl.setStatusAgenda(
			this.<Integer>getColumnOriginalValue("StatusAgenda"));
		trainingAgendaImpl.setJudul(
			this.<String>getColumnOriginalValue("Judul"));
		trainingAgendaImpl.setLocation(
			this.<String>getColumnOriginalValue("Location"));
		trainingAgendaImpl.setLinkMeeting(
			this.<String>getColumnOriginalValue("LinkMeeting"));
		trainingAgendaImpl.setDeskripsi(
			this.<String>getColumnOriginalValue("Deskripsi"));
		trainingAgendaImpl.setStartDate(
			this.<Date>getColumnOriginalValue("StartDate"));
		trainingAgendaImpl.setStartDateHours(
			this.<String>getColumnOriginalValue("StartDateHours"));
		trainingAgendaImpl.setEndDate(
			this.<Date>getColumnOriginalValue("EndDate"));
		trainingAgendaImpl.setEndDateHours(
			this.<String>getColumnOriginalValue("EndDateHours"));
		trainingAgendaImpl.setRegistrationLimitDate(
			this.<Date>getColumnOriginalValue("RegistrationLimitDate"));
		trainingAgendaImpl.setRegistrationLimitDateHours(
			this.<String>getColumnOriginalValue("RegistrationLimitDateHours"));
		trainingAgendaImpl.setImageId(
			this.<Long>getColumnOriginalValue("ImageId"));
		trainingAgendaImpl.setImageName(
			this.<String>getColumnOriginalValue("ImageName"));
		trainingAgendaImpl.setImagePath(
			this.<String>getColumnOriginalValue("ImagePath"));
		trainingAgendaImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		trainingAgendaImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		trainingAgendaImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		trainingAgendaImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		trainingAgendaImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return trainingAgendaImpl;
	}

	@Override
	public int compareTo(TrainingAgenda trainingAgenda) {
		int primaryKey = trainingAgenda.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TrainingAgenda)) {
			return false;
		}

		TrainingAgenda trainingAgenda = (TrainingAgenda)object;

		int primaryKey = trainingAgenda.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TrainingAgenda> toCacheModel() {
		TrainingAgendaCacheModel trainingAgendaCacheModel =
			new TrainingAgendaCacheModel();

		trainingAgendaCacheModel.Id = getId();

		trainingAgendaCacheModel.JenisAgenda = getJenisAgenda();

		trainingAgendaCacheModel.StatusAgenda = getStatusAgenda();

		trainingAgendaCacheModel.Judul = getJudul();

		String Judul = trainingAgendaCacheModel.Judul;

		if ((Judul != null) && (Judul.length() == 0)) {
			trainingAgendaCacheModel.Judul = null;
		}

		trainingAgendaCacheModel.Location = getLocation();

		String Location = trainingAgendaCacheModel.Location;

		if ((Location != null) && (Location.length() == 0)) {
			trainingAgendaCacheModel.Location = null;
		}

		trainingAgendaCacheModel.LinkMeeting = getLinkMeeting();

		String LinkMeeting = trainingAgendaCacheModel.LinkMeeting;

		if ((LinkMeeting != null) && (LinkMeeting.length() == 0)) {
			trainingAgendaCacheModel.LinkMeeting = null;
		}

		trainingAgendaCacheModel.Deskripsi = getDeskripsi();

		String Deskripsi = trainingAgendaCacheModel.Deskripsi;

		if ((Deskripsi != null) && (Deskripsi.length() == 0)) {
			trainingAgendaCacheModel.Deskripsi = null;
		}

		Date StartDate = getStartDate();

		if (StartDate != null) {
			trainingAgendaCacheModel.StartDate = StartDate.getTime();
		}
		else {
			trainingAgendaCacheModel.StartDate = Long.MIN_VALUE;
		}

		trainingAgendaCacheModel.StartDateHours = getStartDateHours();

		String StartDateHours = trainingAgendaCacheModel.StartDateHours;

		if ((StartDateHours != null) && (StartDateHours.length() == 0)) {
			trainingAgendaCacheModel.StartDateHours = null;
		}

		Date EndDate = getEndDate();

		if (EndDate != null) {
			trainingAgendaCacheModel.EndDate = EndDate.getTime();
		}
		else {
			trainingAgendaCacheModel.EndDate = Long.MIN_VALUE;
		}

		trainingAgendaCacheModel.EndDateHours = getEndDateHours();

		String EndDateHours = trainingAgendaCacheModel.EndDateHours;

		if ((EndDateHours != null) && (EndDateHours.length() == 0)) {
			trainingAgendaCacheModel.EndDateHours = null;
		}

		Date RegistrationLimitDate = getRegistrationLimitDate();

		if (RegistrationLimitDate != null) {
			trainingAgendaCacheModel.RegistrationLimitDate =
				RegistrationLimitDate.getTime();
		}
		else {
			trainingAgendaCacheModel.RegistrationLimitDate = Long.MIN_VALUE;
		}

		trainingAgendaCacheModel.RegistrationLimitDateHours =
			getRegistrationLimitDateHours();

		String RegistrationLimitDateHours =
			trainingAgendaCacheModel.RegistrationLimitDateHours;

		if ((RegistrationLimitDateHours != null) &&
			(RegistrationLimitDateHours.length() == 0)) {

			trainingAgendaCacheModel.RegistrationLimitDateHours = null;
		}

		Long ImageId = getImageId();

		if (ImageId != null) {
			trainingAgendaCacheModel.ImageId = ImageId;
		}

		trainingAgendaCacheModel.ImageName = getImageName();

		String ImageName = trainingAgendaCacheModel.ImageName;

		if ((ImageName != null) && (ImageName.length() == 0)) {
			trainingAgendaCacheModel.ImageName = null;
		}

		trainingAgendaCacheModel.ImagePath = getImagePath();

		String ImagePath = trainingAgendaCacheModel.ImagePath;

		if ((ImagePath != null) && (ImagePath.length() == 0)) {
			trainingAgendaCacheModel.ImagePath = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			trainingAgendaCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			trainingAgendaCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			trainingAgendaCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		trainingAgendaCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = trainingAgendaCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			trainingAgendaCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			trainingAgendaCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			trainingAgendaCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		trainingAgendaCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = trainingAgendaCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			trainingAgendaCacheModel.ModifiedBy = null;
		}

		return trainingAgendaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TrainingAgenda, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TrainingAgenda, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TrainingAgenda, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TrainingAgenda)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TrainingAgenda>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TrainingAgenda.class, ModelWrapper.class);

	}

	private int _Id;
	private int _JenisAgenda;
	private int _StatusAgenda;
	private String _Judul;
	private String _Location;
	private String _LinkMeeting;
	private String _Deskripsi;
	private Date _StartDate;
	private String _StartDateHours;
	private Date _EndDate;
	private String _EndDateHours;
	private Date _RegistrationLimitDate;
	private String _RegistrationLimitDateHours;
	private Long _ImageId;
	private String _ImageName;
	private String _ImagePath;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<TrainingAgenda, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TrainingAgenda)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("JenisAgenda", _JenisAgenda);
		_columnOriginalValues.put("StatusAgenda", _StatusAgenda);
		_columnOriginalValues.put("Judul", _Judul);
		_columnOriginalValues.put("Location", _Location);
		_columnOriginalValues.put("LinkMeeting", _LinkMeeting);
		_columnOriginalValues.put("Deskripsi", _Deskripsi);
		_columnOriginalValues.put("StartDate", _StartDate);
		_columnOriginalValues.put("StartDateHours", _StartDateHours);
		_columnOriginalValues.put("EndDate", _EndDate);
		_columnOriginalValues.put("EndDateHours", _EndDateHours);
		_columnOriginalValues.put(
			"RegistrationLimitDate", _RegistrationLimitDate);
		_columnOriginalValues.put(
			"RegistrationLimitDateHours", _RegistrationLimitDateHours);
		_columnOriginalValues.put("ImageId", _ImageId);
		_columnOriginalValues.put("ImageName", _ImageName);
		_columnOriginalValues.put("ImagePath", _ImagePath);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("JenisAgenda", 2L);

		columnBitmasks.put("StatusAgenda", 4L);

		columnBitmasks.put("Judul", 8L);

		columnBitmasks.put("Location", 16L);

		columnBitmasks.put("LinkMeeting", 32L);

		columnBitmasks.put("Deskripsi", 64L);

		columnBitmasks.put("StartDate", 128L);

		columnBitmasks.put("StartDateHours", 256L);

		columnBitmasks.put("EndDate", 512L);

		columnBitmasks.put("EndDateHours", 1024L);

		columnBitmasks.put("RegistrationLimitDate", 2048L);

		columnBitmasks.put("RegistrationLimitDateHours", 4096L);

		columnBitmasks.put("ImageId", 8192L);

		columnBitmasks.put("ImageName", 16384L);

		columnBitmasks.put("ImagePath", 32768L);

		columnBitmasks.put("RowStatus", 65536L);

		columnBitmasks.put("CreatedDate", 131072L);

		columnBitmasks.put("CreatedBy", 262144L);

		columnBitmasks.put("ModifiedDate", 524288L);

		columnBitmasks.put("ModifiedBy", 1048576L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TrainingAgenda _escapedModel;

}