/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.UserRoleType;
import com.astra.dewa.model.UserRoleTypeModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the UserRoleType service. Represents a row in the &quot;UserRoleType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>UserRoleTypeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserRoleTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserRoleTypeImpl
 * @generated
 */
public class UserRoleTypeModelImpl
	extends BaseModelImpl<UserRoleType> implements UserRoleTypeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user role type model instance should use the <code>UserRoleType</code> interface instead.
	 */
	public static final String TABLE_NAME = "UserRoleType";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"UserId", Types.BIGINT},
		{"RoleId", Types.INTEGER}, {"RowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("UserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("RoleId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table UserRoleType (Id INTEGER not null primary key IDENTITY,UserId LONG,RoleId INTEGER,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table UserRoleType";

	public static final String ORDER_BY_JPQL = " ORDER BY userRoleType.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY UserRoleType.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.UserRoleType"));

	public UserRoleTypeModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UserRoleType.class;
	}

	@Override
	public String getModelClassName() {
		return UserRoleType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UserRoleType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UserRoleType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserRoleType, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((UserRoleType)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UserRoleType, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UserRoleType, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UserRoleType)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UserRoleType, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UserRoleType, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<UserRoleType, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<UserRoleType, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<UserRoleType, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<UserRoleType, Object>>();
		Map<String, BiConsumer<UserRoleType, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<UserRoleType, ?>>();

		attributeGetterFunctions.put("Id", UserRoleType::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<UserRoleType, Integer>)UserRoleType::setId);
		attributeGetterFunctions.put("UserId", UserRoleType::getUserId);
		attributeSetterBiConsumers.put(
			"UserId", (BiConsumer<UserRoleType, Long>)UserRoleType::setUserId);
		attributeGetterFunctions.put("RoleId", UserRoleType::getRoleId);
		attributeSetterBiConsumers.put(
			"RoleId",
			(BiConsumer<UserRoleType, Integer>)UserRoleType::setRoleId);
		attributeGetterFunctions.put("RowStatus", UserRoleType::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<UserRoleType, Boolean>)UserRoleType::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", UserRoleType::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<UserRoleType, Date>)UserRoleType::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", UserRoleType::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<UserRoleType, String>)UserRoleType::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", UserRoleType::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<UserRoleType, Date>)UserRoleType::setModifiedDate);
		attributeGetterFunctions.put("ModifiedBy", UserRoleType::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<UserRoleType, String>)UserRoleType::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public long getUserId() {
		return _UserId;
	}

	@Override
	public void setUserId(long UserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_UserId = UserId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String UserUuid) {
	}

	@Override
	public int getRoleId() {
		return _RoleId;
	}

	@Override
	public void setRoleId(int RoleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RoleId = RoleId;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public UserRoleType toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UserRoleType>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UserRoleTypeImpl userRoleTypeImpl = new UserRoleTypeImpl();

		userRoleTypeImpl.setId(getId());
		userRoleTypeImpl.setUserId(getUserId());
		userRoleTypeImpl.setRoleId(getRoleId());
		userRoleTypeImpl.setRowStatus(getRowStatus());
		userRoleTypeImpl.setCreatedDate(getCreatedDate());
		userRoleTypeImpl.setCreatedBy(getCreatedBy());
		userRoleTypeImpl.setModifiedDate(getModifiedDate());
		userRoleTypeImpl.setModifiedBy(getModifiedBy());

		userRoleTypeImpl.resetOriginalValues();

		return userRoleTypeImpl;
	}

	@Override
	public UserRoleType cloneWithOriginalValues() {
		UserRoleTypeImpl userRoleTypeImpl = new UserRoleTypeImpl();

		userRoleTypeImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		userRoleTypeImpl.setUserId(this.<Long>getColumnOriginalValue("UserId"));
		userRoleTypeImpl.setRoleId(
			this.<Integer>getColumnOriginalValue("RoleId"));
		userRoleTypeImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		userRoleTypeImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		userRoleTypeImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		userRoleTypeImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		userRoleTypeImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return userRoleTypeImpl;
	}

	@Override
	public int compareTo(UserRoleType userRoleType) {
		int primaryKey = userRoleType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof UserRoleType)) {
			return false;
		}

		UserRoleType userRoleType = (UserRoleType)object;

		int primaryKey = userRoleType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<UserRoleType> toCacheModel() {
		UserRoleTypeCacheModel userRoleTypeCacheModel =
			new UserRoleTypeCacheModel();

		userRoleTypeCacheModel.Id = getId();

		userRoleTypeCacheModel.UserId = getUserId();

		userRoleTypeCacheModel.RoleId = getRoleId();

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			userRoleTypeCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			userRoleTypeCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			userRoleTypeCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		userRoleTypeCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = userRoleTypeCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			userRoleTypeCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			userRoleTypeCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			userRoleTypeCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		userRoleTypeCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = userRoleTypeCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			userRoleTypeCacheModel.ModifiedBy = null;
		}

		return userRoleTypeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UserRoleType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UserRoleType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserRoleType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((UserRoleType)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, UserRoleType>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					UserRoleType.class, ModelWrapper.class);

	}

	private int _Id;
	private long _UserId;
	private int _RoleId;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<UserRoleType, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((UserRoleType)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("UserId", _UserId);
		_columnOriginalValues.put("RoleId", _RoleId);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("UserId", 2L);

		columnBitmasks.put("RoleId", 4L);

		columnBitmasks.put("RowStatus", 8L);

		columnBitmasks.put("CreatedDate", 16L);

		columnBitmasks.put("CreatedBy", 32L);

		columnBitmasks.put("ModifiedDate", 64L);

		columnBitmasks.put("ModifiedBy", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private UserRoleType _escapedModel;

}