/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.UsersDealers;
import com.astra.dewa.model.UsersDealersModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the UsersDealers service. Represents a row in the &quot;UsersDealers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>UsersDealersModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UsersDealersImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UsersDealersImpl
 * @generated
 */
public class UsersDealersModelImpl
	extends BaseModelImpl<UsersDealers> implements UsersDealersModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a users dealers model instance should use the <code>UsersDealers</code> interface instead.
	 */
	public static final String TABLE_NAME = "UsersDealers";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"UserId", Types.BIGINT},
		{"DealerId", Types.INTEGER}, {"RoleId", Types.INTEGER},
		{"PhotoFileId", Types.BIGINT}, {"ADB2CId", Types.VARCHAR},
		{"userPrincipalName", Types.VARCHAR}, {"FullName", Types.VARCHAR},
		{"UserEmail", Types.VARCHAR}, {"ApprovedDate", Types.TIMESTAMP},
		{"RowStatus", Types.BOOLEAN}, {"CreatedDate", Types.TIMESTAMP},
		{"CreatedBy", Types.VARCHAR}, {"ModifiedDate", Types.TIMESTAMP},
		{"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("UserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("RoleId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("PhotoFileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ADB2CId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userPrincipalName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FullName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("UserEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ApprovedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table UsersDealers (Id INTEGER not null primary key IDENTITY,UserId LONG,DealerId INTEGER,RoleId INTEGER,PhotoFileId LONG,ADB2CId VARCHAR(75) null,userPrincipalName VARCHAR(75) null,FullName VARCHAR(75) null,UserEmail VARCHAR(75) null,ApprovedDate DATE null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table UsersDealers";

	public static final String ORDER_BY_JPQL = " ORDER BY usersDealers.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY UsersDealers.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ROWSTATUS_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.astra.dewa.service.util.ServiceProps.get(
			"lock.expiration.time.com.astra.dewa.model.UsersDealers"));

	public UsersDealersModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UsersDealers.class;
	}

	@Override
	public String getModelClassName() {
		return UsersDealers.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UsersDealers, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UsersDealers, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UsersDealers, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((UsersDealers)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UsersDealers, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UsersDealers, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UsersDealers)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UsersDealers, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UsersDealers, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<UsersDealers, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<UsersDealers, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<UsersDealers, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<UsersDealers, Object>>();
		Map<String, BiConsumer<UsersDealers, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<UsersDealers, ?>>();

		attributeGetterFunctions.put("Id", UsersDealers::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<UsersDealers, Integer>)UsersDealers::setId);
		attributeGetterFunctions.put("UserId", UsersDealers::getUserId);
		attributeSetterBiConsumers.put(
			"UserId", (BiConsumer<UsersDealers, Long>)UsersDealers::setUserId);
		attributeGetterFunctions.put("DealerId", UsersDealers::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId",
			(BiConsumer<UsersDealers, Integer>)UsersDealers::setDealerId);
		attributeGetterFunctions.put("RoleId", UsersDealers::getRoleId);
		attributeSetterBiConsumers.put(
			"RoleId",
			(BiConsumer<UsersDealers, Integer>)UsersDealers::setRoleId);
		attributeGetterFunctions.put(
			"PhotoFileId", UsersDealers::getPhotoFileId);
		attributeSetterBiConsumers.put(
			"PhotoFileId",
			(BiConsumer<UsersDealers, Long>)UsersDealers::setPhotoFileId);
		attributeGetterFunctions.put("ADB2CId", UsersDealers::getADB2CId);
		attributeSetterBiConsumers.put(
			"ADB2CId",
			(BiConsumer<UsersDealers, String>)UsersDealers::setADB2CId);
		attributeGetterFunctions.put(
			"userPrincipalName", UsersDealers::getUserPrincipalName);
		attributeSetterBiConsumers.put(
			"userPrincipalName",
			(BiConsumer<UsersDealers, String>)
				UsersDealers::setUserPrincipalName);
		attributeGetterFunctions.put("FullName", UsersDealers::getFullName);
		attributeSetterBiConsumers.put(
			"FullName",
			(BiConsumer<UsersDealers, String>)UsersDealers::setFullName);
		attributeGetterFunctions.put("UserEmail", UsersDealers::getUserEmail);
		attributeSetterBiConsumers.put(
			"UserEmail",
			(BiConsumer<UsersDealers, String>)UsersDealers::setUserEmail);
		attributeGetterFunctions.put(
			"ApprovedDate", UsersDealers::getApprovedDate);
		attributeSetterBiConsumers.put(
			"ApprovedDate",
			(BiConsumer<UsersDealers, Date>)UsersDealers::setApprovedDate);
		attributeGetterFunctions.put("RowStatus", UsersDealers::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<UsersDealers, Boolean>)UsersDealers::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", UsersDealers::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<UsersDealers, Date>)UsersDealers::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", UsersDealers::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<UsersDealers, String>)UsersDealers::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", UsersDealers::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<UsersDealers, Date>)UsersDealers::setModifiedDate);
		attributeGetterFunctions.put("ModifiedBy", UsersDealers::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<UsersDealers, String>)UsersDealers::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public long getUserId() {
		return _UserId;
	}

	@Override
	public void setUserId(long UserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_UserId = UserId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String UserUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("UserId"));
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public int getRoleId() {
		return _RoleId;
	}

	@Override
	public void setRoleId(int RoleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RoleId = RoleId;
	}

	@Override
	public long getPhotoFileId() {
		return _PhotoFileId;
	}

	@Override
	public void setPhotoFileId(long PhotoFileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_PhotoFileId = PhotoFileId;
	}

	@Override
	public String getADB2CId() {
		if (_ADB2CId == null) {
			return "";
		}
		else {
			return _ADB2CId;
		}
	}

	@Override
	public void setADB2CId(String ADB2CId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ADB2CId = ADB2CId;
	}

	@Override
	public String getUserPrincipalName() {
		if (_userPrincipalName == null) {
			return "";
		}
		else {
			return _userPrincipalName;
		}
	}

	@Override
	public void setUserPrincipalName(String userPrincipalName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userPrincipalName = userPrincipalName;
	}

	@Override
	public String getFullName() {
		if (_FullName == null) {
			return "";
		}
		else {
			return _FullName;
		}
	}

	@Override
	public void setFullName(String FullName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FullName = FullName;
	}

	@Override
	public String getUserEmail() {
		if (_UserEmail == null) {
			return "";
		}
		else {
			return _UserEmail;
		}
	}

	@Override
	public void setUserEmail(String UserEmail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_UserEmail = UserEmail;
	}

	@Override
	public Date getApprovedDate() {
		return _ApprovedDate;
	}

	@Override
	public void setApprovedDate(Date ApprovedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApprovedDate = ApprovedDate;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Boolean getOriginalRowStatus() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public UsersDealers toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UsersDealers>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UsersDealersImpl usersDealersImpl = new UsersDealersImpl();

		usersDealersImpl.setId(getId());
		usersDealersImpl.setUserId(getUserId());
		usersDealersImpl.setDealerId(getDealerId());
		usersDealersImpl.setRoleId(getRoleId());
		usersDealersImpl.setPhotoFileId(getPhotoFileId());
		usersDealersImpl.setADB2CId(getADB2CId());
		usersDealersImpl.setUserPrincipalName(getUserPrincipalName());
		usersDealersImpl.setFullName(getFullName());
		usersDealersImpl.setUserEmail(getUserEmail());
		usersDealersImpl.setApprovedDate(getApprovedDate());
		usersDealersImpl.setRowStatus(getRowStatus());
		usersDealersImpl.setCreatedDate(getCreatedDate());
		usersDealersImpl.setCreatedBy(getCreatedBy());
		usersDealersImpl.setModifiedDate(getModifiedDate());
		usersDealersImpl.setModifiedBy(getModifiedBy());

		usersDealersImpl.resetOriginalValues();

		return usersDealersImpl;
	}

	@Override
	public UsersDealers cloneWithOriginalValues() {
		UsersDealersImpl usersDealersImpl = new UsersDealersImpl();

		usersDealersImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		usersDealersImpl.setUserId(this.<Long>getColumnOriginalValue("UserId"));
		usersDealersImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("DealerId"));
		usersDealersImpl.setRoleId(
			this.<Integer>getColumnOriginalValue("RoleId"));
		usersDealersImpl.setPhotoFileId(
			this.<Long>getColumnOriginalValue("PhotoFileId"));
		usersDealersImpl.setADB2CId(
			this.<String>getColumnOriginalValue("ADB2CId"));
		usersDealersImpl.setUserPrincipalName(
			this.<String>getColumnOriginalValue("userPrincipalName"));
		usersDealersImpl.setFullName(
			this.<String>getColumnOriginalValue("FullName"));
		usersDealersImpl.setUserEmail(
			this.<String>getColumnOriginalValue("UserEmail"));
		usersDealersImpl.setApprovedDate(
			this.<Date>getColumnOriginalValue("ApprovedDate"));
		usersDealersImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		usersDealersImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		usersDealersImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		usersDealersImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		usersDealersImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return usersDealersImpl;
	}

	@Override
	public int compareTo(UsersDealers usersDealers) {
		int primaryKey = usersDealers.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof UsersDealers)) {
			return false;
		}

		UsersDealers usersDealers = (UsersDealers)object;

		int primaryKey = usersDealers.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<UsersDealers> toCacheModel() {
		UsersDealersCacheModel usersDealersCacheModel =
			new UsersDealersCacheModel();

		usersDealersCacheModel.Id = getId();

		usersDealersCacheModel.UserId = getUserId();

		usersDealersCacheModel.DealerId = getDealerId();

		usersDealersCacheModel.RoleId = getRoleId();

		usersDealersCacheModel.PhotoFileId = getPhotoFileId();

		usersDealersCacheModel.ADB2CId = getADB2CId();

		String ADB2CId = usersDealersCacheModel.ADB2CId;

		if ((ADB2CId != null) && (ADB2CId.length() == 0)) {
			usersDealersCacheModel.ADB2CId = null;
		}

		usersDealersCacheModel.userPrincipalName = getUserPrincipalName();

		String userPrincipalName = usersDealersCacheModel.userPrincipalName;

		if ((userPrincipalName != null) && (userPrincipalName.length() == 0)) {
			usersDealersCacheModel.userPrincipalName = null;
		}

		usersDealersCacheModel.FullName = getFullName();

		String FullName = usersDealersCacheModel.FullName;

		if ((FullName != null) && (FullName.length() == 0)) {
			usersDealersCacheModel.FullName = null;
		}

		usersDealersCacheModel.UserEmail = getUserEmail();

		String UserEmail = usersDealersCacheModel.UserEmail;

		if ((UserEmail != null) && (UserEmail.length() == 0)) {
			usersDealersCacheModel.UserEmail = null;
		}

		Date ApprovedDate = getApprovedDate();

		if (ApprovedDate != null) {
			usersDealersCacheModel.ApprovedDate = ApprovedDate.getTime();
		}
		else {
			usersDealersCacheModel.ApprovedDate = Long.MIN_VALUE;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			usersDealersCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			usersDealersCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			usersDealersCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		usersDealersCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = usersDealersCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			usersDealersCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			usersDealersCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			usersDealersCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		usersDealersCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = usersDealersCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			usersDealersCacheModel.ModifiedBy = null;
		}

		return usersDealersCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UsersDealers, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UsersDealers, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UsersDealers, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((UsersDealers)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, UsersDealers>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					UsersDealers.class, ModelWrapper.class);

	}

	private int _Id;
	private long _UserId;
	private int _DealerId;
	private int _RoleId;
	private long _PhotoFileId;
	private String _ADB2CId;
	private String _userPrincipalName;
	private String _FullName;
	private String _UserEmail;
	private Date _ApprovedDate;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<UsersDealers, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((UsersDealers)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("UserId", _UserId);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("RoleId", _RoleId);
		_columnOriginalValues.put("PhotoFileId", _PhotoFileId);
		_columnOriginalValues.put("ADB2CId", _ADB2CId);
		_columnOriginalValues.put("userPrincipalName", _userPrincipalName);
		_columnOriginalValues.put("FullName", _FullName);
		_columnOriginalValues.put("UserEmail", _UserEmail);
		_columnOriginalValues.put("ApprovedDate", _ApprovedDate);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("UserId", 2L);

		columnBitmasks.put("DealerId", 4L);

		columnBitmasks.put("RoleId", 8L);

		columnBitmasks.put("PhotoFileId", 16L);

		columnBitmasks.put("ADB2CId", 32L);

		columnBitmasks.put("userPrincipalName", 64L);

		columnBitmasks.put("FullName", 128L);

		columnBitmasks.put("UserEmail", 256L);

		columnBitmasks.put("ApprovedDate", 512L);

		columnBitmasks.put("RowStatus", 1024L);

		columnBitmasks.put("CreatedDate", 2048L);

		columnBitmasks.put("CreatedBy", 4096L);

		columnBitmasks.put("ModifiedDate", 8192L);

		columnBitmasks.put("ModifiedBy", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private UsersDealers _escapedModel;

}