/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.ApplicationCategory;
import com.astra.dewa.model.ApplicationCategoryModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ApplicationCategory service. Represents a row in the &quot;ApplicationCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ApplicationCategoryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApplicationCategoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApplicationCategoryImpl
 * @generated
 */
public class ApplicationCategoryModelImpl
	extends BaseModelImpl<ApplicationCategory>
	implements ApplicationCategoryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a application category model instance should use the <code>ApplicationCategory</code> interface instead.
	 */
	public static final String TABLE_NAME = "ApplicationCategory";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"Name", Types.VARCHAR},
		{"Description", Types.VARCHAR}, {"CategoryBonus", Types.INTEGER},
		{"RowStatus", Types.BOOLEAN}, {"CreatedBy", Types.VARCHAR},
		{"CreatedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CategoryBonus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ApplicationCategory (Id INTEGER not null primary key IDENTITY,Name VARCHAR(75) null,Description VARCHAR(75) null,CategoryBonus INTEGER,RowStatus BOOLEAN,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table ApplicationCategory";

	public static final String ORDER_BY_JPQL =
		" ORDER BY applicationCategory.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ApplicationCategory.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ApplicationCategoryModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ApplicationCategory.class;
	}

	@Override
	public String getModelClassName() {
		return ApplicationCategory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ApplicationCategory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ApplicationCategory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApplicationCategory, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ApplicationCategory)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ApplicationCategory, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ApplicationCategory, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ApplicationCategory)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ApplicationCategory, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ApplicationCategory, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ApplicationCategory, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ApplicationCategory, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ApplicationCategory, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ApplicationCategory, Object>>();
		Map<String, BiConsumer<ApplicationCategory, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ApplicationCategory, ?>>();

		attributeGetterFunctions.put("Id", ApplicationCategory::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<ApplicationCategory, Integer>)
				ApplicationCategory::setId);
		attributeGetterFunctions.put("Name", ApplicationCategory::getName);
		attributeSetterBiConsumers.put(
			"Name",
			(BiConsumer<ApplicationCategory, String>)
				ApplicationCategory::setName);
		attributeGetterFunctions.put(
			"Description", ApplicationCategory::getDescription);
		attributeSetterBiConsumers.put(
			"Description",
			(BiConsumer<ApplicationCategory, String>)
				ApplicationCategory::setDescription);
		attributeGetterFunctions.put(
			"CategoryBonus", ApplicationCategory::getCategoryBonus);
		attributeSetterBiConsumers.put(
			"CategoryBonus",
			(BiConsumer<ApplicationCategory, Integer>)
				ApplicationCategory::setCategoryBonus);
		attributeGetterFunctions.put(
			"RowStatus", ApplicationCategory::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<ApplicationCategory, Boolean>)
				ApplicationCategory::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedBy", ApplicationCategory::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<ApplicationCategory, String>)
				ApplicationCategory::setCreatedBy);
		attributeGetterFunctions.put(
			"CreatedDate", ApplicationCategory::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<ApplicationCategory, Date>)
				ApplicationCategory::setCreatedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", ApplicationCategory::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<ApplicationCategory, String>)
				ApplicationCategory::setModifiedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", ApplicationCategory::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<ApplicationCategory, Date>)
				ApplicationCategory::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public String getName() {
		if (_Name == null) {
			return "";
		}
		else {
			return _Name;
		}
	}

	@Override
	public void setName(String Name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Name = Name;
	}

	@Override
	public String getDescription() {
		if (_Description == null) {
			return "";
		}
		else {
			return _Description;
		}
	}

	@Override
	public void setDescription(String Description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Description = Description;
	}

	@Override
	public Integer getCategoryBonus() {
		return _CategoryBonus;
	}

	@Override
	public void setCategoryBonus(Integer CategoryBonus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CategoryBonus = CategoryBonus;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ApplicationCategory toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ApplicationCategory>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ApplicationCategoryImpl applicationCategoryImpl =
			new ApplicationCategoryImpl();

		applicationCategoryImpl.setId(getId());
		applicationCategoryImpl.setName(getName());
		applicationCategoryImpl.setDescription(getDescription());
		applicationCategoryImpl.setCategoryBonus(getCategoryBonus());
		applicationCategoryImpl.setRowStatus(getRowStatus());
		applicationCategoryImpl.setCreatedBy(getCreatedBy());
		applicationCategoryImpl.setCreatedDate(getCreatedDate());
		applicationCategoryImpl.setModifiedBy(getModifiedBy());
		applicationCategoryImpl.setModifiedDate(getModifiedDate());

		applicationCategoryImpl.resetOriginalValues();

		return applicationCategoryImpl;
	}

	@Override
	public ApplicationCategory cloneWithOriginalValues() {
		ApplicationCategoryImpl applicationCategoryImpl =
			new ApplicationCategoryImpl();

		applicationCategoryImpl.setId(
			this.<Integer>getColumnOriginalValue("Id"));
		applicationCategoryImpl.setName(
			this.<String>getColumnOriginalValue("Name"));
		applicationCategoryImpl.setDescription(
			this.<String>getColumnOriginalValue("Description"));
		applicationCategoryImpl.setCategoryBonus(
			this.<Integer>getColumnOriginalValue("CategoryBonus"));
		applicationCategoryImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		applicationCategoryImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		applicationCategoryImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		applicationCategoryImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));
		applicationCategoryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));

		return applicationCategoryImpl;
	}

	@Override
	public int compareTo(ApplicationCategory applicationCategory) {
		int primaryKey = applicationCategory.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ApplicationCategory)) {
			return false;
		}

		ApplicationCategory applicationCategory = (ApplicationCategory)object;

		int primaryKey = applicationCategory.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ApplicationCategory> toCacheModel() {
		ApplicationCategoryCacheModel applicationCategoryCacheModel =
			new ApplicationCategoryCacheModel();

		applicationCategoryCacheModel.Id = getId();

		applicationCategoryCacheModel.Name = getName();

		String Name = applicationCategoryCacheModel.Name;

		if ((Name != null) && (Name.length() == 0)) {
			applicationCategoryCacheModel.Name = null;
		}

		applicationCategoryCacheModel.Description = getDescription();

		String Description = applicationCategoryCacheModel.Description;

		if ((Description != null) && (Description.length() == 0)) {
			applicationCategoryCacheModel.Description = null;
		}

		Integer CategoryBonus = getCategoryBonus();

		if (CategoryBonus != null) {
			applicationCategoryCacheModel.CategoryBonus = CategoryBonus;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			applicationCategoryCacheModel.RowStatus = RowStatus;
		}

		applicationCategoryCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = applicationCategoryCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			applicationCategoryCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			applicationCategoryCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			applicationCategoryCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		applicationCategoryCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = applicationCategoryCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			applicationCategoryCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			applicationCategoryCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			applicationCategoryCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		return applicationCategoryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ApplicationCategory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ApplicationCategory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApplicationCategory, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ApplicationCategory)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ApplicationCategory>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ApplicationCategory.class, ModelWrapper.class);

	}

	private int _Id;
	private String _Name;
	private String _Description;
	private Integer _CategoryBonus;
	private Boolean _RowStatus;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<ApplicationCategory, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ApplicationCategory)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("Name", _Name);
		_columnOriginalValues.put("Description", _Description);
		_columnOriginalValues.put("CategoryBonus", _CategoryBonus);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("Name", 2L);

		columnBitmasks.put("Description", 4L);

		columnBitmasks.put("CategoryBonus", 8L);

		columnBitmasks.put("RowStatus", 16L);

		columnBitmasks.put("CreatedBy", 32L);

		columnBitmasks.put("CreatedDate", 64L);

		columnBitmasks.put("ModifiedBy", 128L);

		columnBitmasks.put("ModifiedDate", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ApplicationCategory _escapedModel;

}