/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.ApplicationHeaderJournal;
import com.astra.dewa.model.ApplicationHeaderJournalModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ApplicationHeaderJournal service. Represents a row in the &quot;ApplicationHeaderJournal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ApplicationHeaderJournalModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApplicationHeaderJournalImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApplicationHeaderJournalImpl
 * @generated
 */
public class ApplicationHeaderJournalModelImpl
	extends BaseModelImpl<ApplicationHeaderJournal>
	implements ApplicationHeaderJournalModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a application header journal model instance should use the <code>ApplicationHeaderJournal</code> interface instead.
	 */
	public static final String TABLE_NAME = "ApplicationHeaderJournal";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"ApplicationHeaderId", Types.INTEGER},
		{"ApplicationId", Types.INTEGER},
		{"ApplicationHeaderStatusId", Types.INTEGER},
		{"ApplicationCategoryId", Types.INTEGER}, {"DealerId", Types.INTEGER},
		{"TicketNo", Types.VARCHAR}, {"TicketCode", Types.VARCHAR},
		{"ReqDate", Types.TIMESTAMP}, {"ReqYear", Types.INTEGER},
		{"ReqMonth", Types.INTEGER}, {"ReqScreenName", Types.VARCHAR},
		{"ReqName", Types.VARCHAR}, {"ReqEmail", Types.VARCHAR},
		{"ReqCCEmail", Types.VARCHAR}, {"ReqPhone", Types.VARCHAR},
		{"NominalPengajuan", Types.INTEGER}, {"ReqDesc", Types.VARCHAR},
		{"BusinessBenefit", Types.VARCHAR}, {"FileId", Types.BIGINT},
		{"FileName", Types.VARCHAR}, {"FileUrl", Types.VARCHAR},
		{"Notes", Types.VARCHAR}, {"NotesHistory", Types.VARCHAR},
		{"RowStatus", Types.BOOLEAN}, {"CreatedBy", Types.VARCHAR},
		{"CreatedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApplicationHeaderId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApplicationId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApplicationHeaderStatusId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApplicationCategoryId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("TicketNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("TicketCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ReqDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ReqYear", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ReqMonth", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ReqScreenName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ReqName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ReqEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ReqCCEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ReqPhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("NominalPengajuan", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ReqDesc", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("BusinessBenefit", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FileUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Notes", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("NotesHistory", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ApplicationHeaderJournal (Id INTEGER not null primary key IDENTITY,ApplicationHeaderId INTEGER,ApplicationId INTEGER,ApplicationHeaderStatusId INTEGER,ApplicationCategoryId INTEGER,DealerId INTEGER,TicketNo VARCHAR(75) null,TicketCode VARCHAR(75) null,ReqDate DATE null,ReqYear INTEGER,ReqMonth INTEGER,ReqScreenName VARCHAR(75) null,ReqName VARCHAR(75) null,ReqEmail VARCHAR(75) null,ReqCCEmail VARCHAR(75) null,ReqPhone VARCHAR(75) null,NominalPengajuan INTEGER,ReqDesc VARCHAR(75) null,BusinessBenefit VARCHAR(75) null,FileId LONG,FileName VARCHAR(75) null,FileUrl VARCHAR(75) null,Notes VARCHAR(75) null,NotesHistory VARCHAR(75) null,RowStatus BOOLEAN,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table ApplicationHeaderJournal";

	public static final String ORDER_BY_JPQL =
		" ORDER BY applicationHeaderJournal.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ApplicationHeaderJournal.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ApplicationHeaderJournalModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ApplicationHeaderJournal.class;
	}

	@Override
	public String getModelClassName() {
		return ApplicationHeaderJournal.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ApplicationHeaderJournal, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ApplicationHeaderJournal, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApplicationHeaderJournal, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ApplicationHeaderJournal)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ApplicationHeaderJournal, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ApplicationHeaderJournal, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ApplicationHeaderJournal)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ApplicationHeaderJournal, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ApplicationHeaderJournal, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ApplicationHeaderJournal, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<ApplicationHeaderJournal, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<ApplicationHeaderJournal, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ApplicationHeaderJournal, Object>>();
		Map<String, BiConsumer<ApplicationHeaderJournal, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ApplicationHeaderJournal, ?>>();

		attributeGetterFunctions.put("Id", ApplicationHeaderJournal::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<ApplicationHeaderJournal, Integer>)
				ApplicationHeaderJournal::setId);
		attributeGetterFunctions.put(
			"ApplicationHeaderId",
			ApplicationHeaderJournal::getApplicationHeaderId);
		attributeSetterBiConsumers.put(
			"ApplicationHeaderId",
			(BiConsumer<ApplicationHeaderJournal, Integer>)
				ApplicationHeaderJournal::setApplicationHeaderId);
		attributeGetterFunctions.put(
			"ApplicationId", ApplicationHeaderJournal::getApplicationId);
		attributeSetterBiConsumers.put(
			"ApplicationId",
			(BiConsumer<ApplicationHeaderJournal, Integer>)
				ApplicationHeaderJournal::setApplicationId);
		attributeGetterFunctions.put(
			"ApplicationHeaderStatusId",
			ApplicationHeaderJournal::getApplicationHeaderStatusId);
		attributeSetterBiConsumers.put(
			"ApplicationHeaderStatusId",
			(BiConsumer<ApplicationHeaderJournal, Integer>)
				ApplicationHeaderJournal::setApplicationHeaderStatusId);
		attributeGetterFunctions.put(
			"ApplicationCategoryId",
			ApplicationHeaderJournal::getApplicationCategoryId);
		attributeSetterBiConsumers.put(
			"ApplicationCategoryId",
			(BiConsumer<ApplicationHeaderJournal, Integer>)
				ApplicationHeaderJournal::setApplicationCategoryId);
		attributeGetterFunctions.put(
			"DealerId", ApplicationHeaderJournal::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId",
			(BiConsumer<ApplicationHeaderJournal, Integer>)
				ApplicationHeaderJournal::setDealerId);
		attributeGetterFunctions.put(
			"TicketNo", ApplicationHeaderJournal::getTicketNo);
		attributeSetterBiConsumers.put(
			"TicketNo",
			(BiConsumer<ApplicationHeaderJournal, String>)
				ApplicationHeaderJournal::setTicketNo);
		attributeGetterFunctions.put(
			"TicketCode", ApplicationHeaderJournal::getTicketCode);
		attributeSetterBiConsumers.put(
			"TicketCode",
			(BiConsumer<ApplicationHeaderJournal, String>)
				ApplicationHeaderJournal::setTicketCode);
		attributeGetterFunctions.put(
			"ReqDate", ApplicationHeaderJournal::getReqDate);
		attributeSetterBiConsumers.put(
			"ReqDate",
			(BiConsumer<ApplicationHeaderJournal, Date>)
				ApplicationHeaderJournal::setReqDate);
		attributeGetterFunctions.put(
			"ReqYear", ApplicationHeaderJournal::getReqYear);
		attributeSetterBiConsumers.put(
			"ReqYear",
			(BiConsumer<ApplicationHeaderJournal, Integer>)
				ApplicationHeaderJournal::setReqYear);
		attributeGetterFunctions.put(
			"ReqMonth", ApplicationHeaderJournal::getReqMonth);
		attributeSetterBiConsumers.put(
			"ReqMonth",
			(BiConsumer<ApplicationHeaderJournal, Integer>)
				ApplicationHeaderJournal::setReqMonth);
		attributeGetterFunctions.put(
			"ReqScreenName", ApplicationHeaderJournal::getReqScreenName);
		attributeSetterBiConsumers.put(
			"ReqScreenName",
			(BiConsumer<ApplicationHeaderJournal, String>)
				ApplicationHeaderJournal::setReqScreenName);
		attributeGetterFunctions.put(
			"ReqName", ApplicationHeaderJournal::getReqName);
		attributeSetterBiConsumers.put(
			"ReqName",
			(BiConsumer<ApplicationHeaderJournal, String>)
				ApplicationHeaderJournal::setReqName);
		attributeGetterFunctions.put(
			"ReqEmail", ApplicationHeaderJournal::getReqEmail);
		attributeSetterBiConsumers.put(
			"ReqEmail",
			(BiConsumer<ApplicationHeaderJournal, String>)
				ApplicationHeaderJournal::setReqEmail);
		attributeGetterFunctions.put(
			"ReqCCEmail", ApplicationHeaderJournal::getReqCCEmail);
		attributeSetterBiConsumers.put(
			"ReqCCEmail",
			(BiConsumer<ApplicationHeaderJournal, String>)
				ApplicationHeaderJournal::setReqCCEmail);
		attributeGetterFunctions.put(
			"ReqPhone", ApplicationHeaderJournal::getReqPhone);
		attributeSetterBiConsumers.put(
			"ReqPhone",
			(BiConsumer<ApplicationHeaderJournal, String>)
				ApplicationHeaderJournal::setReqPhone);
		attributeGetterFunctions.put(
			"NominalPengajuan", ApplicationHeaderJournal::getNominalPengajuan);
		attributeSetterBiConsumers.put(
			"NominalPengajuan",
			(BiConsumer<ApplicationHeaderJournal, Integer>)
				ApplicationHeaderJournal::setNominalPengajuan);
		attributeGetterFunctions.put(
			"ReqDesc", ApplicationHeaderJournal::getReqDesc);
		attributeSetterBiConsumers.put(
			"ReqDesc",
			(BiConsumer<ApplicationHeaderJournal, String>)
				ApplicationHeaderJournal::setReqDesc);
		attributeGetterFunctions.put(
			"BusinessBenefit", ApplicationHeaderJournal::getBusinessBenefit);
		attributeSetterBiConsumers.put(
			"BusinessBenefit",
			(BiConsumer<ApplicationHeaderJournal, String>)
				ApplicationHeaderJournal::setBusinessBenefit);
		attributeGetterFunctions.put(
			"FileId", ApplicationHeaderJournal::getFileId);
		attributeSetterBiConsumers.put(
			"FileId",
			(BiConsumer<ApplicationHeaderJournal, Long>)
				ApplicationHeaderJournal::setFileId);
		attributeGetterFunctions.put(
			"FileName", ApplicationHeaderJournal::getFileName);
		attributeSetterBiConsumers.put(
			"FileName",
			(BiConsumer<ApplicationHeaderJournal, String>)
				ApplicationHeaderJournal::setFileName);
		attributeGetterFunctions.put(
			"FileUrl", ApplicationHeaderJournal::getFileUrl);
		attributeSetterBiConsumers.put(
			"FileUrl",
			(BiConsumer<ApplicationHeaderJournal, String>)
				ApplicationHeaderJournal::setFileUrl);
		attributeGetterFunctions.put(
			"Notes", ApplicationHeaderJournal::getNotes);
		attributeSetterBiConsumers.put(
			"Notes",
			(BiConsumer<ApplicationHeaderJournal, String>)
				ApplicationHeaderJournal::setNotes);
		attributeGetterFunctions.put(
			"NotesHistory", ApplicationHeaderJournal::getNotesHistory);
		attributeSetterBiConsumers.put(
			"NotesHistory",
			(BiConsumer<ApplicationHeaderJournal, String>)
				ApplicationHeaderJournal::setNotesHistory);
		attributeGetterFunctions.put(
			"RowStatus", ApplicationHeaderJournal::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<ApplicationHeaderJournal, Boolean>)
				ApplicationHeaderJournal::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedBy", ApplicationHeaderJournal::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<ApplicationHeaderJournal, String>)
				ApplicationHeaderJournal::setCreatedBy);
		attributeGetterFunctions.put(
			"CreatedDate", ApplicationHeaderJournal::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<ApplicationHeaderJournal, Date>)
				ApplicationHeaderJournal::setCreatedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", ApplicationHeaderJournal::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<ApplicationHeaderJournal, String>)
				ApplicationHeaderJournal::setModifiedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", ApplicationHeaderJournal::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<ApplicationHeaderJournal, Date>)
				ApplicationHeaderJournal::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getApplicationHeaderId() {
		return _ApplicationHeaderId;
	}

	@Override
	public void setApplicationHeaderId(int ApplicationHeaderId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApplicationHeaderId = ApplicationHeaderId;
	}

	@Override
	public int getApplicationId() {
		return _ApplicationId;
	}

	@Override
	public void setApplicationId(int ApplicationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApplicationId = ApplicationId;
	}

	@Override
	public int getApplicationHeaderStatusId() {
		return _ApplicationHeaderStatusId;
	}

	@Override
	public void setApplicationHeaderStatusId(int ApplicationHeaderStatusId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApplicationHeaderStatusId = ApplicationHeaderStatusId;
	}

	@Override
	public int getApplicationCategoryId() {
		return _ApplicationCategoryId;
	}

	@Override
	public void setApplicationCategoryId(int ApplicationCategoryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApplicationCategoryId = ApplicationCategoryId;
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public String getTicketNo() {
		if (_TicketNo == null) {
			return "";
		}
		else {
			return _TicketNo;
		}
	}

	@Override
	public void setTicketNo(String TicketNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TicketNo = TicketNo;
	}

	@Override
	public String getTicketCode() {
		if (_TicketCode == null) {
			return "";
		}
		else {
			return _TicketCode;
		}
	}

	@Override
	public void setTicketCode(String TicketCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TicketCode = TicketCode;
	}

	@Override
	public Date getReqDate() {
		return _ReqDate;
	}

	@Override
	public void setReqDate(Date ReqDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ReqDate = ReqDate;
	}

	@Override
	public Integer getReqYear() {
		return _ReqYear;
	}

	@Override
	public void setReqYear(Integer ReqYear) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ReqYear = ReqYear;
	}

	@Override
	public Integer getReqMonth() {
		return _ReqMonth;
	}

	@Override
	public void setReqMonth(Integer ReqMonth) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ReqMonth = ReqMonth;
	}

	@Override
	public String getReqScreenName() {
		if (_ReqScreenName == null) {
			return "";
		}
		else {
			return _ReqScreenName;
		}
	}

	@Override
	public void setReqScreenName(String ReqScreenName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ReqScreenName = ReqScreenName;
	}

	@Override
	public String getReqName() {
		if (_ReqName == null) {
			return "";
		}
		else {
			return _ReqName;
		}
	}

	@Override
	public void setReqName(String ReqName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ReqName = ReqName;
	}

	@Override
	public String getReqEmail() {
		if (_ReqEmail == null) {
			return "";
		}
		else {
			return _ReqEmail;
		}
	}

	@Override
	public void setReqEmail(String ReqEmail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ReqEmail = ReqEmail;
	}

	@Override
	public String getReqCCEmail() {
		if (_ReqCCEmail == null) {
			return "";
		}
		else {
			return _ReqCCEmail;
		}
	}

	@Override
	public void setReqCCEmail(String ReqCCEmail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ReqCCEmail = ReqCCEmail;
	}

	@Override
	public String getReqPhone() {
		if (_ReqPhone == null) {
			return "";
		}
		else {
			return _ReqPhone;
		}
	}

	@Override
	public void setReqPhone(String ReqPhone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ReqPhone = ReqPhone;
	}

	@Override
	public Integer getNominalPengajuan() {
		return _NominalPengajuan;
	}

	@Override
	public void setNominalPengajuan(Integer NominalPengajuan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_NominalPengajuan = NominalPengajuan;
	}

	@Override
	public String getReqDesc() {
		if (_ReqDesc == null) {
			return "";
		}
		else {
			return _ReqDesc;
		}
	}

	@Override
	public void setReqDesc(String ReqDesc) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ReqDesc = ReqDesc;
	}

	@Override
	public String getBusinessBenefit() {
		if (_BusinessBenefit == null) {
			return "";
		}
		else {
			return _BusinessBenefit;
		}
	}

	@Override
	public void setBusinessBenefit(String BusinessBenefit) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_BusinessBenefit = BusinessBenefit;
	}

	@Override
	public Long getFileId() {
		return _FileId;
	}

	@Override
	public void setFileId(Long FileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileId = FileId;
	}

	@Override
	public String getFileName() {
		if (_FileName == null) {
			return "";
		}
		else {
			return _FileName;
		}
	}

	@Override
	public void setFileName(String FileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileName = FileName;
	}

	@Override
	public String getFileUrl() {
		if (_FileUrl == null) {
			return "";
		}
		else {
			return _FileUrl;
		}
	}

	@Override
	public void setFileUrl(String FileUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileUrl = FileUrl;
	}

	@Override
	public String getNotes() {
		if (_Notes == null) {
			return "";
		}
		else {
			return _Notes;
		}
	}

	@Override
	public void setNotes(String Notes) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Notes = Notes;
	}

	@Override
	public String getNotesHistory() {
		if (_NotesHistory == null) {
			return "";
		}
		else {
			return _NotesHistory;
		}
	}

	@Override
	public void setNotesHistory(String NotesHistory) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_NotesHistory = NotesHistory;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ApplicationHeaderJournal toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ApplicationHeaderJournal>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ApplicationHeaderJournalImpl applicationHeaderJournalImpl =
			new ApplicationHeaderJournalImpl();

		applicationHeaderJournalImpl.setId(getId());
		applicationHeaderJournalImpl.setApplicationHeaderId(
			getApplicationHeaderId());
		applicationHeaderJournalImpl.setApplicationId(getApplicationId());
		applicationHeaderJournalImpl.setApplicationHeaderStatusId(
			getApplicationHeaderStatusId());
		applicationHeaderJournalImpl.setApplicationCategoryId(
			getApplicationCategoryId());
		applicationHeaderJournalImpl.setDealerId(getDealerId());
		applicationHeaderJournalImpl.setTicketNo(getTicketNo());
		applicationHeaderJournalImpl.setTicketCode(getTicketCode());
		applicationHeaderJournalImpl.setReqDate(getReqDate());
		applicationHeaderJournalImpl.setReqYear(getReqYear());
		applicationHeaderJournalImpl.setReqMonth(getReqMonth());
		applicationHeaderJournalImpl.setReqScreenName(getReqScreenName());
		applicationHeaderJournalImpl.setReqName(getReqName());
		applicationHeaderJournalImpl.setReqEmail(getReqEmail());
		applicationHeaderJournalImpl.setReqCCEmail(getReqCCEmail());
		applicationHeaderJournalImpl.setReqPhone(getReqPhone());
		applicationHeaderJournalImpl.setNominalPengajuan(getNominalPengajuan());
		applicationHeaderJournalImpl.setReqDesc(getReqDesc());
		applicationHeaderJournalImpl.setBusinessBenefit(getBusinessBenefit());
		applicationHeaderJournalImpl.setFileId(getFileId());
		applicationHeaderJournalImpl.setFileName(getFileName());
		applicationHeaderJournalImpl.setFileUrl(getFileUrl());
		applicationHeaderJournalImpl.setNotes(getNotes());
		applicationHeaderJournalImpl.setNotesHistory(getNotesHistory());
		applicationHeaderJournalImpl.setRowStatus(getRowStatus());
		applicationHeaderJournalImpl.setCreatedBy(getCreatedBy());
		applicationHeaderJournalImpl.setCreatedDate(getCreatedDate());
		applicationHeaderJournalImpl.setModifiedBy(getModifiedBy());
		applicationHeaderJournalImpl.setModifiedDate(getModifiedDate());

		applicationHeaderJournalImpl.resetOriginalValues();

		return applicationHeaderJournalImpl;
	}

	@Override
	public ApplicationHeaderJournal cloneWithOriginalValues() {
		ApplicationHeaderJournalImpl applicationHeaderJournalImpl =
			new ApplicationHeaderJournalImpl();

		applicationHeaderJournalImpl.setId(
			this.<Integer>getColumnOriginalValue("Id"));
		applicationHeaderJournalImpl.setApplicationHeaderId(
			this.<Integer>getColumnOriginalValue("ApplicationHeaderId"));
		applicationHeaderJournalImpl.setApplicationId(
			this.<Integer>getColumnOriginalValue("ApplicationId"));
		applicationHeaderJournalImpl.setApplicationHeaderStatusId(
			this.<Integer>getColumnOriginalValue("ApplicationHeaderStatusId"));
		applicationHeaderJournalImpl.setApplicationCategoryId(
			this.<Integer>getColumnOriginalValue("ApplicationCategoryId"));
		applicationHeaderJournalImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("DealerId"));
		applicationHeaderJournalImpl.setTicketNo(
			this.<String>getColumnOriginalValue("TicketNo"));
		applicationHeaderJournalImpl.setTicketCode(
			this.<String>getColumnOriginalValue("TicketCode"));
		applicationHeaderJournalImpl.setReqDate(
			this.<Date>getColumnOriginalValue("ReqDate"));
		applicationHeaderJournalImpl.setReqYear(
			this.<Integer>getColumnOriginalValue("ReqYear"));
		applicationHeaderJournalImpl.setReqMonth(
			this.<Integer>getColumnOriginalValue("ReqMonth"));
		applicationHeaderJournalImpl.setReqScreenName(
			this.<String>getColumnOriginalValue("ReqScreenName"));
		applicationHeaderJournalImpl.setReqName(
			this.<String>getColumnOriginalValue("ReqName"));
		applicationHeaderJournalImpl.setReqEmail(
			this.<String>getColumnOriginalValue("ReqEmail"));
		applicationHeaderJournalImpl.setReqCCEmail(
			this.<String>getColumnOriginalValue("ReqCCEmail"));
		applicationHeaderJournalImpl.setReqPhone(
			this.<String>getColumnOriginalValue("ReqPhone"));
		applicationHeaderJournalImpl.setNominalPengajuan(
			this.<Integer>getColumnOriginalValue("NominalPengajuan"));
		applicationHeaderJournalImpl.setReqDesc(
			this.<String>getColumnOriginalValue("ReqDesc"));
		applicationHeaderJournalImpl.setBusinessBenefit(
			this.<String>getColumnOriginalValue("BusinessBenefit"));
		applicationHeaderJournalImpl.setFileId(
			this.<Long>getColumnOriginalValue("FileId"));
		applicationHeaderJournalImpl.setFileName(
			this.<String>getColumnOriginalValue("FileName"));
		applicationHeaderJournalImpl.setFileUrl(
			this.<String>getColumnOriginalValue("FileUrl"));
		applicationHeaderJournalImpl.setNotes(
			this.<String>getColumnOriginalValue("Notes"));
		applicationHeaderJournalImpl.setNotesHistory(
			this.<String>getColumnOriginalValue("NotesHistory"));
		applicationHeaderJournalImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		applicationHeaderJournalImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		applicationHeaderJournalImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		applicationHeaderJournalImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));
		applicationHeaderJournalImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));

		return applicationHeaderJournalImpl;
	}

	@Override
	public int compareTo(ApplicationHeaderJournal applicationHeaderJournal) {
		int primaryKey = applicationHeaderJournal.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ApplicationHeaderJournal)) {
			return false;
		}

		ApplicationHeaderJournal applicationHeaderJournal =
			(ApplicationHeaderJournal)object;

		int primaryKey = applicationHeaderJournal.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ApplicationHeaderJournal> toCacheModel() {
		ApplicationHeaderJournalCacheModel applicationHeaderJournalCacheModel =
			new ApplicationHeaderJournalCacheModel();

		applicationHeaderJournalCacheModel.Id = getId();

		applicationHeaderJournalCacheModel.ApplicationHeaderId =
			getApplicationHeaderId();

		applicationHeaderJournalCacheModel.ApplicationId = getApplicationId();

		applicationHeaderJournalCacheModel.ApplicationHeaderStatusId =
			getApplicationHeaderStatusId();

		applicationHeaderJournalCacheModel.ApplicationCategoryId =
			getApplicationCategoryId();

		applicationHeaderJournalCacheModel.DealerId = getDealerId();

		applicationHeaderJournalCacheModel.TicketNo = getTicketNo();

		String TicketNo = applicationHeaderJournalCacheModel.TicketNo;

		if ((TicketNo != null) && (TicketNo.length() == 0)) {
			applicationHeaderJournalCacheModel.TicketNo = null;
		}

		applicationHeaderJournalCacheModel.TicketCode = getTicketCode();

		String TicketCode = applicationHeaderJournalCacheModel.TicketCode;

		if ((TicketCode != null) && (TicketCode.length() == 0)) {
			applicationHeaderJournalCacheModel.TicketCode = null;
		}

		Date ReqDate = getReqDate();

		if (ReqDate != null) {
			applicationHeaderJournalCacheModel.ReqDate = ReqDate.getTime();
		}
		else {
			applicationHeaderJournalCacheModel.ReqDate = Long.MIN_VALUE;
		}

		Integer ReqYear = getReqYear();

		if (ReqYear != null) {
			applicationHeaderJournalCacheModel.ReqYear = ReqYear;
		}

		Integer ReqMonth = getReqMonth();

		if (ReqMonth != null) {
			applicationHeaderJournalCacheModel.ReqMonth = ReqMonth;
		}

		applicationHeaderJournalCacheModel.ReqScreenName = getReqScreenName();

		String ReqScreenName = applicationHeaderJournalCacheModel.ReqScreenName;

		if ((ReqScreenName != null) && (ReqScreenName.length() == 0)) {
			applicationHeaderJournalCacheModel.ReqScreenName = null;
		}

		applicationHeaderJournalCacheModel.ReqName = getReqName();

		String ReqName = applicationHeaderJournalCacheModel.ReqName;

		if ((ReqName != null) && (ReqName.length() == 0)) {
			applicationHeaderJournalCacheModel.ReqName = null;
		}

		applicationHeaderJournalCacheModel.ReqEmail = getReqEmail();

		String ReqEmail = applicationHeaderJournalCacheModel.ReqEmail;

		if ((ReqEmail != null) && (ReqEmail.length() == 0)) {
			applicationHeaderJournalCacheModel.ReqEmail = null;
		}

		applicationHeaderJournalCacheModel.ReqCCEmail = getReqCCEmail();

		String ReqCCEmail = applicationHeaderJournalCacheModel.ReqCCEmail;

		if ((ReqCCEmail != null) && (ReqCCEmail.length() == 0)) {
			applicationHeaderJournalCacheModel.ReqCCEmail = null;
		}

		applicationHeaderJournalCacheModel.ReqPhone = getReqPhone();

		String ReqPhone = applicationHeaderJournalCacheModel.ReqPhone;

		if ((ReqPhone != null) && (ReqPhone.length() == 0)) {
			applicationHeaderJournalCacheModel.ReqPhone = null;
		}

		Integer NominalPengajuan = getNominalPengajuan();

		if (NominalPengajuan != null) {
			applicationHeaderJournalCacheModel.NominalPengajuan =
				NominalPengajuan;
		}

		applicationHeaderJournalCacheModel.ReqDesc = getReqDesc();

		String ReqDesc = applicationHeaderJournalCacheModel.ReqDesc;

		if ((ReqDesc != null) && (ReqDesc.length() == 0)) {
			applicationHeaderJournalCacheModel.ReqDesc = null;
		}

		applicationHeaderJournalCacheModel.BusinessBenefit =
			getBusinessBenefit();

		String BusinessBenefit =
			applicationHeaderJournalCacheModel.BusinessBenefit;

		if ((BusinessBenefit != null) && (BusinessBenefit.length() == 0)) {
			applicationHeaderJournalCacheModel.BusinessBenefit = null;
		}

		Long FileId = getFileId();

		if (FileId != null) {
			applicationHeaderJournalCacheModel.FileId = FileId;
		}

		applicationHeaderJournalCacheModel.FileName = getFileName();

		String FileName = applicationHeaderJournalCacheModel.FileName;

		if ((FileName != null) && (FileName.length() == 0)) {
			applicationHeaderJournalCacheModel.FileName = null;
		}

		applicationHeaderJournalCacheModel.FileUrl = getFileUrl();

		String FileUrl = applicationHeaderJournalCacheModel.FileUrl;

		if ((FileUrl != null) && (FileUrl.length() == 0)) {
			applicationHeaderJournalCacheModel.FileUrl = null;
		}

		applicationHeaderJournalCacheModel.Notes = getNotes();

		String Notes = applicationHeaderJournalCacheModel.Notes;

		if ((Notes != null) && (Notes.length() == 0)) {
			applicationHeaderJournalCacheModel.Notes = null;
		}

		applicationHeaderJournalCacheModel.NotesHistory = getNotesHistory();

		String NotesHistory = applicationHeaderJournalCacheModel.NotesHistory;

		if ((NotesHistory != null) && (NotesHistory.length() == 0)) {
			applicationHeaderJournalCacheModel.NotesHistory = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			applicationHeaderJournalCacheModel.RowStatus = RowStatus;
		}

		applicationHeaderJournalCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = applicationHeaderJournalCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			applicationHeaderJournalCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			applicationHeaderJournalCacheModel.CreatedDate =
				CreatedDate.getTime();
		}
		else {
			applicationHeaderJournalCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		applicationHeaderJournalCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = applicationHeaderJournalCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			applicationHeaderJournalCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			applicationHeaderJournalCacheModel.ModifiedDate =
				ModifiedDate.getTime();
		}
		else {
			applicationHeaderJournalCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		return applicationHeaderJournalCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ApplicationHeaderJournal, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ApplicationHeaderJournal, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApplicationHeaderJournal, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ApplicationHeaderJournal)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, ApplicationHeaderJournal>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						ApplicationHeaderJournal.class, ModelWrapper.class);

	}

	private int _Id;
	private int _ApplicationHeaderId;
	private int _ApplicationId;
	private int _ApplicationHeaderStatusId;
	private int _ApplicationCategoryId;
	private int _DealerId;
	private String _TicketNo;
	private String _TicketCode;
	private Date _ReqDate;
	private Integer _ReqYear;
	private Integer _ReqMonth;
	private String _ReqScreenName;
	private String _ReqName;
	private String _ReqEmail;
	private String _ReqCCEmail;
	private String _ReqPhone;
	private Integer _NominalPengajuan;
	private String _ReqDesc;
	private String _BusinessBenefit;
	private Long _FileId;
	private String _FileName;
	private String _FileUrl;
	private String _Notes;
	private String _NotesHistory;
	private Boolean _RowStatus;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<ApplicationHeaderJournal, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ApplicationHeaderJournal)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("ApplicationHeaderId", _ApplicationHeaderId);
		_columnOriginalValues.put("ApplicationId", _ApplicationId);
		_columnOriginalValues.put(
			"ApplicationHeaderStatusId", _ApplicationHeaderStatusId);
		_columnOriginalValues.put(
			"ApplicationCategoryId", _ApplicationCategoryId);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("TicketNo", _TicketNo);
		_columnOriginalValues.put("TicketCode", _TicketCode);
		_columnOriginalValues.put("ReqDate", _ReqDate);
		_columnOriginalValues.put("ReqYear", _ReqYear);
		_columnOriginalValues.put("ReqMonth", _ReqMonth);
		_columnOriginalValues.put("ReqScreenName", _ReqScreenName);
		_columnOriginalValues.put("ReqName", _ReqName);
		_columnOriginalValues.put("ReqEmail", _ReqEmail);
		_columnOriginalValues.put("ReqCCEmail", _ReqCCEmail);
		_columnOriginalValues.put("ReqPhone", _ReqPhone);
		_columnOriginalValues.put("NominalPengajuan", _NominalPengajuan);
		_columnOriginalValues.put("ReqDesc", _ReqDesc);
		_columnOriginalValues.put("BusinessBenefit", _BusinessBenefit);
		_columnOriginalValues.put("FileId", _FileId);
		_columnOriginalValues.put("FileName", _FileName);
		_columnOriginalValues.put("FileUrl", _FileUrl);
		_columnOriginalValues.put("Notes", _Notes);
		_columnOriginalValues.put("NotesHistory", _NotesHistory);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("ApplicationHeaderId", 2L);

		columnBitmasks.put("ApplicationId", 4L);

		columnBitmasks.put("ApplicationHeaderStatusId", 8L);

		columnBitmasks.put("ApplicationCategoryId", 16L);

		columnBitmasks.put("DealerId", 32L);

		columnBitmasks.put("TicketNo", 64L);

		columnBitmasks.put("TicketCode", 128L);

		columnBitmasks.put("ReqDate", 256L);

		columnBitmasks.put("ReqYear", 512L);

		columnBitmasks.put("ReqMonth", 1024L);

		columnBitmasks.put("ReqScreenName", 2048L);

		columnBitmasks.put("ReqName", 4096L);

		columnBitmasks.put("ReqEmail", 8192L);

		columnBitmasks.put("ReqCCEmail", 16384L);

		columnBitmasks.put("ReqPhone", 32768L);

		columnBitmasks.put("NominalPengajuan", 65536L);

		columnBitmasks.put("ReqDesc", 131072L);

		columnBitmasks.put("BusinessBenefit", 262144L);

		columnBitmasks.put("FileId", 524288L);

		columnBitmasks.put("FileName", 1048576L);

		columnBitmasks.put("FileUrl", 2097152L);

		columnBitmasks.put("Notes", 4194304L);

		columnBitmasks.put("NotesHistory", 8388608L);

		columnBitmasks.put("RowStatus", 16777216L);

		columnBitmasks.put("CreatedBy", 33554432L);

		columnBitmasks.put("CreatedDate", 67108864L);

		columnBitmasks.put("ModifiedBy", 134217728L);

		columnBitmasks.put("ModifiedDate", 268435456L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ApplicationHeaderJournal _escapedModel;

}