/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.ApprovalHistoryUser;
import com.astra.dewa.model.ApprovalHistoryUserModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ApprovalHistoryUser service. Represents a row in the &quot;ApprovalHistoryUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ApprovalHistoryUserModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApprovalHistoryUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApprovalHistoryUserImpl
 * @generated
 */
public class ApprovalHistoryUserModelImpl
	extends BaseModelImpl<ApprovalHistoryUser>
	implements ApprovalHistoryUserModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a approval history user model instance should use the <code>ApprovalHistoryUser</code> interface instead.
	 */
	public static final String TABLE_NAME = "ApprovalHistoryUser";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"ApprovalHeaderUserId", Types.INTEGER},
		{"ApplicationAssignStatusId", Types.INTEGER},
		{"ApproverUserId", Types.BIGINT}, {"DealerId", Types.INTEGER},
		{"CabangId", Types.INTEGER}, {"RequesterName", Types.VARCHAR},
		{"RequesterEmail", Types.VARCHAR}, {"RejectReason", Types.VARCHAR},
		{"RowStatus", Types.BOOLEAN}, {"CreatedBy", Types.VARCHAR},
		{"CreatedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApprovalHeaderUserId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApplicationAssignStatusId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApproverUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("CabangId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("RequesterName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RequesterEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RejectReason", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ApprovalHistoryUser (Id INTEGER not null primary key IDENTITY,ApprovalHeaderUserId INTEGER,ApplicationAssignStatusId INTEGER,ApproverUserId LONG,DealerId INTEGER,CabangId INTEGER,RequesterName VARCHAR(75) null,RequesterEmail VARCHAR(75) null,RejectReason VARCHAR(75) null,RowStatus BOOLEAN,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table ApprovalHistoryUser";

	public static final String ORDER_BY_JPQL =
		" ORDER BY approvalHistoryUser.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ApprovalHistoryUser.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ApprovalHistoryUserModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ApprovalHistoryUser.class;
	}

	@Override
	public String getModelClassName() {
		return ApprovalHistoryUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ApprovalHistoryUser, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ApprovalHistoryUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApprovalHistoryUser, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ApprovalHistoryUser)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ApprovalHistoryUser, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ApprovalHistoryUser, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ApprovalHistoryUser)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ApprovalHistoryUser, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ApprovalHistoryUser, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ApprovalHistoryUser, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ApprovalHistoryUser, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ApprovalHistoryUser, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ApprovalHistoryUser, Object>>();
		Map<String, BiConsumer<ApprovalHistoryUser, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ApprovalHistoryUser, ?>>();

		attributeGetterFunctions.put("Id", ApprovalHistoryUser::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<ApprovalHistoryUser, Integer>)
				ApprovalHistoryUser::setId);
		attributeGetterFunctions.put(
			"ApprovalHeaderUserId",
			ApprovalHistoryUser::getApprovalHeaderUserId);
		attributeSetterBiConsumers.put(
			"ApprovalHeaderUserId",
			(BiConsumer<ApprovalHistoryUser, Integer>)
				ApprovalHistoryUser::setApprovalHeaderUserId);
		attributeGetterFunctions.put(
			"ApplicationAssignStatusId",
			ApprovalHistoryUser::getApplicationAssignStatusId);
		attributeSetterBiConsumers.put(
			"ApplicationAssignStatusId",
			(BiConsumer<ApprovalHistoryUser, Integer>)
				ApprovalHistoryUser::setApplicationAssignStatusId);
		attributeGetterFunctions.put(
			"ApproverUserId", ApprovalHistoryUser::getApproverUserId);
		attributeSetterBiConsumers.put(
			"ApproverUserId",
			(BiConsumer<ApprovalHistoryUser, Long>)
				ApprovalHistoryUser::setApproverUserId);
		attributeGetterFunctions.put(
			"DealerId", ApprovalHistoryUser::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId",
			(BiConsumer<ApprovalHistoryUser, Integer>)
				ApprovalHistoryUser::setDealerId);
		attributeGetterFunctions.put(
			"CabangId", ApprovalHistoryUser::getCabangId);
		attributeSetterBiConsumers.put(
			"CabangId",
			(BiConsumer<ApprovalHistoryUser, Integer>)
				ApprovalHistoryUser::setCabangId);
		attributeGetterFunctions.put(
			"RequesterName", ApprovalHistoryUser::getRequesterName);
		attributeSetterBiConsumers.put(
			"RequesterName",
			(BiConsumer<ApprovalHistoryUser, String>)
				ApprovalHistoryUser::setRequesterName);
		attributeGetterFunctions.put(
			"RequesterEmail", ApprovalHistoryUser::getRequesterEmail);
		attributeSetterBiConsumers.put(
			"RequesterEmail",
			(BiConsumer<ApprovalHistoryUser, String>)
				ApprovalHistoryUser::setRequesterEmail);
		attributeGetterFunctions.put(
			"RejectReason", ApprovalHistoryUser::getRejectReason);
		attributeSetterBiConsumers.put(
			"RejectReason",
			(BiConsumer<ApprovalHistoryUser, String>)
				ApprovalHistoryUser::setRejectReason);
		attributeGetterFunctions.put(
			"RowStatus", ApprovalHistoryUser::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<ApprovalHistoryUser, Boolean>)
				ApprovalHistoryUser::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedBy", ApprovalHistoryUser::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<ApprovalHistoryUser, String>)
				ApprovalHistoryUser::setCreatedBy);
		attributeGetterFunctions.put(
			"CreatedDate", ApprovalHistoryUser::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<ApprovalHistoryUser, Date>)
				ApprovalHistoryUser::setCreatedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", ApprovalHistoryUser::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<ApprovalHistoryUser, String>)
				ApprovalHistoryUser::setModifiedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", ApprovalHistoryUser::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<ApprovalHistoryUser, Date>)
				ApprovalHistoryUser::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getApprovalHeaderUserId() {
		return _ApprovalHeaderUserId;
	}

	@Override
	public void setApprovalHeaderUserId(int ApprovalHeaderUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApprovalHeaderUserId = ApprovalHeaderUserId;
	}

	@Override
	public int getApplicationAssignStatusId() {
		return _ApplicationAssignStatusId;
	}

	@Override
	public void setApplicationAssignStatusId(int ApplicationAssignStatusId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApplicationAssignStatusId = ApplicationAssignStatusId;
	}

	@Override
	public long getApproverUserId() {
		return _ApproverUserId;
	}

	@Override
	public void setApproverUserId(long ApproverUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApproverUserId = ApproverUserId;
	}

	@Override
	public String getApproverUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getApproverUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setApproverUserUuid(String ApproverUserUuid) {
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public int getCabangId() {
		return _CabangId;
	}

	@Override
	public void setCabangId(int CabangId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CabangId = CabangId;
	}

	@Override
	public String getRequesterName() {
		if (_RequesterName == null) {
			return "";
		}
		else {
			return _RequesterName;
		}
	}

	@Override
	public void setRequesterName(String RequesterName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RequesterName = RequesterName;
	}

	@Override
	public String getRequesterEmail() {
		if (_RequesterEmail == null) {
			return "";
		}
		else {
			return _RequesterEmail;
		}
	}

	@Override
	public void setRequesterEmail(String RequesterEmail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RequesterEmail = RequesterEmail;
	}

	@Override
	public String getRejectReason() {
		if (_RejectReason == null) {
			return "";
		}
		else {
			return _RejectReason;
		}
	}

	@Override
	public void setRejectReason(String RejectReason) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RejectReason = RejectReason;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ApprovalHistoryUser toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ApprovalHistoryUser>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ApprovalHistoryUserImpl approvalHistoryUserImpl =
			new ApprovalHistoryUserImpl();

		approvalHistoryUserImpl.setId(getId());
		approvalHistoryUserImpl.setApprovalHeaderUserId(
			getApprovalHeaderUserId());
		approvalHistoryUserImpl.setApplicationAssignStatusId(
			getApplicationAssignStatusId());
		approvalHistoryUserImpl.setApproverUserId(getApproverUserId());
		approvalHistoryUserImpl.setDealerId(getDealerId());
		approvalHistoryUserImpl.setCabangId(getCabangId());
		approvalHistoryUserImpl.setRequesterName(getRequesterName());
		approvalHistoryUserImpl.setRequesterEmail(getRequesterEmail());
		approvalHistoryUserImpl.setRejectReason(getRejectReason());
		approvalHistoryUserImpl.setRowStatus(getRowStatus());
		approvalHistoryUserImpl.setCreatedBy(getCreatedBy());
		approvalHistoryUserImpl.setCreatedDate(getCreatedDate());
		approvalHistoryUserImpl.setModifiedBy(getModifiedBy());
		approvalHistoryUserImpl.setModifiedDate(getModifiedDate());

		approvalHistoryUserImpl.resetOriginalValues();

		return approvalHistoryUserImpl;
	}

	@Override
	public ApprovalHistoryUser cloneWithOriginalValues() {
		ApprovalHistoryUserImpl approvalHistoryUserImpl =
			new ApprovalHistoryUserImpl();

		approvalHistoryUserImpl.setId(
			this.<Integer>getColumnOriginalValue("Id"));
		approvalHistoryUserImpl.setApprovalHeaderUserId(
			this.<Integer>getColumnOriginalValue("ApprovalHeaderUserId"));
		approvalHistoryUserImpl.setApplicationAssignStatusId(
			this.<Integer>getColumnOriginalValue("ApplicationAssignStatusId"));
		approvalHistoryUserImpl.setApproverUserId(
			this.<Long>getColumnOriginalValue("ApproverUserId"));
		approvalHistoryUserImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("DealerId"));
		approvalHistoryUserImpl.setCabangId(
			this.<Integer>getColumnOriginalValue("CabangId"));
		approvalHistoryUserImpl.setRequesterName(
			this.<String>getColumnOriginalValue("RequesterName"));
		approvalHistoryUserImpl.setRequesterEmail(
			this.<String>getColumnOriginalValue("RequesterEmail"));
		approvalHistoryUserImpl.setRejectReason(
			this.<String>getColumnOriginalValue("RejectReason"));
		approvalHistoryUserImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		approvalHistoryUserImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		approvalHistoryUserImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		approvalHistoryUserImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));
		approvalHistoryUserImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));

		return approvalHistoryUserImpl;
	}

	@Override
	public int compareTo(ApprovalHistoryUser approvalHistoryUser) {
		int primaryKey = approvalHistoryUser.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ApprovalHistoryUser)) {
			return false;
		}

		ApprovalHistoryUser approvalHistoryUser = (ApprovalHistoryUser)object;

		int primaryKey = approvalHistoryUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ApprovalHistoryUser> toCacheModel() {
		ApprovalHistoryUserCacheModel approvalHistoryUserCacheModel =
			new ApprovalHistoryUserCacheModel();

		approvalHistoryUserCacheModel.Id = getId();

		approvalHistoryUserCacheModel.ApprovalHeaderUserId =
			getApprovalHeaderUserId();

		approvalHistoryUserCacheModel.ApplicationAssignStatusId =
			getApplicationAssignStatusId();

		approvalHistoryUserCacheModel.ApproverUserId = getApproverUserId();

		approvalHistoryUserCacheModel.DealerId = getDealerId();

		approvalHistoryUserCacheModel.CabangId = getCabangId();

		approvalHistoryUserCacheModel.RequesterName = getRequesterName();

		String RequesterName = approvalHistoryUserCacheModel.RequesterName;

		if ((RequesterName != null) && (RequesterName.length() == 0)) {
			approvalHistoryUserCacheModel.RequesterName = null;
		}

		approvalHistoryUserCacheModel.RequesterEmail = getRequesterEmail();

		String RequesterEmail = approvalHistoryUserCacheModel.RequesterEmail;

		if ((RequesterEmail != null) && (RequesterEmail.length() == 0)) {
			approvalHistoryUserCacheModel.RequesterEmail = null;
		}

		approvalHistoryUserCacheModel.RejectReason = getRejectReason();

		String RejectReason = approvalHistoryUserCacheModel.RejectReason;

		if ((RejectReason != null) && (RejectReason.length() == 0)) {
			approvalHistoryUserCacheModel.RejectReason = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			approvalHistoryUserCacheModel.RowStatus = RowStatus;
		}

		approvalHistoryUserCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = approvalHistoryUserCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			approvalHistoryUserCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			approvalHistoryUserCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			approvalHistoryUserCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		approvalHistoryUserCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = approvalHistoryUserCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			approvalHistoryUserCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			approvalHistoryUserCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			approvalHistoryUserCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		return approvalHistoryUserCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ApprovalHistoryUser, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ApprovalHistoryUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApprovalHistoryUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ApprovalHistoryUser)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ApprovalHistoryUser>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ApprovalHistoryUser.class, ModelWrapper.class);

	}

	private int _Id;
	private int _ApprovalHeaderUserId;
	private int _ApplicationAssignStatusId;
	private long _ApproverUserId;
	private int _DealerId;
	private int _CabangId;
	private String _RequesterName;
	private String _RequesterEmail;
	private String _RejectReason;
	private Boolean _RowStatus;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<ApprovalHistoryUser, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ApprovalHistoryUser)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put(
			"ApprovalHeaderUserId", _ApprovalHeaderUserId);
		_columnOriginalValues.put(
			"ApplicationAssignStatusId", _ApplicationAssignStatusId);
		_columnOriginalValues.put("ApproverUserId", _ApproverUserId);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("CabangId", _CabangId);
		_columnOriginalValues.put("RequesterName", _RequesterName);
		_columnOriginalValues.put("RequesterEmail", _RequesterEmail);
		_columnOriginalValues.put("RejectReason", _RejectReason);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("ApprovalHeaderUserId", 2L);

		columnBitmasks.put("ApplicationAssignStatusId", 4L);

		columnBitmasks.put("ApproverUserId", 8L);

		columnBitmasks.put("DealerId", 16L);

		columnBitmasks.put("CabangId", 32L);

		columnBitmasks.put("RequesterName", 64L);

		columnBitmasks.put("RequesterEmail", 128L);

		columnBitmasks.put("RejectReason", 256L);

		columnBitmasks.put("RowStatus", 512L);

		columnBitmasks.put("CreatedBy", 1024L);

		columnBitmasks.put("CreatedDate", 2048L);

		columnBitmasks.put("ModifiedBy", 4096L);

		columnBitmasks.put("ModifiedDate", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ApprovalHistoryUser _escapedModel;

}