/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.ApprovalDetailUser;
import com.astra.dewa.model.ApprovalDetailUserModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ApprovalDetailUser service. Represents a row in the &quot;ApprovalDetailUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ApprovalDetailUserModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ApprovalDetailUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApprovalDetailUserImpl
 * @generated
 */
public class ApprovalDetailUserModelImpl
	extends BaseModelImpl<ApprovalDetailUser>
	implements ApprovalDetailUserModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a approval detail user model instance should use the <code>ApprovalDetailUser</code> interface instead.
	 */
	public static final String TABLE_NAME = "ApprovalDetailUser";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"ApprovalHeaderUserId", Types.INTEGER},
		{"RoleId", Types.INTEGER}, {"RowStatus", Types.BOOLEAN},
		{"CreatedBy", Types.VARCHAR}, {"CreatedDate", Types.TIMESTAMP},
		{"ModifiedBy", Types.VARCHAR}, {"ModifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApprovalHeaderUserId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("RoleId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ApprovalDetailUser (Id INTEGER not null primary key IDENTITY,ApprovalHeaderUserId INTEGER,RoleId INTEGER,RowStatus BOOLEAN,CreatedBy VARCHAR(75) null,CreatedDate DATE null,ModifiedBy VARCHAR(75) null,ModifiedDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table ApprovalDetailUser";

	public static final String ORDER_BY_JPQL =
		" ORDER BY approvalDetailUser.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ApprovalDetailUser.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long APPROVALHEADERUSERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ROWSTATUS_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ApprovalDetailUserModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ApprovalDetailUser.class;
	}

	@Override
	public String getModelClassName() {
		return ApprovalDetailUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ApprovalDetailUser, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ApprovalDetailUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApprovalDetailUser, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ApprovalDetailUser)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ApprovalDetailUser, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ApprovalDetailUser, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ApprovalDetailUser)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ApprovalDetailUser, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ApprovalDetailUser, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ApprovalDetailUser, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ApprovalDetailUser, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ApprovalDetailUser, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ApprovalDetailUser, Object>>();
		Map<String, BiConsumer<ApprovalDetailUser, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ApprovalDetailUser, ?>>();

		attributeGetterFunctions.put("Id", ApprovalDetailUser::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<ApprovalDetailUser, Integer>)ApprovalDetailUser::setId);
		attributeGetterFunctions.put(
			"ApprovalHeaderUserId",
			ApprovalDetailUser::getApprovalHeaderUserId);
		attributeSetterBiConsumers.put(
			"ApprovalHeaderUserId",
			(BiConsumer<ApprovalDetailUser, Integer>)
				ApprovalDetailUser::setApprovalHeaderUserId);
		attributeGetterFunctions.put("RoleId", ApprovalDetailUser::getRoleId);
		attributeSetterBiConsumers.put(
			"RoleId",
			(BiConsumer<ApprovalDetailUser, Integer>)
				ApprovalDetailUser::setRoleId);
		attributeGetterFunctions.put(
			"RowStatus", ApprovalDetailUser::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<ApprovalDetailUser, Boolean>)
				ApprovalDetailUser::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedBy", ApprovalDetailUser::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<ApprovalDetailUser, String>)
				ApprovalDetailUser::setCreatedBy);
		attributeGetterFunctions.put(
			"CreatedDate", ApprovalDetailUser::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<ApprovalDetailUser, Date>)
				ApprovalDetailUser::setCreatedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", ApprovalDetailUser::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<ApprovalDetailUser, String>)
				ApprovalDetailUser::setModifiedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", ApprovalDetailUser::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<ApprovalDetailUser, Date>)
				ApprovalDetailUser::setModifiedDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getApprovalHeaderUserId() {
		return _ApprovalHeaderUserId;
	}

	@Override
	public void setApprovalHeaderUserId(int ApprovalHeaderUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApprovalHeaderUserId = ApprovalHeaderUserId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalApprovalHeaderUserId() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("ApprovalHeaderUserId"));
	}

	@Override
	public int getRoleId() {
		return _RoleId;
	}

	@Override
	public void setRoleId(int RoleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RoleId = RoleId;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Boolean getOriginalRowStatus() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ApprovalDetailUser toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ApprovalDetailUser>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ApprovalDetailUserImpl approvalDetailUserImpl =
			new ApprovalDetailUserImpl();

		approvalDetailUserImpl.setId(getId());
		approvalDetailUserImpl.setApprovalHeaderUserId(
			getApprovalHeaderUserId());
		approvalDetailUserImpl.setRoleId(getRoleId());
		approvalDetailUserImpl.setRowStatus(getRowStatus());
		approvalDetailUserImpl.setCreatedBy(getCreatedBy());
		approvalDetailUserImpl.setCreatedDate(getCreatedDate());
		approvalDetailUserImpl.setModifiedBy(getModifiedBy());
		approvalDetailUserImpl.setModifiedDate(getModifiedDate());

		approvalDetailUserImpl.resetOriginalValues();

		return approvalDetailUserImpl;
	}

	@Override
	public ApprovalDetailUser cloneWithOriginalValues() {
		ApprovalDetailUserImpl approvalDetailUserImpl =
			new ApprovalDetailUserImpl();

		approvalDetailUserImpl.setId(
			this.<Integer>getColumnOriginalValue("Id"));
		approvalDetailUserImpl.setApprovalHeaderUserId(
			this.<Integer>getColumnOriginalValue("ApprovalHeaderUserId"));
		approvalDetailUserImpl.setRoleId(
			this.<Integer>getColumnOriginalValue("RoleId"));
		approvalDetailUserImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		approvalDetailUserImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		approvalDetailUserImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		approvalDetailUserImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));
		approvalDetailUserImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));

		return approvalDetailUserImpl;
	}

	@Override
	public int compareTo(ApprovalDetailUser approvalDetailUser) {
		int primaryKey = approvalDetailUser.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ApprovalDetailUser)) {
			return false;
		}

		ApprovalDetailUser approvalDetailUser = (ApprovalDetailUser)object;

		int primaryKey = approvalDetailUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ApprovalDetailUser> toCacheModel() {
		ApprovalDetailUserCacheModel approvalDetailUserCacheModel =
			new ApprovalDetailUserCacheModel();

		approvalDetailUserCacheModel.Id = getId();

		approvalDetailUserCacheModel.ApprovalHeaderUserId =
			getApprovalHeaderUserId();

		approvalDetailUserCacheModel.RoleId = getRoleId();

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			approvalDetailUserCacheModel.RowStatus = RowStatus;
		}

		approvalDetailUserCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = approvalDetailUserCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			approvalDetailUserCacheModel.CreatedBy = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			approvalDetailUserCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			approvalDetailUserCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		approvalDetailUserCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = approvalDetailUserCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			approvalDetailUserCacheModel.ModifiedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			approvalDetailUserCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			approvalDetailUserCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		return approvalDetailUserCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ApprovalDetailUser, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ApprovalDetailUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ApprovalDetailUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ApprovalDetailUser)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ApprovalDetailUser>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ApprovalDetailUser.class, ModelWrapper.class);

	}

	private int _Id;
	private int _ApprovalHeaderUserId;
	private int _RoleId;
	private Boolean _RowStatus;
	private String _CreatedBy;
	private Date _CreatedDate;
	private String _ModifiedBy;
	private Date _ModifiedDate;

	public <T> T getColumnValue(String columnName) {
		Function<ApprovalDetailUser, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ApprovalDetailUser)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put(
			"ApprovalHeaderUserId", _ApprovalHeaderUserId);
		_columnOriginalValues.put("RoleId", _RoleId);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("ApprovalHeaderUserId", 2L);

		columnBitmasks.put("RoleId", 4L);

		columnBitmasks.put("RowStatus", 8L);

		columnBitmasks.put("CreatedBy", 16L);

		columnBitmasks.put("CreatedDate", 32L);

		columnBitmasks.put("ModifiedBy", 64L);

		columnBitmasks.put("ModifiedDate", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ApprovalDetailUser _escapedModel;

}