/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.CalenderEvent;
import com.astra.dewa.model.CalenderEventModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CalenderEvent service. Represents a row in the &quot;calender_event&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CalenderEventModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CalenderEventImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CalenderEventImpl
 * @generated
 */
public class CalenderEventModelImpl
	extends BaseModelImpl<CalenderEvent> implements CalenderEventModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a calender event model instance should use the <code>CalenderEvent</code> interface instead.
	 */
	public static final String TABLE_NAME = "calender_event";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"JenisAcara", Types.INTEGER},
		{"StatusAcara", Types.INTEGER}, {"Judul", Types.VARCHAR},
		{"Location", Types.VARCHAR}, {"LinkMeeting", Types.VARCHAR},
		{"StartDate", Types.TIMESTAMP}, {"StartDateHours", Types.VARCHAR},
		{"EndDate", Types.TIMESTAMP}, {"EndDateHours", Types.VARCHAR},
		{"RegistrationLimitDate", Types.TIMESTAMP},
		{"RegistrationLimitDateHours", Types.VARCHAR},
		{"Deskripsi", Types.VARCHAR}, {"ImageId", Types.BIGINT},
		{"ImageName", Types.VARCHAR}, {"ImagePath", Types.VARCHAR},
		{"RowStatus", Types.BOOLEAN}, {"CreatedDate", Types.TIMESTAMP},
		{"CreatedBy", Types.VARCHAR}, {"ModifiedDate", Types.TIMESTAMP},
		{"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("JenisAcara", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("StatusAcara", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Judul", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Location", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("LinkMeeting", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("StartDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("StartDateHours", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("EndDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("EndDateHours", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RegistrationLimitDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("RegistrationLimitDateHours", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Deskripsi", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ImageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ImageName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ImagePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table calender_event (Id INTEGER not null primary key IDENTITY,JenisAcara INTEGER,StatusAcara INTEGER,Judul VARCHAR(75) null,Location VARCHAR(75) null,LinkMeeting VARCHAR(75) null,StartDate DATE null,StartDateHours VARCHAR(75) null,EndDate DATE null,EndDateHours VARCHAR(75) null,RegistrationLimitDate DATE null,RegistrationLimitDateHours VARCHAR(75) null,Deskripsi VARCHAR(75) null,ImageId LONG,ImageName VARCHAR(75) null,ImagePath VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table calender_event";

	public static final String ORDER_BY_JPQL = " ORDER BY calenderEvent.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY calender_event.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CalenderEventModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CalenderEvent.class;
	}

	@Override
	public String getModelClassName() {
		return CalenderEvent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CalenderEvent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CalenderEvent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CalenderEvent, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CalenderEvent)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CalenderEvent, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CalenderEvent, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CalenderEvent)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CalenderEvent, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CalenderEvent, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<CalenderEvent, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CalenderEvent, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CalenderEvent, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CalenderEvent, Object>>();
		Map<String, BiConsumer<CalenderEvent, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CalenderEvent, ?>>();

		attributeGetterFunctions.put("Id", CalenderEvent::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<CalenderEvent, Integer>)CalenderEvent::setId);
		attributeGetterFunctions.put(
			"JenisAcara", CalenderEvent::getJenisAcara);
		attributeSetterBiConsumers.put(
			"JenisAcara",
			(BiConsumer<CalenderEvent, Integer>)CalenderEvent::setJenisAcara);
		attributeGetterFunctions.put(
			"StatusAcara", CalenderEvent::getStatusAcara);
		attributeSetterBiConsumers.put(
			"StatusAcara",
			(BiConsumer<CalenderEvent, Integer>)CalenderEvent::setStatusAcara);
		attributeGetterFunctions.put("Judul", CalenderEvent::getJudul);
		attributeSetterBiConsumers.put(
			"Judul",
			(BiConsumer<CalenderEvent, String>)CalenderEvent::setJudul);
		attributeGetterFunctions.put("Location", CalenderEvent::getLocation);
		attributeSetterBiConsumers.put(
			"Location",
			(BiConsumer<CalenderEvent, String>)CalenderEvent::setLocation);
		attributeGetterFunctions.put(
			"LinkMeeting", CalenderEvent::getLinkMeeting);
		attributeSetterBiConsumers.put(
			"LinkMeeting",
			(BiConsumer<CalenderEvent, String>)CalenderEvent::setLinkMeeting);
		attributeGetterFunctions.put("StartDate", CalenderEvent::getStartDate);
		attributeSetterBiConsumers.put(
			"StartDate",
			(BiConsumer<CalenderEvent, Date>)CalenderEvent::setStartDate);
		attributeGetterFunctions.put(
			"StartDateHours", CalenderEvent::getStartDateHours);
		attributeSetterBiConsumers.put(
			"StartDateHours",
			(BiConsumer<CalenderEvent, String>)
				CalenderEvent::setStartDateHours);
		attributeGetterFunctions.put("EndDate", CalenderEvent::getEndDate);
		attributeSetterBiConsumers.put(
			"EndDate",
			(BiConsumer<CalenderEvent, Date>)CalenderEvent::setEndDate);
		attributeGetterFunctions.put(
			"EndDateHours", CalenderEvent::getEndDateHours);
		attributeSetterBiConsumers.put(
			"EndDateHours",
			(BiConsumer<CalenderEvent, String>)CalenderEvent::setEndDateHours);
		attributeGetterFunctions.put(
			"RegistrationLimitDate", CalenderEvent::getRegistrationLimitDate);
		attributeSetterBiConsumers.put(
			"RegistrationLimitDate",
			(BiConsumer<CalenderEvent, Date>)
				CalenderEvent::setRegistrationLimitDate);
		attributeGetterFunctions.put(
			"RegistrationLimitDateHours",
			CalenderEvent::getRegistrationLimitDateHours);
		attributeSetterBiConsumers.put(
			"RegistrationLimitDateHours",
			(BiConsumer<CalenderEvent, String>)
				CalenderEvent::setRegistrationLimitDateHours);
		attributeGetterFunctions.put("Deskripsi", CalenderEvent::getDeskripsi);
		attributeSetterBiConsumers.put(
			"Deskripsi",
			(BiConsumer<CalenderEvent, String>)CalenderEvent::setDeskripsi);
		attributeGetterFunctions.put("ImageId", CalenderEvent::getImageId);
		attributeSetterBiConsumers.put(
			"ImageId",
			(BiConsumer<CalenderEvent, Long>)CalenderEvent::setImageId);
		attributeGetterFunctions.put("ImageName", CalenderEvent::getImageName);
		attributeSetterBiConsumers.put(
			"ImageName",
			(BiConsumer<CalenderEvent, String>)CalenderEvent::setImageName);
		attributeGetterFunctions.put("ImagePath", CalenderEvent::getImagePath);
		attributeSetterBiConsumers.put(
			"ImagePath",
			(BiConsumer<CalenderEvent, String>)CalenderEvent::setImagePath);
		attributeGetterFunctions.put("RowStatus", CalenderEvent::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<CalenderEvent, Boolean>)CalenderEvent::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", CalenderEvent::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<CalenderEvent, Date>)CalenderEvent::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", CalenderEvent::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<CalenderEvent, String>)CalenderEvent::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", CalenderEvent::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<CalenderEvent, Date>)CalenderEvent::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", CalenderEvent::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<CalenderEvent, String>)CalenderEvent::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getJenisAcara() {
		return _JenisAcara;
	}

	@Override
	public void setJenisAcara(int JenisAcara) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_JenisAcara = JenisAcara;
	}

	@Override
	public int getStatusAcara() {
		return _StatusAcara;
	}

	@Override
	public void setStatusAcara(int StatusAcara) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_StatusAcara = StatusAcara;
	}

	@Override
	public String getJudul() {
		if (_Judul == null) {
			return "";
		}
		else {
			return _Judul;
		}
	}

	@Override
	public void setJudul(String Judul) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Judul = Judul;
	}

	@Override
	public String getLocation() {
		if (_Location == null) {
			return "";
		}
		else {
			return _Location;
		}
	}

	@Override
	public void setLocation(String Location) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Location = Location;
	}

	@Override
	public String getLinkMeeting() {
		if (_LinkMeeting == null) {
			return "";
		}
		else {
			return _LinkMeeting;
		}
	}

	@Override
	public void setLinkMeeting(String LinkMeeting) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_LinkMeeting = LinkMeeting;
	}

	@Override
	public Date getStartDate() {
		return _StartDate;
	}

	@Override
	public void setStartDate(Date StartDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_StartDate = StartDate;
	}

	@Override
	public String getStartDateHours() {
		if (_StartDateHours == null) {
			return "";
		}
		else {
			return _StartDateHours;
		}
	}

	@Override
	public void setStartDateHours(String StartDateHours) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_StartDateHours = StartDateHours;
	}

	@Override
	public Date getEndDate() {
		return _EndDate;
	}

	@Override
	public void setEndDate(Date EndDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_EndDate = EndDate;
	}

	@Override
	public String getEndDateHours() {
		if (_EndDateHours == null) {
			return "";
		}
		else {
			return _EndDateHours;
		}
	}

	@Override
	public void setEndDateHours(String EndDateHours) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_EndDateHours = EndDateHours;
	}

	@Override
	public Date getRegistrationLimitDate() {
		return _RegistrationLimitDate;
	}

	@Override
	public void setRegistrationLimitDate(Date RegistrationLimitDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RegistrationLimitDate = RegistrationLimitDate;
	}

	@Override
	public String getRegistrationLimitDateHours() {
		if (_RegistrationLimitDateHours == null) {
			return "";
		}
		else {
			return _RegistrationLimitDateHours;
		}
	}

	@Override
	public void setRegistrationLimitDateHours(
		String RegistrationLimitDateHours) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RegistrationLimitDateHours = RegistrationLimitDateHours;
	}

	@Override
	public String getDeskripsi() {
		if (_Deskripsi == null) {
			return "";
		}
		else {
			return _Deskripsi;
		}
	}

	@Override
	public void setDeskripsi(String Deskripsi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Deskripsi = Deskripsi;
	}

	@Override
	public Long getImageId() {
		return _ImageId;
	}

	@Override
	public void setImageId(Long ImageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ImageId = ImageId;
	}

	@Override
	public String getImageName() {
		if (_ImageName == null) {
			return "";
		}
		else {
			return _ImageName;
		}
	}

	@Override
	public void setImageName(String ImageName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ImageName = ImageName;
	}

	@Override
	public String getImagePath() {
		if (_ImagePath == null) {
			return "";
		}
		else {
			return _ImagePath;
		}
	}

	@Override
	public void setImagePath(String ImagePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ImagePath = ImagePath;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public CalenderEvent toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CalenderEvent>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CalenderEventImpl calenderEventImpl = new CalenderEventImpl();

		calenderEventImpl.setId(getId());
		calenderEventImpl.setJenisAcara(getJenisAcara());
		calenderEventImpl.setStatusAcara(getStatusAcara());
		calenderEventImpl.setJudul(getJudul());
		calenderEventImpl.setLocation(getLocation());
		calenderEventImpl.setLinkMeeting(getLinkMeeting());
		calenderEventImpl.setStartDate(getStartDate());
		calenderEventImpl.setStartDateHours(getStartDateHours());
		calenderEventImpl.setEndDate(getEndDate());
		calenderEventImpl.setEndDateHours(getEndDateHours());
		calenderEventImpl.setRegistrationLimitDate(getRegistrationLimitDate());
		calenderEventImpl.setRegistrationLimitDateHours(
			getRegistrationLimitDateHours());
		calenderEventImpl.setDeskripsi(getDeskripsi());
		calenderEventImpl.setImageId(getImageId());
		calenderEventImpl.setImageName(getImageName());
		calenderEventImpl.setImagePath(getImagePath());
		calenderEventImpl.setRowStatus(getRowStatus());
		calenderEventImpl.setCreatedDate(getCreatedDate());
		calenderEventImpl.setCreatedBy(getCreatedBy());
		calenderEventImpl.setModifiedDate(getModifiedDate());
		calenderEventImpl.setModifiedBy(getModifiedBy());

		calenderEventImpl.resetOriginalValues();

		return calenderEventImpl;
	}

	@Override
	public CalenderEvent cloneWithOriginalValues() {
		CalenderEventImpl calenderEventImpl = new CalenderEventImpl();

		calenderEventImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		calenderEventImpl.setJenisAcara(
			this.<Integer>getColumnOriginalValue("JenisAcara"));
		calenderEventImpl.setStatusAcara(
			this.<Integer>getColumnOriginalValue("StatusAcara"));
		calenderEventImpl.setJudul(
			this.<String>getColumnOriginalValue("Judul"));
		calenderEventImpl.setLocation(
			this.<String>getColumnOriginalValue("Location"));
		calenderEventImpl.setLinkMeeting(
			this.<String>getColumnOriginalValue("LinkMeeting"));
		calenderEventImpl.setStartDate(
			this.<Date>getColumnOriginalValue("StartDate"));
		calenderEventImpl.setStartDateHours(
			this.<String>getColumnOriginalValue("StartDateHours"));
		calenderEventImpl.setEndDate(
			this.<Date>getColumnOriginalValue("EndDate"));
		calenderEventImpl.setEndDateHours(
			this.<String>getColumnOriginalValue("EndDateHours"));
		calenderEventImpl.setRegistrationLimitDate(
			this.<Date>getColumnOriginalValue("RegistrationLimitDate"));
		calenderEventImpl.setRegistrationLimitDateHours(
			this.<String>getColumnOriginalValue("RegistrationLimitDateHours"));
		calenderEventImpl.setDeskripsi(
			this.<String>getColumnOriginalValue("Deskripsi"));
		calenderEventImpl.setImageId(
			this.<Long>getColumnOriginalValue("ImageId"));
		calenderEventImpl.setImageName(
			this.<String>getColumnOriginalValue("ImageName"));
		calenderEventImpl.setImagePath(
			this.<String>getColumnOriginalValue("ImagePath"));
		calenderEventImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		calenderEventImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		calenderEventImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		calenderEventImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		calenderEventImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return calenderEventImpl;
	}

	@Override
	public int compareTo(CalenderEvent calenderEvent) {
		int primaryKey = calenderEvent.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CalenderEvent)) {
			return false;
		}

		CalenderEvent calenderEvent = (CalenderEvent)object;

		int primaryKey = calenderEvent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CalenderEvent> toCacheModel() {
		CalenderEventCacheModel calenderEventCacheModel =
			new CalenderEventCacheModel();

		calenderEventCacheModel.Id = getId();

		calenderEventCacheModel.JenisAcara = getJenisAcara();

		calenderEventCacheModel.StatusAcara = getStatusAcara();

		calenderEventCacheModel.Judul = getJudul();

		String Judul = calenderEventCacheModel.Judul;

		if ((Judul != null) && (Judul.length() == 0)) {
			calenderEventCacheModel.Judul = null;
		}

		calenderEventCacheModel.Location = getLocation();

		String Location = calenderEventCacheModel.Location;

		if ((Location != null) && (Location.length() == 0)) {
			calenderEventCacheModel.Location = null;
		}

		calenderEventCacheModel.LinkMeeting = getLinkMeeting();

		String LinkMeeting = calenderEventCacheModel.LinkMeeting;

		if ((LinkMeeting != null) && (LinkMeeting.length() == 0)) {
			calenderEventCacheModel.LinkMeeting = null;
		}

		Date StartDate = getStartDate();

		if (StartDate != null) {
			calenderEventCacheModel.StartDate = StartDate.getTime();
		}
		else {
			calenderEventCacheModel.StartDate = Long.MIN_VALUE;
		}

		calenderEventCacheModel.StartDateHours = getStartDateHours();

		String StartDateHours = calenderEventCacheModel.StartDateHours;

		if ((StartDateHours != null) && (StartDateHours.length() == 0)) {
			calenderEventCacheModel.StartDateHours = null;
		}

		Date EndDate = getEndDate();

		if (EndDate != null) {
			calenderEventCacheModel.EndDate = EndDate.getTime();
		}
		else {
			calenderEventCacheModel.EndDate = Long.MIN_VALUE;
		}

		calenderEventCacheModel.EndDateHours = getEndDateHours();

		String EndDateHours = calenderEventCacheModel.EndDateHours;

		if ((EndDateHours != null) && (EndDateHours.length() == 0)) {
			calenderEventCacheModel.EndDateHours = null;
		}

		Date RegistrationLimitDate = getRegistrationLimitDate();

		if (RegistrationLimitDate != null) {
			calenderEventCacheModel.RegistrationLimitDate =
				RegistrationLimitDate.getTime();
		}
		else {
			calenderEventCacheModel.RegistrationLimitDate = Long.MIN_VALUE;
		}

		calenderEventCacheModel.RegistrationLimitDateHours =
			getRegistrationLimitDateHours();

		String RegistrationLimitDateHours =
			calenderEventCacheModel.RegistrationLimitDateHours;

		if ((RegistrationLimitDateHours != null) &&
			(RegistrationLimitDateHours.length() == 0)) {

			calenderEventCacheModel.RegistrationLimitDateHours = null;
		}

		calenderEventCacheModel.Deskripsi = getDeskripsi();

		String Deskripsi = calenderEventCacheModel.Deskripsi;

		if ((Deskripsi != null) && (Deskripsi.length() == 0)) {
			calenderEventCacheModel.Deskripsi = null;
		}

		Long ImageId = getImageId();

		if (ImageId != null) {
			calenderEventCacheModel.ImageId = ImageId;
		}

		calenderEventCacheModel.ImageName = getImageName();

		String ImageName = calenderEventCacheModel.ImageName;

		if ((ImageName != null) && (ImageName.length() == 0)) {
			calenderEventCacheModel.ImageName = null;
		}

		calenderEventCacheModel.ImagePath = getImagePath();

		String ImagePath = calenderEventCacheModel.ImagePath;

		if ((ImagePath != null) && (ImagePath.length() == 0)) {
			calenderEventCacheModel.ImagePath = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			calenderEventCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			calenderEventCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			calenderEventCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		calenderEventCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = calenderEventCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			calenderEventCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			calenderEventCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			calenderEventCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		calenderEventCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = calenderEventCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			calenderEventCacheModel.ModifiedBy = null;
		}

		return calenderEventCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CalenderEvent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CalenderEvent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CalenderEvent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((CalenderEvent)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CalenderEvent>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CalenderEvent.class, ModelWrapper.class);

	}

	private int _Id;
	private int _JenisAcara;
	private int _StatusAcara;
	private String _Judul;
	private String _Location;
	private String _LinkMeeting;
	private Date _StartDate;
	private String _StartDateHours;
	private Date _EndDate;
	private String _EndDateHours;
	private Date _RegistrationLimitDate;
	private String _RegistrationLimitDateHours;
	private String _Deskripsi;
	private Long _ImageId;
	private String _ImageName;
	private String _ImagePath;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<CalenderEvent, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CalenderEvent)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("JenisAcara", _JenisAcara);
		_columnOriginalValues.put("StatusAcara", _StatusAcara);
		_columnOriginalValues.put("Judul", _Judul);
		_columnOriginalValues.put("Location", _Location);
		_columnOriginalValues.put("LinkMeeting", _LinkMeeting);
		_columnOriginalValues.put("StartDate", _StartDate);
		_columnOriginalValues.put("StartDateHours", _StartDateHours);
		_columnOriginalValues.put("EndDate", _EndDate);
		_columnOriginalValues.put("EndDateHours", _EndDateHours);
		_columnOriginalValues.put(
			"RegistrationLimitDate", _RegistrationLimitDate);
		_columnOriginalValues.put(
			"RegistrationLimitDateHours", _RegistrationLimitDateHours);
		_columnOriginalValues.put("Deskripsi", _Deskripsi);
		_columnOriginalValues.put("ImageId", _ImageId);
		_columnOriginalValues.put("ImageName", _ImageName);
		_columnOriginalValues.put("ImagePath", _ImagePath);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("JenisAcara", 2L);

		columnBitmasks.put("StatusAcara", 4L);

		columnBitmasks.put("Judul", 8L);

		columnBitmasks.put("Location", 16L);

		columnBitmasks.put("LinkMeeting", 32L);

		columnBitmasks.put("StartDate", 64L);

		columnBitmasks.put("StartDateHours", 128L);

		columnBitmasks.put("EndDate", 256L);

		columnBitmasks.put("EndDateHours", 512L);

		columnBitmasks.put("RegistrationLimitDate", 1024L);

		columnBitmasks.put("RegistrationLimitDateHours", 2048L);

		columnBitmasks.put("Deskripsi", 4096L);

		columnBitmasks.put("ImageId", 8192L);

		columnBitmasks.put("ImageName", 16384L);

		columnBitmasks.put("ImagePath", 32768L);

		columnBitmasks.put("RowStatus", 65536L);

		columnBitmasks.put("CreatedDate", 131072L);

		columnBitmasks.put("CreatedBy", 262144L);

		columnBitmasks.put("ModifiedDate", 524288L);

		columnBitmasks.put("ModifiedBy", 1048576L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CalenderEvent _escapedModel;

}