/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.Dealer;
import com.astra.dewa.model.DealerModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Dealer service. Represents a row in the &quot;Dealer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DealerModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DealerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DealerImpl
 * @generated
 */
public class DealerModelImpl
	extends BaseModelImpl<Dealer> implements DealerModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dealer model instance should use the <code>Dealer</code> interface instead.
	 */
	public static final String TABLE_NAME = "Dealer";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"CabangId", Types.INTEGER},
		{"WilayahId", Types.INTEGER}, {"GroupDealer", Types.INTEGER},
		{"Name", Types.VARCHAR}, {"Code", Types.VARCHAR},
		{"KodeHo", Types.VARCHAR}, {"RowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("CabangId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("WilayahId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("GroupDealer", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("KodeHo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Dealer (Id INTEGER not null primary key IDENTITY,CabangId INTEGER,WilayahId INTEGER,GroupDealer INTEGER,Name VARCHAR(75) null,Code VARCHAR(75) null,KodeHo VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table Dealer";

	public static final String ORDER_BY_JPQL = " ORDER BY dealer.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY Dealer.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DealerModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Dealer.class;
	}

	@Override
	public String getModelClassName() {
		return Dealer.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Dealer, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Dealer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Dealer, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Dealer)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Dealer, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Dealer, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Dealer)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Dealer, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Dealer, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Dealer, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Dealer, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Dealer, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Dealer, Object>>();
		Map<String, BiConsumer<Dealer, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Dealer, ?>>();

		attributeGetterFunctions.put("Id", Dealer::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<Dealer, Integer>)Dealer::setId);
		attributeGetterFunctions.put("CabangId", Dealer::getCabangId);
		attributeSetterBiConsumers.put(
			"CabangId", (BiConsumer<Dealer, Integer>)Dealer::setCabangId);
		attributeGetterFunctions.put("WilayahId", Dealer::getWilayahId);
		attributeSetterBiConsumers.put(
			"WilayahId", (BiConsumer<Dealer, Integer>)Dealer::setWilayahId);
		attributeGetterFunctions.put("GroupDealer", Dealer::getGroupDealer);
		attributeSetterBiConsumers.put(
			"GroupDealer", (BiConsumer<Dealer, Integer>)Dealer::setGroupDealer);
		attributeGetterFunctions.put("Name", Dealer::getName);
		attributeSetterBiConsumers.put(
			"Name", (BiConsumer<Dealer, String>)Dealer::setName);
		attributeGetterFunctions.put("Code", Dealer::getCode);
		attributeSetterBiConsumers.put(
			"Code", (BiConsumer<Dealer, String>)Dealer::setCode);
		attributeGetterFunctions.put("KodeHo", Dealer::getKodeHo);
		attributeSetterBiConsumers.put(
			"KodeHo", (BiConsumer<Dealer, String>)Dealer::setKodeHo);
		attributeGetterFunctions.put("RowStatus", Dealer::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus", (BiConsumer<Dealer, Boolean>)Dealer::setRowStatus);
		attributeGetterFunctions.put("CreatedDate", Dealer::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate", (BiConsumer<Dealer, Date>)Dealer::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", Dealer::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy", (BiConsumer<Dealer, String>)Dealer::setCreatedBy);
		attributeGetterFunctions.put("ModifiedDate", Dealer::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate", (BiConsumer<Dealer, Date>)Dealer::setModifiedDate);
		attributeGetterFunctions.put("ModifiedBy", Dealer::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy", (BiConsumer<Dealer, String>)Dealer::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getCabangId() {
		return _CabangId;
	}

	@Override
	public void setCabangId(int CabangId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CabangId = CabangId;
	}

	@Override
	public int getWilayahId() {
		return _WilayahId;
	}

	@Override
	public void setWilayahId(int WilayahId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_WilayahId = WilayahId;
	}

	@Override
	public int getGroupDealer() {
		return _GroupDealer;
	}

	@Override
	public void setGroupDealer(int GroupDealer) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_GroupDealer = GroupDealer;
	}

	@Override
	public String getName() {
		if (_Name == null) {
			return "";
		}
		else {
			return _Name;
		}
	}

	@Override
	public void setName(String Name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Name = Name;
	}

	@Override
	public String getCode() {
		if (_Code == null) {
			return "";
		}
		else {
			return _Code;
		}
	}

	@Override
	public void setCode(String Code) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Code = Code;
	}

	@Override
	public String getKodeHo() {
		if (_KodeHo == null) {
			return "";
		}
		else {
			return _KodeHo;
		}
	}

	@Override
	public void setKodeHo(String KodeHo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_KodeHo = KodeHo;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Dealer toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Dealer>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DealerImpl dealerImpl = new DealerImpl();

		dealerImpl.setId(getId());
		dealerImpl.setCabangId(getCabangId());
		dealerImpl.setWilayahId(getWilayahId());
		dealerImpl.setGroupDealer(getGroupDealer());
		dealerImpl.setName(getName());
		dealerImpl.setCode(getCode());
		dealerImpl.setKodeHo(getKodeHo());
		dealerImpl.setRowStatus(getRowStatus());
		dealerImpl.setCreatedDate(getCreatedDate());
		dealerImpl.setCreatedBy(getCreatedBy());
		dealerImpl.setModifiedDate(getModifiedDate());
		dealerImpl.setModifiedBy(getModifiedBy());

		dealerImpl.resetOriginalValues();

		return dealerImpl;
	}

	@Override
	public Dealer cloneWithOriginalValues() {
		DealerImpl dealerImpl = new DealerImpl();

		dealerImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		dealerImpl.setCabangId(
			this.<Integer>getColumnOriginalValue("CabangId"));
		dealerImpl.setWilayahId(
			this.<Integer>getColumnOriginalValue("WilayahId"));
		dealerImpl.setGroupDealer(
			this.<Integer>getColumnOriginalValue("GroupDealer"));
		dealerImpl.setName(this.<String>getColumnOriginalValue("Name"));
		dealerImpl.setCode(this.<String>getColumnOriginalValue("Code"));
		dealerImpl.setKodeHo(this.<String>getColumnOriginalValue("KodeHo"));
		dealerImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		dealerImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		dealerImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		dealerImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		dealerImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return dealerImpl;
	}

	@Override
	public int compareTo(Dealer dealer) {
		int primaryKey = dealer.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Dealer)) {
			return false;
		}

		Dealer dealer = (Dealer)object;

		int primaryKey = dealer.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Dealer> toCacheModel() {
		DealerCacheModel dealerCacheModel = new DealerCacheModel();

		dealerCacheModel.Id = getId();

		dealerCacheModel.CabangId = getCabangId();

		dealerCacheModel.WilayahId = getWilayahId();

		dealerCacheModel.GroupDealer = getGroupDealer();

		dealerCacheModel.Name = getName();

		String Name = dealerCacheModel.Name;

		if ((Name != null) && (Name.length() == 0)) {
			dealerCacheModel.Name = null;
		}

		dealerCacheModel.Code = getCode();

		String Code = dealerCacheModel.Code;

		if ((Code != null) && (Code.length() == 0)) {
			dealerCacheModel.Code = null;
		}

		dealerCacheModel.KodeHo = getKodeHo();

		String KodeHo = dealerCacheModel.KodeHo;

		if ((KodeHo != null) && (KodeHo.length() == 0)) {
			dealerCacheModel.KodeHo = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			dealerCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			dealerCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			dealerCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		dealerCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = dealerCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			dealerCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			dealerCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			dealerCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		dealerCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = dealerCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			dealerCacheModel.ModifiedBy = null;
		}

		return dealerCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Dealer, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Dealer, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Dealer, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Dealer)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Dealer>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Dealer.class, ModelWrapper.class);

	}

	private int _Id;
	private int _CabangId;
	private int _WilayahId;
	private int _GroupDealer;
	private String _Name;
	private String _Code;
	private String _KodeHo;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<Dealer, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Dealer)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("CabangId", _CabangId);
		_columnOriginalValues.put("WilayahId", _WilayahId);
		_columnOriginalValues.put("GroupDealer", _GroupDealer);
		_columnOriginalValues.put("Name", _Name);
		_columnOriginalValues.put("Code", _Code);
		_columnOriginalValues.put("KodeHo", _KodeHo);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("CabangId", 2L);

		columnBitmasks.put("WilayahId", 4L);

		columnBitmasks.put("GroupDealer", 8L);

		columnBitmasks.put("Name", 16L);

		columnBitmasks.put("Code", 32L);

		columnBitmasks.put("KodeHo", 64L);

		columnBitmasks.put("RowStatus", 128L);

		columnBitmasks.put("CreatedDate", 256L);

		columnBitmasks.put("CreatedBy", 512L);

		columnBitmasks.put("ModifiedDate", 1024L);

		columnBitmasks.put("ModifiedBy", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Dealer _escapedModel;

}