/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.DiskonTestCar;
import com.astra.dewa.model.DiskonTestCarModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DiskonTestCar service. Represents a row in the &quot;diskon_test_car&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DiskonTestCarModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DiskonTestCarImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DiskonTestCarImpl
 * @generated
 */
public class DiskonTestCarModelImpl
	extends BaseModelImpl<DiskonTestCar> implements DiskonTestCarModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a diskon test car model instance should use the <code>DiskonTestCar</code> interface instead.
	 */
	public static final String TABLE_NAME = "diskon_test_car";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"DealerId", Types.INTEGER},
		{"KuartalId", Types.VARCHAR}, {"TipeKendaraanId", Types.INTEGER},
		{"Tahun", Types.INTEGER}, {"Keterangan", Types.VARCHAR},
		{"FileId", Types.BIGINT}, {"FileName", Types.VARCHAR},
		{"FilePath", Types.VARCHAR}, {"RowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("KuartalId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("TipeKendaraanId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Tahun", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Keterangan", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FilePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table diskon_test_car (Id INTEGER not null primary key IDENTITY,DealerId INTEGER,KuartalId VARCHAR(75) null,TipeKendaraanId INTEGER,Tahun INTEGER,Keterangan VARCHAR(75) null,FileId LONG,FileName VARCHAR(75) null,FilePath VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table diskon_test_car";

	public static final String ORDER_BY_JPQL = " ORDER BY diskonTestCar.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY diskon_test_car.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DiskonTestCarModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DiskonTestCar.class;
	}

	@Override
	public String getModelClassName() {
		return DiskonTestCar.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DiskonTestCar, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DiskonTestCar, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DiskonTestCar, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DiskonTestCar)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DiskonTestCar, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DiskonTestCar, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DiskonTestCar)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DiskonTestCar, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DiskonTestCar, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<DiskonTestCar, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DiskonTestCar, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DiskonTestCar, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<DiskonTestCar, Object>>();
		Map<String, BiConsumer<DiskonTestCar, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DiskonTestCar, ?>>();

		attributeGetterFunctions.put("Id", DiskonTestCar::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<DiskonTestCar, Integer>)DiskonTestCar::setId);
		attributeGetterFunctions.put("DealerId", DiskonTestCar::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId",
			(BiConsumer<DiskonTestCar, Integer>)DiskonTestCar::setDealerId);
		attributeGetterFunctions.put("KuartalId", DiskonTestCar::getKuartalId);
		attributeSetterBiConsumers.put(
			"KuartalId",
			(BiConsumer<DiskonTestCar, String>)DiskonTestCar::setKuartalId);
		attributeGetterFunctions.put(
			"TipeKendaraanId", DiskonTestCar::getTipeKendaraanId);
		attributeSetterBiConsumers.put(
			"TipeKendaraanId",
			(BiConsumer<DiskonTestCar, Integer>)
				DiskonTestCar::setTipeKendaraanId);
		attributeGetterFunctions.put("Tahun", DiskonTestCar::getTahun);
		attributeSetterBiConsumers.put(
			"Tahun",
			(BiConsumer<DiskonTestCar, Integer>)DiskonTestCar::setTahun);
		attributeGetterFunctions.put(
			"Keterangan", DiskonTestCar::getKeterangan);
		attributeSetterBiConsumers.put(
			"Keterangan",
			(BiConsumer<DiskonTestCar, String>)DiskonTestCar::setKeterangan);
		attributeGetterFunctions.put("FileId", DiskonTestCar::getFileId);
		attributeSetterBiConsumers.put(
			"FileId",
			(BiConsumer<DiskonTestCar, Long>)DiskonTestCar::setFileId);
		attributeGetterFunctions.put("FileName", DiskonTestCar::getFileName);
		attributeSetterBiConsumers.put(
			"FileName",
			(BiConsumer<DiskonTestCar, String>)DiskonTestCar::setFileName);
		attributeGetterFunctions.put("FilePath", DiskonTestCar::getFilePath);
		attributeSetterBiConsumers.put(
			"FilePath",
			(BiConsumer<DiskonTestCar, String>)DiskonTestCar::setFilePath);
		attributeGetterFunctions.put("RowStatus", DiskonTestCar::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<DiskonTestCar, Boolean>)DiskonTestCar::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", DiskonTestCar::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<DiskonTestCar, Date>)DiskonTestCar::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", DiskonTestCar::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<DiskonTestCar, String>)DiskonTestCar::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", DiskonTestCar::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<DiskonTestCar, Date>)DiskonTestCar::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", DiskonTestCar::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<DiskonTestCar, String>)DiskonTestCar::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public String getKuartalId() {
		if (_KuartalId == null) {
			return "";
		}
		else {
			return _KuartalId;
		}
	}

	@Override
	public void setKuartalId(String KuartalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_KuartalId = KuartalId;
	}

	@Override
	public int getTipeKendaraanId() {
		return _TipeKendaraanId;
	}

	@Override
	public void setTipeKendaraanId(int TipeKendaraanId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TipeKendaraanId = TipeKendaraanId;
	}

	@Override
	public Integer getTahun() {
		return _Tahun;
	}

	@Override
	public void setTahun(Integer Tahun) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Tahun = Tahun;
	}

	@Override
	public String getKeterangan() {
		if (_Keterangan == null) {
			return "";
		}
		else {
			return _Keterangan;
		}
	}

	@Override
	public void setKeterangan(String Keterangan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Keterangan = Keterangan;
	}

	@Override
	public Long getFileId() {
		return _FileId;
	}

	@Override
	public void setFileId(Long FileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileId = FileId;
	}

	@Override
	public String getFileName() {
		if (_FileName == null) {
			return "";
		}
		else {
			return _FileName;
		}
	}

	@Override
	public void setFileName(String FileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileName = FileName;
	}

	@Override
	public String getFilePath() {
		if (_FilePath == null) {
			return "";
		}
		else {
			return _FilePath;
		}
	}

	@Override
	public void setFilePath(String FilePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FilePath = FilePath;
	}

	@Override
	public boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public boolean isRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public DiskonTestCar toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DiskonTestCar>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DiskonTestCarImpl diskonTestCarImpl = new DiskonTestCarImpl();

		diskonTestCarImpl.setId(getId());
		diskonTestCarImpl.setDealerId(getDealerId());
		diskonTestCarImpl.setKuartalId(getKuartalId());
		diskonTestCarImpl.setTipeKendaraanId(getTipeKendaraanId());
		diskonTestCarImpl.setTahun(getTahun());
		diskonTestCarImpl.setKeterangan(getKeterangan());
		diskonTestCarImpl.setFileId(getFileId());
		diskonTestCarImpl.setFileName(getFileName());
		diskonTestCarImpl.setFilePath(getFilePath());
		diskonTestCarImpl.setRowStatus(isRowStatus());
		diskonTestCarImpl.setCreatedDate(getCreatedDate());
		diskonTestCarImpl.setCreatedBy(getCreatedBy());
		diskonTestCarImpl.setModifiedDate(getModifiedDate());
		diskonTestCarImpl.setModifiedBy(getModifiedBy());

		diskonTestCarImpl.resetOriginalValues();

		return diskonTestCarImpl;
	}

	@Override
	public DiskonTestCar cloneWithOriginalValues() {
		DiskonTestCarImpl diskonTestCarImpl = new DiskonTestCarImpl();

		diskonTestCarImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		diskonTestCarImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("DealerId"));
		diskonTestCarImpl.setKuartalId(
			this.<String>getColumnOriginalValue("KuartalId"));
		diskonTestCarImpl.setTipeKendaraanId(
			this.<Integer>getColumnOriginalValue("TipeKendaraanId"));
		diskonTestCarImpl.setTahun(
			this.<Integer>getColumnOriginalValue("Tahun"));
		diskonTestCarImpl.setKeterangan(
			this.<String>getColumnOriginalValue("Keterangan"));
		diskonTestCarImpl.setFileId(
			this.<Long>getColumnOriginalValue("FileId"));
		diskonTestCarImpl.setFileName(
			this.<String>getColumnOriginalValue("FileName"));
		diskonTestCarImpl.setFilePath(
			this.<String>getColumnOriginalValue("FilePath"));
		diskonTestCarImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		diskonTestCarImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		diskonTestCarImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		diskonTestCarImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		diskonTestCarImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return diskonTestCarImpl;
	}

	@Override
	public int compareTo(DiskonTestCar diskonTestCar) {
		int primaryKey = diskonTestCar.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DiskonTestCar)) {
			return false;
		}

		DiskonTestCar diskonTestCar = (DiskonTestCar)object;

		int primaryKey = diskonTestCar.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DiskonTestCar> toCacheModel() {
		DiskonTestCarCacheModel diskonTestCarCacheModel =
			new DiskonTestCarCacheModel();

		diskonTestCarCacheModel.Id = getId();

		diskonTestCarCacheModel.DealerId = getDealerId();

		diskonTestCarCacheModel.KuartalId = getKuartalId();

		String KuartalId = diskonTestCarCacheModel.KuartalId;

		if ((KuartalId != null) && (KuartalId.length() == 0)) {
			diskonTestCarCacheModel.KuartalId = null;
		}

		diskonTestCarCacheModel.TipeKendaraanId = getTipeKendaraanId();

		Integer Tahun = getTahun();

		if (Tahun != null) {
			diskonTestCarCacheModel.Tahun = Tahun;
		}

		diskonTestCarCacheModel.Keterangan = getKeterangan();

		String Keterangan = diskonTestCarCacheModel.Keterangan;

		if ((Keterangan != null) && (Keterangan.length() == 0)) {
			diskonTestCarCacheModel.Keterangan = null;
		}

		Long FileId = getFileId();

		if (FileId != null) {
			diskonTestCarCacheModel.FileId = FileId;
		}

		diskonTestCarCacheModel.FileName = getFileName();

		String FileName = diskonTestCarCacheModel.FileName;

		if ((FileName != null) && (FileName.length() == 0)) {
			diskonTestCarCacheModel.FileName = null;
		}

		diskonTestCarCacheModel.FilePath = getFilePath();

		String FilePath = diskonTestCarCacheModel.FilePath;

		if ((FilePath != null) && (FilePath.length() == 0)) {
			diskonTestCarCacheModel.FilePath = null;
		}

		diskonTestCarCacheModel.RowStatus = isRowStatus();

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			diskonTestCarCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			diskonTestCarCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		diskonTestCarCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = diskonTestCarCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			diskonTestCarCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			diskonTestCarCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			diskonTestCarCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		diskonTestCarCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = diskonTestCarCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			diskonTestCarCacheModel.ModifiedBy = null;
		}

		return diskonTestCarCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DiskonTestCar, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DiskonTestCar, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DiskonTestCar, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((DiskonTestCar)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DiskonTestCar>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DiskonTestCar.class, ModelWrapper.class);

	}

	private int _Id;
	private int _DealerId;
	private String _KuartalId;
	private int _TipeKendaraanId;
	private Integer _Tahun;
	private String _Keterangan;
	private Long _FileId;
	private String _FileName;
	private String _FilePath;
	private boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<DiskonTestCar, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DiskonTestCar)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("KuartalId", _KuartalId);
		_columnOriginalValues.put("TipeKendaraanId", _TipeKendaraanId);
		_columnOriginalValues.put("Tahun", _Tahun);
		_columnOriginalValues.put("Keterangan", _Keterangan);
		_columnOriginalValues.put("FileId", _FileId);
		_columnOriginalValues.put("FileName", _FileName);
		_columnOriginalValues.put("FilePath", _FilePath);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("DealerId", 2L);

		columnBitmasks.put("KuartalId", 4L);

		columnBitmasks.put("TipeKendaraanId", 8L);

		columnBitmasks.put("Tahun", 16L);

		columnBitmasks.put("Keterangan", 32L);

		columnBitmasks.put("FileId", 64L);

		columnBitmasks.put("FileName", 128L);

		columnBitmasks.put("FilePath", 256L);

		columnBitmasks.put("RowStatus", 512L);

		columnBitmasks.put("CreatedDate", 1024L);

		columnBitmasks.put("CreatedBy", 2048L);

		columnBitmasks.put("ModifiedDate", 4096L);

		columnBitmasks.put("ModifiedBy", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DiskonTestCar _escapedModel;

}