/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.DiskonOther;
import com.astra.dewa.model.DiskonOtherModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DiskonOther service. Represents a row in the &quot;diskon_others&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DiskonOtherModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DiskonOtherImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DiskonOtherImpl
 * @generated
 */
public class DiskonOtherModelImpl
	extends BaseModelImpl<DiskonOther> implements DiskonOtherModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a diskon other model instance should use the <code>DiskonOther</code> interface instead.
	 */
	public static final String TABLE_NAME = "diskon_others";

	public static final Object[][] TABLE_COLUMNS = {
		{"diskonOtherId", Types.BIGINT}, {"dealerId", Types.INTEGER},
		{"tahun", Types.INTEGER}, {"kuartalId", Types.INTEGER},
		{"keterangan", Types.VARCHAR}, {"fileId", Types.BIGINT},
		{"fileName", Types.VARCHAR}, {"filePath", Types.VARCHAR},
		{"rowStatus", Types.BOOLEAN}, {"createdDate", Types.TIMESTAMP},
		{"createdBy", Types.VARCHAR}, {"modifiedDate", Types.TIMESTAMP},
		{"modifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("diskonOtherId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("tahun", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("kuartalId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("keterangan", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("filePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("rowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createdBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table diskon_others (diskonOtherId LONG not null primary key IDENTITY,dealerId INTEGER,tahun INTEGER,kuartalId INTEGER,keterangan VARCHAR(75) null,fileId LONG,fileName VARCHAR(75) null,filePath VARCHAR(75) null,rowStatus BOOLEAN,createdDate DATE null,createdBy VARCHAR(75) null,modifiedDate DATE null,modifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table diskon_others";

	public static final String ORDER_BY_JPQL =
		" ORDER BY diskonOther.diskonOtherId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY diskon_others.diskonOtherId ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DISKONOTHERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DiskonOtherModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _diskonOtherId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDiskonOtherId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _diskonOtherId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DiskonOther.class;
	}

	@Override
	public String getModelClassName() {
		return DiskonOther.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DiskonOther, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DiskonOther, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DiskonOther, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DiskonOther)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DiskonOther, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DiskonOther, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DiskonOther)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DiskonOther, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DiskonOther, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<DiskonOther, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DiskonOther, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DiskonOther, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<DiskonOther, Object>>();
		Map<String, BiConsumer<DiskonOther, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DiskonOther, ?>>();

		attributeGetterFunctions.put(
			"diskonOtherId", DiskonOther::getDiskonOtherId);
		attributeSetterBiConsumers.put(
			"diskonOtherId",
			(BiConsumer<DiskonOther, Long>)DiskonOther::setDiskonOtherId);
		attributeGetterFunctions.put("dealerId", DiskonOther::getDealerId);
		attributeSetterBiConsumers.put(
			"dealerId",
			(BiConsumer<DiskonOther, Integer>)DiskonOther::setDealerId);
		attributeGetterFunctions.put("tahun", DiskonOther::getTahun);
		attributeSetterBiConsumers.put(
			"tahun", (BiConsumer<DiskonOther, Integer>)DiskonOther::setTahun);
		attributeGetterFunctions.put("kuartalId", DiskonOther::getKuartalId);
		attributeSetterBiConsumers.put(
			"kuartalId",
			(BiConsumer<DiskonOther, Integer>)DiskonOther::setKuartalId);
		attributeGetterFunctions.put("keterangan", DiskonOther::getKeterangan);
		attributeSetterBiConsumers.put(
			"keterangan",
			(BiConsumer<DiskonOther, String>)DiskonOther::setKeterangan);
		attributeGetterFunctions.put("fileId", DiskonOther::getFileId);
		attributeSetterBiConsumers.put(
			"fileId", (BiConsumer<DiskonOther, Long>)DiskonOther::setFileId);
		attributeGetterFunctions.put("fileName", DiskonOther::getFileName);
		attributeSetterBiConsumers.put(
			"fileName",
			(BiConsumer<DiskonOther, String>)DiskonOther::setFileName);
		attributeGetterFunctions.put("filePath", DiskonOther::getFilePath);
		attributeSetterBiConsumers.put(
			"filePath",
			(BiConsumer<DiskonOther, String>)DiskonOther::setFilePath);
		attributeGetterFunctions.put("rowStatus", DiskonOther::getRowStatus);
		attributeSetterBiConsumers.put(
			"rowStatus",
			(BiConsumer<DiskonOther, Boolean>)DiskonOther::setRowStatus);
		attributeGetterFunctions.put(
			"createdDate", DiskonOther::getCreatedDate);
		attributeSetterBiConsumers.put(
			"createdDate",
			(BiConsumer<DiskonOther, Date>)DiskonOther::setCreatedDate);
		attributeGetterFunctions.put("createdBy", DiskonOther::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<DiskonOther, String>)DiskonOther::setCreatedBy);
		attributeGetterFunctions.put(
			"modifiedDate", DiskonOther::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<DiskonOther, Date>)DiskonOther::setModifiedDate);
		attributeGetterFunctions.put("modifiedBy", DiskonOther::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<DiskonOther, String>)DiskonOther::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getDiskonOtherId() {
		return _diskonOtherId;
	}

	@Override
	public void setDiskonOtherId(long diskonOtherId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_diskonOtherId = diskonOtherId;
	}

	@Override
	public int getDealerId() {
		return _dealerId;
	}

	@Override
	public void setDealerId(int dealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dealerId = dealerId;
	}

	@Override
	public int getTahun() {
		return _tahun;
	}

	@Override
	public void setTahun(int tahun) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tahun = tahun;
	}

	@Override
	public int getKuartalId() {
		return _kuartalId;
	}

	@Override
	public void setKuartalId(int kuartalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_kuartalId = kuartalId;
	}

	@Override
	public String getKeterangan() {
		if (_keterangan == null) {
			return "";
		}
		else {
			return _keterangan;
		}
	}

	@Override
	public void setKeterangan(String keterangan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_keterangan = keterangan;
	}

	@Override
	public long getFileId() {
		return _fileId;
	}

	@Override
	public void setFileId(long fileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileId = fileId;
	}

	@Override
	public String getFileName() {
		if (_fileName == null) {
			return "";
		}
		else {
			return _fileName;
		}
	}

	@Override
	public void setFileName(String fileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileName = fileName;
	}

	@Override
	public String getFilePath() {
		if (_filePath == null) {
			return "";
		}
		else {
			return _filePath;
		}
	}

	@Override
	public void setFilePath(String filePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_filePath = filePath;
	}

	@Override
	public boolean getRowStatus() {
		return _rowStatus;
	}

	@Override
	public boolean isRowStatus() {
		return _rowStatus;
	}

	@Override
	public void setRowStatus(boolean rowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_rowStatus = rowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdDate = createdDate;
	}

	@Override
	public String getCreatedBy() {
		if (_createdBy == null) {
			return "";
		}
		else {
			return _createdBy;
		}
	}

	@Override
	public void setCreatedBy(String createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_modifiedBy == null) {
			return "";
		}
		else {
			return _modifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, DiskonOther.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DiskonOther toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DiskonOther>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DiskonOtherImpl diskonOtherImpl = new DiskonOtherImpl();

		diskonOtherImpl.setDiskonOtherId(getDiskonOtherId());
		diskonOtherImpl.setDealerId(getDealerId());
		diskonOtherImpl.setTahun(getTahun());
		diskonOtherImpl.setKuartalId(getKuartalId());
		diskonOtherImpl.setKeterangan(getKeterangan());
		diskonOtherImpl.setFileId(getFileId());
		diskonOtherImpl.setFileName(getFileName());
		diskonOtherImpl.setFilePath(getFilePath());
		diskonOtherImpl.setRowStatus(isRowStatus());
		diskonOtherImpl.setCreatedDate(getCreatedDate());
		diskonOtherImpl.setCreatedBy(getCreatedBy());
		diskonOtherImpl.setModifiedDate(getModifiedDate());
		diskonOtherImpl.setModifiedBy(getModifiedBy());

		diskonOtherImpl.resetOriginalValues();

		return diskonOtherImpl;
	}

	@Override
	public DiskonOther cloneWithOriginalValues() {
		DiskonOtherImpl diskonOtherImpl = new DiskonOtherImpl();

		diskonOtherImpl.setDiskonOtherId(
			this.<Long>getColumnOriginalValue("diskonOtherId"));
		diskonOtherImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("dealerId"));
		diskonOtherImpl.setTahun(this.<Integer>getColumnOriginalValue("tahun"));
		diskonOtherImpl.setKuartalId(
			this.<Integer>getColumnOriginalValue("kuartalId"));
		diskonOtherImpl.setKeterangan(
			this.<String>getColumnOriginalValue("keterangan"));
		diskonOtherImpl.setFileId(this.<Long>getColumnOriginalValue("fileId"));
		diskonOtherImpl.setFileName(
			this.<String>getColumnOriginalValue("fileName"));
		diskonOtherImpl.setFilePath(
			this.<String>getColumnOriginalValue("filePath"));
		diskonOtherImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("rowStatus"));
		diskonOtherImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("createdDate"));
		diskonOtherImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("createdBy"));
		diskonOtherImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		diskonOtherImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("modifiedBy"));

		return diskonOtherImpl;
	}

	@Override
	public int compareTo(DiskonOther diskonOther) {
		long primaryKey = diskonOther.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DiskonOther)) {
			return false;
		}

		DiskonOther diskonOther = (DiskonOther)object;

		long primaryKey = diskonOther.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DiskonOther> toCacheModel() {
		DiskonOtherCacheModel diskonOtherCacheModel =
			new DiskonOtherCacheModel();

		diskonOtherCacheModel.diskonOtherId = getDiskonOtherId();

		diskonOtherCacheModel.dealerId = getDealerId();

		diskonOtherCacheModel.tahun = getTahun();

		diskonOtherCacheModel.kuartalId = getKuartalId();

		diskonOtherCacheModel.keterangan = getKeterangan();

		String keterangan = diskonOtherCacheModel.keterangan;

		if ((keterangan != null) && (keterangan.length() == 0)) {
			diskonOtherCacheModel.keterangan = null;
		}

		diskonOtherCacheModel.fileId = getFileId();

		diskonOtherCacheModel.fileName = getFileName();

		String fileName = diskonOtherCacheModel.fileName;

		if ((fileName != null) && (fileName.length() == 0)) {
			diskonOtherCacheModel.fileName = null;
		}

		diskonOtherCacheModel.filePath = getFilePath();

		String filePath = diskonOtherCacheModel.filePath;

		if ((filePath != null) && (filePath.length() == 0)) {
			diskonOtherCacheModel.filePath = null;
		}

		diskonOtherCacheModel.rowStatus = isRowStatus();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			diskonOtherCacheModel.createdDate = createdDate.getTime();
		}
		else {
			diskonOtherCacheModel.createdDate = Long.MIN_VALUE;
		}

		diskonOtherCacheModel.createdBy = getCreatedBy();

		String createdBy = diskonOtherCacheModel.createdBy;

		if ((createdBy != null) && (createdBy.length() == 0)) {
			diskonOtherCacheModel.createdBy = null;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			diskonOtherCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			diskonOtherCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		diskonOtherCacheModel.modifiedBy = getModifiedBy();

		String modifiedBy = diskonOtherCacheModel.modifiedBy;

		if ((modifiedBy != null) && (modifiedBy.length() == 0)) {
			diskonOtherCacheModel.modifiedBy = null;
		}

		return diskonOtherCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DiskonOther, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DiskonOther, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DiskonOther, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((DiskonOther)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DiskonOther>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DiskonOther.class, ModelWrapper.class);

	}

	private long _diskonOtherId;
	private int _dealerId;
	private int _tahun;
	private int _kuartalId;
	private String _keterangan;
	private long _fileId;
	private String _fileName;
	private String _filePath;
	private boolean _rowStatus;
	private Date _createdDate;
	private String _createdBy;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _modifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<DiskonOther, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DiskonOther)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("diskonOtherId", _diskonOtherId);
		_columnOriginalValues.put("dealerId", _dealerId);
		_columnOriginalValues.put("tahun", _tahun);
		_columnOriginalValues.put("kuartalId", _kuartalId);
		_columnOriginalValues.put("keterangan", _keterangan);
		_columnOriginalValues.put("fileId", _fileId);
		_columnOriginalValues.put("fileName", _fileName);
		_columnOriginalValues.put("filePath", _filePath);
		_columnOriginalValues.put("rowStatus", _rowStatus);
		_columnOriginalValues.put("createdDate", _createdDate);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("diskonOtherId", 1L);

		columnBitmasks.put("dealerId", 2L);

		columnBitmasks.put("tahun", 4L);

		columnBitmasks.put("kuartalId", 8L);

		columnBitmasks.put("keterangan", 16L);

		columnBitmasks.put("fileId", 32L);

		columnBitmasks.put("fileName", 64L);

		columnBitmasks.put("filePath", 128L);

		columnBitmasks.put("rowStatus", 256L);

		columnBitmasks.put("createdDate", 512L);

		columnBitmasks.put("createdBy", 1024L);

		columnBitmasks.put("modifiedDate", 2048L);

		columnBitmasks.put("modifiedBy", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DiskonOther _escapedModel;

}