/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.DiskonFakpol;
import com.astra.dewa.model.DiskonFakpolModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DiskonFakpol service. Represents a row in the &quot;diskon_fakpol&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DiskonFakpolModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DiskonFakpolImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DiskonFakpolImpl
 * @generated
 */
public class DiskonFakpolModelImpl
	extends BaseModelImpl<DiskonFakpol> implements DiskonFakpolModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a diskon fakpol model instance should use the <code>DiskonFakpol</code> interface instead.
	 */
	public static final String TABLE_NAME = "diskon_fakpol";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"DealerId", Types.INTEGER},
		{"Tahun", Types.INTEGER}, {"Periode", Types.VARCHAR},
		{"Keterangan", Types.VARCHAR}, {"FileId", Types.BIGINT},
		{"FileName", Types.VARCHAR}, {"FilePath", Types.VARCHAR},
		{"RowStatus", Types.BOOLEAN}, {"CreatedDate", Types.TIMESTAMP},
		{"CreatedBy", Types.VARCHAR}, {"ModifiedDate", Types.TIMESTAMP},
		{"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Tahun", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Periode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Keterangan", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FilePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table diskon_fakpol (Id INTEGER not null primary key IDENTITY,DealerId INTEGER,Tahun INTEGER,Periode VARCHAR(75) null,Keterangan VARCHAR(75) null,FileId LONG,FileName VARCHAR(75) null,FilePath VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table diskon_fakpol";

	public static final String ORDER_BY_JPQL = " ORDER BY diskonFakpol.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY diskon_fakpol.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DiskonFakpolModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DiskonFakpol.class;
	}

	@Override
	public String getModelClassName() {
		return DiskonFakpol.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DiskonFakpol, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DiskonFakpol, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DiskonFakpol, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DiskonFakpol)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DiskonFakpol, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DiskonFakpol, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DiskonFakpol)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DiskonFakpol, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DiskonFakpol, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<DiskonFakpol, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DiskonFakpol, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DiskonFakpol, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<DiskonFakpol, Object>>();
		Map<String, BiConsumer<DiskonFakpol, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DiskonFakpol, ?>>();

		attributeGetterFunctions.put("Id", DiskonFakpol::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<DiskonFakpol, Integer>)DiskonFakpol::setId);
		attributeGetterFunctions.put("DealerId", DiskonFakpol::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId",
			(BiConsumer<DiskonFakpol, Integer>)DiskonFakpol::setDealerId);
		attributeGetterFunctions.put("Tahun", DiskonFakpol::getTahun);
		attributeSetterBiConsumers.put(
			"Tahun", (BiConsumer<DiskonFakpol, Integer>)DiskonFakpol::setTahun);
		attributeGetterFunctions.put("Periode", DiskonFakpol::getPeriode);
		attributeSetterBiConsumers.put(
			"Periode",
			(BiConsumer<DiskonFakpol, String>)DiskonFakpol::setPeriode);
		attributeGetterFunctions.put("Keterangan", DiskonFakpol::getKeterangan);
		attributeSetterBiConsumers.put(
			"Keterangan",
			(BiConsumer<DiskonFakpol, String>)DiskonFakpol::setKeterangan);
		attributeGetterFunctions.put("FileId", DiskonFakpol::getFileId);
		attributeSetterBiConsumers.put(
			"FileId", (BiConsumer<DiskonFakpol, Long>)DiskonFakpol::setFileId);
		attributeGetterFunctions.put("FileName", DiskonFakpol::getFileName);
		attributeSetterBiConsumers.put(
			"FileName",
			(BiConsumer<DiskonFakpol, String>)DiskonFakpol::setFileName);
		attributeGetterFunctions.put("FilePath", DiskonFakpol::getFilePath);
		attributeSetterBiConsumers.put(
			"FilePath",
			(BiConsumer<DiskonFakpol, String>)DiskonFakpol::setFilePath);
		attributeGetterFunctions.put("RowStatus", DiskonFakpol::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<DiskonFakpol, Boolean>)DiskonFakpol::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", DiskonFakpol::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<DiskonFakpol, Date>)DiskonFakpol::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", DiskonFakpol::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<DiskonFakpol, String>)DiskonFakpol::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", DiskonFakpol::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<DiskonFakpol, Date>)DiskonFakpol::setModifiedDate);
		attributeGetterFunctions.put("ModifiedBy", DiskonFakpol::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<DiskonFakpol, String>)DiskonFakpol::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public Integer getTahun() {
		return _Tahun;
	}

	@Override
	public void setTahun(Integer Tahun) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Tahun = Tahun;
	}

	@Override
	public String getPeriode() {
		if (_Periode == null) {
			return "";
		}
		else {
			return _Periode;
		}
	}

	@Override
	public void setPeriode(String Periode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Periode = Periode;
	}

	@Override
	public String getKeterangan() {
		if (_Keterangan == null) {
			return "";
		}
		else {
			return _Keterangan;
		}
	}

	@Override
	public void setKeterangan(String Keterangan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Keterangan = Keterangan;
	}

	@Override
	public Long getFileId() {
		return _FileId;
	}

	@Override
	public void setFileId(Long FileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileId = FileId;
	}

	@Override
	public String getFileName() {
		if (_FileName == null) {
			return "";
		}
		else {
			return _FileName;
		}
	}

	@Override
	public void setFileName(String FileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileName = FileName;
	}

	@Override
	public String getFilePath() {
		if (_FilePath == null) {
			return "";
		}
		else {
			return _FilePath;
		}
	}

	@Override
	public void setFilePath(String FilePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FilePath = FilePath;
	}

	@Override
	public boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public boolean isRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public DiskonFakpol toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DiskonFakpol>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DiskonFakpolImpl diskonFakpolImpl = new DiskonFakpolImpl();

		diskonFakpolImpl.setId(getId());
		diskonFakpolImpl.setDealerId(getDealerId());
		diskonFakpolImpl.setTahun(getTahun());
		diskonFakpolImpl.setPeriode(getPeriode());
		diskonFakpolImpl.setKeterangan(getKeterangan());
		diskonFakpolImpl.setFileId(getFileId());
		diskonFakpolImpl.setFileName(getFileName());
		diskonFakpolImpl.setFilePath(getFilePath());
		diskonFakpolImpl.setRowStatus(isRowStatus());
		diskonFakpolImpl.setCreatedDate(getCreatedDate());
		diskonFakpolImpl.setCreatedBy(getCreatedBy());
		diskonFakpolImpl.setModifiedDate(getModifiedDate());
		diskonFakpolImpl.setModifiedBy(getModifiedBy());

		diskonFakpolImpl.resetOriginalValues();

		return diskonFakpolImpl;
	}

	@Override
	public DiskonFakpol cloneWithOriginalValues() {
		DiskonFakpolImpl diskonFakpolImpl = new DiskonFakpolImpl();

		diskonFakpolImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		diskonFakpolImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("DealerId"));
		diskonFakpolImpl.setTahun(
			this.<Integer>getColumnOriginalValue("Tahun"));
		diskonFakpolImpl.setPeriode(
			this.<String>getColumnOriginalValue("Periode"));
		diskonFakpolImpl.setKeterangan(
			this.<String>getColumnOriginalValue("Keterangan"));
		diskonFakpolImpl.setFileId(this.<Long>getColumnOriginalValue("FileId"));
		diskonFakpolImpl.setFileName(
			this.<String>getColumnOriginalValue("FileName"));
		diskonFakpolImpl.setFilePath(
			this.<String>getColumnOriginalValue("FilePath"));
		diskonFakpolImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		diskonFakpolImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		diskonFakpolImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		diskonFakpolImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		diskonFakpolImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return diskonFakpolImpl;
	}

	@Override
	public int compareTo(DiskonFakpol diskonFakpol) {
		int primaryKey = diskonFakpol.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DiskonFakpol)) {
			return false;
		}

		DiskonFakpol diskonFakpol = (DiskonFakpol)object;

		int primaryKey = diskonFakpol.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DiskonFakpol> toCacheModel() {
		DiskonFakpolCacheModel diskonFakpolCacheModel =
			new DiskonFakpolCacheModel();

		diskonFakpolCacheModel.Id = getId();

		diskonFakpolCacheModel.DealerId = getDealerId();

		Integer Tahun = getTahun();

		if (Tahun != null) {
			diskonFakpolCacheModel.Tahun = Tahun;
		}

		diskonFakpolCacheModel.Periode = getPeriode();

		String Periode = diskonFakpolCacheModel.Periode;

		if ((Periode != null) && (Periode.length() == 0)) {
			diskonFakpolCacheModel.Periode = null;
		}

		diskonFakpolCacheModel.Keterangan = getKeterangan();

		String Keterangan = diskonFakpolCacheModel.Keterangan;

		if ((Keterangan != null) && (Keterangan.length() == 0)) {
			diskonFakpolCacheModel.Keterangan = null;
		}

		Long FileId = getFileId();

		if (FileId != null) {
			diskonFakpolCacheModel.FileId = FileId;
		}

		diskonFakpolCacheModel.FileName = getFileName();

		String FileName = diskonFakpolCacheModel.FileName;

		if ((FileName != null) && (FileName.length() == 0)) {
			diskonFakpolCacheModel.FileName = null;
		}

		diskonFakpolCacheModel.FilePath = getFilePath();

		String FilePath = diskonFakpolCacheModel.FilePath;

		if ((FilePath != null) && (FilePath.length() == 0)) {
			diskonFakpolCacheModel.FilePath = null;
		}

		diskonFakpolCacheModel.RowStatus = isRowStatus();

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			diskonFakpolCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			diskonFakpolCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		diskonFakpolCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = diskonFakpolCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			diskonFakpolCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			diskonFakpolCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			diskonFakpolCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		diskonFakpolCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = diskonFakpolCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			diskonFakpolCacheModel.ModifiedBy = null;
		}

		return diskonFakpolCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DiskonFakpol, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DiskonFakpol, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DiskonFakpol, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((DiskonFakpol)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DiskonFakpol>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DiskonFakpol.class, ModelWrapper.class);

	}

	private int _Id;
	private int _DealerId;
	private Integer _Tahun;
	private String _Periode;
	private String _Keterangan;
	private Long _FileId;
	private String _FileName;
	private String _FilePath;
	private boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<DiskonFakpol, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DiskonFakpol)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("Tahun", _Tahun);
		_columnOriginalValues.put("Periode", _Periode);
		_columnOriginalValues.put("Keterangan", _Keterangan);
		_columnOriginalValues.put("FileId", _FileId);
		_columnOriginalValues.put("FileName", _FileName);
		_columnOriginalValues.put("FilePath", _FilePath);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("DealerId", 2L);

		columnBitmasks.put("Tahun", 4L);

		columnBitmasks.put("Periode", 8L);

		columnBitmasks.put("Keterangan", 16L);

		columnBitmasks.put("FileId", 32L);

		columnBitmasks.put("FileName", 64L);

		columnBitmasks.put("FilePath", 128L);

		columnBitmasks.put("RowStatus", 256L);

		columnBitmasks.put("CreatedDate", 512L);

		columnBitmasks.put("CreatedBy", 1024L);

		columnBitmasks.put("ModifiedDate", 2048L);

		columnBitmasks.put("ModifiedBy", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DiskonFakpol _escapedModel;

}