/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.DiskonFleet;
import com.astra.dewa.model.DiskonFleetModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DiskonFleet service. Represents a row in the &quot;diskon_fleet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DiskonFleetModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DiskonFleetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DiskonFleetImpl
 * @generated
 */
public class DiskonFleetModelImpl
	extends BaseModelImpl<DiskonFleet> implements DiskonFleetModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a diskon fleet model instance should use the <code>DiskonFleet</code> interface instead.
	 */
	public static final String TABLE_NAME = "diskon_fleet";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"DealerId", Types.INTEGER},
		{"Tahun", Types.INTEGER}, {"Kuartal", Types.VARCHAR},
		{"Keterangan", Types.VARCHAR}, {"FileId", Types.BIGINT},
		{"FileName", Types.VARCHAR}, {"FilePath", Types.VARCHAR},
		{"RowStatus", Types.BOOLEAN}, {"CreatedDate", Types.TIMESTAMP},
		{"CreatedBy", Types.VARCHAR}, {"ModifiedDate", Types.TIMESTAMP},
		{"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Tahun", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Kuartal", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Keterangan", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FilePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table diskon_fleet (Id INTEGER not null primary key IDENTITY,DealerId INTEGER,Tahun INTEGER,Kuartal VARCHAR(75) null,Keterangan VARCHAR(75) null,FileId LONG,FileName VARCHAR(75) null,FilePath VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table diskon_fleet";

	public static final String ORDER_BY_JPQL = " ORDER BY diskonFleet.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY diskon_fleet.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DiskonFleetModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DiskonFleet.class;
	}

	@Override
	public String getModelClassName() {
		return DiskonFleet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DiskonFleet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DiskonFleet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DiskonFleet, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DiskonFleet)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DiskonFleet, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DiskonFleet, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DiskonFleet)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DiskonFleet, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DiskonFleet, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<DiskonFleet, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DiskonFleet, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DiskonFleet, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<DiskonFleet, Object>>();
		Map<String, BiConsumer<DiskonFleet, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DiskonFleet, ?>>();

		attributeGetterFunctions.put("Id", DiskonFleet::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<DiskonFleet, Integer>)DiskonFleet::setId);
		attributeGetterFunctions.put("DealerId", DiskonFleet::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId",
			(BiConsumer<DiskonFleet, Integer>)DiskonFleet::setDealerId);
		attributeGetterFunctions.put("Tahun", DiskonFleet::getTahun);
		attributeSetterBiConsumers.put(
			"Tahun", (BiConsumer<DiskonFleet, Integer>)DiskonFleet::setTahun);
		attributeGetterFunctions.put("Kuartal", DiskonFleet::getKuartal);
		attributeSetterBiConsumers.put(
			"Kuartal",
			(BiConsumer<DiskonFleet, String>)DiskonFleet::setKuartal);
		attributeGetterFunctions.put("Keterangan", DiskonFleet::getKeterangan);
		attributeSetterBiConsumers.put(
			"Keterangan",
			(BiConsumer<DiskonFleet, String>)DiskonFleet::setKeterangan);
		attributeGetterFunctions.put("FileId", DiskonFleet::getFileId);
		attributeSetterBiConsumers.put(
			"FileId", (BiConsumer<DiskonFleet, Long>)DiskonFleet::setFileId);
		attributeGetterFunctions.put("FileName", DiskonFleet::getFileName);
		attributeSetterBiConsumers.put(
			"FileName",
			(BiConsumer<DiskonFleet, String>)DiskonFleet::setFileName);
		attributeGetterFunctions.put("FilePath", DiskonFleet::getFilePath);
		attributeSetterBiConsumers.put(
			"FilePath",
			(BiConsumer<DiskonFleet, String>)DiskonFleet::setFilePath);
		attributeGetterFunctions.put("RowStatus", DiskonFleet::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<DiskonFleet, Boolean>)DiskonFleet::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", DiskonFleet::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<DiskonFleet, Date>)DiskonFleet::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", DiskonFleet::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<DiskonFleet, String>)DiskonFleet::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", DiskonFleet::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<DiskonFleet, Date>)DiskonFleet::setModifiedDate);
		attributeGetterFunctions.put("ModifiedBy", DiskonFleet::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<DiskonFleet, String>)DiskonFleet::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public Integer getTahun() {
		return _Tahun;
	}

	@Override
	public void setTahun(Integer Tahun) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Tahun = Tahun;
	}

	@Override
	public String getKuartal() {
		if (_Kuartal == null) {
			return "";
		}
		else {
			return _Kuartal;
		}
	}

	@Override
	public void setKuartal(String Kuartal) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Kuartal = Kuartal;
	}

	@Override
	public String getKeterangan() {
		if (_Keterangan == null) {
			return "";
		}
		else {
			return _Keterangan;
		}
	}

	@Override
	public void setKeterangan(String Keterangan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Keterangan = Keterangan;
	}

	@Override
	public Long getFileId() {
		return _FileId;
	}

	@Override
	public void setFileId(Long FileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileId = FileId;
	}

	@Override
	public String getFileName() {
		if (_FileName == null) {
			return "";
		}
		else {
			return _FileName;
		}
	}

	@Override
	public void setFileName(String FileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileName = FileName;
	}

	@Override
	public String getFilePath() {
		if (_FilePath == null) {
			return "";
		}
		else {
			return _FilePath;
		}
	}

	@Override
	public void setFilePath(String FilePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FilePath = FilePath;
	}

	@Override
	public boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public boolean isRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public DiskonFleet toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DiskonFleet>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DiskonFleetImpl diskonFleetImpl = new DiskonFleetImpl();

		diskonFleetImpl.setId(getId());
		diskonFleetImpl.setDealerId(getDealerId());
		diskonFleetImpl.setTahun(getTahun());
		diskonFleetImpl.setKuartal(getKuartal());
		diskonFleetImpl.setKeterangan(getKeterangan());
		diskonFleetImpl.setFileId(getFileId());
		diskonFleetImpl.setFileName(getFileName());
		diskonFleetImpl.setFilePath(getFilePath());
		diskonFleetImpl.setRowStatus(isRowStatus());
		diskonFleetImpl.setCreatedDate(getCreatedDate());
		diskonFleetImpl.setCreatedBy(getCreatedBy());
		diskonFleetImpl.setModifiedDate(getModifiedDate());
		diskonFleetImpl.setModifiedBy(getModifiedBy());

		diskonFleetImpl.resetOriginalValues();

		return diskonFleetImpl;
	}

	@Override
	public DiskonFleet cloneWithOriginalValues() {
		DiskonFleetImpl diskonFleetImpl = new DiskonFleetImpl();

		diskonFleetImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		diskonFleetImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("DealerId"));
		diskonFleetImpl.setTahun(this.<Integer>getColumnOriginalValue("Tahun"));
		diskonFleetImpl.setKuartal(
			this.<String>getColumnOriginalValue("Kuartal"));
		diskonFleetImpl.setKeterangan(
			this.<String>getColumnOriginalValue("Keterangan"));
		diskonFleetImpl.setFileId(this.<Long>getColumnOriginalValue("FileId"));
		diskonFleetImpl.setFileName(
			this.<String>getColumnOriginalValue("FileName"));
		diskonFleetImpl.setFilePath(
			this.<String>getColumnOriginalValue("FilePath"));
		diskonFleetImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		diskonFleetImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		diskonFleetImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		diskonFleetImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		diskonFleetImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return diskonFleetImpl;
	}

	@Override
	public int compareTo(DiskonFleet diskonFleet) {
		int primaryKey = diskonFleet.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DiskonFleet)) {
			return false;
		}

		DiskonFleet diskonFleet = (DiskonFleet)object;

		int primaryKey = diskonFleet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DiskonFleet> toCacheModel() {
		DiskonFleetCacheModel diskonFleetCacheModel =
			new DiskonFleetCacheModel();

		diskonFleetCacheModel.Id = getId();

		diskonFleetCacheModel.DealerId = getDealerId();

		Integer Tahun = getTahun();

		if (Tahun != null) {
			diskonFleetCacheModel.Tahun = Tahun;
		}

		diskonFleetCacheModel.Kuartal = getKuartal();

		String Kuartal = diskonFleetCacheModel.Kuartal;

		if ((Kuartal != null) && (Kuartal.length() == 0)) {
			diskonFleetCacheModel.Kuartal = null;
		}

		diskonFleetCacheModel.Keterangan = getKeterangan();

		String Keterangan = diskonFleetCacheModel.Keterangan;

		if ((Keterangan != null) && (Keterangan.length() == 0)) {
			diskonFleetCacheModel.Keterangan = null;
		}

		Long FileId = getFileId();

		if (FileId != null) {
			diskonFleetCacheModel.FileId = FileId;
		}

		diskonFleetCacheModel.FileName = getFileName();

		String FileName = diskonFleetCacheModel.FileName;

		if ((FileName != null) && (FileName.length() == 0)) {
			diskonFleetCacheModel.FileName = null;
		}

		diskonFleetCacheModel.FilePath = getFilePath();

		String FilePath = diskonFleetCacheModel.FilePath;

		if ((FilePath != null) && (FilePath.length() == 0)) {
			diskonFleetCacheModel.FilePath = null;
		}

		diskonFleetCacheModel.RowStatus = isRowStatus();

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			diskonFleetCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			diskonFleetCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		diskonFleetCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = diskonFleetCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			diskonFleetCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			diskonFleetCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			diskonFleetCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		diskonFleetCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = diskonFleetCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			diskonFleetCacheModel.ModifiedBy = null;
		}

		return diskonFleetCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DiskonFleet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DiskonFleet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DiskonFleet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((DiskonFleet)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DiskonFleet>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DiskonFleet.class, ModelWrapper.class);

	}

	private int _Id;
	private int _DealerId;
	private Integer _Tahun;
	private String _Kuartal;
	private String _Keterangan;
	private Long _FileId;
	private String _FileName;
	private String _FilePath;
	private boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<DiskonFleet, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DiskonFleet)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("Tahun", _Tahun);
		_columnOriginalValues.put("Kuartal", _Kuartal);
		_columnOriginalValues.put("Keterangan", _Keterangan);
		_columnOriginalValues.put("FileId", _FileId);
		_columnOriginalValues.put("FileName", _FileName);
		_columnOriginalValues.put("FilePath", _FilePath);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("DealerId", 2L);

		columnBitmasks.put("Tahun", 4L);

		columnBitmasks.put("Kuartal", 8L);

		columnBitmasks.put("Keterangan", 16L);

		columnBitmasks.put("FileId", 32L);

		columnBitmasks.put("FileName", 64L);

		columnBitmasks.put("FilePath", 128L);

		columnBitmasks.put("RowStatus", 256L);

		columnBitmasks.put("CreatedDate", 512L);

		columnBitmasks.put("CreatedBy", 1024L);

		columnBitmasks.put("ModifiedDate", 2048L);

		columnBitmasks.put("ModifiedBy", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DiskonFleet _escapedModel;

}