/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.ESrut;
import com.astra.dewa.model.ESrutModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ESrut service. Represents a row in the &quot;e_srut&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ESrutModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ESrutImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ESrutImpl
 * @generated
 */
public class ESrutModelImpl extends BaseModelImpl<ESrut> implements ESrutModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e srut model instance should use the <code>ESrut</code> interface instead.
	 */
	public static final String TABLE_NAME = "e_srut";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"DealerId", Types.INTEGER},
		{"FileId", Types.BIGINT}, {"FileName", Types.VARCHAR},
		{"FilePath", Types.VARCHAR}, {"PeriodDate", Types.TIMESTAMP},
		{"Keterangan", Types.VARCHAR}, {"CreatedDate", Types.TIMESTAMP},
		{"CreatedBy", Types.VARCHAR}, {"ModifiedDate", Types.TIMESTAMP},
		{"ModifiedBy", Types.VARCHAR}, {"RowStatus", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("FileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FilePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PeriodDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("Keterangan", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table e_srut (Id INTEGER not null primary key IDENTITY,DealerId INTEGER,FileId LONG,FileName VARCHAR(75) null,FilePath VARCHAR(75) null,PeriodDate DATE null,Keterangan VARCHAR(75) null,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null,RowStatus BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table e_srut";

	public static final String ORDER_BY_JPQL = " ORDER BY eSrut.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY e_srut.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ESrutModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ESrut.class;
	}

	@Override
	public String getModelClassName() {
		return ESrut.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ESrut, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ESrut, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ESrut, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((ESrut)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ESrut, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ESrut, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((ESrut)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ESrut, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ESrut, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ESrut, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ESrut, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ESrut, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ESrut, Object>>();
		Map<String, BiConsumer<ESrut, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ESrut, ?>>();

		attributeGetterFunctions.put("Id", ESrut::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<ESrut, Integer>)ESrut::setId);
		attributeGetterFunctions.put("DealerId", ESrut::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId", (BiConsumer<ESrut, Integer>)ESrut::setDealerId);
		attributeGetterFunctions.put("FileId", ESrut::getFileId);
		attributeSetterBiConsumers.put(
			"FileId", (BiConsumer<ESrut, Long>)ESrut::setFileId);
		attributeGetterFunctions.put("FileName", ESrut::getFileName);
		attributeSetterBiConsumers.put(
			"FileName", (BiConsumer<ESrut, String>)ESrut::setFileName);
		attributeGetterFunctions.put("FilePath", ESrut::getFilePath);
		attributeSetterBiConsumers.put(
			"FilePath", (BiConsumer<ESrut, String>)ESrut::setFilePath);
		attributeGetterFunctions.put("PeriodDate", ESrut::getPeriodDate);
		attributeSetterBiConsumers.put(
			"PeriodDate", (BiConsumer<ESrut, Date>)ESrut::setPeriodDate);
		attributeGetterFunctions.put("Keterangan", ESrut::getKeterangan);
		attributeSetterBiConsumers.put(
			"Keterangan", (BiConsumer<ESrut, String>)ESrut::setKeterangan);
		attributeGetterFunctions.put("CreatedDate", ESrut::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate", (BiConsumer<ESrut, Date>)ESrut::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", ESrut::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy", (BiConsumer<ESrut, String>)ESrut::setCreatedBy);
		attributeGetterFunctions.put("ModifiedDate", ESrut::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate", (BiConsumer<ESrut, Date>)ESrut::setModifiedDate);
		attributeGetterFunctions.put("ModifiedBy", ESrut::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy", (BiConsumer<ESrut, String>)ESrut::setModifiedBy);
		attributeGetterFunctions.put("RowStatus", ESrut::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus", (BiConsumer<ESrut, Boolean>)ESrut::setRowStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public Long getFileId() {
		return _FileId;
	}

	@Override
	public void setFileId(Long FileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileId = FileId;
	}

	@Override
	public String getFileName() {
		if (_FileName == null) {
			return "";
		}
		else {
			return _FileName;
		}
	}

	@Override
	public void setFileName(String FileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileName = FileName;
	}

	@Override
	public String getFilePath() {
		if (_FilePath == null) {
			return "";
		}
		else {
			return _FilePath;
		}
	}

	@Override
	public void setFilePath(String FilePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FilePath = FilePath;
	}

	@Override
	public Date getPeriodDate() {
		return _PeriodDate;
	}

	@Override
	public void setPeriodDate(Date PeriodDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_PeriodDate = PeriodDate;
	}

	@Override
	public String getKeterangan() {
		if (_Keterangan == null) {
			return "";
		}
		else {
			return _Keterangan;
		}
	}

	@Override
	public void setKeterangan(String Keterangan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Keterangan = Keterangan;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	@Override
	public boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public boolean isRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ESrut toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ESrut>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ESrutImpl eSrutImpl = new ESrutImpl();

		eSrutImpl.setId(getId());
		eSrutImpl.setDealerId(getDealerId());
		eSrutImpl.setFileId(getFileId());
		eSrutImpl.setFileName(getFileName());
		eSrutImpl.setFilePath(getFilePath());
		eSrutImpl.setPeriodDate(getPeriodDate());
		eSrutImpl.setKeterangan(getKeterangan());
		eSrutImpl.setCreatedDate(getCreatedDate());
		eSrutImpl.setCreatedBy(getCreatedBy());
		eSrutImpl.setModifiedDate(getModifiedDate());
		eSrutImpl.setModifiedBy(getModifiedBy());
		eSrutImpl.setRowStatus(isRowStatus());

		eSrutImpl.resetOriginalValues();

		return eSrutImpl;
	}

	@Override
	public ESrut cloneWithOriginalValues() {
		ESrutImpl eSrutImpl = new ESrutImpl();

		eSrutImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		eSrutImpl.setDealerId(this.<Integer>getColumnOriginalValue("DealerId"));
		eSrutImpl.setFileId(this.<Long>getColumnOriginalValue("FileId"));
		eSrutImpl.setFileName(this.<String>getColumnOriginalValue("FileName"));
		eSrutImpl.setFilePath(this.<String>getColumnOriginalValue("FilePath"));
		eSrutImpl.setPeriodDate(
			this.<Date>getColumnOriginalValue("PeriodDate"));
		eSrutImpl.setKeterangan(
			this.<String>getColumnOriginalValue("Keterangan"));
		eSrutImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		eSrutImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		eSrutImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		eSrutImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));
		eSrutImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));

		return eSrutImpl;
	}

	@Override
	public int compareTo(ESrut eSrut) {
		int primaryKey = eSrut.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ESrut)) {
			return false;
		}

		ESrut eSrut = (ESrut)object;

		int primaryKey = eSrut.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ESrut> toCacheModel() {
		ESrutCacheModel eSrutCacheModel = new ESrutCacheModel();

		eSrutCacheModel.Id = getId();

		eSrutCacheModel.DealerId = getDealerId();

		Long FileId = getFileId();

		if (FileId != null) {
			eSrutCacheModel.FileId = FileId;
		}

		eSrutCacheModel.FileName = getFileName();

		String FileName = eSrutCacheModel.FileName;

		if ((FileName != null) && (FileName.length() == 0)) {
			eSrutCacheModel.FileName = null;
		}

		eSrutCacheModel.FilePath = getFilePath();

		String FilePath = eSrutCacheModel.FilePath;

		if ((FilePath != null) && (FilePath.length() == 0)) {
			eSrutCacheModel.FilePath = null;
		}

		Date PeriodDate = getPeriodDate();

		if (PeriodDate != null) {
			eSrutCacheModel.PeriodDate = PeriodDate.getTime();
		}
		else {
			eSrutCacheModel.PeriodDate = Long.MIN_VALUE;
		}

		eSrutCacheModel.Keterangan = getKeterangan();

		String Keterangan = eSrutCacheModel.Keterangan;

		if ((Keterangan != null) && (Keterangan.length() == 0)) {
			eSrutCacheModel.Keterangan = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			eSrutCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			eSrutCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		eSrutCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = eSrutCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			eSrutCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			eSrutCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			eSrutCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		eSrutCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = eSrutCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			eSrutCacheModel.ModifiedBy = null;
		}

		eSrutCacheModel.RowStatus = isRowStatus();

		return eSrutCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ESrut, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ESrut, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ESrut, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ESrut)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ESrut>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ESrut.class, ModelWrapper.class);

	}

	private int _Id;
	private int _DealerId;
	private Long _FileId;
	private String _FileName;
	private String _FilePath;
	private Date _PeriodDate;
	private String _Keterangan;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;
	private boolean _RowStatus;

	public <T> T getColumnValue(String columnName) {
		Function<ESrut, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ESrut)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("FileId", _FileId);
		_columnOriginalValues.put("FileName", _FileName);
		_columnOriginalValues.put("FilePath", _FilePath);
		_columnOriginalValues.put("PeriodDate", _PeriodDate);
		_columnOriginalValues.put("Keterangan", _Keterangan);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
		_columnOriginalValues.put("RowStatus", _RowStatus);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("DealerId", 2L);

		columnBitmasks.put("FileId", 4L);

		columnBitmasks.put("FileName", 8L);

		columnBitmasks.put("FilePath", 16L);

		columnBitmasks.put("PeriodDate", 32L);

		columnBitmasks.put("Keterangan", 64L);

		columnBitmasks.put("CreatedDate", 128L);

		columnBitmasks.put("CreatedBy", 256L);

		columnBitmasks.put("ModifiedDate", 512L);

		columnBitmasks.put("ModifiedBy", 1024L);

		columnBitmasks.put("RowStatus", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ESrut _escapedModel;

}