/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.MasterApproval;
import com.astra.dewa.model.MasterApprovalModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MasterApproval service. Represents a row in the &quot;master_approval&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MasterApprovalModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MasterApprovalImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MasterApprovalImpl
 * @generated
 */
public class MasterApprovalModelImpl
	extends BaseModelImpl<MasterApproval> implements MasterApprovalModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a master approval model instance should use the <code>MasterApproval</code> interface instead.
	 */
	public static final String TABLE_NAME = "master_approval";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"RoleId", Types.INTEGER},
		{"MenuId", Types.INTEGER}, {"ApprovalGroup", Types.VARCHAR},
		{"ApprovalWorkflow", Types.BOOLEAN}, {"RowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("RoleId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("MenuId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApprovalGroup", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ApprovalWorkflow", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table master_approval (Id INTEGER not null primary key IDENTITY,RoleId INTEGER,MenuId INTEGER,ApprovalGroup VARCHAR(75) null,ApprovalWorkflow BOOLEAN,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table master_approval";

	public static final String ORDER_BY_JPQL =
		" ORDER BY masterApproval.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY master_approval.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public MasterApprovalModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MasterApproval.class;
	}

	@Override
	public String getModelClassName() {
		return MasterApproval.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MasterApproval, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MasterApproval, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterApproval, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MasterApproval)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MasterApproval, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MasterApproval, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MasterApproval)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MasterApproval, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MasterApproval, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MasterApproval, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MasterApproval, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MasterApproval, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<MasterApproval, Object>>();
		Map<String, BiConsumer<MasterApproval, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MasterApproval, ?>>();

		attributeGetterFunctions.put("Id", MasterApproval::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<MasterApproval, Integer>)MasterApproval::setId);
		attributeGetterFunctions.put("RoleId", MasterApproval::getRoleId);
		attributeSetterBiConsumers.put(
			"RoleId",
			(BiConsumer<MasterApproval, Integer>)MasterApproval::setRoleId);
		attributeGetterFunctions.put("MenuId", MasterApproval::getMenuId);
		attributeSetterBiConsumers.put(
			"MenuId",
			(BiConsumer<MasterApproval, Integer>)MasterApproval::setMenuId);
		attributeGetterFunctions.put(
			"ApprovalGroup", MasterApproval::getApprovalGroup);
		attributeSetterBiConsumers.put(
			"ApprovalGroup",
			(BiConsumer<MasterApproval, String>)
				MasterApproval::setApprovalGroup);
		attributeGetterFunctions.put(
			"ApprovalWorkflow", MasterApproval::getApprovalWorkflow);
		attributeSetterBiConsumers.put(
			"ApprovalWorkflow",
			(BiConsumer<MasterApproval, Boolean>)
				MasterApproval::setApprovalWorkflow);
		attributeGetterFunctions.put("RowStatus", MasterApproval::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<MasterApproval, Boolean>)MasterApproval::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", MasterApproval::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<MasterApproval, Date>)MasterApproval::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", MasterApproval::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<MasterApproval, String>)MasterApproval::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", MasterApproval::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<MasterApproval, Date>)MasterApproval::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", MasterApproval::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<MasterApproval, String>)MasterApproval::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getRoleId() {
		return _RoleId;
	}

	@Override
	public void setRoleId(int RoleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RoleId = RoleId;
	}

	@Override
	public int getMenuId() {
		return _MenuId;
	}

	@Override
	public void setMenuId(int MenuId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_MenuId = MenuId;
	}

	@Override
	public String getApprovalGroup() {
		if (_ApprovalGroup == null) {
			return "";
		}
		else {
			return _ApprovalGroup;
		}
	}

	@Override
	public void setApprovalGroup(String ApprovalGroup) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApprovalGroup = ApprovalGroup;
	}

	@Override
	public boolean getApprovalWorkflow() {
		return _ApprovalWorkflow;
	}

	@Override
	public boolean isApprovalWorkflow() {
		return _ApprovalWorkflow;
	}

	@Override
	public void setApprovalWorkflow(boolean ApprovalWorkflow) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApprovalWorkflow = ApprovalWorkflow;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public MasterApproval toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MasterApproval>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MasterApprovalImpl masterApprovalImpl = new MasterApprovalImpl();

		masterApprovalImpl.setId(getId());
		masterApprovalImpl.setRoleId(getRoleId());
		masterApprovalImpl.setMenuId(getMenuId());
		masterApprovalImpl.setApprovalGroup(getApprovalGroup());
		masterApprovalImpl.setApprovalWorkflow(isApprovalWorkflow());
		masterApprovalImpl.setRowStatus(getRowStatus());
		masterApprovalImpl.setCreatedDate(getCreatedDate());
		masterApprovalImpl.setCreatedBy(getCreatedBy());
		masterApprovalImpl.setModifiedDate(getModifiedDate());
		masterApprovalImpl.setModifiedBy(getModifiedBy());

		masterApprovalImpl.resetOriginalValues();

		return masterApprovalImpl;
	}

	@Override
	public MasterApproval cloneWithOriginalValues() {
		MasterApprovalImpl masterApprovalImpl = new MasterApprovalImpl();

		masterApprovalImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		masterApprovalImpl.setRoleId(
			this.<Integer>getColumnOriginalValue("RoleId"));
		masterApprovalImpl.setMenuId(
			this.<Integer>getColumnOriginalValue("MenuId"));
		masterApprovalImpl.setApprovalGroup(
			this.<String>getColumnOriginalValue("ApprovalGroup"));
		masterApprovalImpl.setApprovalWorkflow(
			this.<Boolean>getColumnOriginalValue("ApprovalWorkflow"));
		masterApprovalImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		masterApprovalImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		masterApprovalImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		masterApprovalImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		masterApprovalImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return masterApprovalImpl;
	}

	@Override
	public int compareTo(MasterApproval masterApproval) {
		int primaryKey = masterApproval.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MasterApproval)) {
			return false;
		}

		MasterApproval masterApproval = (MasterApproval)object;

		int primaryKey = masterApproval.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MasterApproval> toCacheModel() {
		MasterApprovalCacheModel masterApprovalCacheModel =
			new MasterApprovalCacheModel();

		masterApprovalCacheModel.Id = getId();

		masterApprovalCacheModel.RoleId = getRoleId();

		masterApprovalCacheModel.MenuId = getMenuId();

		masterApprovalCacheModel.ApprovalGroup = getApprovalGroup();

		String ApprovalGroup = masterApprovalCacheModel.ApprovalGroup;

		if ((ApprovalGroup != null) && (ApprovalGroup.length() == 0)) {
			masterApprovalCacheModel.ApprovalGroup = null;
		}

		masterApprovalCacheModel.ApprovalWorkflow = isApprovalWorkflow();

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			masterApprovalCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			masterApprovalCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			masterApprovalCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		masterApprovalCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = masterApprovalCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			masterApprovalCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			masterApprovalCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			masterApprovalCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		masterApprovalCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = masterApprovalCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			masterApprovalCacheModel.ModifiedBy = null;
		}

		return masterApprovalCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MasterApproval, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MasterApproval, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterApproval, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((MasterApproval)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MasterApproval>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MasterApproval.class, ModelWrapper.class);

	}

	private int _Id;
	private int _RoleId;
	private int _MenuId;
	private String _ApprovalGroup;
	private boolean _ApprovalWorkflow;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<MasterApproval, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MasterApproval)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("RoleId", _RoleId);
		_columnOriginalValues.put("MenuId", _MenuId);
		_columnOriginalValues.put("ApprovalGroup", _ApprovalGroup);
		_columnOriginalValues.put("ApprovalWorkflow", _ApprovalWorkflow);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("RoleId", 2L);

		columnBitmasks.put("MenuId", 4L);

		columnBitmasks.put("ApprovalGroup", 8L);

		columnBitmasks.put("ApprovalWorkflow", 16L);

		columnBitmasks.put("RowStatus", 32L);

		columnBitmasks.put("CreatedDate", 64L);

		columnBitmasks.put("CreatedBy", 128L);

		columnBitmasks.put("ModifiedDate", 256L);

		columnBitmasks.put("ModifiedBy", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MasterApproval _escapedModel;

}