/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.MasterApprovalJournal;
import com.astra.dewa.model.MasterApprovalJournalModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MasterApprovalJournal service. Represents a row in the &quot;master_approval_journal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MasterApprovalJournalModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MasterApprovalJournalImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MasterApprovalJournalImpl
 * @generated
 */
public class MasterApprovalJournalModelImpl
	extends BaseModelImpl<MasterApprovalJournal>
	implements MasterApprovalJournalModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a master approval journal model instance should use the <code>MasterApprovalJournal</code> interface instead.
	 */
	public static final String TABLE_NAME = "master_approval_journal";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"MasterApprovalId", Types.INTEGER},
		{"RoleId", Types.INTEGER}, {"MenuId", Types.INTEGER},
		{"ApprovalGroup", Types.VARCHAR}, {"ApprovalWorkflow", Types.BOOLEAN},
		{"RowStatus", Types.BOOLEAN}, {"CreatedDate", Types.TIMESTAMP},
		{"CreatedBy", Types.VARCHAR}, {"ModifiedDate", Types.TIMESTAMP},
		{"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("MasterApprovalId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("RoleId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("MenuId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ApprovalGroup", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ApprovalWorkflow", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table master_approval_journal (Id INTEGER not null primary key IDENTITY,MasterApprovalId INTEGER,RoleId INTEGER,MenuId INTEGER,ApprovalGroup VARCHAR(75) null,ApprovalWorkflow BOOLEAN,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table master_approval_journal";

	public static final String ORDER_BY_JPQL =
		" ORDER BY masterApprovalJournal.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY master_approval_journal.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public MasterApprovalJournalModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MasterApprovalJournal.class;
	}

	@Override
	public String getModelClassName() {
		return MasterApprovalJournal.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MasterApprovalJournal, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MasterApprovalJournal, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterApprovalJournal, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MasterApprovalJournal)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MasterApprovalJournal, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MasterApprovalJournal, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MasterApprovalJournal)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MasterApprovalJournal, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MasterApprovalJournal, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MasterApprovalJournal, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MasterApprovalJournal, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MasterApprovalJournal, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<MasterApprovalJournal, Object>>();
		Map<String, BiConsumer<MasterApprovalJournal, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<MasterApprovalJournal, ?>>();

		attributeGetterFunctions.put("Id", MasterApprovalJournal::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<MasterApprovalJournal, Integer>)
				MasterApprovalJournal::setId);
		attributeGetterFunctions.put(
			"MasterApprovalId", MasterApprovalJournal::getMasterApprovalId);
		attributeSetterBiConsumers.put(
			"MasterApprovalId",
			(BiConsumer<MasterApprovalJournal, Integer>)
				MasterApprovalJournal::setMasterApprovalId);
		attributeGetterFunctions.put(
			"RoleId", MasterApprovalJournal::getRoleId);
		attributeSetterBiConsumers.put(
			"RoleId",
			(BiConsumer<MasterApprovalJournal, Integer>)
				MasterApprovalJournal::setRoleId);
		attributeGetterFunctions.put(
			"MenuId", MasterApprovalJournal::getMenuId);
		attributeSetterBiConsumers.put(
			"MenuId",
			(BiConsumer<MasterApprovalJournal, Integer>)
				MasterApprovalJournal::setMenuId);
		attributeGetterFunctions.put(
			"ApprovalGroup", MasterApprovalJournal::getApprovalGroup);
		attributeSetterBiConsumers.put(
			"ApprovalGroup",
			(BiConsumer<MasterApprovalJournal, String>)
				MasterApprovalJournal::setApprovalGroup);
		attributeGetterFunctions.put(
			"ApprovalWorkflow", MasterApprovalJournal::getApprovalWorkflow);
		attributeSetterBiConsumers.put(
			"ApprovalWorkflow",
			(BiConsumer<MasterApprovalJournal, Boolean>)
				MasterApprovalJournal::setApprovalWorkflow);
		attributeGetterFunctions.put(
			"RowStatus", MasterApprovalJournal::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<MasterApprovalJournal, Boolean>)
				MasterApprovalJournal::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", MasterApprovalJournal::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<MasterApprovalJournal, Date>)
				MasterApprovalJournal::setCreatedDate);
		attributeGetterFunctions.put(
			"CreatedBy", MasterApprovalJournal::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<MasterApprovalJournal, String>)
				MasterApprovalJournal::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", MasterApprovalJournal::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<MasterApprovalJournal, Date>)
				MasterApprovalJournal::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", MasterApprovalJournal::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<MasterApprovalJournal, String>)
				MasterApprovalJournal::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getMasterApprovalId() {
		return _MasterApprovalId;
	}

	@Override
	public void setMasterApprovalId(int MasterApprovalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_MasterApprovalId = MasterApprovalId;
	}

	@Override
	public int getRoleId() {
		return _RoleId;
	}

	@Override
	public void setRoleId(int RoleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RoleId = RoleId;
	}

	@Override
	public int getMenuId() {
		return _MenuId;
	}

	@Override
	public void setMenuId(int MenuId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_MenuId = MenuId;
	}

	@Override
	public String getApprovalGroup() {
		if (_ApprovalGroup == null) {
			return "";
		}
		else {
			return _ApprovalGroup;
		}
	}

	@Override
	public void setApprovalGroup(String ApprovalGroup) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApprovalGroup = ApprovalGroup;
	}

	@Override
	public boolean getApprovalWorkflow() {
		return _ApprovalWorkflow;
	}

	@Override
	public boolean isApprovalWorkflow() {
		return _ApprovalWorkflow;
	}

	@Override
	public void setApprovalWorkflow(boolean ApprovalWorkflow) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ApprovalWorkflow = ApprovalWorkflow;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public MasterApprovalJournal toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MasterApprovalJournal>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MasterApprovalJournalImpl masterApprovalJournalImpl =
			new MasterApprovalJournalImpl();

		masterApprovalJournalImpl.setId(getId());
		masterApprovalJournalImpl.setMasterApprovalId(getMasterApprovalId());
		masterApprovalJournalImpl.setRoleId(getRoleId());
		masterApprovalJournalImpl.setMenuId(getMenuId());
		masterApprovalJournalImpl.setApprovalGroup(getApprovalGroup());
		masterApprovalJournalImpl.setApprovalWorkflow(isApprovalWorkflow());
		masterApprovalJournalImpl.setRowStatus(getRowStatus());
		masterApprovalJournalImpl.setCreatedDate(getCreatedDate());
		masterApprovalJournalImpl.setCreatedBy(getCreatedBy());
		masterApprovalJournalImpl.setModifiedDate(getModifiedDate());
		masterApprovalJournalImpl.setModifiedBy(getModifiedBy());

		masterApprovalJournalImpl.resetOriginalValues();

		return masterApprovalJournalImpl;
	}

	@Override
	public MasterApprovalJournal cloneWithOriginalValues() {
		MasterApprovalJournalImpl masterApprovalJournalImpl =
			new MasterApprovalJournalImpl();

		masterApprovalJournalImpl.setId(
			this.<Integer>getColumnOriginalValue("Id"));
		masterApprovalJournalImpl.setMasterApprovalId(
			this.<Integer>getColumnOriginalValue("MasterApprovalId"));
		masterApprovalJournalImpl.setRoleId(
			this.<Integer>getColumnOriginalValue("RoleId"));
		masterApprovalJournalImpl.setMenuId(
			this.<Integer>getColumnOriginalValue("MenuId"));
		masterApprovalJournalImpl.setApprovalGroup(
			this.<String>getColumnOriginalValue("ApprovalGroup"));
		masterApprovalJournalImpl.setApprovalWorkflow(
			this.<Boolean>getColumnOriginalValue("ApprovalWorkflow"));
		masterApprovalJournalImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		masterApprovalJournalImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		masterApprovalJournalImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		masterApprovalJournalImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		masterApprovalJournalImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return masterApprovalJournalImpl;
	}

	@Override
	public int compareTo(MasterApprovalJournal masterApprovalJournal) {
		int primaryKey = masterApprovalJournal.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MasterApprovalJournal)) {
			return false;
		}

		MasterApprovalJournal masterApprovalJournal =
			(MasterApprovalJournal)object;

		int primaryKey = masterApprovalJournal.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MasterApprovalJournal> toCacheModel() {
		MasterApprovalJournalCacheModel masterApprovalJournalCacheModel =
			new MasterApprovalJournalCacheModel();

		masterApprovalJournalCacheModel.Id = getId();

		masterApprovalJournalCacheModel.MasterApprovalId =
			getMasterApprovalId();

		masterApprovalJournalCacheModel.RoleId = getRoleId();

		masterApprovalJournalCacheModel.MenuId = getMenuId();

		masterApprovalJournalCacheModel.ApprovalGroup = getApprovalGroup();

		String ApprovalGroup = masterApprovalJournalCacheModel.ApprovalGroup;

		if ((ApprovalGroup != null) && (ApprovalGroup.length() == 0)) {
			masterApprovalJournalCacheModel.ApprovalGroup = null;
		}

		masterApprovalJournalCacheModel.ApprovalWorkflow = isApprovalWorkflow();

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			masterApprovalJournalCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			masterApprovalJournalCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			masterApprovalJournalCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		masterApprovalJournalCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = masterApprovalJournalCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			masterApprovalJournalCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			masterApprovalJournalCacheModel.ModifiedDate =
				ModifiedDate.getTime();
		}
		else {
			masterApprovalJournalCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		masterApprovalJournalCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = masterApprovalJournalCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			masterApprovalJournalCacheModel.ModifiedBy = null;
		}

		return masterApprovalJournalCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MasterApprovalJournal, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MasterApprovalJournal, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MasterApprovalJournal, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(MasterApprovalJournal)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MasterApprovalJournal>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MasterApprovalJournal.class, ModelWrapper.class);

	}

	private int _Id;
	private int _MasterApprovalId;
	private int _RoleId;
	private int _MenuId;
	private String _ApprovalGroup;
	private boolean _ApprovalWorkflow;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<MasterApprovalJournal, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MasterApprovalJournal)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("MasterApprovalId", _MasterApprovalId);
		_columnOriginalValues.put("RoleId", _RoleId);
		_columnOriginalValues.put("MenuId", _MenuId);
		_columnOriginalValues.put("ApprovalGroup", _ApprovalGroup);
		_columnOriginalValues.put("ApprovalWorkflow", _ApprovalWorkflow);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("MasterApprovalId", 2L);

		columnBitmasks.put("RoleId", 4L);

		columnBitmasks.put("MenuId", 8L);

		columnBitmasks.put("ApprovalGroup", 16L);

		columnBitmasks.put("ApprovalWorkflow", 32L);

		columnBitmasks.put("RowStatus", 64L);

		columnBitmasks.put("CreatedDate", 128L);

		columnBitmasks.put("CreatedBy", 256L);

		columnBitmasks.put("ModifiedDate", 512L);

		columnBitmasks.put("ModifiedBy", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MasterApprovalJournal _escapedModel;

}