/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.MenuAuthorization;
import com.astra.dewa.model.MenuAuthorizationModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MenuAuthorization service. Represents a row in the &quot;MenuAuthorization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MenuAuthorizationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MenuAuthorizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MenuAuthorizationImpl
 * @generated
 */
public class MenuAuthorizationModelImpl
	extends BaseModelImpl<MenuAuthorization> implements MenuAuthorizationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a menu authorization model instance should use the <code>MenuAuthorization</code> interface instead.
	 */
	public static final String TABLE_NAME = "MenuAuthorization";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"RoleId", Types.INTEGER},
		{"Menus", Types.VARCHAR}, {"IsRssp", Types.BOOLEAN},
		{"IsCmsDso", Types.BOOLEAN}, {"RowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("RoleId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Menus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("IsRssp", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("IsCmsDso", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MenuAuthorization (Id INTEGER not null primary key IDENTITY,RoleId INTEGER,Menus VARCHAR(75) null,IsRssp BOOLEAN,IsCmsDso BOOLEAN,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table MenuAuthorization";

	public static final String ORDER_BY_JPQL =
		" ORDER BY menuAuthorization.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MenuAuthorization.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public MenuAuthorizationModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MenuAuthorization.class;
	}

	@Override
	public String getModelClassName() {
		return MenuAuthorization.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MenuAuthorization, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MenuAuthorization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MenuAuthorization, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MenuAuthorization)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MenuAuthorization, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MenuAuthorization, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MenuAuthorization)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MenuAuthorization, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MenuAuthorization, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MenuAuthorization, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MenuAuthorization, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MenuAuthorization, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<MenuAuthorization, Object>>();
		Map<String, BiConsumer<MenuAuthorization, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<MenuAuthorization, ?>>();

		attributeGetterFunctions.put("Id", MenuAuthorization::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<MenuAuthorization, Integer>)MenuAuthorization::setId);
		attributeGetterFunctions.put("RoleId", MenuAuthorization::getRoleId);
		attributeSetterBiConsumers.put(
			"RoleId",
			(BiConsumer<MenuAuthorization, Integer>)
				MenuAuthorization::setRoleId);
		attributeGetterFunctions.put("Menus", MenuAuthorization::getMenus);
		attributeSetterBiConsumers.put(
			"Menus",
			(BiConsumer<MenuAuthorization, String>)MenuAuthorization::setMenus);
		attributeGetterFunctions.put("IsRssp", MenuAuthorization::getIsRssp);
		attributeSetterBiConsumers.put(
			"IsRssp",
			(BiConsumer<MenuAuthorization, Boolean>)
				MenuAuthorization::setIsRssp);
		attributeGetterFunctions.put(
			"IsCmsDso", MenuAuthorization::getIsCmsDso);
		attributeSetterBiConsumers.put(
			"IsCmsDso",
			(BiConsumer<MenuAuthorization, Boolean>)
				MenuAuthorization::setIsCmsDso);
		attributeGetterFunctions.put(
			"RowStatus", MenuAuthorization::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<MenuAuthorization, Boolean>)
				MenuAuthorization::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", MenuAuthorization::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<MenuAuthorization, Date>)
				MenuAuthorization::setCreatedDate);
		attributeGetterFunctions.put(
			"CreatedBy", MenuAuthorization::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<MenuAuthorization, String>)
				MenuAuthorization::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", MenuAuthorization::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<MenuAuthorization, Date>)
				MenuAuthorization::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", MenuAuthorization::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<MenuAuthorization, String>)
				MenuAuthorization::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getRoleId() {
		return _RoleId;
	}

	@Override
	public void setRoleId(int RoleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RoleId = RoleId;
	}

	@Override
	public String getMenus() {
		if (_Menus == null) {
			return "";
		}
		else {
			return _Menus;
		}
	}

	@Override
	public void setMenus(String Menus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Menus = Menus;
	}

	@Override
	public boolean getIsRssp() {
		return _IsRssp;
	}

	@Override
	public boolean isIsRssp() {
		return _IsRssp;
	}

	@Override
	public void setIsRssp(boolean IsRssp) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_IsRssp = IsRssp;
	}

	@Override
	public boolean getIsCmsDso() {
		return _IsCmsDso;
	}

	@Override
	public boolean isIsCmsDso() {
		return _IsCmsDso;
	}

	@Override
	public void setIsCmsDso(boolean IsCmsDso) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_IsCmsDso = IsCmsDso;
	}

	@Override
	public boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public boolean isRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public MenuAuthorization toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MenuAuthorization>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MenuAuthorizationImpl menuAuthorizationImpl =
			new MenuAuthorizationImpl();

		menuAuthorizationImpl.setId(getId());
		menuAuthorizationImpl.setRoleId(getRoleId());
		menuAuthorizationImpl.setMenus(getMenus());
		menuAuthorizationImpl.setIsRssp(isIsRssp());
		menuAuthorizationImpl.setIsCmsDso(isIsCmsDso());
		menuAuthorizationImpl.setRowStatus(isRowStatus());
		menuAuthorizationImpl.setCreatedDate(getCreatedDate());
		menuAuthorizationImpl.setCreatedBy(getCreatedBy());
		menuAuthorizationImpl.setModifiedDate(getModifiedDate());
		menuAuthorizationImpl.setModifiedBy(getModifiedBy());

		menuAuthorizationImpl.resetOriginalValues();

		return menuAuthorizationImpl;
	}

	@Override
	public MenuAuthorization cloneWithOriginalValues() {
		MenuAuthorizationImpl menuAuthorizationImpl =
			new MenuAuthorizationImpl();

		menuAuthorizationImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		menuAuthorizationImpl.setRoleId(
			this.<Integer>getColumnOriginalValue("RoleId"));
		menuAuthorizationImpl.setMenus(
			this.<String>getColumnOriginalValue("Menus"));
		menuAuthorizationImpl.setIsRssp(
			this.<Boolean>getColumnOriginalValue("IsRssp"));
		menuAuthorizationImpl.setIsCmsDso(
			this.<Boolean>getColumnOriginalValue("IsCmsDso"));
		menuAuthorizationImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		menuAuthorizationImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		menuAuthorizationImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		menuAuthorizationImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		menuAuthorizationImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return menuAuthorizationImpl;
	}

	@Override
	public int compareTo(MenuAuthorization menuAuthorization) {
		int primaryKey = menuAuthorization.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MenuAuthorization)) {
			return false;
		}

		MenuAuthorization menuAuthorization = (MenuAuthorization)object;

		int primaryKey = menuAuthorization.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<MenuAuthorization> toCacheModel() {
		MenuAuthorizationCacheModel menuAuthorizationCacheModel =
			new MenuAuthorizationCacheModel();

		menuAuthorizationCacheModel.Id = getId();

		menuAuthorizationCacheModel.RoleId = getRoleId();

		menuAuthorizationCacheModel.Menus = getMenus();

		String Menus = menuAuthorizationCacheModel.Menus;

		if ((Menus != null) && (Menus.length() == 0)) {
			menuAuthorizationCacheModel.Menus = null;
		}

		menuAuthorizationCacheModel.IsRssp = isIsRssp();

		menuAuthorizationCacheModel.IsCmsDso = isIsCmsDso();

		menuAuthorizationCacheModel.RowStatus = isRowStatus();

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			menuAuthorizationCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			menuAuthorizationCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		menuAuthorizationCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = menuAuthorizationCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			menuAuthorizationCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			menuAuthorizationCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			menuAuthorizationCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		menuAuthorizationCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = menuAuthorizationCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			menuAuthorizationCacheModel.ModifiedBy = null;
		}

		return menuAuthorizationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MenuAuthorization, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MenuAuthorization, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MenuAuthorization, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(MenuAuthorization)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MenuAuthorization>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					MenuAuthorization.class, ModelWrapper.class);

	}

	private int _Id;
	private int _RoleId;
	private String _Menus;
	private boolean _IsRssp;
	private boolean _IsCmsDso;
	private boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<MenuAuthorization, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((MenuAuthorization)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("RoleId", _RoleId);
		_columnOriginalValues.put("Menus", _Menus);
		_columnOriginalValues.put("IsRssp", _IsRssp);
		_columnOriginalValues.put("IsCmsDso", _IsCmsDso);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("RoleId", 2L);

		columnBitmasks.put("Menus", 4L);

		columnBitmasks.put("IsRssp", 8L);

		columnBitmasks.put("IsCmsDso", 16L);

		columnBitmasks.put("RowStatus", 32L);

		columnBitmasks.put("CreatedDate", 64L);

		columnBitmasks.put("CreatedBy", 128L);

		columnBitmasks.put("ModifiedDate", 256L);

		columnBitmasks.put("ModifiedBy", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private MenuAuthorization _escapedModel;

}