/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.OTP;
import com.astra.dewa.model.OTPModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the OTP service. Represents a row in the &quot;OTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OTPModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OTPImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OTPImpl
 * @generated
 */
public class OTPModelImpl extends BaseModelImpl<OTP> implements OTPModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a otp model instance should use the <code>OTP</code> interface instead.
	 */
	public static final String TABLE_NAME = "OTP";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"OTPNumber", Types.INTEGER},
		{"EmailNewUser", Types.VARCHAR}, {"CreatedDate", Types.TIMESTAMP},
		{"ExpiredDate", Types.TIMESTAMP}, {"IsVerified", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("OTPNumber", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("EmailNewUser", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ExpiredDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("IsVerified", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OTP (Id INTEGER not null primary key IDENTITY,OTPNumber INTEGER,EmailNewUser VARCHAR(75) null,CreatedDate DATE null,ExpiredDate DATE null,IsVerified BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table OTP";

	public static final String ORDER_BY_JPQL = " ORDER BY otp.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY OTP.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public OTPModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OTP.class;
	}

	@Override
	public String getModelClassName() {
		return OTP.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<OTP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<OTP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OTP, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((OTP)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<OTP, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<OTP, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((OTP)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<OTP, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<OTP, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<OTP, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<OTP, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<OTP, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<OTP, Object>>();
		Map<String, BiConsumer<OTP, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<OTP, ?>>();

		attributeGetterFunctions.put("Id", OTP::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<OTP, Integer>)OTP::setId);
		attributeGetterFunctions.put("OTPNumber", OTP::getOTPNumber);
		attributeSetterBiConsumers.put(
			"OTPNumber", (BiConsumer<OTP, Integer>)OTP::setOTPNumber);
		attributeGetterFunctions.put("EmailNewUser", OTP::getEmailNewUser);
		attributeSetterBiConsumers.put(
			"EmailNewUser", (BiConsumer<OTP, String>)OTP::setEmailNewUser);
		attributeGetterFunctions.put("CreatedDate", OTP::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate", (BiConsumer<OTP, Date>)OTP::setCreatedDate);
		attributeGetterFunctions.put("ExpiredDate", OTP::getExpiredDate);
		attributeSetterBiConsumers.put(
			"ExpiredDate", (BiConsumer<OTP, Date>)OTP::setExpiredDate);
		attributeGetterFunctions.put("IsVerified", OTP::getIsVerified);
		attributeSetterBiConsumers.put(
			"IsVerified", (BiConsumer<OTP, Boolean>)OTP::setIsVerified);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getOTPNumber() {
		return _OTPNumber;
	}

	@Override
	public void setOTPNumber(int OTPNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_OTPNumber = OTPNumber;
	}

	@Override
	public String getEmailNewUser() {
		if (_EmailNewUser == null) {
			return "";
		}
		else {
			return _EmailNewUser;
		}
	}

	@Override
	public void setEmailNewUser(String EmailNewUser) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_EmailNewUser = EmailNewUser;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public Date getExpiredDate() {
		return _ExpiredDate;
	}

	@Override
	public void setExpiredDate(Date ExpiredDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ExpiredDate = ExpiredDate;
	}

	@Override
	public boolean getIsVerified() {
		return _IsVerified;
	}

	@Override
	public boolean isIsVerified() {
		return _IsVerified;
	}

	@Override
	public void setIsVerified(boolean IsVerified) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_IsVerified = IsVerified;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public OTP toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, OTP> escapedModelProxyProviderFunction =
				EscapedModelProxyProviderFunctionHolder.
					_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OTPImpl otpImpl = new OTPImpl();

		otpImpl.setId(getId());
		otpImpl.setOTPNumber(getOTPNumber());
		otpImpl.setEmailNewUser(getEmailNewUser());
		otpImpl.setCreatedDate(getCreatedDate());
		otpImpl.setExpiredDate(getExpiredDate());
		otpImpl.setIsVerified(isIsVerified());

		otpImpl.resetOriginalValues();

		return otpImpl;
	}

	@Override
	public OTP cloneWithOriginalValues() {
		OTPImpl otpImpl = new OTPImpl();

		otpImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		otpImpl.setOTPNumber(this.<Integer>getColumnOriginalValue("OTPNumber"));
		otpImpl.setEmailNewUser(
			this.<String>getColumnOriginalValue("EmailNewUser"));
		otpImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		otpImpl.setExpiredDate(
			this.<Date>getColumnOriginalValue("ExpiredDate"));
		otpImpl.setIsVerified(
			this.<Boolean>getColumnOriginalValue("IsVerified"));

		return otpImpl;
	}

	@Override
	public int compareTo(OTP otp) {
		int primaryKey = otp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof OTP)) {
			return false;
		}

		OTP otp = (OTP)object;

		int primaryKey = otp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<OTP> toCacheModel() {
		OTPCacheModel otpCacheModel = new OTPCacheModel();

		otpCacheModel.Id = getId();

		otpCacheModel.OTPNumber = getOTPNumber();

		otpCacheModel.EmailNewUser = getEmailNewUser();

		String EmailNewUser = otpCacheModel.EmailNewUser;

		if ((EmailNewUser != null) && (EmailNewUser.length() == 0)) {
			otpCacheModel.EmailNewUser = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			otpCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			otpCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		Date ExpiredDate = getExpiredDate();

		if (ExpiredDate != null) {
			otpCacheModel.ExpiredDate = ExpiredDate.getTime();
		}
		else {
			otpCacheModel.ExpiredDate = Long.MIN_VALUE;
		}

		otpCacheModel.IsVerified = isIsVerified();

		return otpCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<OTP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<OTP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OTP, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((OTP)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, OTP>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					OTP.class, ModelWrapper.class);

	}

	private int _Id;
	private int _OTPNumber;
	private String _EmailNewUser;
	private Date _CreatedDate;
	private Date _ExpiredDate;
	private boolean _IsVerified;

	public <T> T getColumnValue(String columnName) {
		Function<OTP, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((OTP)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("OTPNumber", _OTPNumber);
		_columnOriginalValues.put("EmailNewUser", _EmailNewUser);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("ExpiredDate", _ExpiredDate);
		_columnOriginalValues.put("IsVerified", _IsVerified);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("OTPNumber", 2L);

		columnBitmasks.put("EmailNewUser", 4L);

		columnBitmasks.put("CreatedDate", 8L);

		columnBitmasks.put("ExpiredDate", 16L);

		columnBitmasks.put("IsVerified", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private OTP _escapedModel;

}