/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.PeriodeReview;
import com.astra.dewa.model.PeriodeReviewModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PeriodeReview service. Represents a row in the &quot;periode_review&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PeriodeReviewModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PeriodeReviewImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PeriodeReviewImpl
 * @generated
 */
public class PeriodeReviewModelImpl
	extends BaseModelImpl<PeriodeReview> implements PeriodeReviewModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a periode review model instance should use the <code>PeriodeReview</code> interface instead.
	 */
	public static final String TABLE_NAME = "periode_review";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.VARCHAR}, {"Name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table periode_review (Id VARCHAR(75) not null primary key,Name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table periode_review";

	public static final String ORDER_BY_JPQL = " ORDER BY periodeReview.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY periode_review.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PeriodeReviewModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return PeriodeReview.class;
	}

	@Override
	public String getModelClassName() {
		return PeriodeReview.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PeriodeReview, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PeriodeReview, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PeriodeReview, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PeriodeReview)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PeriodeReview, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PeriodeReview, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PeriodeReview)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PeriodeReview, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PeriodeReview, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<PeriodeReview, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PeriodeReview, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PeriodeReview, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<PeriodeReview, Object>>();
		Map<String, BiConsumer<PeriodeReview, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<PeriodeReview, ?>>();

		attributeGetterFunctions.put("Id", PeriodeReview::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<PeriodeReview, String>)PeriodeReview::setId);
		attributeGetterFunctions.put("Name", PeriodeReview::getName);
		attributeSetterBiConsumers.put(
			"Name", (BiConsumer<PeriodeReview, String>)PeriodeReview::setName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getId() {
		if (_Id == null) {
			return "";
		}
		else {
			return _Id;
		}
	}

	@Override
	public void setId(String Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public String getName() {
		if (_Name == null) {
			return "";
		}
		else {
			return _Name;
		}
	}

	@Override
	public void setName(String Name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Name = Name;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public PeriodeReview toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PeriodeReview>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PeriodeReviewImpl periodeReviewImpl = new PeriodeReviewImpl();

		periodeReviewImpl.setId(getId());
		periodeReviewImpl.setName(getName());

		periodeReviewImpl.resetOriginalValues();

		return periodeReviewImpl;
	}

	@Override
	public PeriodeReview cloneWithOriginalValues() {
		PeriodeReviewImpl periodeReviewImpl = new PeriodeReviewImpl();

		periodeReviewImpl.setId(this.<String>getColumnOriginalValue("Id"));
		periodeReviewImpl.setName(this.<String>getColumnOriginalValue("Name"));

		return periodeReviewImpl;
	}

	@Override
	public int compareTo(PeriodeReview periodeReview) {
		String primaryKey = periodeReview.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PeriodeReview)) {
			return false;
		}

		PeriodeReview periodeReview = (PeriodeReview)object;

		String primaryKey = periodeReview.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PeriodeReview> toCacheModel() {
		PeriodeReviewCacheModel periodeReviewCacheModel =
			new PeriodeReviewCacheModel();

		periodeReviewCacheModel.Id = getId();

		String Id = periodeReviewCacheModel.Id;

		if ((Id != null) && (Id.length() == 0)) {
			periodeReviewCacheModel.Id = null;
		}

		periodeReviewCacheModel.Name = getName();

		String Name = periodeReviewCacheModel.Name;

		if ((Name != null) && (Name.length() == 0)) {
			periodeReviewCacheModel.Name = null;
		}

		return periodeReviewCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PeriodeReview, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PeriodeReview, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PeriodeReview, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((PeriodeReview)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PeriodeReview>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PeriodeReview.class, ModelWrapper.class);

	}

	private String _Id;
	private String _Name;

	public <T> T getColumnValue(String columnName) {
		Function<PeriodeReview, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PeriodeReview)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("Name", _Name);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("Name", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PeriodeReview _escapedModel;

}