/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.Roles;
import com.astra.dewa.model.RolesModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Roles service. Represents a row in the &quot;Roles&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RolesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RolesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RolesImpl
 * @generated
 */
public class RolesModelImpl extends BaseModelImpl<Roles> implements RolesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a roles model instance should use the <code>Roles</code> interface instead.
	 */
	public static final String TABLE_NAME = "Roles";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"Name", Types.VARCHAR},
		{"Description", Types.VARCHAR}, {"RoleIdMember", Types.VARCHAR},
		{"RowStatus", Types.BOOLEAN}, {"CreatedDate", Types.TIMESTAMP},
		{"CreatedBy", Types.VARCHAR}, {"ModifiedDate", Types.TIMESTAMP},
		{"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RoleIdMember", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Roles (Id INTEGER not null primary key IDENTITY,Name VARCHAR(75) null,Description VARCHAR(75) null,RoleIdMember VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table Roles";

	public static final String ORDER_BY_JPQL = " ORDER BY roles.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY Roles.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public RolesModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Roles.class;
	}

	@Override
	public String getModelClassName() {
		return Roles.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Roles, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Roles, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Roles, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Roles)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Roles, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Roles, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Roles)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Roles, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Roles, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Roles, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Roles, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Roles, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Roles, Object>>();
		Map<String, BiConsumer<Roles, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Roles, ?>>();

		attributeGetterFunctions.put("Id", Roles::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<Roles, Integer>)Roles::setId);
		attributeGetterFunctions.put("Name", Roles::getName);
		attributeSetterBiConsumers.put(
			"Name", (BiConsumer<Roles, String>)Roles::setName);
		attributeGetterFunctions.put("Description", Roles::getDescription);
		attributeSetterBiConsumers.put(
			"Description", (BiConsumer<Roles, String>)Roles::setDescription);
		attributeGetterFunctions.put("RoleIdMember", Roles::getRoleIdMember);
		attributeSetterBiConsumers.put(
			"RoleIdMember", (BiConsumer<Roles, String>)Roles::setRoleIdMember);
		attributeGetterFunctions.put("RowStatus", Roles::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus", (BiConsumer<Roles, Boolean>)Roles::setRowStatus);
		attributeGetterFunctions.put("CreatedDate", Roles::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate", (BiConsumer<Roles, Date>)Roles::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", Roles::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy", (BiConsumer<Roles, String>)Roles::setCreatedBy);
		attributeGetterFunctions.put("ModifiedDate", Roles::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate", (BiConsumer<Roles, Date>)Roles::setModifiedDate);
		attributeGetterFunctions.put("ModifiedBy", Roles::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy", (BiConsumer<Roles, String>)Roles::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public String getName() {
		if (_Name == null) {
			return "";
		}
		else {
			return _Name;
		}
	}

	@Override
	public void setName(String Name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Name = Name;
	}

	@Override
	public String getDescription() {
		if (_Description == null) {
			return "";
		}
		else {
			return _Description;
		}
	}

	@Override
	public void setDescription(String Description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Description = Description;
	}

	@Override
	public String getRoleIdMember() {
		if (_RoleIdMember == null) {
			return "";
		}
		else {
			return _RoleIdMember;
		}
	}

	@Override
	public void setRoleIdMember(String RoleIdMember) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RoleIdMember = RoleIdMember;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Roles toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Roles>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RolesImpl rolesImpl = new RolesImpl();

		rolesImpl.setId(getId());
		rolesImpl.setName(getName());
		rolesImpl.setDescription(getDescription());
		rolesImpl.setRoleIdMember(getRoleIdMember());
		rolesImpl.setRowStatus(getRowStatus());
		rolesImpl.setCreatedDate(getCreatedDate());
		rolesImpl.setCreatedBy(getCreatedBy());
		rolesImpl.setModifiedDate(getModifiedDate());
		rolesImpl.setModifiedBy(getModifiedBy());

		rolesImpl.resetOriginalValues();

		return rolesImpl;
	}

	@Override
	public Roles cloneWithOriginalValues() {
		RolesImpl rolesImpl = new RolesImpl();

		rolesImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		rolesImpl.setName(this.<String>getColumnOriginalValue("Name"));
		rolesImpl.setDescription(
			this.<String>getColumnOriginalValue("Description"));
		rolesImpl.setRoleIdMember(
			this.<String>getColumnOriginalValue("RoleIdMember"));
		rolesImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		rolesImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		rolesImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		rolesImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		rolesImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return rolesImpl;
	}

	@Override
	public int compareTo(Roles roles) {
		int primaryKey = roles.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Roles)) {
			return false;
		}

		Roles roles = (Roles)object;

		int primaryKey = roles.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Roles> toCacheModel() {
		RolesCacheModel rolesCacheModel = new RolesCacheModel();

		rolesCacheModel.Id = getId();

		rolesCacheModel.Name = getName();

		String Name = rolesCacheModel.Name;

		if ((Name != null) && (Name.length() == 0)) {
			rolesCacheModel.Name = null;
		}

		rolesCacheModel.Description = getDescription();

		String Description = rolesCacheModel.Description;

		if ((Description != null) && (Description.length() == 0)) {
			rolesCacheModel.Description = null;
		}

		rolesCacheModel.RoleIdMember = getRoleIdMember();

		String RoleIdMember = rolesCacheModel.RoleIdMember;

		if ((RoleIdMember != null) && (RoleIdMember.length() == 0)) {
			rolesCacheModel.RoleIdMember = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			rolesCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			rolesCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			rolesCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		rolesCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = rolesCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			rolesCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			rolesCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			rolesCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		rolesCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = rolesCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			rolesCacheModel.ModifiedBy = null;
		}

		return rolesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Roles, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Roles, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Roles, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Roles)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Roles>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Roles.class, ModelWrapper.class);

	}

	private int _Id;
	private String _Name;
	private String _Description;
	private String _RoleIdMember;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<Roles, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Roles)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("Name", _Name);
		_columnOriginalValues.put("Description", _Description);
		_columnOriginalValues.put("RoleIdMember", _RoleIdMember);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("Name", 2L);

		columnBitmasks.put("Description", 4L);

		columnBitmasks.put("RoleIdMember", 8L);

		columnBitmasks.put("RowStatus", 16L);

		columnBitmasks.put("CreatedDate", 32L);

		columnBitmasks.put("CreatedBy", 64L);

		columnBitmasks.put("ModifiedDate", 128L);

		columnBitmasks.put("ModifiedBy", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Roles _escapedModel;

}