/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.SkIris;
import com.astra.dewa.model.SkIrisModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SkIris service. Represents a row in the &quot;sk_iris&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SkIrisModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SkIrisImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SkIrisImpl
 * @generated
 */
public class SkIrisModelImpl
	extends BaseModelImpl<SkIris> implements SkIrisModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sk iris model instance should use the <code>SkIris</code> interface instead.
	 */
	public static final String TABLE_NAME = "sk_iris";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"Periode", Types.VARCHAR},
		{"DealerId", Types.INTEGER}, {"WilayahId", Types.BIGINT},
		{"Tahun", Types.INTEGER}, {"Kategori", Types.VARCHAR},
		{"FileId", Types.BIGINT}, {"FileName", Types.VARCHAR},
		{"FilePath", Types.VARCHAR}, {"RowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Periode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("WilayahId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Tahun", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Kategori", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FilePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table sk_iris (Id INTEGER not null primary key IDENTITY,Periode VARCHAR(75) null,DealerId INTEGER,WilayahId LONG,Tahun INTEGER,Kategori VARCHAR(75) null,FileId LONG,FileName VARCHAR(75) null,FilePath VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table sk_iris";

	public static final String ORDER_BY_JPQL = " ORDER BY skIris.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY sk_iris.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SkIrisModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SkIris.class;
	}

	@Override
	public String getModelClassName() {
		return SkIris.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SkIris, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SkIris, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SkIris, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((SkIris)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SkIris, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SkIris, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SkIris)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SkIris, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SkIris, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SkIris, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SkIris, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SkIris, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<SkIris, Object>>();
		Map<String, BiConsumer<SkIris, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SkIris, ?>>();

		attributeGetterFunctions.put("Id", SkIris::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<SkIris, Integer>)SkIris::setId);
		attributeGetterFunctions.put("Periode", SkIris::getPeriode);
		attributeSetterBiConsumers.put(
			"Periode", (BiConsumer<SkIris, String>)SkIris::setPeriode);
		attributeGetterFunctions.put("DealerId", SkIris::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId", (BiConsumer<SkIris, Integer>)SkIris::setDealerId);
		attributeGetterFunctions.put("WilayahId", SkIris::getWilayahId);
		attributeSetterBiConsumers.put(
			"WilayahId", (BiConsumer<SkIris, Long>)SkIris::setWilayahId);
		attributeGetterFunctions.put("Tahun", SkIris::getTahun);
		attributeSetterBiConsumers.put(
			"Tahun", (BiConsumer<SkIris, Integer>)SkIris::setTahun);
		attributeGetterFunctions.put("Kategori", SkIris::getKategori);
		attributeSetterBiConsumers.put(
			"Kategori", (BiConsumer<SkIris, String>)SkIris::setKategori);
		attributeGetterFunctions.put("FileId", SkIris::getFileId);
		attributeSetterBiConsumers.put(
			"FileId", (BiConsumer<SkIris, Long>)SkIris::setFileId);
		attributeGetterFunctions.put("FileName", SkIris::getFileName);
		attributeSetterBiConsumers.put(
			"FileName", (BiConsumer<SkIris, String>)SkIris::setFileName);
		attributeGetterFunctions.put("FilePath", SkIris::getFilePath);
		attributeSetterBiConsumers.put(
			"FilePath", (BiConsumer<SkIris, String>)SkIris::setFilePath);
		attributeGetterFunctions.put("RowStatus", SkIris::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus", (BiConsumer<SkIris, Boolean>)SkIris::setRowStatus);
		attributeGetterFunctions.put("CreatedDate", SkIris::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate", (BiConsumer<SkIris, Date>)SkIris::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", SkIris::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy", (BiConsumer<SkIris, String>)SkIris::setCreatedBy);
		attributeGetterFunctions.put("ModifiedDate", SkIris::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate", (BiConsumer<SkIris, Date>)SkIris::setModifiedDate);
		attributeGetterFunctions.put("ModifiedBy", SkIris::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy", (BiConsumer<SkIris, String>)SkIris::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public String getPeriode() {
		if (_Periode == null) {
			return "";
		}
		else {
			return _Periode;
		}
	}

	@Override
	public void setPeriode(String Periode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Periode = Periode;
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public long getWilayahId() {
		return _WilayahId;
	}

	@Override
	public void setWilayahId(long WilayahId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_WilayahId = WilayahId;
	}

	@Override
	public Integer getTahun() {
		return _Tahun;
	}

	@Override
	public void setTahun(Integer Tahun) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Tahun = Tahun;
	}

	@Override
	public String getKategori() {
		if (_Kategori == null) {
			return "";
		}
		else {
			return _Kategori;
		}
	}

	@Override
	public void setKategori(String Kategori) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Kategori = Kategori;
	}

	@Override
	public Long getFileId() {
		return _FileId;
	}

	@Override
	public void setFileId(Long FileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileId = FileId;
	}

	@Override
	public String getFileName() {
		if (_FileName == null) {
			return "";
		}
		else {
			return _FileName;
		}
	}

	@Override
	public void setFileName(String FileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileName = FileName;
	}

	@Override
	public String getFilePath() {
		if (_FilePath == null) {
			return "";
		}
		else {
			return _FilePath;
		}
	}

	@Override
	public void setFilePath(String FilePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FilePath = FilePath;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public SkIris toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SkIris>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SkIrisImpl skIrisImpl = new SkIrisImpl();

		skIrisImpl.setId(getId());
		skIrisImpl.setPeriode(getPeriode());
		skIrisImpl.setDealerId(getDealerId());
		skIrisImpl.setWilayahId(getWilayahId());
		skIrisImpl.setTahun(getTahun());
		skIrisImpl.setKategori(getKategori());
		skIrisImpl.setFileId(getFileId());
		skIrisImpl.setFileName(getFileName());
		skIrisImpl.setFilePath(getFilePath());
		skIrisImpl.setRowStatus(getRowStatus());
		skIrisImpl.setCreatedDate(getCreatedDate());
		skIrisImpl.setCreatedBy(getCreatedBy());
		skIrisImpl.setModifiedDate(getModifiedDate());
		skIrisImpl.setModifiedBy(getModifiedBy());

		skIrisImpl.resetOriginalValues();

		return skIrisImpl;
	}

	@Override
	public SkIris cloneWithOriginalValues() {
		SkIrisImpl skIrisImpl = new SkIrisImpl();

		skIrisImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		skIrisImpl.setPeriode(this.<String>getColumnOriginalValue("Periode"));
		skIrisImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("DealerId"));
		skIrisImpl.setWilayahId(this.<Long>getColumnOriginalValue("WilayahId"));
		skIrisImpl.setTahun(this.<Integer>getColumnOriginalValue("Tahun"));
		skIrisImpl.setKategori(this.<String>getColumnOriginalValue("Kategori"));
		skIrisImpl.setFileId(this.<Long>getColumnOriginalValue("FileId"));
		skIrisImpl.setFileName(this.<String>getColumnOriginalValue("FileName"));
		skIrisImpl.setFilePath(this.<String>getColumnOriginalValue("FilePath"));
		skIrisImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		skIrisImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		skIrisImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		skIrisImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		skIrisImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return skIrisImpl;
	}

	@Override
	public int compareTo(SkIris skIris) {
		int primaryKey = skIris.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SkIris)) {
			return false;
		}

		SkIris skIris = (SkIris)object;

		int primaryKey = skIris.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SkIris> toCacheModel() {
		SkIrisCacheModel skIrisCacheModel = new SkIrisCacheModel();

		skIrisCacheModel.Id = getId();

		skIrisCacheModel.Periode = getPeriode();

		String Periode = skIrisCacheModel.Periode;

		if ((Periode != null) && (Periode.length() == 0)) {
			skIrisCacheModel.Periode = null;
		}

		skIrisCacheModel.DealerId = getDealerId();

		skIrisCacheModel.WilayahId = getWilayahId();

		Integer Tahun = getTahun();

		if (Tahun != null) {
			skIrisCacheModel.Tahun = Tahun;
		}

		skIrisCacheModel.Kategori = getKategori();

		String Kategori = skIrisCacheModel.Kategori;

		if ((Kategori != null) && (Kategori.length() == 0)) {
			skIrisCacheModel.Kategori = null;
		}

		Long FileId = getFileId();

		if (FileId != null) {
			skIrisCacheModel.FileId = FileId;
		}

		skIrisCacheModel.FileName = getFileName();

		String FileName = skIrisCacheModel.FileName;

		if ((FileName != null) && (FileName.length() == 0)) {
			skIrisCacheModel.FileName = null;
		}

		skIrisCacheModel.FilePath = getFilePath();

		String FilePath = skIrisCacheModel.FilePath;

		if ((FilePath != null) && (FilePath.length() == 0)) {
			skIrisCacheModel.FilePath = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			skIrisCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			skIrisCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			skIrisCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		skIrisCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = skIrisCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			skIrisCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			skIrisCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			skIrisCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		skIrisCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = skIrisCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			skIrisCacheModel.ModifiedBy = null;
		}

		return skIrisCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SkIris, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SkIris, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SkIris, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SkIris)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SkIris>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SkIris.class, ModelWrapper.class);

	}

	private int _Id;
	private String _Periode;
	private int _DealerId;
	private long _WilayahId;
	private Integer _Tahun;
	private String _Kategori;
	private Long _FileId;
	private String _FileName;
	private String _FilePath;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<SkIris, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SkIris)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("Periode", _Periode);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("WilayahId", _WilayahId);
		_columnOriginalValues.put("Tahun", _Tahun);
		_columnOriginalValues.put("Kategori", _Kategori);
		_columnOriginalValues.put("FileId", _FileId);
		_columnOriginalValues.put("FileName", _FileName);
		_columnOriginalValues.put("FilePath", _FilePath);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("Periode", 2L);

		columnBitmasks.put("DealerId", 4L);

		columnBitmasks.put("WilayahId", 8L);

		columnBitmasks.put("Tahun", 16L);

		columnBitmasks.put("Kategori", 32L);

		columnBitmasks.put("FileId", 64L);

		columnBitmasks.put("FileName", 128L);

		columnBitmasks.put("FilePath", 256L);

		columnBitmasks.put("RowStatus", 512L);

		columnBitmasks.put("CreatedDate", 1024L);

		columnBitmasks.put("CreatedBy", 2048L);

		columnBitmasks.put("ModifiedDate", 4096L);

		columnBitmasks.put("ModifiedBy", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SkIris _escapedModel;

}