/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.SuratPenaltyStock;
import com.astra.dewa.model.SuratPenaltyStockModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SuratPenaltyStock service. Represents a row in the &quot;surat_penalty_stock&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SuratPenaltyStockModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SuratPenaltyStockImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SuratPenaltyStockImpl
 * @generated
 */
public class SuratPenaltyStockModelImpl
	extends BaseModelImpl<SuratPenaltyStock> implements SuratPenaltyStockModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a surat penalty stock model instance should use the <code>SuratPenaltyStock</code> interface instead.
	 */
	public static final String TABLE_NAME = "surat_penalty_stock";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.BIGINT}, {"DealerId", Types.INTEGER},
		{"Judul", Types.VARCHAR}, {"Periode", Types.VARCHAR},
		{"Tahun", Types.INTEGER}, {"FileId", Types.BIGINT},
		{"FileName", Types.VARCHAR}, {"CreatedDate", Types.TIMESTAMP},
		{"CreatedBy", Types.VARCHAR}, {"ModifiedDate", Types.TIMESTAMP},
		{"ModifiedBy", Types.VARCHAR}, {"RowStatus", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Judul", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Periode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Tahun", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("FileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table surat_penalty_stock (Id LONG not null primary key,DealerId INTEGER,Judul VARCHAR(75) null,Periode VARCHAR(75) null,Tahun INTEGER,FileId LONG,FileName VARCHAR(75) null,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null,RowStatus BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table surat_penalty_stock";

	public static final String ORDER_BY_JPQL =
		" ORDER BY suratPenaltyStock.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY surat_penalty_stock.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SuratPenaltyStockModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SuratPenaltyStock.class;
	}

	@Override
	public String getModelClassName() {
		return SuratPenaltyStock.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SuratPenaltyStock, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SuratPenaltyStock, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SuratPenaltyStock, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SuratPenaltyStock)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SuratPenaltyStock, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SuratPenaltyStock, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SuratPenaltyStock)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SuratPenaltyStock, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SuratPenaltyStock, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SuratPenaltyStock, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SuratPenaltyStock, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SuratPenaltyStock, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<SuratPenaltyStock, Object>>();
		Map<String, BiConsumer<SuratPenaltyStock, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<SuratPenaltyStock, ?>>();

		attributeGetterFunctions.put("Id", SuratPenaltyStock::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<SuratPenaltyStock, Long>)SuratPenaltyStock::setId);
		attributeGetterFunctions.put(
			"DealerId", SuratPenaltyStock::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId",
			(BiConsumer<SuratPenaltyStock, Integer>)
				SuratPenaltyStock::setDealerId);
		attributeGetterFunctions.put("Judul", SuratPenaltyStock::getJudul);
		attributeSetterBiConsumers.put(
			"Judul",
			(BiConsumer<SuratPenaltyStock, String>)SuratPenaltyStock::setJudul);
		attributeGetterFunctions.put("Periode", SuratPenaltyStock::getPeriode);
		attributeSetterBiConsumers.put(
			"Periode",
			(BiConsumer<SuratPenaltyStock, String>)
				SuratPenaltyStock::setPeriode);
		attributeGetterFunctions.put("Tahun", SuratPenaltyStock::getTahun);
		attributeSetterBiConsumers.put(
			"Tahun",
			(BiConsumer<SuratPenaltyStock, Integer>)
				SuratPenaltyStock::setTahun);
		attributeGetterFunctions.put("FileId", SuratPenaltyStock::getFileId);
		attributeSetterBiConsumers.put(
			"FileId",
			(BiConsumer<SuratPenaltyStock, Long>)SuratPenaltyStock::setFileId);
		attributeGetterFunctions.put(
			"FileName", SuratPenaltyStock::getFileName);
		attributeSetterBiConsumers.put(
			"FileName",
			(BiConsumer<SuratPenaltyStock, String>)
				SuratPenaltyStock::setFileName);
		attributeGetterFunctions.put(
			"CreatedDate", SuratPenaltyStock::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<SuratPenaltyStock, Date>)
				SuratPenaltyStock::setCreatedDate);
		attributeGetterFunctions.put(
			"CreatedBy", SuratPenaltyStock::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<SuratPenaltyStock, String>)
				SuratPenaltyStock::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", SuratPenaltyStock::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<SuratPenaltyStock, Date>)
				SuratPenaltyStock::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", SuratPenaltyStock::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<SuratPenaltyStock, String>)
				SuratPenaltyStock::setModifiedBy);
		attributeGetterFunctions.put(
			"RowStatus", SuratPenaltyStock::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<SuratPenaltyStock, Boolean>)
				SuratPenaltyStock::setRowStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _Id;
	}

	@Override
	public void setId(long Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public String getJudul() {
		if (_Judul == null) {
			return "";
		}
		else {
			return _Judul;
		}
	}

	@Override
	public void setJudul(String Judul) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Judul = Judul;
	}

	@Override
	public String getPeriode() {
		if (_Periode == null) {
			return "";
		}
		else {
			return _Periode;
		}
	}

	@Override
	public void setPeriode(String Periode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Periode = Periode;
	}

	@Override
	public int getTahun() {
		return _Tahun;
	}

	@Override
	public void setTahun(int Tahun) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Tahun = Tahun;
	}

	@Override
	public Long getFileId() {
		return _FileId;
	}

	@Override
	public void setFileId(Long FileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileId = FileId;
	}

	@Override
	public String getFileName() {
		if (_FileName == null) {
			return "";
		}
		else {
			return _FileName;
		}
	}

	@Override
	public void setFileName(String FileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FileName = FileName;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, SuratPenaltyStock.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SuratPenaltyStock toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SuratPenaltyStock>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SuratPenaltyStockImpl suratPenaltyStockImpl =
			new SuratPenaltyStockImpl();

		suratPenaltyStockImpl.setId(getId());
		suratPenaltyStockImpl.setDealerId(getDealerId());
		suratPenaltyStockImpl.setJudul(getJudul());
		suratPenaltyStockImpl.setPeriode(getPeriode());
		suratPenaltyStockImpl.setTahun(getTahun());
		suratPenaltyStockImpl.setFileId(getFileId());
		suratPenaltyStockImpl.setFileName(getFileName());
		suratPenaltyStockImpl.setCreatedDate(getCreatedDate());
		suratPenaltyStockImpl.setCreatedBy(getCreatedBy());
		suratPenaltyStockImpl.setModifiedDate(getModifiedDate());
		suratPenaltyStockImpl.setModifiedBy(getModifiedBy());
		suratPenaltyStockImpl.setRowStatus(getRowStatus());

		suratPenaltyStockImpl.resetOriginalValues();

		return suratPenaltyStockImpl;
	}

	@Override
	public SuratPenaltyStock cloneWithOriginalValues() {
		SuratPenaltyStockImpl suratPenaltyStockImpl =
			new SuratPenaltyStockImpl();

		suratPenaltyStockImpl.setId(this.<Long>getColumnOriginalValue("Id"));
		suratPenaltyStockImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("DealerId"));
		suratPenaltyStockImpl.setJudul(
			this.<String>getColumnOriginalValue("Judul"));
		suratPenaltyStockImpl.setPeriode(
			this.<String>getColumnOriginalValue("Periode"));
		suratPenaltyStockImpl.setTahun(
			this.<Integer>getColumnOriginalValue("Tahun"));
		suratPenaltyStockImpl.setFileId(
			this.<Long>getColumnOriginalValue("FileId"));
		suratPenaltyStockImpl.setFileName(
			this.<String>getColumnOriginalValue("FileName"));
		suratPenaltyStockImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		suratPenaltyStockImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		suratPenaltyStockImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		suratPenaltyStockImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));
		suratPenaltyStockImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));

		return suratPenaltyStockImpl;
	}

	@Override
	public int compareTo(SuratPenaltyStock suratPenaltyStock) {
		long primaryKey = suratPenaltyStock.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SuratPenaltyStock)) {
			return false;
		}

		SuratPenaltyStock suratPenaltyStock = (SuratPenaltyStock)object;

		long primaryKey = suratPenaltyStock.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SuratPenaltyStock> toCacheModel() {
		SuratPenaltyStockCacheModel suratPenaltyStockCacheModel =
			new SuratPenaltyStockCacheModel();

		suratPenaltyStockCacheModel.Id = getId();

		suratPenaltyStockCacheModel.DealerId = getDealerId();

		suratPenaltyStockCacheModel.Judul = getJudul();

		String Judul = suratPenaltyStockCacheModel.Judul;

		if ((Judul != null) && (Judul.length() == 0)) {
			suratPenaltyStockCacheModel.Judul = null;
		}

		suratPenaltyStockCacheModel.Periode = getPeriode();

		String Periode = suratPenaltyStockCacheModel.Periode;

		if ((Periode != null) && (Periode.length() == 0)) {
			suratPenaltyStockCacheModel.Periode = null;
		}

		suratPenaltyStockCacheModel.Tahun = getTahun();

		Long FileId = getFileId();

		if (FileId != null) {
			suratPenaltyStockCacheModel.FileId = FileId;
		}

		suratPenaltyStockCacheModel.FileName = getFileName();

		String FileName = suratPenaltyStockCacheModel.FileName;

		if ((FileName != null) && (FileName.length() == 0)) {
			suratPenaltyStockCacheModel.FileName = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			suratPenaltyStockCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			suratPenaltyStockCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		suratPenaltyStockCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = suratPenaltyStockCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			suratPenaltyStockCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			suratPenaltyStockCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			suratPenaltyStockCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		suratPenaltyStockCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = suratPenaltyStockCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			suratPenaltyStockCacheModel.ModifiedBy = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			suratPenaltyStockCacheModel.RowStatus = RowStatus;
		}

		return suratPenaltyStockCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SuratPenaltyStock, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SuratPenaltyStock, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SuratPenaltyStock, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(SuratPenaltyStock)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SuratPenaltyStock>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SuratPenaltyStock.class, ModelWrapper.class);

	}

	private long _Id;
	private int _DealerId;
	private String _Judul;
	private String _Periode;
	private int _Tahun;
	private Long _FileId;
	private String _FileName;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;
	private Boolean _RowStatus;

	public <T> T getColumnValue(String columnName) {
		Function<SuratPenaltyStock, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SuratPenaltyStock)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("Judul", _Judul);
		_columnOriginalValues.put("Periode", _Periode);
		_columnOriginalValues.put("Tahun", _Tahun);
		_columnOriginalValues.put("FileId", _FileId);
		_columnOriginalValues.put("FileName", _FileName);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
		_columnOriginalValues.put("RowStatus", _RowStatus);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("DealerId", 2L);

		columnBitmasks.put("Judul", 4L);

		columnBitmasks.put("Periode", 8L);

		columnBitmasks.put("Tahun", 16L);

		columnBitmasks.put("FileId", 32L);

		columnBitmasks.put("FileName", 64L);

		columnBitmasks.put("CreatedDate", 128L);

		columnBitmasks.put("CreatedBy", 256L);

		columnBitmasks.put("ModifiedDate", 512L);

		columnBitmasks.put("ModifiedBy", 1024L);

		columnBitmasks.put("RowStatus", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SuratPenaltyStock _escapedModel;

}