/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.TipeKendaraan;
import com.astra.dewa.model.TipeKendaraanModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TipeKendaraan service. Represents a row in the &quot;tipe_kendaraan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TipeKendaraanModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TipeKendaraanImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TipeKendaraanImpl
 * @generated
 */
public class TipeKendaraanModelImpl
	extends BaseModelImpl<TipeKendaraan> implements TipeKendaraanModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tipe kendaraan model instance should use the <code>TipeKendaraan</code> interface instead.
	 */
	public static final String TABLE_NAME = "tipe_kendaraan";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"Name", Types.VARCHAR},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR},
		{"RowStatus", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table tipe_kendaraan (Id INTEGER not null primary key IDENTITY,Name VARCHAR(75) null,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null,RowStatus BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table tipe_kendaraan";

	public static final String ORDER_BY_JPQL = " ORDER BY tipeKendaraan.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY tipe_kendaraan.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TipeKendaraanModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TipeKendaraan.class;
	}

	@Override
	public String getModelClassName() {
		return TipeKendaraan.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TipeKendaraan, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TipeKendaraan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TipeKendaraan, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TipeKendaraan)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TipeKendaraan, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TipeKendaraan, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TipeKendaraan)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TipeKendaraan, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TipeKendaraan, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TipeKendaraan, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TipeKendaraan, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TipeKendaraan, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TipeKendaraan, Object>>();
		Map<String, BiConsumer<TipeKendaraan, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TipeKendaraan, ?>>();

		attributeGetterFunctions.put("Id", TipeKendaraan::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<TipeKendaraan, Integer>)TipeKendaraan::setId);
		attributeGetterFunctions.put("Name", TipeKendaraan::getName);
		attributeSetterBiConsumers.put(
			"Name", (BiConsumer<TipeKendaraan, String>)TipeKendaraan::setName);
		attributeGetterFunctions.put(
			"CreatedDate", TipeKendaraan::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<TipeKendaraan, Date>)TipeKendaraan::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", TipeKendaraan::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<TipeKendaraan, String>)TipeKendaraan::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", TipeKendaraan::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<TipeKendaraan, Date>)TipeKendaraan::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", TipeKendaraan::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<TipeKendaraan, String>)TipeKendaraan::setModifiedBy);
		attributeGetterFunctions.put("RowStatus", TipeKendaraan::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<TipeKendaraan, Boolean>)TipeKendaraan::setRowStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public String getName() {
		if (_Name == null) {
			return "";
		}
		else {
			return _Name;
		}
	}

	@Override
	public void setName(String Name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Name = Name;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	@Override
	public boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public boolean isRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public TipeKendaraan toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TipeKendaraan>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TipeKendaraanImpl tipeKendaraanImpl = new TipeKendaraanImpl();

		tipeKendaraanImpl.setId(getId());
		tipeKendaraanImpl.setName(getName());
		tipeKendaraanImpl.setCreatedDate(getCreatedDate());
		tipeKendaraanImpl.setCreatedBy(getCreatedBy());
		tipeKendaraanImpl.setModifiedDate(getModifiedDate());
		tipeKendaraanImpl.setModifiedBy(getModifiedBy());
		tipeKendaraanImpl.setRowStatus(isRowStatus());

		tipeKendaraanImpl.resetOriginalValues();

		return tipeKendaraanImpl;
	}

	@Override
	public TipeKendaraan cloneWithOriginalValues() {
		TipeKendaraanImpl tipeKendaraanImpl = new TipeKendaraanImpl();

		tipeKendaraanImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		tipeKendaraanImpl.setName(this.<String>getColumnOriginalValue("Name"));
		tipeKendaraanImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		tipeKendaraanImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		tipeKendaraanImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		tipeKendaraanImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));
		tipeKendaraanImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));

		return tipeKendaraanImpl;
	}

	@Override
	public int compareTo(TipeKendaraan tipeKendaraan) {
		int primaryKey = tipeKendaraan.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TipeKendaraan)) {
			return false;
		}

		TipeKendaraan tipeKendaraan = (TipeKendaraan)object;

		int primaryKey = tipeKendaraan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TipeKendaraan> toCacheModel() {
		TipeKendaraanCacheModel tipeKendaraanCacheModel =
			new TipeKendaraanCacheModel();

		tipeKendaraanCacheModel.Id = getId();

		tipeKendaraanCacheModel.Name = getName();

		String Name = tipeKendaraanCacheModel.Name;

		if ((Name != null) && (Name.length() == 0)) {
			tipeKendaraanCacheModel.Name = null;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			tipeKendaraanCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			tipeKendaraanCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		tipeKendaraanCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = tipeKendaraanCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			tipeKendaraanCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			tipeKendaraanCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			tipeKendaraanCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		tipeKendaraanCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = tipeKendaraanCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			tipeKendaraanCacheModel.ModifiedBy = null;
		}

		tipeKendaraanCacheModel.RowStatus = isRowStatus();

		return tipeKendaraanCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TipeKendaraan, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TipeKendaraan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TipeKendaraan, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TipeKendaraan)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TipeKendaraan>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TipeKendaraan.class, ModelWrapper.class);

	}

	private int _Id;
	private String _Name;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;
	private boolean _RowStatus;

	public <T> T getColumnValue(String columnName) {
		Function<TipeKendaraan, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TipeKendaraan)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("Name", _Name);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
		_columnOriginalValues.put("RowStatus", _RowStatus);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("Name", 2L);

		columnBitmasks.put("CreatedDate", 4L);

		columnBitmasks.put("CreatedBy", 8L);

		columnBitmasks.put("ModifiedDate", 16L);

		columnBitmasks.put("ModifiedBy", 32L);

		columnBitmasks.put("RowStatus", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TipeKendaraan _escapedModel;

}