/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.TrainingAgendaParticipant;
import com.astra.dewa.service.TrainingAgendaParticipantLocalServiceUtil;

/**
 * The extended model base implementation for the TrainingAgendaParticipant service. Represents a row in the &quot;training_agenda_participant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrainingAgendaParticipantImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TrainingAgendaParticipantImpl
 * @see TrainingAgendaParticipant
 * @generated
 */
public abstract class TrainingAgendaParticipantBaseImpl
	extends TrainingAgendaParticipantModelImpl
	implements TrainingAgendaParticipant {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a training agenda participant model instance should use the <code>TrainingAgendaParticipant</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TrainingAgendaParticipantLocalServiceUtil.
				addTrainingAgendaParticipant(this);
		}
		else {
			TrainingAgendaParticipantLocalServiceUtil.
				updateTrainingAgendaParticipant(this);
		}
	}

}