/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.TrainingAgendaParticipant;
import com.astra.dewa.model.TrainingAgendaParticipantModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TrainingAgendaParticipant service. Represents a row in the &quot;training_agenda_participant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TrainingAgendaParticipantModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrainingAgendaParticipantImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TrainingAgendaParticipantImpl
 * @generated
 */
public class TrainingAgendaParticipantModelImpl
	extends BaseModelImpl<TrainingAgendaParticipant>
	implements TrainingAgendaParticipantModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a training agenda participant model instance should use the <code>TrainingAgendaParticipant</code> interface instead.
	 */
	public static final String TABLE_NAME = "training_agenda_participant";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"TrainingAgendaId", Types.INTEGER},
		{"DealerId", Types.INTEGER}, {"FullName", Types.VARCHAR},
		{"Email", Types.VARCHAR}, {"Phone", Types.VARCHAR},
		{"RowStatus", Types.BOOLEAN}, {"CreatedDate", Types.TIMESTAMP},
		{"CreatedBy", Types.VARCHAR}, {"ModifiedDate", Types.TIMESTAMP},
		{"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("TrainingAgendaId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("DealerId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("FullName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Phone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table training_agenda_participant (Id INTEGER not null primary key IDENTITY,TrainingAgendaId INTEGER,DealerId INTEGER,FullName VARCHAR(75) null,Email VARCHAR(75) null,Phone VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table training_agenda_participant";

	public static final String ORDER_BY_JPQL =
		" ORDER BY trainingAgendaParticipant.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY training_agenda_participant.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TrainingAgendaParticipantModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TrainingAgendaParticipant.class;
	}

	@Override
	public String getModelClassName() {
		return TrainingAgendaParticipant.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TrainingAgendaParticipant, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TrainingAgendaParticipant, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TrainingAgendaParticipant, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TrainingAgendaParticipant)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TrainingAgendaParticipant, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TrainingAgendaParticipant, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TrainingAgendaParticipant)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TrainingAgendaParticipant, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TrainingAgendaParticipant, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<TrainingAgendaParticipant, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<TrainingAgendaParticipant, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<TrainingAgendaParticipant, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<TrainingAgendaParticipant, Object>>();
		Map<String, BiConsumer<TrainingAgendaParticipant, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<TrainingAgendaParticipant, ?>>();

		attributeGetterFunctions.put("Id", TrainingAgendaParticipant::getId);
		attributeSetterBiConsumers.put(
			"Id",
			(BiConsumer<TrainingAgendaParticipant, Integer>)
				TrainingAgendaParticipant::setId);
		attributeGetterFunctions.put(
			"TrainingAgendaId", TrainingAgendaParticipant::getTrainingAgendaId);
		attributeSetterBiConsumers.put(
			"TrainingAgendaId",
			(BiConsumer<TrainingAgendaParticipant, Integer>)
				TrainingAgendaParticipant::setTrainingAgendaId);
		attributeGetterFunctions.put(
			"DealerId", TrainingAgendaParticipant::getDealerId);
		attributeSetterBiConsumers.put(
			"DealerId",
			(BiConsumer<TrainingAgendaParticipant, Integer>)
				TrainingAgendaParticipant::setDealerId);
		attributeGetterFunctions.put(
			"FullName", TrainingAgendaParticipant::getFullName);
		attributeSetterBiConsumers.put(
			"FullName",
			(BiConsumer<TrainingAgendaParticipant, String>)
				TrainingAgendaParticipant::setFullName);
		attributeGetterFunctions.put(
			"Email", TrainingAgendaParticipant::getEmail);
		attributeSetterBiConsumers.put(
			"Email",
			(BiConsumer<TrainingAgendaParticipant, String>)
				TrainingAgendaParticipant::setEmail);
		attributeGetterFunctions.put(
			"Phone", TrainingAgendaParticipant::getPhone);
		attributeSetterBiConsumers.put(
			"Phone",
			(BiConsumer<TrainingAgendaParticipant, String>)
				TrainingAgendaParticipant::setPhone);
		attributeGetterFunctions.put(
			"RowStatus", TrainingAgendaParticipant::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus",
			(BiConsumer<TrainingAgendaParticipant, Boolean>)
				TrainingAgendaParticipant::setRowStatus);
		attributeGetterFunctions.put(
			"CreatedDate", TrainingAgendaParticipant::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate",
			(BiConsumer<TrainingAgendaParticipant, Date>)
				TrainingAgendaParticipant::setCreatedDate);
		attributeGetterFunctions.put(
			"CreatedBy", TrainingAgendaParticipant::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy",
			(BiConsumer<TrainingAgendaParticipant, String>)
				TrainingAgendaParticipant::setCreatedBy);
		attributeGetterFunctions.put(
			"ModifiedDate", TrainingAgendaParticipant::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<TrainingAgendaParticipant, Date>)
				TrainingAgendaParticipant::setModifiedDate);
		attributeGetterFunctions.put(
			"ModifiedBy", TrainingAgendaParticipant::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy",
			(BiConsumer<TrainingAgendaParticipant, String>)
				TrainingAgendaParticipant::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public int getTrainingAgendaId() {
		return _TrainingAgendaId;
	}

	@Override
	public void setTrainingAgendaId(int TrainingAgendaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TrainingAgendaId = TrainingAgendaId;
	}

	@Override
	public int getDealerId() {
		return _DealerId;
	}

	@Override
	public void setDealerId(int DealerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DealerId = DealerId;
	}

	@Override
	public String getFullName() {
		if (_FullName == null) {
			return "";
		}
		else {
			return _FullName;
		}
	}

	@Override
	public void setFullName(String FullName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FullName = FullName;
	}

	@Override
	public String getEmail() {
		if (_Email == null) {
			return "";
		}
		else {
			return _Email;
		}
	}

	@Override
	public void setEmail(String Email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Email = Email;
	}

	@Override
	public String getPhone() {
		if (_Phone == null) {
			return "";
		}
		else {
			return _Phone;
		}
	}

	@Override
	public void setPhone(String Phone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Phone = Phone;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public TrainingAgendaParticipant toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TrainingAgendaParticipant>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TrainingAgendaParticipantImpl trainingAgendaParticipantImpl =
			new TrainingAgendaParticipantImpl();

		trainingAgendaParticipantImpl.setId(getId());
		trainingAgendaParticipantImpl.setTrainingAgendaId(
			getTrainingAgendaId());
		trainingAgendaParticipantImpl.setDealerId(getDealerId());
		trainingAgendaParticipantImpl.setFullName(getFullName());
		trainingAgendaParticipantImpl.setEmail(getEmail());
		trainingAgendaParticipantImpl.setPhone(getPhone());
		trainingAgendaParticipantImpl.setRowStatus(getRowStatus());
		trainingAgendaParticipantImpl.setCreatedDate(getCreatedDate());
		trainingAgendaParticipantImpl.setCreatedBy(getCreatedBy());
		trainingAgendaParticipantImpl.setModifiedDate(getModifiedDate());
		trainingAgendaParticipantImpl.setModifiedBy(getModifiedBy());

		trainingAgendaParticipantImpl.resetOriginalValues();

		return trainingAgendaParticipantImpl;
	}

	@Override
	public TrainingAgendaParticipant cloneWithOriginalValues() {
		TrainingAgendaParticipantImpl trainingAgendaParticipantImpl =
			new TrainingAgendaParticipantImpl();

		trainingAgendaParticipantImpl.setId(
			this.<Integer>getColumnOriginalValue("Id"));
		trainingAgendaParticipantImpl.setTrainingAgendaId(
			this.<Integer>getColumnOriginalValue("TrainingAgendaId"));
		trainingAgendaParticipantImpl.setDealerId(
			this.<Integer>getColumnOriginalValue("DealerId"));
		trainingAgendaParticipantImpl.setFullName(
			this.<String>getColumnOriginalValue("FullName"));
		trainingAgendaParticipantImpl.setEmail(
			this.<String>getColumnOriginalValue("Email"));
		trainingAgendaParticipantImpl.setPhone(
			this.<String>getColumnOriginalValue("Phone"));
		trainingAgendaParticipantImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		trainingAgendaParticipantImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		trainingAgendaParticipantImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		trainingAgendaParticipantImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		trainingAgendaParticipantImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return trainingAgendaParticipantImpl;
	}

	@Override
	public int compareTo(TrainingAgendaParticipant trainingAgendaParticipant) {
		int primaryKey = trainingAgendaParticipant.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TrainingAgendaParticipant)) {
			return false;
		}

		TrainingAgendaParticipant trainingAgendaParticipant =
			(TrainingAgendaParticipant)object;

		int primaryKey = trainingAgendaParticipant.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TrainingAgendaParticipant> toCacheModel() {
		TrainingAgendaParticipantCacheModel
			trainingAgendaParticipantCacheModel =
				new TrainingAgendaParticipantCacheModel();

		trainingAgendaParticipantCacheModel.Id = getId();

		trainingAgendaParticipantCacheModel.TrainingAgendaId =
			getTrainingAgendaId();

		trainingAgendaParticipantCacheModel.DealerId = getDealerId();

		trainingAgendaParticipantCacheModel.FullName = getFullName();

		String FullName = trainingAgendaParticipantCacheModel.FullName;

		if ((FullName != null) && (FullName.length() == 0)) {
			trainingAgendaParticipantCacheModel.FullName = null;
		}

		trainingAgendaParticipantCacheModel.Email = getEmail();

		String Email = trainingAgendaParticipantCacheModel.Email;

		if ((Email != null) && (Email.length() == 0)) {
			trainingAgendaParticipantCacheModel.Email = null;
		}

		trainingAgendaParticipantCacheModel.Phone = getPhone();

		String Phone = trainingAgendaParticipantCacheModel.Phone;

		if ((Phone != null) && (Phone.length() == 0)) {
			trainingAgendaParticipantCacheModel.Phone = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			trainingAgendaParticipantCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			trainingAgendaParticipantCacheModel.CreatedDate =
				CreatedDate.getTime();
		}
		else {
			trainingAgendaParticipantCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		trainingAgendaParticipantCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = trainingAgendaParticipantCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			trainingAgendaParticipantCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			trainingAgendaParticipantCacheModel.ModifiedDate =
				ModifiedDate.getTime();
		}
		else {
			trainingAgendaParticipantCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		trainingAgendaParticipantCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = trainingAgendaParticipantCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			trainingAgendaParticipantCacheModel.ModifiedBy = null;
		}

		return trainingAgendaParticipantCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TrainingAgendaParticipant, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TrainingAgendaParticipant, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TrainingAgendaParticipant, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(TrainingAgendaParticipant)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, TrainingAgendaParticipant>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						TrainingAgendaParticipant.class, ModelWrapper.class);

	}

	private int _Id;
	private int _TrainingAgendaId;
	private int _DealerId;
	private String _FullName;
	private String _Email;
	private String _Phone;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<TrainingAgendaParticipant, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TrainingAgendaParticipant)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("TrainingAgendaId", _TrainingAgendaId);
		_columnOriginalValues.put("DealerId", _DealerId);
		_columnOriginalValues.put("FullName", _FullName);
		_columnOriginalValues.put("Email", _Email);
		_columnOriginalValues.put("Phone", _Phone);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("TrainingAgendaId", 2L);

		columnBitmasks.put("DealerId", 4L);

		columnBitmasks.put("FullName", 8L);

		columnBitmasks.put("Email", 16L);

		columnBitmasks.put("Phone", 32L);

		columnBitmasks.put("RowStatus", 64L);

		columnBitmasks.put("CreatedDate", 128L);

		columnBitmasks.put("CreatedBy", 256L);

		columnBitmasks.put("ModifiedDate", 512L);

		columnBitmasks.put("ModifiedBy", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TrainingAgendaParticipant _escapedModel;

}