/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model.impl;

import com.astra.dewa.model.Wilayah;
import com.astra.dewa.model.WilayahModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Wilayah service. Represents a row in the &quot;Wilayah&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WilayahModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WilayahImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WilayahImpl
 * @generated
 */
public class WilayahModelImpl
	extends BaseModelImpl<Wilayah> implements WilayahModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a wilayah model instance should use the <code>Wilayah</code> interface instead.
	 */
	public static final String TABLE_NAME = "Wilayah";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.INTEGER}, {"Name", Types.VARCHAR}, {"SK", Types.VARCHAR},
		{"Description", Types.VARCHAR}, {"RowStatus", Types.BOOLEAN},
		{"CreatedDate", Types.TIMESTAMP}, {"CreatedBy", Types.VARCHAR},
		{"ModifiedDate", Types.TIMESTAMP}, {"ModifiedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SK", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RowStatus", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("CreatedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Wilayah (Id INTEGER not null primary key IDENTITY,Name VARCHAR(75) null,SK VARCHAR(75) null,Description VARCHAR(75) null,RowStatus BOOLEAN,CreatedDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table Wilayah";

	public static final String ORDER_BY_JPQL = " ORDER BY wilayah.Id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY Wilayah.Id ASC";

	public static final String DATA_SOURCE = "dewaDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public WilayahModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Wilayah.class;
	}

	@Override
	public String getModelClassName() {
		return Wilayah.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Wilayah, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Wilayah, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Wilayah, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Wilayah)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Wilayah, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Wilayah, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Wilayah)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Wilayah, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Wilayah, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Wilayah, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Wilayah, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Wilayah, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Wilayah, Object>>();
		Map<String, BiConsumer<Wilayah, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Wilayah, ?>>();

		attributeGetterFunctions.put("Id", Wilayah::getId);
		attributeSetterBiConsumers.put(
			"Id", (BiConsumer<Wilayah, Integer>)Wilayah::setId);
		attributeGetterFunctions.put("Name", Wilayah::getName);
		attributeSetterBiConsumers.put(
			"Name", (BiConsumer<Wilayah, String>)Wilayah::setName);
		attributeGetterFunctions.put("SK", Wilayah::getSK);
		attributeSetterBiConsumers.put(
			"SK", (BiConsumer<Wilayah, String>)Wilayah::setSK);
		attributeGetterFunctions.put("Description", Wilayah::getDescription);
		attributeSetterBiConsumers.put(
			"Description",
			(BiConsumer<Wilayah, String>)Wilayah::setDescription);
		attributeGetterFunctions.put("RowStatus", Wilayah::getRowStatus);
		attributeSetterBiConsumers.put(
			"RowStatus", (BiConsumer<Wilayah, Boolean>)Wilayah::setRowStatus);
		attributeGetterFunctions.put("CreatedDate", Wilayah::getCreatedDate);
		attributeSetterBiConsumers.put(
			"CreatedDate", (BiConsumer<Wilayah, Date>)Wilayah::setCreatedDate);
		attributeGetterFunctions.put("CreatedBy", Wilayah::getCreatedBy);
		attributeSetterBiConsumers.put(
			"CreatedBy", (BiConsumer<Wilayah, String>)Wilayah::setCreatedBy);
		attributeGetterFunctions.put("ModifiedDate", Wilayah::getModifiedDate);
		attributeSetterBiConsumers.put(
			"ModifiedDate",
			(BiConsumer<Wilayah, Date>)Wilayah::setModifiedDate);
		attributeGetterFunctions.put("ModifiedBy", Wilayah::getModifiedBy);
		attributeSetterBiConsumers.put(
			"ModifiedBy", (BiConsumer<Wilayah, String>)Wilayah::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getId() {
		return _Id;
	}

	@Override
	public void setId(int Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@Override
	public String getName() {
		if (_Name == null) {
			return "";
		}
		else {
			return _Name;
		}
	}

	@Override
	public void setName(String Name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Name = Name;
	}

	@Override
	public String getSK() {
		if (_SK == null) {
			return "";
		}
		else {
			return _SK;
		}
	}

	@Override
	public void setSK(String SK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_SK = SK;
	}

	@Override
	public String getDescription() {
		if (_Description == null) {
			return "";
		}
		else {
			return _Description;
		}
	}

	@Override
	public void setDescription(String Description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Description = Description;
	}

	@Override
	public Boolean getRowStatus() {
		return _RowStatus;
	}

	@Override
	public void setRowStatus(Boolean RowStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_RowStatus = RowStatus;
	}

	@Override
	public Date getCreatedDate() {
		return _CreatedDate;
	}

	@Override
	public void setCreatedDate(Date CreatedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedDate = CreatedDate;
	}

	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return "";
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CreatedBy = CreatedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedDate = ModifiedDate;
	}

	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return "";
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ModifiedBy = ModifiedBy;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Wilayah toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Wilayah>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WilayahImpl wilayahImpl = new WilayahImpl();

		wilayahImpl.setId(getId());
		wilayahImpl.setName(getName());
		wilayahImpl.setSK(getSK());
		wilayahImpl.setDescription(getDescription());
		wilayahImpl.setRowStatus(getRowStatus());
		wilayahImpl.setCreatedDate(getCreatedDate());
		wilayahImpl.setCreatedBy(getCreatedBy());
		wilayahImpl.setModifiedDate(getModifiedDate());
		wilayahImpl.setModifiedBy(getModifiedBy());

		wilayahImpl.resetOriginalValues();

		return wilayahImpl;
	}

	@Override
	public Wilayah cloneWithOriginalValues() {
		WilayahImpl wilayahImpl = new WilayahImpl();

		wilayahImpl.setId(this.<Integer>getColumnOriginalValue("Id"));
		wilayahImpl.setName(this.<String>getColumnOriginalValue("Name"));
		wilayahImpl.setSK(this.<String>getColumnOriginalValue("SK"));
		wilayahImpl.setDescription(
			this.<String>getColumnOriginalValue("Description"));
		wilayahImpl.setRowStatus(
			this.<Boolean>getColumnOriginalValue("RowStatus"));
		wilayahImpl.setCreatedDate(
			this.<Date>getColumnOriginalValue("CreatedDate"));
		wilayahImpl.setCreatedBy(
			this.<String>getColumnOriginalValue("CreatedBy"));
		wilayahImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("ModifiedDate"));
		wilayahImpl.setModifiedBy(
			this.<String>getColumnOriginalValue("ModifiedBy"));

		return wilayahImpl;
	}

	@Override
	public int compareTo(Wilayah wilayah) {
		int primaryKey = wilayah.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Wilayah)) {
			return false;
		}

		Wilayah wilayah = (Wilayah)object;

		int primaryKey = wilayah.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Wilayah> toCacheModel() {
		WilayahCacheModel wilayahCacheModel = new WilayahCacheModel();

		wilayahCacheModel.Id = getId();

		wilayahCacheModel.Name = getName();

		String Name = wilayahCacheModel.Name;

		if ((Name != null) && (Name.length() == 0)) {
			wilayahCacheModel.Name = null;
		}

		wilayahCacheModel.SK = getSK();

		String SK = wilayahCacheModel.SK;

		if ((SK != null) && (SK.length() == 0)) {
			wilayahCacheModel.SK = null;
		}

		wilayahCacheModel.Description = getDescription();

		String Description = wilayahCacheModel.Description;

		if ((Description != null) && (Description.length() == 0)) {
			wilayahCacheModel.Description = null;
		}

		Boolean RowStatus = getRowStatus();

		if (RowStatus != null) {
			wilayahCacheModel.RowStatus = RowStatus;
		}

		Date CreatedDate = getCreatedDate();

		if (CreatedDate != null) {
			wilayahCacheModel.CreatedDate = CreatedDate.getTime();
		}
		else {
			wilayahCacheModel.CreatedDate = Long.MIN_VALUE;
		}

		wilayahCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = wilayahCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			wilayahCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			wilayahCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			wilayahCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		wilayahCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = wilayahCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			wilayahCacheModel.ModifiedBy = null;
		}

		return wilayahCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Wilayah, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Wilayah, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Wilayah, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Wilayah)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Wilayah>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Wilayah.class, ModelWrapper.class);

	}

	private int _Id;
	private String _Name;

	private String _SK;

	private String _Description;
	private Boolean _RowStatus;
	private Date _CreatedDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;

	public <T> T getColumnValue(String columnName) {
		Function<Wilayah, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Wilayah)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("Name", _Name);
		_columnOriginalValues.put("SK", _SK);
		_columnOriginalValues.put("Description", _Description);
		_columnOriginalValues.put("RowStatus", _RowStatus);
		_columnOriginalValues.put("CreatedDate", _CreatedDate);
		_columnOriginalValues.put("CreatedBy", _CreatedBy);
		_columnOriginalValues.put("ModifiedDate", _ModifiedDate);
		_columnOriginalValues.put("ModifiedBy", _ModifiedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("Name", 2L);

		columnBitmasks.put("SK", 4L);

		columnBitmasks.put("Description", 8L);

		columnBitmasks.put("RowStatus", 16L);

		columnBitmasks.put("CreatedDate", 32L);

		columnBitmasks.put("CreatedBy", 64L);

		columnBitmasks.put("ModifiedDate", 128L);

		columnBitmasks.put("ModifiedBy", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Wilayah _escapedModel;

}