/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ApplicationAssignJournal service. Represents a row in the &quot;ApplicationAssignJournal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.astra.dewa.model.impl.ApplicationAssignJournalModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.astra.dewa.model.impl.ApplicationAssignJournalImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApplicationAssignJournal
 * @generated
 */
@ProviderType
public interface ApplicationAssignJournalModel
	extends BaseModel<ApplicationAssignJournal> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a application assign journal model instance should use the {@link ApplicationAssignJournal} interface instead.
	 */

	/**
	 * Returns the primary key of this application assign journal.
	 *
	 * @return the primary key of this application assign journal
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this application assign journal.
	 *
	 * @param primaryKey the primary key of this application assign journal
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this application assign journal.
	 *
	 * @return the ID of this application assign journal
	 */
	public int getId();

	/**
	 * Sets the ID of this application assign journal.
	 *
	 * @param Id the ID of this application assign journal
	 */
	public void setId(int Id);

	/**
	 * Returns the application assign ID of this application assign journal.
	 *
	 * @return the application assign ID of this application assign journal
	 */
	public int getApplicationAssignId();

	/**
	 * Sets the application assign ID of this application assign journal.
	 *
	 * @param ApplicationAssignId the application assign ID of this application assign journal
	 */
	public void setApplicationAssignId(int ApplicationAssignId);

	/**
	 * Returns the application header ID of this application assign journal.
	 *
	 * @return the application header ID of this application assign journal
	 */
	public int getApplicationHeaderId();

	/**
	 * Sets the application header ID of this application assign journal.
	 *
	 * @param ApplicationHeaderId the application header ID of this application assign journal
	 */
	public void setApplicationHeaderId(int ApplicationHeaderId);

	/**
	 * Returns the application assign status ID of this application assign journal.
	 *
	 * @return the application assign status ID of this application assign journal
	 */
	public int getApplicationAssignStatusId();

	/**
	 * Sets the application assign status ID of this application assign journal.
	 *
	 * @param ApplicationAssignStatusId the application assign status ID of this application assign journal
	 */
	public void setApplicationAssignStatusId(int ApplicationAssignStatusId);

	/**
	 * Returns the profile ID of this application assign journal.
	 *
	 * @return the profile ID of this application assign journal
	 */
	public long getProfileId();

	/**
	 * Sets the profile ID of this application assign journal.
	 *
	 * @param ProfileId the profile ID of this application assign journal
	 */
	public void setProfileId(long ProfileId);

	/**
	 * Returns the start date on of this application assign journal.
	 *
	 * @return the start date on of this application assign journal
	 */
	public Date getStartDateOn();

	/**
	 * Sets the start date on of this application assign journal.
	 *
	 * @param StartDateOn the start date on of this application assign journal
	 */
	public void setStartDateOn(Date StartDateOn);

	/**
	 * Returns the completed date on of this application assign journal.
	 *
	 * @return the completed date on of this application assign journal
	 */
	public Date getCompletedDateOn();

	/**
	 * Sets the completed date on of this application assign journal.
	 *
	 * @param CompletedDateOn the completed date on of this application assign journal
	 */
	public void setCompletedDateOn(Date CompletedDateOn);

	/**
	 * Returns the notes of this application assign journal.
	 *
	 * @return the notes of this application assign journal
	 */
	@AutoEscape
	public String getNotes();

	/**
	 * Sets the notes of this application assign journal.
	 *
	 * @param Notes the notes of this application assign journal
	 */
	public void setNotes(String Notes);

	/**
	 * Returns the row status of this application assign journal.
	 *
	 * @return the row status of this application assign journal
	 */
	public Boolean getRowStatus();

	/**
	 * Sets the row status of this application assign journal.
	 *
	 * @param RowStatus the row status of this application assign journal
	 */
	public void setRowStatus(Boolean RowStatus);

	/**
	 * Returns the created by of this application assign journal.
	 *
	 * @return the created by of this application assign journal
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this application assign journal.
	 *
	 * @param CreatedBy the created by of this application assign journal
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this application assign journal.
	 *
	 * @return the created date of this application assign journal
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this application assign journal.
	 *
	 * @param CreatedDate the created date of this application assign journal
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this application assign journal.
	 *
	 * @return the modified by of this application assign journal
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this application assign journal.
	 *
	 * @param ModifiedBy the modified by of this application assign journal
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this application assign journal.
	 *
	 * @return the modified date of this application assign journal
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this application assign journal.
	 *
	 * @param ModifiedDate the modified date of this application assign journal
	 */
	public void setModifiedDate(Date ModifiedDate);

	@Override
	public ApplicationAssignJournal cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}