/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Application service. Represents a row in the &quot;Application&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.astra.dewa.model.impl.ApplicationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.astra.dewa.model.impl.ApplicationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Application
 * @generated
 */
@ProviderType
public interface ApplicationModel extends BaseModel<Application> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a application model instance should use the {@link Application} interface instead.
	 */

	/**
	 * Returns the primary key of this application.
	 *
	 * @return the primary key of this application
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this application.
	 *
	 * @param primaryKey the primary key of this application
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this application.
	 *
	 * @return the ID of this application
	 */
	public int getId();

	/**
	 * Sets the ID of this application.
	 *
	 * @param Id the ID of this application
	 */
	public void setId(int Id);

	/**
	 * Returns the name of this application.
	 *
	 * @return the name of this application
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this application.
	 *
	 * @param Name the name of this application
	 */
	public void setName(String Name);

	/**
	 * Returns the description of this application.
	 *
	 * @return the description of this application
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this application.
	 *
	 * @param Description the description of this application
	 */
	public void setDescription(String Description);

	/**
	 * Returns the row status of this application.
	 *
	 * @return the row status of this application
	 */
	public Boolean getRowStatus();

	/**
	 * Sets the row status of this application.
	 *
	 * @param RowStatus the row status of this application
	 */
	public void setRowStatus(Boolean RowStatus);

	/**
	 * Returns the created by of this application.
	 *
	 * @return the created by of this application
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this application.
	 *
	 * @param CreatedBy the created by of this application
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this application.
	 *
	 * @return the created date of this application
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this application.
	 *
	 * @param CreatedDate the created date of this application
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this application.
	 *
	 * @return the modified by of this application
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this application.
	 *
	 * @param ModifiedBy the modified by of this application
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this application.
	 *
	 * @return the modified date of this application
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this application.
	 *
	 * @param ModifiedDate the modified date of this application
	 */
	public void setModifiedDate(Date ModifiedDate);

	@Override
	public Application cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}