/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ApprovalDetailUser service. Represents a row in the &quot;ApprovalDetailUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.astra.dewa.model.impl.ApprovalDetailUserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.astra.dewa.model.impl.ApprovalDetailUserImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ApprovalDetailUser
 * @generated
 */
@ProviderType
public interface ApprovalDetailUserModel extends BaseModel<ApprovalDetailUser> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a approval detail user model instance should use the {@link ApprovalDetailUser} interface instead.
	 */

	/**
	 * Returns the primary key of this approval detail user.
	 *
	 * @return the primary key of this approval detail user
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this approval detail user.
	 *
	 * @param primaryKey the primary key of this approval detail user
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this approval detail user.
	 *
	 * @return the ID of this approval detail user
	 */
	public int getId();

	/**
	 * Sets the ID of this approval detail user.
	 *
	 * @param Id the ID of this approval detail user
	 */
	public void setId(int Id);

	/**
	 * Returns the approval header user ID of this approval detail user.
	 *
	 * @return the approval header user ID of this approval detail user
	 */
	public int getApprovalHeaderUserId();

	/**
	 * Sets the approval header user ID of this approval detail user.
	 *
	 * @param ApprovalHeaderUserId the approval header user ID of this approval detail user
	 */
	public void setApprovalHeaderUserId(int ApprovalHeaderUserId);

	/**
	 * Returns the role ID of this approval detail user.
	 *
	 * @return the role ID of this approval detail user
	 */
	public int getRoleId();

	/**
	 * Sets the role ID of this approval detail user.
	 *
	 * @param RoleId the role ID of this approval detail user
	 */
	public void setRoleId(int RoleId);

	/**
	 * Returns the row status of this approval detail user.
	 *
	 * @return the row status of this approval detail user
	 */
	public Boolean getRowStatus();

	/**
	 * Sets the row status of this approval detail user.
	 *
	 * @param RowStatus the row status of this approval detail user
	 */
	public void setRowStatus(Boolean RowStatus);

	/**
	 * Returns the created by of this approval detail user.
	 *
	 * @return the created by of this approval detail user
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this approval detail user.
	 *
	 * @param CreatedBy the created by of this approval detail user
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this approval detail user.
	 *
	 * @return the created date of this approval detail user
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this approval detail user.
	 *
	 * @param CreatedDate the created date of this approval detail user
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this approval detail user.
	 *
	 * @return the modified by of this approval detail user
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this approval detail user.
	 *
	 * @param ModifiedBy the modified by of this approval detail user
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this approval detail user.
	 *
	 * @return the modified date of this approval detail user
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this approval detail user.
	 *
	 * @param ModifiedDate the modified date of this approval detail user
	 */
	public void setModifiedDate(Date ModifiedDate);

	@Override
	public ApprovalDetailUser cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}