/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmailDomain service. Represents a row in the &quot;email_domain&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.astra.dewa.model.impl.EmailDomainModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.astra.dewa.model.impl.EmailDomainImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmailDomain
 * @generated
 */
@ProviderType
public interface EmailDomainModel extends BaseModel<EmailDomain> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a email domain model instance should use the {@link EmailDomain} interface instead.
	 */

	/**
	 * Returns the primary key of this email domain.
	 *
	 * @return the primary key of this email domain
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this email domain.
	 *
	 * @param primaryKey the primary key of this email domain
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this email domain.
	 *
	 * @return the ID of this email domain
	 */
	public int getId();

	/**
	 * Sets the ID of this email domain.
	 *
	 * @param Id the ID of this email domain
	 */
	public void setId(int Id);

	/**
	 * Returns the domain name of this email domain.
	 *
	 * @return the domain name of this email domain
	 */
	@AutoEscape
	public String getDomainName();

	/**
	 * Sets the domain name of this email domain.
	 *
	 * @param DomainName the domain name of this email domain
	 */
	public void setDomainName(String DomainName);

	/**
	 * Returns the category of this email domain.
	 *
	 * @return the category of this email domain
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this email domain.
	 *
	 * @param Category the category of this email domain
	 */
	public void setCategory(String Category);

	/**
	 * Returns the row status of this email domain.
	 *
	 * @return the row status of this email domain
	 */
	public boolean getRowStatus();

	/**
	 * Returns <code>true</code> if this email domain is row status.
	 *
	 * @return <code>true</code> if this email domain is row status; <code>false</code> otherwise
	 */
	public boolean isRowStatus();

	/**
	 * Sets whether this email domain is row status.
	 *
	 * @param RowStatus the row status of this email domain
	 */
	public void setRowStatus(boolean RowStatus);

	/**
	 * Returns the created by of this email domain.
	 *
	 * @return the created by of this email domain
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this email domain.
	 *
	 * @param CreatedBy the created by of this email domain
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the created date of this email domain.
	 *
	 * @return the created date of this email domain
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this email domain.
	 *
	 * @param CreatedDate the created date of this email domain
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the modified by of this email domain.
	 *
	 * @return the modified by of this email domain
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this email domain.
	 *
	 * @param ModifiedBy the modified by of this email domain
	 */
	public void setModifiedBy(String ModifiedBy);

	/**
	 * Returns the modified date of this email domain.
	 *
	 * @return the modified date of this email domain
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this email domain.
	 *
	 * @param ModifiedDate the modified date of this email domain
	 */
	public void setModifiedDate(Date ModifiedDate);

	@Override
	public EmailDomain cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}