/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MasterApprovalDetailJournal service. Represents a row in the &quot;master_approval_detail_journal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.astra.dewa.model.impl.MasterApprovalDetailJournalModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.astra.dewa.model.impl.MasterApprovalDetailJournalImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MasterApprovalDetailJournal
 * @generated
 */
@ProviderType
public interface MasterApprovalDetailJournalModel
	extends BaseModel<MasterApprovalDetailJournal> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a master approval detail journal model instance should use the {@link MasterApprovalDetailJournal} interface instead.
	 */

	/**
	 * Returns the primary key of this master approval detail journal.
	 *
	 * @return the primary key of this master approval detail journal
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this master approval detail journal.
	 *
	 * @param primaryKey the primary key of this master approval detail journal
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this master approval detail journal.
	 *
	 * @return the ID of this master approval detail journal
	 */
	public int getId();

	/**
	 * Sets the ID of this master approval detail journal.
	 *
	 * @param Id the ID of this master approval detail journal
	 */
	public void setId(int Id);

	/**
	 * Returns the master approval ID of this master approval detail journal.
	 *
	 * @return the master approval ID of this master approval detail journal
	 */
	public int getMasterApprovalId();

	/**
	 * Sets the master approval ID of this master approval detail journal.
	 *
	 * @param MasterApprovalId the master approval ID of this master approval detail journal
	 */
	public void setMasterApprovalId(int MasterApprovalId);

	/**
	 * Returns the master approval journal ID of this master approval detail journal.
	 *
	 * @return the master approval journal ID of this master approval detail journal
	 */
	public int getMasterApprovalJournalId();

	/**
	 * Sets the master approval journal ID of this master approval detail journal.
	 *
	 * @param MasterApprovalJournalId the master approval journal ID of this master approval detail journal
	 */
	public void setMasterApprovalJournalId(int MasterApprovalJournalId);

	/**
	 * Returns the master approval detail ID of this master approval detail journal.
	 *
	 * @return the master approval detail ID of this master approval detail journal
	 */
	public int getMasterApprovalDetailId();

	/**
	 * Sets the master approval detail ID of this master approval detail journal.
	 *
	 * @param MasterApprovalDetailId the master approval detail ID of this master approval detail journal
	 */
	public void setMasterApprovalDetailId(int MasterApprovalDetailId);

	/**
	 * Returns the user ID of this master approval detail journal.
	 *
	 * @return the user ID of this master approval detail journal
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this master approval detail journal.
	 *
	 * @param UserId the user ID of this master approval detail journal
	 */
	public void setUserId(long UserId);

	/**
	 * Returns the user uuid of this master approval detail journal.
	 *
	 * @return the user uuid of this master approval detail journal
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this master approval detail journal.
	 *
	 * @param UserUuid the user uuid of this master approval detail journal
	 */
	public void setUserUuid(String UserUuid);

	/**
	 * Returns the approval level of this master approval detail journal.
	 *
	 * @return the approval level of this master approval detail journal
	 */
	public int getApprovalLevel();

	/**
	 * Sets the approval level of this master approval detail journal.
	 *
	 * @param ApprovalLevel the approval level of this master approval detail journal
	 */
	public void setApprovalLevel(int ApprovalLevel);

	/**
	 * Returns the is default of this master approval detail journal.
	 *
	 * @return the is default of this master approval detail journal
	 */
	public boolean getIsDefault();

	/**
	 * Returns <code>true</code> if this master approval detail journal is is default.
	 *
	 * @return <code>true</code> if this master approval detail journal is is default; <code>false</code> otherwise
	 */
	public boolean isIsDefault();

	/**
	 * Sets whether this master approval detail journal is is default.
	 *
	 * @param IsDefault the is default of this master approval detail journal
	 */
	public void setIsDefault(boolean IsDefault);

	/**
	 * Returns the row status of this master approval detail journal.
	 *
	 * @return the row status of this master approval detail journal
	 */
	public Boolean getRowStatus();

	/**
	 * Sets the row status of this master approval detail journal.
	 *
	 * @param RowStatus the row status of this master approval detail journal
	 */
	public void setRowStatus(Boolean RowStatus);

	/**
	 * Returns the created date of this master approval detail journal.
	 *
	 * @return the created date of this master approval detail journal
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this master approval detail journal.
	 *
	 * @param CreatedDate the created date of this master approval detail journal
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the created by of this master approval detail journal.
	 *
	 * @return the created by of this master approval detail journal
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this master approval detail journal.
	 *
	 * @param CreatedBy the created by of this master approval detail journal
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the modified date of this master approval detail journal.
	 *
	 * @return the modified date of this master approval detail journal
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this master approval detail journal.
	 *
	 * @param ModifiedDate the modified date of this master approval detail journal
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the modified by of this master approval detail journal.
	 *
	 * @return the modified by of this master approval detail journal
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this master approval detail journal.
	 *
	 * @param ModifiedBy the modified by of this master approval detail journal
	 */
	public void setModifiedBy(String ModifiedBy);

	@Override
	public MasterApprovalDetailJournal cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}