/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Tahun service. Represents a row in the &quot;tahun&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.astra.dewa.model.impl.TahunModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.astra.dewa.model.impl.TahunImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Tahun
 * @generated
 */
@ProviderType
public interface TahunModel extends BaseModel<Tahun> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tahun model instance should use the {@link Tahun} interface instead.
	 */

	/**
	 * Returns the primary key of this tahun.
	 *
	 * @return the primary key of this tahun
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this tahun.
	 *
	 * @param primaryKey the primary key of this tahun
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the ID of this tahun.
	 *
	 * @return the ID of this tahun
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the ID of this tahun.
	 *
	 * @param Id the ID of this tahun
	 */
	public void setId(String Id);

	/**
	 * Returns the name of this tahun.
	 *
	 * @return the name of this tahun
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this tahun.
	 *
	 * @param Name the name of this tahun
	 */
	public void setName(String Name);

	@Override
	public Tahun cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}