/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MasterApprovalJournal service. Represents a row in the &quot;master_approval_journal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.astra.dewa.model.impl.MasterApprovalJournalModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.astra.dewa.model.impl.MasterApprovalJournalImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MasterApprovalJournal
 * @generated
 */
@ProviderType
public interface MasterApprovalJournalModel
	extends BaseModel<MasterApprovalJournal> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a master approval journal model instance should use the {@link MasterApprovalJournal} interface instead.
	 */

	/**
	 * Returns the primary key of this master approval journal.
	 *
	 * @return the primary key of this master approval journal
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this master approval journal.
	 *
	 * @param primaryKey the primary key of this master approval journal
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this master approval journal.
	 *
	 * @return the ID of this master approval journal
	 */
	public int getId();

	/**
	 * Sets the ID of this master approval journal.
	 *
	 * @param Id the ID of this master approval journal
	 */
	public void setId(int Id);

	/**
	 * Returns the master approval ID of this master approval journal.
	 *
	 * @return the master approval ID of this master approval journal
	 */
	public int getMasterApprovalId();

	/**
	 * Sets the master approval ID of this master approval journal.
	 *
	 * @param MasterApprovalId the master approval ID of this master approval journal
	 */
	public void setMasterApprovalId(int MasterApprovalId);

	/**
	 * Returns the role ID of this master approval journal.
	 *
	 * @return the role ID of this master approval journal
	 */
	public int getRoleId();

	/**
	 * Sets the role ID of this master approval journal.
	 *
	 * @param RoleId the role ID of this master approval journal
	 */
	public void setRoleId(int RoleId);

	/**
	 * Returns the menu ID of this master approval journal.
	 *
	 * @return the menu ID of this master approval journal
	 */
	public int getMenuId();

	/**
	 * Sets the menu ID of this master approval journal.
	 *
	 * @param MenuId the menu ID of this master approval journal
	 */
	public void setMenuId(int MenuId);

	/**
	 * Returns the approval group of this master approval journal.
	 *
	 * @return the approval group of this master approval journal
	 */
	@AutoEscape
	public String getApprovalGroup();

	/**
	 * Sets the approval group of this master approval journal.
	 *
	 * @param ApprovalGroup the approval group of this master approval journal
	 */
	public void setApprovalGroup(String ApprovalGroup);

	/**
	 * Returns the approval workflow of this master approval journal.
	 *
	 * @return the approval workflow of this master approval journal
	 */
	public boolean getApprovalWorkflow();

	/**
	 * Returns <code>true</code> if this master approval journal is approval workflow.
	 *
	 * @return <code>true</code> if this master approval journal is approval workflow; <code>false</code> otherwise
	 */
	public boolean isApprovalWorkflow();

	/**
	 * Sets whether this master approval journal is approval workflow.
	 *
	 * @param ApprovalWorkflow the approval workflow of this master approval journal
	 */
	public void setApprovalWorkflow(boolean ApprovalWorkflow);

	/**
	 * Returns the row status of this master approval journal.
	 *
	 * @return the row status of this master approval journal
	 */
	public Boolean getRowStatus();

	/**
	 * Sets the row status of this master approval journal.
	 *
	 * @param RowStatus the row status of this master approval journal
	 */
	public void setRowStatus(Boolean RowStatus);

	/**
	 * Returns the created date of this master approval journal.
	 *
	 * @return the created date of this master approval journal
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this master approval journal.
	 *
	 * @param CreatedDate the created date of this master approval journal
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the created by of this master approval journal.
	 *
	 * @return the created by of this master approval journal
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this master approval journal.
	 *
	 * @param CreatedBy the created by of this master approval journal
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the modified date of this master approval journal.
	 *
	 * @return the modified date of this master approval journal
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this master approval journal.
	 *
	 * @param ModifiedDate the modified date of this master approval journal
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the modified by of this master approval journal.
	 *
	 * @return the modified by of this master approval journal
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this master approval journal.
	 *
	 * @param ModifiedBy the modified by of this master approval journal
	 */
	public void setModifiedBy(String ModifiedBy);

	@Override
	public MasterApprovalJournal cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}