/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TrainingMateri service. Represents a row in the &quot;training_materi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.astra.dewa.model.impl.TrainingMateriModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.astra.dewa.model.impl.TrainingMateriImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TrainingMateri
 * @generated
 */
@ProviderType
public interface TrainingMateriModel extends BaseModel<TrainingMateri> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a training materi model instance should use the {@link TrainingMateri} interface instead.
	 */

	/**
	 * Returns the primary key of this training materi.
	 *
	 * @return the primary key of this training materi
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this training materi.
	 *
	 * @param primaryKey the primary key of this training materi
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this training materi.
	 *
	 * @return the ID of this training materi
	 */
	public int getId();

	/**
	 * Sets the ID of this training materi.
	 *
	 * @param Id the ID of this training materi
	 */
	public void setId(int Id);

	/**
	 * Returns the jenis materi ID of this training materi.
	 *
	 * @return the jenis materi ID of this training materi
	 */
	public int getJenisMateriId();

	/**
	 * Sets the jenis materi ID of this training materi.
	 *
	 * @param JenisMateriId the jenis materi ID of this training materi
	 */
	public void setJenisMateriId(int JenisMateriId);

	/**
	 * Returns the topik materi ID of this training materi.
	 *
	 * @return the topik materi ID of this training materi
	 */
	public int getTopikMateriId();

	/**
	 * Sets the topik materi ID of this training materi.
	 *
	 * @param TopikMateriId the topik materi ID of this training materi
	 */
	public void setTopikMateriId(int TopikMateriId);

	/**
	 * Returns the judul materi of this training materi.
	 *
	 * @return the judul materi of this training materi
	 */
	@AutoEscape
	public String getJudulMateri();

	/**
	 * Sets the judul materi of this training materi.
	 *
	 * @param JudulMateri the judul materi of this training materi
	 */
	public void setJudulMateri(String JudulMateri);

	/**
	 * Returns the image ID of this training materi.
	 *
	 * @return the image ID of this training materi
	 */
	public Long getImageId();

	/**
	 * Sets the image ID of this training materi.
	 *
	 * @param ImageId the image ID of this training materi
	 */
	public void setImageId(Long ImageId);

	/**
	 * Returns the image name of this training materi.
	 *
	 * @return the image name of this training materi
	 */
	@AutoEscape
	public String getImageName();

	/**
	 * Sets the image name of this training materi.
	 *
	 * @param ImageName the image name of this training materi
	 */
	public void setImageName(String ImageName);

	/**
	 * Returns the image path of this training materi.
	 *
	 * @return the image path of this training materi
	 */
	@AutoEscape
	public String getImagePath();

	/**
	 * Sets the image path of this training materi.
	 *
	 * @param ImagePath the image path of this training materi
	 */
	public void setImagePath(String ImagePath);

	/**
	 * Returns the row status of this training materi.
	 *
	 * @return the row status of this training materi
	 */
	public Boolean getRowStatus();

	/**
	 * Sets the row status of this training materi.
	 *
	 * @param RowStatus the row status of this training materi
	 */
	public void setRowStatus(Boolean RowStatus);

	/**
	 * Returns the created date of this training materi.
	 *
	 * @return the created date of this training materi
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this training materi.
	 *
	 * @param CreatedDate the created date of this training materi
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the created by of this training materi.
	 *
	 * @return the created by of this training materi
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this training materi.
	 *
	 * @param CreatedBy the created by of this training materi
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the modified date of this training materi.
	 *
	 * @return the modified date of this training materi
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this training materi.
	 *
	 * @param ModifiedDate the modified date of this training materi
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the modified by of this training materi.
	 *
	 * @return the modified by of this training materi
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this training materi.
	 *
	 * @param ModifiedBy the modified by of this training materi
	 */
	public void setModifiedBy(String ModifiedBy);

	@Override
	public TrainingMateri cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}