/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.dewa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TrainingAgendaParticipantUf service. Represents a row in the &quot;training_agenda_participant_uf&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.astra.dewa.model.impl.TrainingAgendaParticipantUfModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.astra.dewa.model.impl.TrainingAgendaParticipantUfImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TrainingAgendaParticipantUf
 * @generated
 */
@ProviderType
public interface TrainingAgendaParticipantUfModel
	extends BaseModel<TrainingAgendaParticipantUf> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a training agenda participant uf model instance should use the {@link TrainingAgendaParticipantUf} interface instead.
	 */

	/**
	 * Returns the primary key of this training agenda participant uf.
	 *
	 * @return the primary key of this training agenda participant uf
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this training agenda participant uf.
	 *
	 * @param primaryKey the primary key of this training agenda participant uf
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this training agenda participant uf.
	 *
	 * @return the ID of this training agenda participant uf
	 */
	public int getId();

	/**
	 * Sets the ID of this training agenda participant uf.
	 *
	 * @param Id the ID of this training agenda participant uf
	 */
	public void setId(int Id);

	/**
	 * Returns the training agenda ID of this training agenda participant uf.
	 *
	 * @return the training agenda ID of this training agenda participant uf
	 */
	public int getTrainingAgendaId();

	/**
	 * Sets the training agenda ID of this training agenda participant uf.
	 *
	 * @param TrainingAgendaId the training agenda ID of this training agenda participant uf
	 */
	public void setTrainingAgendaId(int TrainingAgendaId);

	/**
	 * Returns the dealer ID of this training agenda participant uf.
	 *
	 * @return the dealer ID of this training agenda participant uf
	 */
	public int getDealerId();

	/**
	 * Sets the dealer ID of this training agenda participant uf.
	 *
	 * @param DealerId the dealer ID of this training agenda participant uf
	 */
	public void setDealerId(int DealerId);

	/**
	 * Returns the file ID of this training agenda participant uf.
	 *
	 * @return the file ID of this training agenda participant uf
	 */
	public Long getFileId();

	/**
	 * Sets the file ID of this training agenda participant uf.
	 *
	 * @param FileId the file ID of this training agenda participant uf
	 */
	public void setFileId(Long FileId);

	/**
	 * Returns the file name of this training agenda participant uf.
	 *
	 * @return the file name of this training agenda participant uf
	 */
	@AutoEscape
	public String getFileName();

	/**
	 * Sets the file name of this training agenda participant uf.
	 *
	 * @param FileName the file name of this training agenda participant uf
	 */
	public void setFileName(String FileName);

	/**
	 * Returns the file path of this training agenda participant uf.
	 *
	 * @return the file path of this training agenda participant uf
	 */
	@AutoEscape
	public String getFilePath();

	/**
	 * Sets the file path of this training agenda participant uf.
	 *
	 * @param FilePath the file path of this training agenda participant uf
	 */
	public void setFilePath(String FilePath);

	/**
	 * Returns the row status of this training agenda participant uf.
	 *
	 * @return the row status of this training agenda participant uf
	 */
	public Boolean getRowStatus();

	/**
	 * Sets the row status of this training agenda participant uf.
	 *
	 * @param RowStatus the row status of this training agenda participant uf
	 */
	public void setRowStatus(Boolean RowStatus);

	/**
	 * Returns the created date of this training agenda participant uf.
	 *
	 * @return the created date of this training agenda participant uf
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this training agenda participant uf.
	 *
	 * @param CreatedDate the created date of this training agenda participant uf
	 */
	public void setCreatedDate(Date CreatedDate);

	/**
	 * Returns the created by of this training agenda participant uf.
	 *
	 * @return the created by of this training agenda participant uf
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this training agenda participant uf.
	 *
	 * @param CreatedBy the created by of this training agenda participant uf
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the modified date of this training agenda participant uf.
	 *
	 * @return the modified date of this training agenda participant uf
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this training agenda participant uf.
	 *
	 * @param ModifiedDate the modified date of this training agenda participant uf
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the modified by of this training agenda participant uf.
	 *
	 * @return the modified by of this training agenda participant uf
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this training agenda participant uf.
	 *
	 * @param ModifiedBy the modified by of this training agenda participant uf
	 */
	public void setModifiedBy(String ModifiedBy);

	@Override
	public TrainingAgendaParticipantUf cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}